lib/fluent/engine.rb, lib/fluent/supervisor.rb
Ref https://github.com/fluent/fluentd/pull/2647
`MessagePackFactory.init` does not need to be call in Engine class.
no need
no need
=> Move MessgePackFactory.init outside of Engine

lib/fluent/plugin_helper/child_process.rb, test/plugin_helper/test_child_process.rb
Fixes #2609 
reopen with IO::NULL is not correct way to discard message.
It replaces ruby side IO object, not process. Thanks nurse-san!
Need to specify IO::NULL when launch the process.
No need
Same as title
=> child_process helper: fix stderr blocking for discard case. fix #2609

lib/fluent/supervisor.rb
Ref https://github.com/fluent/fluentd/issues/2624
No need to use ivar since since https://github.com/fluent/fluentd/pull/496 .
no need
no need
=> No need to use instance variable

lib/fluent/plugin/out_forward.rb, lib/fluent/plugin_helper/service_discovery.rb, test/plugin_helper/test_service_discovery.rb
None.
Fix typo.
service_disovery_create_manager -> 
service_dis"c"overy_create_manager
None 
None
=> fix typo of service_discovery

lib/fluent/plugin_helper/record_accessor.rb
None
Make record_accessor code simple by moving `call_index` to default implementation.
New implementation is bit faster.
```
base   317.029k i/100ms
test   327.406k i/100ms
base     10.600M (± 6.1%) i/s -     52.944M in   5.019043s
test     10.797M (± 4.2%) i/s -     54.022M in   5.013882s
```
No need
Same as title.
=> record_accessor: Make code simple and bit faster

lib/fluent/command/fluentd.rb, lib/fluent/supervisor.rb
Fixes #2446
In Windows multi-process environment, we cannot rename a file which is opened by another process.
Then, we should do this:
* Separate log file for each process on Windows
I'll add a note in https://docs.fluentd.org/deployment/logging#log-rotation-setting.
Same as title.
=> Support logrotate on Windows correctly. Fix #2446

lib/fluent/command/cat.rb, lib/fluent/compat/exec_util.rb, lib/fluent/counter/base_socket.rb, lib/fluent/engine.rb, lib/fluent/event.rb, lib/fluent/msgpack_factory.rb, lib/fluent/plugin/buffer/file_chunk.rb, lib/fluent/plugin/buffer/file_single_chunk.rb, lib/fluent/plugin/in_forward.rb, lib/fluent/plugin/in_unix.rb, lib/fluent/plugin/out_forward.rb, lib/fluent/plugin/out_forward/ack_handler.rb, lib/fluent/plugin/out_stream.rb, test/plugin/out_forward/test_handshake_protocol.rb, test/plugin/test_in_forward.rb, test/plugin/test_in_unix.rb, test/plugin/test_out_stream.rb, test/test_event.rb
Ref  https://github.com/fluent/fluentd/issues/2624
Remove redundant dependency from Fluent::Engine.
Fluent::Engine has too many states. it's a blocker of new reload feature.
Also, MessagePackFactory::Mixin is used for just reducing types. So I removed `include MessagePackFactory::Mixin` expression and made these methods deprecated.
no need
no need
=> there is no reason calling mesgpacker_unapcker/packer from Fluent::Engine

lib/fluent/engine.rb
no 
Follow up https://github.com/fluent/fluentd/pull/2657
Revive `Engine.msgpack_*` for compat.
no need
no need
=> Revive MsgpackPack for compat

lib/fluent/config/configure_proxy.rb, lib/fluent/plugin/buffer/chunk.rb, lib/fluent/plugin/formatter_csv.rb, lib/fluent/plugin_helper/child_process.rb, lib/fluent/plugin_helper/extract.rb, lib/fluent/plugin_helper/inject.rb, lib/fluent/plugin_helper/server.rb, lib/fluent/test/driver/base_owned.rb, lib/fluent/time.rb, test/counter/test_client.rb
no
For https://bugs.ruby-lang.org/issues/14183
there are a vast number of warnings in https://travis-ci.org/fluent/fluentd/jobs/602120485 which is tested in ruby 2.7 preview2.
See also https://www.ruby-lang.org/en/news/2019/10/22/ruby-2-7-0-preview2-released/
no need
no need
=> Suppress warning about keyword argument introduced from ruby 2.7

lib/fluent/time.rb
None
We recently encountered a weird error showing that:
`value must be a string or a number: (value.class)"`
After digging into the source code, I finally realized that I passed `nil` into the parser but the message was quite confusing.
From my perspective, I thought `(value.class)` should actually be `(#{value.class})`, which showed the class name of the value. In my case, it will be `(NilClass)`, which should be clear for users to understand.
None
None
=> Properly show class names

lib/fluent/engine.rb, lib/fluent/fluent_log_event_router.rb, lib/fluent/supervisor.rb, test/test_fluent_log_event_router.rb
Ref https://github.com/fluent/fluentd/issues/2624
Make engine lighter for safe reloading.
no need
no need
=> Make engine lighter

fluentd.gemspec
Fixes #2634
The pull request #2479 enforces using tzinfo ~> 2.0 but it conflicts
with plugins which depend on activesupport such as fluent-plugin-sql
since it requires tzinfo ~> 1.1.
Until activesupport upgrades it, it would be better to accept also
tzinfo 1.x to keep availability of such plugins. Fluentd can accept
both versions of tzinfo since #2479 absorb the difference of their
API.
None
None
=> Accept tzinfo not only 2.x but also 1.x

lib/fluent/command/fluentd.rb, lib/fluent/engine.rb, lib/fluent/supervisor.rb, lib/fluent/system_config.rb, test/config/test_system_config.rb, test/plugin/test_in_monitor_agent.rb, test/test_supervisor.rb
Ref #2624 
Use `@system_config` explicitly so that supervisor doesn't need to expose all context to system_config.  the current implementation is hard to understand since there are too many states.
no need
no need
=> Set system config variables explicitly

lib/fluent/supervisor.rb
ref https://github.com/fluent/fluentd/pull/2674
Delete unnecessary methods and write them directry.
These methods have only one line. so they're duplicated.
no need
no need
=> Delete unnecessary methods and write them directry

lib/fluent/supervisor.rb
None in GitHub issues, but it will fix the following bug report:
* https://groups.google.com/d/msg/fluentd/Ten_apYLAX8/PD4jYk8KDwAJ
We ClearCode Inc. recently received same bug reports from our some customers.
Their fluentd is v0.12 but I think the same potential bug still exists in the latest version.
This PR removes redundant `run` calls for some Thread objects.
It may cause the following error on SIGUSR1:
```
[error]: unexpected error error_class=ThreadError error=#<ThreadError: killed thread>
```
as reported in
* https://groups.google.com/d/msg/fluentd/Ten_apYLAX8/PD4jYk8KDwAJ
because the new thread may finish before calling "run" method at main
thread.
In addition this PR also replaces `{ ... }` style blocks …
=> Fix a potential bug that ThreadError may occur on SIGUSR1

lib/fluent/agent.rb, lib/fluent/command/fluentd.rb, lib/fluent/engine.rb, lib/fluent/plugin/base.rb, lib/fluent/root_agent.rb, lib/fluent/supervisor.rb, test/command/test_fluentd.rb
ref #2624
<details>
Example config
```
<system>
workers 2
</system>
<worker 0>
<source>
@type fake
secret very-secret-string0
test 1
</source>
<match>
@type null
</match>
</worker>
<worker 1>
<source>
@type fake
secret very-secret-string1
</source>
<match>
@type null
</match>
</worker>
```
```
$ fluentd -c example/debug/secret.conf --dry-run
```
Before (supervisor and worker show same log about `@type fake`)
```
2019-10-15 15:16:44 +0900 [info]: parsing config file is succeeded path="example/debug/secret.conf"
2019-10-15 15:16:44 +0900 [info]: adding match pattern="**" type="null"
2019-10-15 15:16:44 +0900 [info]: adding match pattern="**" type="null"
2019-10-15 15:16:44 +0900 [info]: adding source type="fake" …
```
=> Fix dry run mode

.github/ISSUE_TEMPLATE/bug_report.md
it's noisy to add bug label automatically even if it's not a bug.
cc @repeatedly
=> Remove bug label from issue template

lib/fluent/plugin/buf_file.rb, lib/fluent/plugin/buf_file_single.rb, lib/fluent/plugin/buffer/file_chunk.rb, lib/fluent/plugin/buffer/file_single_chunk.rb, test/plugin/test_buf_file.rb, test/plugin/test_buf_file_single.rb, test/plugin/test_buffer_file_chunk.rb, test/plugin/test_buffer_file_single_chunk.rb
Ref https://github.com/fluent/fluentd/issues/2624
Remove unnecessary mixin and condition
no need
no need
=> Delete unnecessary condition

lib/fluent/fluent_log_event_router.rb, test/command/test_fluentd.rb
Related to https://github.com/fluent/fluentd/pull/2688#issuecomment-550985395 discussion.
Deprecate fluentd v0.10 log capturing configuration, top level `<match fluent.**>`.
We have `<label @FLUENT_LOG>` for clear data flow, so old syntax should be deprecated.
Maybe, we can delete this feature in fluentd v2.
Add note for deprecation.
Same as title
=> log: Deprecate top-level match for capturing fluentd logs

lib/fluent/plugin_helper/server.rb
Fixes #2694 
Ignore unrecoverable error in `SSL_accept`
No need.
Same as title.
=> server: Ignore ECONNREFUSED in TLS accept to avoid fluentd restart.

lib/fluent/plugin_helper/server.rb, test/plugin_helper/test_server.rb
Fixes #2682 
Use other socket method to set `IPV6_V6ONLY`.
See also https://github.com/treasure-data/serverengine/pull/101
No need
Same as title
=> server helper: Fix IPv6 dual stack mode issue for tcp socket.

lib/fluent/plugin/in_monitor_agent.rb, test/plugin/test_in_monitor_agent.rb
**Which issue(s) this PR fixes**: Fixes #2705 
**What this PR does / why we need it**: add a `version` key to the response returned by `/config.json` and `/config` endpoints from the REST monitoring APIs, so that monitoring systems can retrieve what version of Fluentd is running via a remote HTTP call (i.e. without having to run `fluentd --version` on the host machine).
**Docs Changes**: I haven't found existing documentation on the config endpoints, but if there are I'll gladly update them with this change.
**Release Note**: /
=> Expose Fluentd version in config REST endpoints

lib/fluent/supervisor.rb, test/test_supervisor.rb
no
Current implementation calling `STDIN.read` in supervisors and workers.
it causes blocking in worker side.
no
same as the title .
=> inline_config is replaced with the input value when user specify `-`

lib/fluent/plugin_helper/compat_parameters.rb, lib/fluent/time.rb, test/plugin/test_out_stdout.rb
None
I think `localtime = true && utc =false` and `locatime= false && utc = true` should be valid. 
In the current implementation, stdout format plugin raises the error like below with `utc true` in format section.
```
2019-12-10 15:06:02 +0900 [error]: config error file="example/debug/nginx.conf" error_class=Fluent::ConfigError error="both of utc and localtime are specified, use only one of them"
```
example conf
```
<match *>
@type stdout
<format>
@type stdout
utc true
</format>
</match>
```
This is because of calling [TimeParameters#configure](https://github.com/fluent/fluentd/blob/master/lib/fluent/time.rb#L153) twice.
but it seems to be inevitable since the stdout format plugin has sub_formater object …
=> Accept localtime xor utc

lib/fluent/plugin/formatter_stdout.rb, test/plugin/test_out_stdout.rb
ref https://github.com/fluent/fluentd/issues/2718#issuecomment-563372355
stdout format does not see the time_format even if user can set the value. 
no need(already mentioned but it doesn't work)
=> Make time_format configurable in stdout format

lib/fluent/command/fluentd.rb, lib/fluent/config/element.rb, lib/fluent/config/error.rb, lib/fluent/config/literal_parser.rb, lib/fluent/config/section.rb, lib/fluent/config/types.rb, lib/fluent/configurable.rb, lib/fluent/plugin/base.rb, lib/fluent/supervisor.rb, lib/fluent/system_config.rb, test/config/test_configurable.rb, test/config/test_element.rb, test/config/test_literal_parser.rb, test/config/test_system_config.rb, test/config/test_types.rb, test/plugin/test_output.rb
Fixes #2616
Add a new command line option `--strict-config-value` to parse `integer`, `float` and `bool` values in a config file more strictly. A system config item `strict_config_value` is also added.
Since non-numerical (or unrecognized values for `bool`) values for them in config values are implicitly parsed as `0` , sometimes it makes troubleshooting hard. This option will raise an error for such values to clarify such issues in a config file.
In addition, this PR also adds helper methods to set `nil` or default value to parameters in config files, since many users expect `nil` for `"#{ENV['SOME_ENV_VAR']}"` with empty `SOME_ENV_VAR` environment variable (but it's converted to an empty string in actual).
``` …
```
=> Make config values more strictly and enable to set nil or default

test/plugin/test_out_stdout.rb
follow up https://github.com/fluent/fluentd/pull/2720
delete `Notification: <StdoutOutputTest#test: configure with localtime and utc> was redefined [test: configure with localtime and utc[utc and localtime](StdoutOutputTest)]`
https://travis-ci.org/fluent/fluentd/jobs/623812636?utm_medium=notification&utm_source=github_status
no need
no need
=> Suppress redefined test suits

lib/fluent/plugin/output.rb
This used `$1` to print the key name.  However, there are no capture groups in `CHUNK_KEY_PLACEHOLDER_PATTERN`, so `$1` would not be set.  According to the Ruby docs I looked up, `$&` can be used to get the part of the string that matched, which I think will give the correct output in this case.
=> Fix warning printed when chunk key placeholder not replaced

lib/fluent/supervisor.rb, lib/fluent/system_config.rb, test/config/test_system_config.rb, test/test_supervisor.rb
follow up https://github.com/fluent/fluentd/pull/2674
Fix bug that log level in system config doesn't affect
need to change [log_level](https://docs.fluentd.org/deployment/system-config#log_level) default value https://github.com/fluent/fluentd-docs-gitbook/pull/122
=> Fix bug that log level in system config doesn't affect

lib/fluent/plugin/output.rb, test/plugin/test_output.rb
ref: https://github.com/fluent/fluentd/pull/2523
Fixed regext to match with https://github.com/fluent/fluentd/blob/7482802d75ba7b61a2997b15a02c45ff6a376e61/lib/fluent/plugin/output.rb#L753.
Be able to output a warning log even if  chunk_key is passed.
none
=> Fix regex and output warning log correctly

lib/fluent/root_agent.rb, test/test_root_agent.rb
ref https://github.com/fluent/fluentd/issues/2624
introduce at
https://github.com/fluent/fluentd/commit/ed93293a0360d839bb7da0183e0d4a06e19cbc1d
Label class's error_collector can not be not nil.
because error_collector is assigned a value by root_agent. and Lable
inherits Agent not RootAgent.
https://github.com/fluent/fluentd/blob/fcef949ce40472547fde295ddd2cfe297e1eddd6/lib/fluent/label.rb
no
no
=> This class is no more used

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
None
If the file path which in_tail plugin reads includes strftime format, it is determined by system timezone.
I want to determine this path in the specified timezone for each tail plugin object.
For example, a fluentd process reads a UTC file path ( `/path/to/data/test_utc/20191210_04.json` ) and a JST file path ( `/path/to/data/test_jst/20191210_13.json` ) in one conf.
```
$ TZ='Asia/Tokyo' ./bin/fluentd -c test.conf
2019-12-10 13:48:19 +0900 [info]: parsing config file is succeeded path="test.conf"
2019-12-10 13:48:19 +0900 [info]: using configuration file: <ROOT>
<source>
@type tail
path "/path/to/data/test_utc/%Y%m%d_%H.json"
pos_file "/path/to/pos/test_utc.pos"
tag "test_utc"
timezone "+00"
<parse>
@type …
```
=> format in_tail path with the specified timezone

lib/fluent/supervisor.rb
ref: https://github.com/fluent/fluentd/issues/2711
add log when inline_config is `-`. it's good to remove this feature in v1.20.0.
no need
no need
=> Add deprecated log for inline_config

lib/fluent/plugin/out_copy.rb, test/plugin/test_out_copy.rb
Fixes #2744 
Add `copy_mode` parameter to control no / shallow / deep copy.
Here is benchmark code:
```rb
require 'active_support/core_ext/object/deep_dup'
require 'fluent/event'
require 'fluent/time'
require 'msgpack'
test1 = Fluent::MultiEventStream.new
100.times { |i|
record = {"time" => 1362020400,"host" => "192.168.0.1","size" => 777,"method" => "PUT", "kubernetes" => {"pod" => "test", "labels" => {"app" => "foo"}}}
test1.add(Fluent::EventTime.now, record)
}
def f_n(es)
es
end
def f_d(es)
es.dup
end
def f_dd(es)
new_es = Fluent::MultiEventStream.new
es.each { |time, record|
new_es.add(time, record.deep_dup)
}
new_es
end
def …
```
=> out_copy: Add copy_mode parameter. fix #2744

lib/fluent/plugin/parser_ltsv.rb, test/plugin/test_parser_labeled_tsv.rb
I have not opened one yet.
The LTSV parser does not check whether the delimiter is in the pair before it tries to parse it. With `delimiter_pattern /\s+/` and `label_delimiter =`,If I give it the value:
```
"Sylvanus_007               : ok=45   changed=6"
```
it parses it like this:
```
{ "Sylvanus_007":null,":":null,"ok":"45","changed":"6" }
```
Both `Sylvanus_007: null` and `":": null` were never specified by key=value. This PR prevents this drastically wrong behavior and parses it like this:
```
{ "ok":"45","changed":"6" }
```
None
None
=> Prevent garbage from coming out of the LTSV parser

.travis.yml, Gemfile, fluentd.gemspec, lib/fluent/plugin_helper/http_server.rb, lib/fluent/plugin_helper/record_accessor.rb, lib/fluent/plugin_helper/server.rb
Fixes #2380 
See also: https://www.fluentd.org/blog/drop-schedule-announcement-in-2019
This is for fluentd v1.9.0 which will be released in 2020
Drop older rubies and related gems.
Need to update supported version
Same as title.
=> Drop ruby 2.1/2.2/2.3 support

lib/fluent/plugin/buffer.rb
https://github.com/fluent/fluentd/issues/2712
Fixes #
When writing chunks to buffer, the `stage_size` computation can be thread-unsafe as mentioned in the bug which can result in `BufferOverflowErrors` even though the buffer is not actually full. This happened on a live long running fluentd. The method `buffer.write` is supposed to write to a chunk atmost once and hence `stage_size` should be added for a chunk only once but due to `write_step_by_step` the block which updates the value of `staged_bytesize` may be called multiple times and the chunk can be rollbacked but the value of `staged_bytesize` is not reverted causing the `stage_size` to be more than the actual value.
This PR addresses this issue. 
**Docs …
=> Make stage_size & stage computation thread safe

lib/fluent/command/plugin_generator.rb, lib/fluent/plugin/parser.rb, lib/fluent/supervisor.rb, lib/fluent/test/driver/base.rb, test/config/test_system_config.rb, test/plugin/test_out_http.rb, test/test_supervisor.rb
none
Suppress warning for 2.7 found in https://travis-ci.org/fluent/fluentd/jobs/629889081?utm_medium=notification&utm_source=github_status
none
none
=> Suppress warning for 2.7

lib/fluent/plugin/output.rb, test/plugin/test_output.rb, test/plugin/test_output_as_buffered_secondary.rb, test/test_output.rb
No issue in this repository.
Current message is bit misleading for users. Some output plugins work with primary.
No need for now.
Same as title.
=> output: Show better message for different secondary type

lib/fluent/plugin/in_http.rb, test/plugin/test_in_http.rb
Fixes https://github.com/fluent/fluentd/issues/2754
none
=> Exact match for in http header

lib/fluent/config.rb, lib/fluent/engine.rb, lib/fluent/plugin/base.rb, lib/fluent/plugin/buf_file.rb, lib/fluent/plugin/buf_file_single.rb, lib/fluent/plugin/in_tail.rb, lib/fluent/plugin_id.rb, lib/fluent/root_agent.rb, lib/fluent/static_config_analysis.rb, lib/fluent/supervisor.rb, lib/fluent/variable_store.rb, test/test_config.rb, test/test_engine.rb, test/test_static_config_analysis.rb, test/test_supervisor.rb, test/test_variable_store.rb
Fixes https://github.com/fluent/fluentd/issues/2624
This change make fluentd be able to reload new config without restarting process with SIGUSR2 signal. 
it's very lighter and safer than existing reloading feature. but it has 2 limitations.
1.  A change to system_config is ignored because it needs to restart(kill/spawn) process. 
2. All plugins must not use class variable when restarting.
Add USR2 description.
same as title
=> Reload new config without restarting process

fluentd.gemspec, lib/fluent/command/plugin_generator.rb
none
Update development_dependency to latest version
none
none
=> Update development_dependency to latest version

lib/fluent/plugin_helper/server.rb
Which issue(s) this PR fixes:
Fixes #2772
What this PR does / why we need it:
Ignore unrecoverable error in SSL_accept
Docs Changes:
No need.
Release Note:
Same as title.
=> server: Ignore Errno::EHOSTUNREACH in TLS accept to avoid fluentd restart. #2772

fluentd.gemspec, lib/fluent/msgpack_factory.rb, lib/fluent/supervisor.rb, lib/fluent/system_config.rb, test/config/test_system_config.rb
No issue.
Recent msgpack-ruby can (de)serialize Time class.
Add `enable_msgpack_time_support` parameter to system config for this feature.
This is useful for multiple time fields.
See also: https://github.com/msgpack/msgpack-ruby#serializing-and-deserializing-time-instances
fluentd v2 will enable this feature by default.
Will add `enable_msgpack_time_support` to system config article after merged the patch.
Same as title.
=> Support Ruby's Time class in msgpack serde

lib/fluent/plugin/buffer.rb
Because this data will be differed unexpectedly on Windows.
This unexpected differing caused flood of buffer files
due to wrong metadata comparision.
`hash` method inside Metadata struct should be used on non-Windows environment.
This object_id value's unstability is monitored as follows:
```
{:timekey_object_id=>36247560}
{:timekey_object_id=>36247560}
{:timekey_object_id=>38199640}
{:timekey_object_id=>38199640}
{:timekey_object_id=>38199640}
{:timekey_object_id=>38240520}
{:timekey_object_id=>38240520}
{:timekey_object_id=>38240520}
{:timekey_object_id=>38277560}
{:timekey_object_id=>38277560}
{:timekey_object_id=>38277560}
{:timekey_object_id=>38314220}
{:timekey_object_id=>38314220}
{:timekey_object_id=>38314220}
{:timekey_object_id=>40539060}
{:timekey_object_id=>40539060} …
```
=> Don't use timekey.object_id for Metadata instance comparison on Windows. Fix #2713

lib/fluent/config/v1_parser.rb, test/config/test_config_parser.rb
Based on @repeatedly's patch:
https://github.com/fluent/fluentd/issues/2485#issuecomment-510105857
Fixes #2485 
Support @include/include directive for spaces included path.
Needed?
Same as title.
=> Support @include/include directive for spaces included path. Fix #2485

lib/fluent/plugin_helper/server.rb, test/plugin_helper/test_server.rb
Fixes #2768 
Set `IPV6_V6ONLY` to udp socket.
No need
Same at title.
=> server: Fix IPv6 dual stack mode issue for udp socket. fix #2768

test/plugin/test_in_exec.rb, test/plugin/test_in_forward.rb, test/plugin/test_in_object_space.rb, test/plugin/test_out_exec_filter.rb, test/plugin/test_out_forward.rb, test/plugin/test_output_as_buffered.rb, test/plugin/test_output_as_buffered_overflow.rb, test/plugin_helper/test_child_process.rb, test/plugin_helper/test_timer.rb, test/test_supervisor.rb, test/test_test_drivers.rb
none
Tests of fluentd became more stable than old versions. I tried to reduce the duration time of them for the next step.
As a result, reduced about 4 mins in ruby (17 min 43 sec ->  13 min 37 sec)
Before https://travis-ci.org/fluent/fluentd/jobs/637322326?utm_medium=notification&utm_source=github_status
After: https://travis-ci.org/fluent/fluentd/jobs/637798871?utm_medium=notification&utm_source=github_status
none
none
=> Reduce time of test

lib/fluent/plugin/in_tail.rb
none
config
```
<source>
@type tail
path ...
pos_file ...
tag ...
<parse>
</parse>
</source>
```
before
```
2020-01-24 15:03:15 +0900 [info]: parsing config file is succeeded path="example/debug/in_tail.conf"
2020-01-24 15:03:15 +0900 [info]: gem 'fluentd' version '1.9.0'
2020-01-24 15:03:15 +0900 [error]: config error file="example/debug/in_tail.conf" error_class=Fluent::ConfigError error="parse/@type is required."
```
after
```
2020-01-24 15:03:24 +0900 [info]: parsing config file is succeeded path="example/debug/in_tail.conf"
2020-01-24 15:03:24 +0900 [info]: gem 'fluentd' version '1.9.0'
2020-01-24 15:03:24 +0900 [error]: config error in:
<parse>
</parse>
2020-01-24 15:03:24 +0900 [error]: config error …
```
=> Parser's error is more informative

lib/fluent/plugin/parser_syslog.rb, test/plugin/test_parser_syslog.rb
Fixes #
RFC5424 (https://tools.ietf.org/html/rfc5424) supports multi-line syslog messages. Specifically, all octets are supposed to be accepted rather than treating \n as a end of message marker, see page 8 and 9 of the RFC. Proper framing and unframing of messages should be handled by the transport layer. Note, support for multi-line log is an explicit and intentional change in RFC5424 compared to the legacy syslog message format.
More importantly the existing implementation will reject any FRC5424 message that ends in a \n. Which has resulted in all fluentd syslog input plugins (both core and 3rd party) silently truncating all log messages. Sometimes with chomp, sometimes with rstrip, and sometimes just dropping …
=> Add multiline RFC5424 support

appveyor.yml
None
Fluentd v1.9.0 will support Ruby 2.4 or later. 
Current AppVeyor CI settings cause trouble on Ruby 2.3 due to Fluentd v1.9.0 bumping Ruby version requirements.
We should tidy up AppVeyor CI tasks for it.
None.
Same as title.
=> Follow AppVeyor CI task definitions for Fluentd v1.9.0

lib/fluent/plugin/in_tail.rb, lib/fluent/plugin/in_tail/position_file.rb, test/plugin/in_tail/test_position_file.rb
none
* Remove a entry from PositionFile when it is unwatched to release memory
* Change not to allow duplicated path lines (It does not happen unless a user change pos file manually)
no need
=> Remove a entry from PositionFile when it is unwatched

lib/fluent/plugin/output.rb, test/plugin/test_output_as_buffered_backup.rb
Fixes #2741 
Add `EncodingError` to unrecoverable errors to avoid infinite retry.
EncodingError can't be recovered.
Add `EncodingError` to output article.
Same as title.
=> output: Add EncodingError to unrecoverable errors. fix #2741

lib/fluent/plugin/out_http.rb, test/plugin/test_out_http.rb
ref https://github.com/fluent/fluentd/pull/2779#discussion_r368345580
Added warning message when a user uses a default `retryable_response_codes`  to remove 503 from `retryable_response_codes` next release(fluentd 2.0?).
no need
=> Add warning about retryable_response_codes

lib/fluent/plugin/out_forward.rb, lib/fluent/plugin/out_http.rb, lib/fluent/plugin_helper/cert_option.rb, lib/fluent/plugin_helper/server.rb, lib/fluent/plugin_helper/socket.rb, lib/fluent/tls.rb, test/plugin_helper/test_server.rb, test/test_tls.rb
- Fix bug of https://groups.google.com/forum/#!topic/fluentd/B818cI-OHdU
Add TLS module to unify fluentd code.
In addition, support recent SSLContext changes about TLS version
TODO: Add test soon
Add `min_version`/`max_version` to TLS transport.
- Add TLS module to unify code
- Allow TLS v1.3 when available
- Fix bug of TLS version setting
=> Add TLS module

lib/fluent/supervisor.rb, test/command/test_fluentd.rb
ruby does not have the option whose key and value are separated with space
https://github.com/ruby/ruby/blob/3893a8dd42fb3bbd71750648c3c0de118955a6ea/ruby.c#L1028
Fixes https://github.com/fluent/fluentd/issues/2801
no need
Accept RUBYOPT with two or more options
=> Split RUBYOPT with space

lib/fluent/supervisor.rb, test/test_supervisor.rb
Fixes https://github.com/fluent/fluentd/issues/2811
Logger applied with `format` and `format_time` is passed to serverengine so that serverengines' log is formatted with the fluentd's one.
no need.
```
{"time":"2020-02-03T15:20:07.423+0900","level":"info","message":"parsing config file is succeeded path=\"example/debug/log_time_format.conf\""}
{"time":"2020-02-03T15:20:07.423+0900","level":"info","message":"gem 'fluentd' version '1.9.1'"}
{"time":"2020-02-03T15:20:07.450+0900","level":"warn","message":"both of Plugin @id and path for <storage> are not specified. Using on-memory store."} …
```
=> serverengine's log should be formatted with the same format of fluentd.

.travis.yml, lib/fluent/supervisor.rb, test/command/test_fluentd.rb
ref: https://github.com/fluent/fluentd/issues/2799
When `RUBYOPT=a`(other invalid options do the same) is added,  fluentd gets into an infinite loop.
```
$ RUBYOPT=a be fluentd -c example/debug/dummy.conf                                                                                              
2020-02-03 16:27:32 +0900 [info]: parsing config file is succeeded path="example/debug/dummy.conf"
2020-02-03 16:27:32 +0900 [info]: gem 'fluentd' version '1.9.1'
2020-02-03 16:27:32 +0900 [warn]: both of Plugin @id and path for <storage> are not specified. Using on-memory store.
2020-02-03 16:27:32 +0900 [warn]: both of Plugin @id and path for <storage> are not specified. Using on-memory store.
2020-02-03 16:27:32 +0900 …
```
=> Fix bug when RUBYOPT is invalid

lib/fluent/plugin/in_tail.rb, lib/fluent/plugin/in_tail/position_file.rb, test/plugin/in_tail/test_position_file.rb, test/plugin/test_in_tail.rb
Fixes https://github.com/fluent/fluentd/issues/1126
note: merge after https://github.com/fluent/fluentd/pull/2803
needed
=> Impl posfile auto-compaction in in_tail

lib/fluent/supervisor.rb, test/command/test_fluentd.rb
merge after https://github.com/fluent/fluentd/pull/2813
Fix https://github.com/fluent/fluentd/issues/2799
note: 
~~I decided that fluentd uses the last option of `-E`, but I'm not sure it's the best way.
Any suggestions are welcome!~~
Use the encoding options(`-E`, `--encoding`,  `--external-encoding`, `--internal-encoding`) in RUBYOPT env var as it is if exists. if not fluentd `-Eascii-8bit:ascii-8bit`. https://github.com/fluent/fluentd/pull/2814/commits/f51154699ca30485473c4097208148e91d15e3ab#diff-dbe0e1ec4079138e48ca6a4d7c7248f9R884
no need
=> Use given encoding when RUBYOPT has -E

lib/fluent/plugin/in_http.rb
Fixes https://github.com/fluent/fluentd/issues/2820
nil check about `@origin`
no 
=> Fix when origin is nil in http input plugin

lib/fluent/plugin/parser_syslog.rb, test/plugin/test_parser_syslog.rb
Fixes https://github.com/fluent/fluentd/issues/2815
as described in the issue, updated the regex expression to cover the listed cases.
It's a bug fix, nothing doced should change
Improved for parsing RFC5424 structured data in `parser_syslog`
=> fix for RFC5424 parsing

lib/fluent/plugin/in_unix.rb
nope
socket and yaml are already required in L18 and L21
https://github.com/fluent/fluentd/blob/9d113029d4550ce576d8825bfa9612aa3e55bff0/lib/fluent/plugin/in_unix.rb#L18-L21
nope
nope
=> socket and yajl are already required in L18 and L21

lib/fluent/plugin/in_tail.rb
no
Cleanup in_tail file 
no 
no
=> Clenanup in tail

lib/fluent/plugin/buf_file.rb, lib/fluent/plugin/buffer.rb, lib/fluent/plugin/buffer/file_chunk.rb, test/plugin/test_buf_file.rb, test/plugin/test_buffer.rb, test/plugin/test_buffer_file_chunk.rb
Fixes https://github.com/fluent/fluentd/issues/2698
no need
=> Add seq to metadata that it can be unique

lib/fluent/plugin/in_tail.rb, lib/fluent/plugin/output.rb, lib/fluent/plugin_id.rb, lib/fluent/supervisor.rb, test/command/test_fluentd.rb, test/plugin/test_in_tail.rb, test/plugin/test_output_as_buffered_backup.rb, test/test_logger_initializer.rb, test/test_plugin_id.rb
Fixes https://github.com/fluent/fluentd/issues/2821
Specify the dir permission mode explicitly to avoid creating world writable dir in some env.
no need
Specify the dir permission mode explicitly
=> Specify the dir mode explicitly

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
no
Reduce `TailWatcher`'s arguments. it's hard to maintain now.
no
no
=> Reduce tailwatcher argument

test/plugin_helper/test_http_server_helper.rb
follow up https://github.com/fluent/fluentd/commit/2aa775ebc90373dc1db650122f75640893ff9522
no
no
=> Remove unnecessary condition

lib/fluent/env.rb, lib/fluent/plugin/buf_file.rb, lib/fluent/plugin/buf_file_single.rb, lib/fluent/plugin/buffer/file_chunk.rb, lib/fluent/plugin/buffer/file_single_chunk.rb, lib/fluent/plugin/in_tail.rb, lib/fluent/plugin/out_file.rb, lib/fluent/plugin/out_secondary_file.rb, test/plugin/test_buf_file.rb, test/plugin/test_buf_file_single.rb, test/plugin/test_buffer_file_chunk.rb, test/plugin/test_buffer_file_single_chunk.rb
follow up https://github.com/fluent/fluentd/pull/2827#pullrequestreview-360964414
Collect all dir and file permission into one place
no
no
=> Collect all dir and file permission into one place

lib/fluent/plugin/out_file.rb
No issues
This reverts #1995 changes. Recent fluentd doesn't have thread interruption issue for zlib.
No need
Same as title or put it in `clean up code` list.
=> out_file: Revert #1995 changes

lib/fluent/plugin/buffer/chunk.rb
=> chunk: Use Tempfile for decompressing as binmode

lib/fluent/plugin/in_tail.rb
after https://github.com/fluent/fluentd/pull/2837
no
no
=> Flush buffer is invoked in line buffer

lib/fluent/plugin/in_tail.rb
https://github.com/fluent/fluentd/pull/2843/files
follows up https://github.com/fluent/fluentd/pull/2843
I've noticed that I moved log.warn out of the else cond in https://github.com/fluent/fluentd/pull/2843/files#diff-1da710c9dcc8d0fc57996df7a9d39695L450-L451. so I reverted the change. 
no
no
=> log should be in else cond

lib/fluent/plugin/in_tail.rb, lib/fluent/plugin/parser_multiline.rb, test/plugin/test_in_tail.rb, test/plugin/test_parser_multiline.rb
no
Fix the data loss in in_tail when emit_unmatched_lines  is enabled.
Add unmatched_lines to multiline parser
=> Fix the data loss in in_tail when emit_unmatched_lines  is enabled.

test/plugin/test_in_tail.rb, test/plugin/test_output_as_buffered_backup.rb, test/test_logger_initializer.rb, test/test_plugin_id.rb, test/test_supervisor.rb
Related to #2854.
* Omit/Fix permission related testcases.
* Prevent raising error on `$log.out.reset` for non `Fluent::Test::DummyLogDevice` instance case.
We should take care of AppVeyor CI result.
No needed.
None.
=> Fix appveyor ci round1

lib/fluent/plugin/buf_file.rb, lib/fluent/plugin/buffer.rb, test/plugin/test_buf_file.rb, test/plugin/test_buffer.rb
Follow up https://github.com/fluent/fluentd/pull/2824
In #2824, I added `seq` to Metadata class so that it can identify the chunks which are created in Buffer#write_step_by_step for Buffer#resume.
When chunks are queued, their `metadata.seq` should be 0 for `@queued_num`. so I change seq to 0 when the chunks are queue. 
no
=> When chunks are queued, their `metadata.seq` should be 0

test/command/test_fluentd.rb
Related to #2854.
* Fix permission related testcases on Fluentd command.
* Fix `#create_cmdline` method to handle launching Fluentd on Windows
We should take care of AppVeyor CI result.
No needed.
None.
=> Fix appveyor ci for fluentd command testcases

lib/fluent/plugin_helper/server.rb
No issue
Follow `on_readable` and identify what is the cause.
With trace level, users hard to find ssl setting mistake.
No need.
Same as title.
=> server helper: Change SSLError log level to warn in accept

lib/fluent/plugin_helper/socket_option.rb, test/plugin/test_buf_file.rb
Related to #2854.
* Omit deleting ephemeral buffer file due to permission error.
* Windows does not permit removing files which are used in another process even if administrator.
* Fix `linger_timeout` handling on Windows
We should take care of AppVeyor CI result.
No needed.
None.
=> Fix appveyor ci for round3

lib/fluent/plugin/out_forward.rb
[The previous commit](https://github.com/fluent/fluentd/pull/2862/commits/7d16531c0fdf05763f25efb4b1cdb4314b1b1f70) solved linger_timeout member types glitch.
In the previous linger_timeout behavior is always occurring dropping data.
But the fixing member type glitches, Fluentd can handle linger_timeout on Windows.
This type glitch causes overflow and then linger_timeout should be 0.
So, this is why specifying linger_timeout causes data loss on Windows.
LIBC: { int l_onoff; int l_linger; } # I!I!
Winsock: { u_short l_onoff; u_short l_linger; } #S!S!
Really fixes for https://github.com/fluent/fluentd/issues/1968.
Reverted https://github.com/fluent/fluentd/pull/2398
No Fixes.
**What this PR does / why …
=> out_forward: windows: Permit to specify linger_timeout

test/plugin/in_tail/test_position_file.rb, test/plugin/test_in_forward.rb, test/plugin/test_out_forward.rb
Related to #2854.
* Fix expected position in posfile
* Use correct error message on connecting error
* Sort by tag name instead of timestamps which are same integer value (this causes unstable result)
We should take care of AppVeyor CI result.
No needed.
None.
=> Fix appveyor ci for round4

test/helper.rb
None.
Without this patch, we need to run testcases with `bundle exec rake test` or additional `TEST_OPTS` environment variable to run individual testcases.
```
~\Documents\GitHub\fluentd [master ≡ +6 ~0 -0 !]> bundle exec ruby .\test\plugin\test_bare_output.rb
Traceback (most recent call last):
3: from ./test/plugin/test_bare_output.rb:1:in `<main>'
2: from ./test/plugin/test_bare_output.rb:1:in `require_relative'
1: from C:/Users/cosmo/Documents/GitHub/fluentd/test/helper.rb:52:in `<top (required)>'
C:/Users/cosmo/Documents/GitHub/fluentd/test/helper.rb:52:in `require': cannot load such file -- helpers/fuzzy_assert (LoadError)
```
`ruby …
=> test: Use require_relative for test helpers files

lib/fluent/plugin/sd_file.rb, test/plugin/test_sd_file.rb
adding a test for raising an error.
no need
no need
=> test: skip if error is occured

lib/fluent/plugin/buffer.rb, test/plugin/test_buffer.rb
Fixes https://github.com/fluent/fluentd/issues/2857
To return correct number of available ration.
no need
=> Fix bug available_buffer_space_ratios which is set 0 or 1

lib/fluent/plugin/out_forward.rb, lib/fluent/plugin/out_forward/handshake_protocol.rb, test/plugin/out_forward/test_handshake_protocol.rb, test/plugin/test_out_forward.rb
out_forward ensures that password and username are not nil because sd_file can pass the server whose password and username are nil.
https://github.com/fluent/fluentd/blob/026c0d7234eda99e3b5519d8dbf457995eb077b5/lib/fluent/plugin/sd_file.rb#L131-L132
no need
=> out_forward ensures that password and username are not nil

lib/fluent/plugin/sd_srv.rb, test/plugin/test_sd_srv.rb
follow up https://github.com/fluent/fluentd/pull/2496
needed
Same as the title
=> Support  service discovery with SRV record

test/plugin/test_in_tail.rb
Fixes https://travis-ci.org/github/fluent/fluentd/jobs/663376812#L619
Fluent::Test::Driver#run assumes that it emits the mount of message bigger than `expect_emits`.
https://github.com/fluent/fluentd/blob/4d7cb814064c244841c3c94c977ed8dd2e530de0/lib/fluent/test/driver/base_owner.rb#L124
no need
no need
=> emit_count can be bigger than num_events

lib/fluent/plugin_helper/cert_option.rb, lib/fluent/plugin_helper/server.rb
No issue.
Support user defined verifier for certificate via `cert_verifier` parameter.
This parameter uses `SSLContext#verify_callback` internally.
- conf
```
<transport tls>
client_cert_auth true
cert_verifier /path/to/cert_checker.rb
</transport>
```
Code must be return callbale object. It means returned object must have `#call` method with 2 arguments.
- Proc or lambda for simple case
```
Proc.new { |ok, ctx|
}
```
- Use class for complicated case
```
class HooBarChecker
def initialize
end
def call(ok, ctx)
end
end
HooBarChecker.new
```
Here is actual command and conf: https://gist.github.com/repeatedly/6df9881d7ce62bcf321e2a07799d8909 …
=> server: Add cert_verifier parameter for TLS transport

lib/fluent/plugin/in_dummy.rb, test/plugin/test_in_dummy.rb
introduced in
https://github.com/fluent/fluentd/commit/c612e64a637012da946e2b2fa7bbf746bc44b798
and no need since https://github.com/fluent/fluentd/commit/7a547624b36bb0c4c20b3b9b6c91ac4235362df0
no need
no need
=> Delete suspend parameter

test/plugin/test_in_tail.rb
fixes https://travis-ci.org/github/fluent/fluentd/jobs/663388229#L761
`@tails` can be 0 after Driver::Base#run
when [this line](https://github.com/fluent/fluentd/blob/2b7ed60ddc7edbab0dcbb57d4a13c4dd5175512d/lib/fluent/test/driver/base.rb#L96
) is performed between [#setup_watcher](https://github.com/fluent/fluentd/blob/2b7ed60ddc7edbab0dcbb57d4a13c4dd5175512d/lib/fluent/plugin/in_tail.rb#L334) in [#start_watchers](https://github.com/fluent/fluentd/blob/2b7ed60ddc7edbab0dcbb57d4a13c4dd5175512d/lib/fluent/plugin/in_tail.rb#L368) and [setting the value to @tails](https://github.com/fluent/fluentd/blob/2b7ed60ddc7edbab0dcbb57d4a13c4dd5175512d/lib/fluent/plugin/in_tail.rb#L …
=> Wait until `@tails` is set a new watcher

test/plugin/test_compressable.rb
Fixes https://travis-ci.org/github/fluent/fluentd/jobs/662952965#L617
Making gzip's header uses time so it doesn't return the same value.
https://github.com/ruby/ruby/blob/afd23ed0491b9df0b6a1753a2f66cd3f80428930/ext/zlib/zlib.c#L2520
```rb
require 'zlib'
require 'stringio'
def compress(data, **kwargs)
output_io = kwargs[:output_io]
io = output_io || StringIO.new
Zlib::GzipWriter.wrap(io, Zlib::DEFAULT_COMPRESSION, Zlib::FILTERED) do |gz|
gz.write data
end
output_io || io.string
end
@src = 'text data for compressing' * 5
v = compress(@src)
sleep 2                         # needed
io = StringIO.new
a = compress(@src, output_io: io)
v1 = a.string
if v != v1
p v
p v1
end
```
no need
**Release …
=> Make compress test stable

test/command/test_fluentd.rb
Fixes https://travis-ci.org/github/fluent/fluentd/jobs/660453169#L1233
When data is bigger than 1024, data loss can happen.
This causes like this unstable test https://travis-ci.org/github/fluent/fluentd/jobs/660453169#L1233
no need
no need
=> When data is bigger than 1024, data loss can happen

test/plugin/test_output_as_buffered_secondary.rb
Fixes https://travis-ci.org/github/fluent/fluentd/jobs/664260115#L1720
If it exceeds the retry limit,  https://travis-ci.org/github/fluent/fluentd/jobs/664260115#L1720 can happen (setting nil to `@retry`).
https://github.com/fluent/fluentd/blob/b18f995335b5d573cfbb56bc3e2759c2d287da67/lib/fluent/plugin/output.rb#L1241
if `i` become over 10, `@i.retry` can be `nil`.
https://github.com/fluent/fluentd/blob/b18f995335b5d573cfbb56bc3e2759c2d287da67/test/plugin/test_output_as_buffered_secondary.rb#L619-L625
no need
no need
=> Avoid timeout of retry state

test/plugin/test_in_dummy.rb
Fixes https://travis-ci.org/github/fluent/fluentd/jobs/663376812#L619
Extend timeout and remove unnecessary emit(decreasing rate)
emitting data issues a lot of IO
https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin_helper/storage.rb#L275-L283
it can take some time
no need
no need
=> Extend timeout and remove unnecessary emit(decreasing rate)

lib/fluent/msgpack_factory.rb, test/test_msgpack_factory.rb
Fixes https://github.com/fluent/fluentd/issues/2871
Stop to output a deprecated warning multiple times.
fluent-plugin-google-cloud uses  Fluent::Engine.msgpack_factory and the method changed  deprecated in [this commit](https://github.com/fluent/fluentd/commit/7b166f08f1f1c5d7aa8f49709843bc0b332ee33e).
https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/65b9d0e1afdec26ea14e01d7a731f05d499d3477/lib/fluent/plugin/out_google_cloud.rb#L1912
The deprecated method print [warning log]( https://github.com/fluent/fluentd/commit/fcd467c722c491919c7044c772e9e49ead3ef787#diff-2127cc829c2d543c1d9564680b1d4050R33) and it causes the performance issue.
no need
same as the …
=> Stop to output deprecated warning log about MessagePackFactory::Mixin multiple times for performance

lib/fluent/plugin/parser_syslog.rb, test/plugin/test_parser_syslog.rb
Fixes https://github.com/fluent/fluentd/issues/2856
Setting `time_format`  in syslog hasn't worked well in some situations.
I made a change to work with all formats.  There is no performance degradation.
```rb
require 'fluent/env'
require 'fluent/engine'
require_relative '../lib/fluent/plugin/parser_syslog'
parser = Fluent::Plugin::SyslogParser.new
parser.configure(Fluent::Config::Element.new('ROOT', '', {'keep_time_key' => true}, []))
log = 'Feb 28 12:00:00 192.168.0.1 fluentd[11111]: [error] Syslog test'
parser2 = Fluent::Plugin::SyslogParser.new
parser2.configure(Fluent::Config::Element.new('ROOT', '', {'with_priority' => true, 'keep_time_key' => true}, []))
log2 = '<1>Feb 28 12:00:00 …
```
=> Syslog parser works with any time format

test/plugin_helper/test_child_process.rb
Fixes https://cloud.drone.io/fluent/fluentd/449/1/2, https://travis-ci.org/github/fluent/fluentd/jobs/662889852?utm_medium=notification&utm_source=github_status
It can take some time to output lines
no need
no need
=> It can take some time to output lines

test/plugin/test_output_as_buffered_secondary.rb
Follow up https://github.com/fluent/fluentd/pull/2901
in this test retry_state = 60. So `i` should be less than 9
https://github.com/fluent/fluentd/blob/b18f995335b5d573cfbb56bc3e2759c2d287da67/lib/fluent/plugin_helper/retry_state.rb#L134
no need
no need
=> 60 * 0.8 + 2 * i should be less than retry_state

lib/fluent/command/fluentd.rb, lib/fluent/daemonizer.rb, test/test_daemonizer.rb
Fixes https://github.com/fluent/fluentd/issues/2735
fix bugs when a user gives  `--daemon` and `--no-supervisor` as options.
no need
no need
=> Enable combination daemon and no supervisor

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
Fixes https://github.com/fluent/fluentd/issues/2917
A type of pos_file_compaction_interval is time.
no need
=> Fix pos_file_compaction_interval type

lib/fluent/plugin/parser_syslog.rb, test/plugin/test_in_syslog.rb, test/plugin/test_parser_syslog.rb
Fixes https://github.com/treasure-data/omnibus-td-agent/issues/245
Convert string to integer of pri in syslog parser.
no need
=> Fix regression in the case with_priority and rfc5424

lib/fluent/plugin/in_tail/position_file.rb, test/plugin/in_tail/test_position_file.rb
Fixes https://github.com/fluent/fluentd/issues/2918
Update seek position of position file entry after compaction. if some position files are compacted, others' seek position change.
no need
=> Update seek position of position file entry

lib/fluent/plugin/out_copy.rb
ref https://github.com/fluent/fluentd/issues/2928
Added output.plugin_id into log message of out_copy in order to identify which output plugin the error happens is
no need
=> Add output.plugin_id into log message of out_copy

lib/fluent/plugin_helper/socket.rb, test/plugin_helper/test_http_server_helper.rb, test/plugin_helper/test_server.rb
ref: https://github.com/fluent/fluentd/issues/2699
Suppress warning of verify_hostname
https://travis-ci.org/github/fluent/fluentd/jobs/671447462#L758
no need
no need
=> Suppress warning of verify_hostname

test/plugin/test_in_tail.rb
Fixes https://travis-ci.org/github/fluent/fluentd/jobs/670028558#L1924, https://travis-ci.org/github/fluent/fluentd/jobs/671897056#L746
This test checks that tail_watcher must be empty when the tailed file no longer exists.
No need to check object count since it's very fragile
no need
no need
=> This test checks that tail_watcher must be empty

test/plugin/test_output_as_buffered_retries.rb
Fixes https://travis-ci.org/github/fluent/fluentd/jobs/671460800#L624
wait until next interval
https://github.com/fluent/fluentd/blob/02f34e74b2209281ac56974722be1d449cf4dbc0/lib/fluent/plugin/output.rb#L1462
no need
no need
=> Fix unstable test

lib/fluent/supervisor.rb, test/command/test_fluentd.rb
Fixes #2915
On testing arguments in RUBYOPT, command line arguments aren't quoted so that it will fail if ruby command (which is passed as the first arugment) is placed under a directory which contains spaces.
Since `C:\Profram Files\` is the default application directory on Windows, it may be unfriendly for Windows users.
This patch uses `spawn(program, *args)` instead of `spawn(command, options={})` to fix it.
no need
no need
=> Allow to launch fluentd from `C:\Program Files\`

lib/fluent/log.rb, lib/fluent/supervisor.rb, lib/fluent/system_config.rb, test/config/test_system_config.rb, test/test_log.rb
No issue
Specify interval to ignore repeated log/stacktrace messages.
Under high loaded environment, output destination sometimes becomes unstable and it causes lots of logs with same message. This parameter mitigates such situation.
Add `ignore_repeated_log_interval` to system config.
Same as title.
=> log: Add ignore_repeated_log_interval parameter

lib/fluent/plugin/out_forward.rb, test/plugin/test_out_forward.rb
ref https://github.com/fluent/fluentd/issues/2926
If connection sockets raise some errors, the cached socket is revoked.
Revoked cached socket(`@inactive_sockets`) must be deleted by
purge_obsolete_socks method so that memory usage doesn't increase.
https://github.com/fluent/fluentd/blob/0e901e7974232dd05f098ad74ea5be956aaba0e3/lib/fluent/plugin/out_forward/connection_manager.rb#L99
https://github.com/fluent/fluentd/blob/0e901e7974232dd05f098ad74ea5be956aaba0e3/lib/fluent/plugin/out_forward/socket_cache.rb#L63
This memory leak happens when keepalive and user_auth are on.
The memory leaking is easier to detect in TLS connection than in TCP connection since a lot of error can happen in …
=> Creating timer of purging obsolete sockets if keepalive_timeout is nil

test/plugin/test_in_tail.rb
Fix https://travis-ci.org/github/fluent/fluentd/jobs/674236542#L752
if timeout is given, the breaking condition is set. 
https://github.com/fluent/fluentd/blob/a8b6d6ff4aa83bb0f7c8aa54f3367018383236d6/lib/fluent/test/driver/base.rb#L81
if breaking condition is true, it passed without errors. So timeout must be removed.
https://github.com/fluent/fluentd/blob/a8b6d6ff4aa83bb0f7c8aa54f3367018383236d6/lib/fluent/test/driver/base.rb#L215
no need
same as title
=> Remove unnecessary timeout to fix unstable test

lib/fluent/plugin/out_forward.rb, test/plugin/test_out_forward.rb
Ref https://github.com/fluent/fluentd/issues/2926
When you turn keepalive config on and sending heartbeat and sending data happens at the same time, sending heartbeat creates new connection. The new heartbeat connection doesn't try to do user auth. So if the connection is used for sending data,  the error will happen.
no need
=> Need authentication when sending tcp heartbeat and keepalive in out_forward

lib/fluent/command/fluentd.rb
Follow up of #2912 
Don't daemonize supervisor's worker. It is handled by serverengine.
=> command: Avoid daemonize for supervisor's worker

lib/fluent/plugin/out_forward.rb
None
Enabling SO_LINGER causes tcp port exhaustion on Windows.
This is because dynamic ports are only 16384 (from 49152 to 65535) and
expiring SO_LINGER enabled ports should wait 4 minutes where set by TcpTimeDelay.
Its default value is 4 minutes.
So, we should disable SO_LINGER on Windows to prevent flood of waiting ports.
No needed.
Same as title
=> windows: Disable specifying linger_timeout again

lib/fluent/match.rb, lib/fluent/plugin/parser_multiline.rb
No issue.
fluentd dropped ruby 2.3 or earlier, so we can use `match?` for faster matching.
No need
Improve regexp match with `match?` method.
=> '#match?' is better than '#match'

lib/fluent/config.rb
Ref https://github.com/fluent/fluentd/issues
Added a warning log
no need
same as title
=> Make ruby dsl config deprecated

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
Avoid duplicates in path config
- removed duplicate in path config
- added testcase
Fixes # None
**What this PR does / why we need it**: Avoid duplicates in path config
**Docs Changes**: Needed
=> Avoid duplicates in path config

lib/fluent/plugin_helper/service_discovery.rb, lib/fluent/plugin_helper/service_discovery/manager.rb, test/plugin_helper/test_service_discovery.rb
Fixes https://github.com/fluent/fluentd/issues/2972
The plugins which are managed by service discovery manager are not called lifecycle method such as `after_start`,  `stop`,  `before_shutdown`, `shutdown`, `after_shutdown`, `close`, and  `terminate`. This causes that these plugins last forever because they can't notice fluentd is stopping. so threads don't stop and fluentd kill the thread forcibly.
no need
Fix warning of service discovery manager when fluentd stops.
=> Fix warning of sd manager

lib/fluent/plugin_helper/record_accessor.rb, test/plugin_helper/test_record_accessor.rb
No issue
Add `set` method to record_accessor.
This method will be used in `<record>`'s nested update.
Add `set` section to record_accessor article.
Same as title.
=> record_accessor: Add set method for nested record

lib/fluent/plugin/out_http.rb, test/plugin/test_out_http.rb
Signed-off-by: Roman Geraskin <roman.n.geraskin@gmail.com>
Fixes #2909 
This PR implements the `json_array` option (bool, default false) for the out_http plugin. With this option, we can use the JSON array data format for the HTTP request body.
Docs update required.
This is quick and easy feature implementation, sort of proof of concept. I will be grateful for any feedback.
=> PoC: json_array switch to use json array data format for HTTP request body

lib/fluent/plugin/in_dummy.rb, lib/fluent/plugin/in_forward.rb, lib/fluent/plugin/in_http.rb, lib/fluent/plugin/in_monitor_agent.rb, lib/fluent/plugin/in_unix.rb, lib/fluent/plugin/out_file.rb, lib/fluent/plugin/out_forward.rb, lib/fluent/test/filter_test.rb, lib/fluent/test/output_test.rb, test/plugin/test_in_unix.rb
No issue.
`Engine.now` is wrapper of `EventTime.now` for backward compatibility.
Use `EventTime.now` is better.
No need
Refactoring.
=> Use EventTime.now instead of Engine.now

lib/fluent/supervisor.rb
Fixes #2984 
Add missing `File.umask(0)` for standalone worker mode.
With supervisor, serverengine handles chuser, chgroup and chumask here.
https://github.com/treasure-data/serverengine/blob/master/lib/serverengine/multi_process_server.rb#L79-L80
No need
Same as title
=> supervisor: Call File.umask for standalone worker. fix #2984

lib/fluent/plugin/out_forward/load_balancer.rb, test/plugin/out_forward/test_load_balancer.rb
=> Fix ZeroDivisionError when one node and its weight is 0 

lib/fluent/plugin/in_gc_stat.rb, test/plugin/test_in_gc_stat.rb
None
`in_gc_stat` is used to check GC stat. This plugin assumes output plugin is stdout. For other output plugins, need to emit string key record.
No need.
Same as title.
=> in_gc_stat: Add use_symbol_keys parameter

lib/fluent/plugin/parser_syslog.rb, test/plugin/test_parser_syslog.rb
Follow up of #2886 
Support non-standard `time_format` in rfc3164 string parser.
Keep original implementation for the performance.
```
regexp    22.144k i/100ms
string    50.456k i/100ms
regexp    241.978k (± 4.8%) i/s -      1.218M in   5.047216s
string    589.696k (± 4.0%) i/s -      2.977M in   5.057291s
regexp    22.600k i/100ms
string    37.845k i/100ms
regexp    249.855k (± 2.7%) i/s -      1.266M in   5.069147s
string    435.649k (± 4.3%) i/s -      2.195M …
```
=> parser_syslog: Support configured time_format for rfc3164 string parser

lib/fluent/plugin/parser_syslog.rb, test/plugin/test_parser_syslog.rb
Fixes #2997
Follow up of https://github.com/fluent/fluentd/pull/2599
Add non-regexp parser to fix issues and improve the performance
New parser is 2x faster than current regexp based parser.
```
require 'fluent/env'
require 'fluent/engine'
require_relative 'lib/fluent/plugin/parser_syslog'
log1 = '<16>1 2017-02-06T13:14:15.003Z 192.168.0.1 fluentd - - - Hi, from Fluentd!'
log2 = '<16>1 2017-02-06T13:14:15.003Z 192.168.0.1 fluentd 11111 ID24224 [exampleSDID@20224 iut="3" eventSource="Application" eventID="11211"] [Hi] from Fluentd!'
parser = Fluent::Plugin::SyslogParser.new
parser.configure(Fluent::Config::Element.new('ROOT', '', …
```
=> syslog_parser: Add string parser for rfc5424

lib/fluent/plugin/in_unix.rb, test/plugin/test_in_unix.rb
No issue
Use v1 plugin API in `in_unix` plugin.
In addition, add `tag` parameter to follow `in_forward`.
Add tag parameter
Same as title.
=> in_unix: Use v1 plugin API

lib/fluent/plugin/parser_syslog.rb, test/plugin/test_parser_syslog.rb
None
Improve the syslog parser code
- bit faster with `match?` for `auto` mode
- make code clean and remove unnecessary condition
No change.
Improve syslog parser and add new parser for rfc5424
Merge #3015 and this into 1 release note.
=> Improve syslog parser

lib/fluent/command/fluentd.rb
This will allow the fluentd Windows service to be registered as delayed auto-start (https://docs.microsoft.com/en-us/windows/win32/api/winsvc/ns-winsvc-service_delayed_auto_start_info).
=> Allow the Fluentd Windows Service to be "Automatic (Delayed start)".

lib/fluent/plugin/in_tail.rb
fix #3038
Put actual path instead of base pattern into ignore list.
No need
Same as title.
=> in_tail: Use actual path instead of pattern for ignore list. ref #3038

lib/fluent/plugin/in_http.rb, test/plugin/test_in_http.rb
Ref #3036 
Accept time_type / time_format to support string time value.
In addition, move `rescue` position to separate 400 and 500.
After merge this PR, I will send clean up PR.
Add `time_format` example to in_http.
Same as title.
=> in_http: Improve time field processing

lib/fluent/plugin_helper/child_process.rb, test/plugin_helper/test_child_process.rb
If I use exec output plugin with `command` which writes data to stdout (i.e. /bin/echo foo), the command fails due to SIGPIPE(13).
```
2020-06-18 20:00:08 +0900 [debug]: #0 Executing command title=:out_exec_process spawn=[{}, "/bin/echo foo.bar.baz foo /tmp/fluent-plugin-out-exec-20200618-8149-1hyzffl"] mode=[] stderr=:connect
...
2020-06-18 20:00:08 +0900 [warn]: #0 command exits with error code prog="/bin/echo foo.bar.baz foo /tmp/fluent-plugin-out-exec-20200618-8149-1hyzffl" status=nil signal=13
```
Setting the stdout to /dev/null via spawn_opts rather than after spawning process should fix this.
=> Fix child process failure due to SIGPIPE if the command uses stdout

lib/fluent/plugin/in_http.rb
Follow up: #3046 
in_http has duplicated code and creates new object for fixed values.
This patch fixes these points.
No need.
Same as title.
=> in_http: refactoring

lib/fluent/match.rb, test/test_match.rb
Fixes #3057
Allow a (plain) regex as MatchPattern in <filter .... >
With a regex - assertion it allows a pattern that matches a tag not starting with a string. I think the regex MatchPattern can also replace the commented-out carachter classes.
Following lines should be added to https://docs.fluentd.org/configuration/config-file#how-match-patterns-work:
Starting with fluentd <version> a match pattern may be a regex by enclosing the regex with slashes.
A regex match pattern looks like <filter /regex/>
This allows character classes or match patterns _not_ starting with a string.
```
<filter a.** >
....
</filter
<filter /(?!a\.).*/ >
....
</filter>
```
For a complete list of supported regex …
=> MatchPattern: allow regex patterns

lib/fluent/plugin_helper/cert_option.rb, lib/fluent/plugin_helper/socket.rb, test/plugin_helper/test_cert_option.rb, test/plugin_helper/test_socket.rb
Fixes #3085
Raise an error instead of warning message for broken cert.
No need.
Same as title.
=> Raise an error for broken certificate file. fix #3085

lib/fluent/plugin/buffer.rb
Object#object_id should return values the following rule:
```
On Windows:
irb(main):140:0> RUBY_VERSION
=> "2.7.1"
irb(main):141:0> a = 2**30 - 1
irb(main):142:0> a.object_id
=> 2147483647
irb(main):143:0> a = 2**30 - 1
irb(main):144:0> a.object_id
=> 2147483647
irb(main):145:0> a = 2**30
irb(main):146:0> a.object_id
=> 640
irb(main):147:0> a = 2**30
irb(main):148:0> a.object_id
=> 660
```
For Windows, less than equal `2^30 - 1` should be stable and be able to use with #hash.
---
```
On GNU/Linux x86_64:
irb(main):001:0> RUBY_VERSION
=> "2.7.0"
irb(main):002:0> a = 2**30 - 1
irb(main):003:0> a.object_id
=> 2147483647
irb(main):004:0> a = 2**30 - 1
irb(main):005:0> a.object_id
=> 2147483647
irb(main):006:0> a = 2**30
irb(main):007:0> a.object_id
=> 2147483649
irb(main):008:0> a = 2**30 …
```
=> buffer: Do more precise timekey optimization handling. Fix #3088

lib/fluent/plugin_helper/cert_option.rb, test/plugin_helper/test_server.rb
None.
Since `SSL_CTX_set_ssl_version()` of older OpenSSL reverts to the default
ciphers list, `SSL_CTX_set_cipher_list()` has to be called after that.
OpenSSL 1.1.1 doesn't have this issue.
See also:
https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/ssl/ssl_lib.c#L285
https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/ssl/ssl_ciph.c#L1473
None.
Same as title.
=> Set TLS ciphers list correcty on older OpenSSL

fluentd.gemspec
Our td-agent 4 building system can detect dependent gem versions with
bundler.
So, we should update dependent gem versions to be "bundler friendly".
None. But it is needed for releasing td-agent 4.0.1.
Our new td-agent building system detects dependent gem versions.
But, currently, Fluentd locks win32 gems' version.
No need.
Same as title.
=> Upgrade win32 related gem dependency for Windows

lib/fluent/plugin/in_exec.rb, test/plugin/test_in_exec.rb
Fixes #3091
Add `connect_mode` parameter to read stderr message.
This is useful for debugging.
Need to add `connect_mode` parameter to in_exec article.
Same as title.
=> in_exec: Add connect_mode parameter to read stderr. fix #3091

lib/fluent/plugin/buffer.rb, test/plugin/test_buffer.rb
The `oldest_timekey` stat in buffer is broken.
The current approach of using `add_timekey` and `del_timekey` to track the count of chunks in each timekey doesn't work as intended - the count is never decreased to zero because of complications in chunk creation, as a result the `oldest_timekey` stat is almost never updated after initial flush(es).
A simple and not-so-timely alternative, to perform recalculation in every flush cycle.
Signed-off-by: Ji-Ping Shen <ji-ping.shen@relexsolutions.com>
=> buffer: Fix calculation of timekey stats

test/plugin/test_in_tail.rb, test/plugin_helper/test_http_server_helper.rb
In Windows, aborted testcases seems to be aborted with self certficates and
`Errno::ECONNABORTED`. These will be disabled for now. But they needed to debug.
none
For Windows CIs, we hadn't seen green for a bit of long time.
This is inconvenient to confirm whether PR patches will break backward compatibility or not. 
No needed.
No needed.
=> test: Turn off aborted testcases on windows

lib/fluent/plugin/buffer.rb, lib/fluent/plugin/output.rb
Follow up: #3018 
- Skip timekeys calculation when no time chunk key. This is for the performance.
- Improve/refactor buffer code
No need
Listed in Refactoring code section.
=> Refactor buffer code

lib/fluent/log.rb, lib/fluent/supervisor.rb, lib/fluent/system_config.rb, test/test_log.rb
No issues
We noticed `ignore_repeated_log_interval` is not enough for some frequent log generation case.
For example, if plugin generates several log messages in one action, logs are not repeated:
```
def write(chunk)
log.error "message1"
log.error "message2"
end
```
`ignore_same_log_interval` resolves these cases. With this option, logger keeps to store all log messages for validation. The number of log message is limited, so increased memory usage is ignorable.
Add `ignore_same_log_interval` to system parameters.
Same as title.
=> Add ignore_same_log _interval parameter

lib/fluent/plugin/buffer/chunk.rb
Fixes #3110 
I had a same problems as the issue.
Just set binmode, not use return value.
It is because IO#binmode returns File not Tempfile, so It would be collected by GC in if block.
```
irb(main):001:0>  require 'tempfile'
=> true
irb(main):002:0>  a = Tempfile.new("example")
=> #<Tempfile:/var/folders/bm/69m8bqqd343fx6vddc3lkqyc0000gp/T/example20200929-59624-zqnwq>
irb(main):003:0>
irb(main):004:0> a.binmode
=> #<File:/var/folders/bm/69m8bqqd343fx6vddc3lkqyc0000gp/T/example20200929-59624-zqnwq>
irb(main):005:0> a.binmode?
=> true
irb(main):006:0> a
=> #<Tempfile:/var/folders/bm/69m8bqqd343fx6vddc3lkqyc0000gp/T/example20200929-59624-zqnwq>
irb(main):007:0> a.class
=> Tempfile
irb(main):008:0> b = a.binmode
=> …
```
=> chunk: fix binmode usage for prevent gc

lib/fluent/plugin/out_http.rb
Fixes #3139 
`buf_memory`'s `read` returns same object. Don't use destructive method to avoid broken data.
No need
Same as title
=> out_http: Don't use destructive method for json_array. fix #3139

lib/fluent/plugin_helper/inject.rb, test/plugin_helper/test_inject.rb
It is useful to add timestamp as milliseconds since Unix epoch.
This is the short hand to add the filed using filter
record_transformer like followings:
```
<filter>
@type record_transformer
enable_ruby
<record>
time ${time.to_f.floor(3) * 1000}
</record>
</filter>
```
This is useful to reduce data size with presto like system such as AWS Athena with S3.
**Docs Changes**: Need
Add unixtime_millis to inject plugin helper
=> Add unixtime_millis to inject plugin helper

lib/fluent/plugin/output.rb, test/plugin/test_output.rb
The updated implementation makes sure to replace instances of
${chunk_id} prior to looking for and warning on unreplaced keys in the
pattern. Prior to this, a warning line was printed for every chunk that
was flushed even though nothing was actually wrong (replacement happened
right after).
Signed-off-by: Brian Atkinson <brian@atkinson.mn>
None filed.
When using the s3 output plugin, with the `path` set to `"${tag}/%Y/%m/%d/%H/${chunk_id}_#{ENV['RUN_ID']}_#{worker_id}"` the fluentd process would print a log line like the following for every chunk flushed.
```
2020-09-25 00:32:49 +0000 [warn]: #1 [s3_output] chunk key placeholder 'chunk_id' not replaced. template:${tag}/%Y/%m/%d/%H/${chunk_id}_6ead9663854b0799849b47 …
```
=> output: Replace ${chunk_id} before logging warning.

lib/fluent/plugin/formatter.rb, lib/fluent/plugin/formatter_hash.rb, lib/fluent/plugin/formatter_json.rb, lib/fluent/plugin/formatter_ltsv.rb, lib/fluent/plugin/formatter_out_file.rb, lib/fluent/plugin/formatter_single_value.rb, lib/fluent/plugin/formatter_tsv.rb, test/command/test_binlog_reader.rb, test/plugin/test_filter_stdout.rb, test/plugin/test_formatter_hash.rb, test/plugin/test_formatter_json.rb, test/plugin/test_formatter_ltsv.rb, test/plugin/test_formatter_out_file.rb, test/plugin/test_formatter_single_value.rb, test/plugin/test_formatter_tsv.rb, test/plugin/test_out_file.rb, test/plugin_helper/test_compat_parameters.rb, test/test_formatter.rb, test/test_output.rb
Fixes #3151 
Currently, built-in formatter plugins use hard-coded LF newline.
We should provide CRLF style newline choice mainly for Windows users.
https://github.com/fluent/fluentd-docs-gitbook/pull/247
Same as title.
=> Provide CRLF newline style choice on formatter plugins. Fix #3151

lib/fluent/plugin/out_http.rb
Signed-off-by: Tzach Yarimi <tyarimi@salesforce.com>
THIS PR REPLACES #3101 (switching the head branch)
Fixes #
Add support for sending a client certificate chain for mutual TLS authentication in the `out_http` plugin.
(same as PR name)
=> out_http: adding support for intermediate certificates (supersedes #3101)

fluentd.gemspec, lib/fluent/supervisor.rb, test/test_supervisor.rb
None.
[Fluentd uses win32 event](https://github.com/fluent/fluentd/blob/1c28d6ed0cf346c322fbca92bb4eafa65307c3eb/lib/fluent/supervisor.rb#L180) for shutting down windows service. In this mechanism, it uses `stop` method of `ServerEngine::Supervisor` to send a command to workers to stop them gracefully. But current implementation calls `kill_worker` before it so that [workers are killed forcedly](https://github.com/fluent/fluentd/blob/1c28d6ed0cf346c322fbca92bb4eafa65307c3eb/lib/fluent/supervisor.rb#L237) before sending commands. It doesn't make sense.
This PR removes the needless `kill_worker` call.
You can confirm the issue by shutting down a fluentd process by the following procedure
* Run fluentd with …
=> Fix a bug that windows service isn't stopped gracefuly

fluentd.gemspec
Fixes #1481
It fixes the following error with `fluentd --gemfile Gemfile`
when bundler is not installed.
error: Gem::MissingSpecError
No need to change
NOTE: since ruby 2.6 or later, bundler is bundled with ruby itself,
so this error has occurred with ruby 2.5 which will reach EOL
at 2021-03-31.
=> Fix missing runtime bundler dependency

appveyor.yml
Via #3153 PR, I've found Windows CI fails.
There is an install issue on Windows about http-protocol2.
It breaks Windows CI when executing bundle install.
ref. https://github.com/socketry/protocol-http2/issues/6
It seems that even though 0.14.0, it doesn't affect functionality because the only https://github.com/socketry/protocol-http2/commit/8769e9f8dfcb95c6e7bd015002a74a82bb14a83f is commited.
No need to change.
No need to change.
=> windows: use protocol-http2 0.14.0 explicitly

test/plugin/test_in_tail.rb
Fixes: #3166
It will fix the following error on windows (especially AppVeyor CI).
```
Failure: test_emit_with_read_lines_limit[flat 10](TailInputTest::singleline)
C:/projects/fluentd/test/plugin/test_in_tail.rb:243:in `test_emit_with_read_lines_limit'
240:       end
241:
242:       events = d.events
=> 243:       assert_equal(true, events.length > 0)
244:       assert_equal({"message" => msg}, events[0][2])
245:       assert_equal({"message" => msg}, events[1][2])
246:       assert num_events <= d.emit_count
<true> expected but was
<false>
```
No need to change
No need to change
=> windows test in_tail: relax timeout limitation to receive events

.travis.yml, lib/fluent/capability.rb, lib/fluent/env.rb, lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb, test/test_capability.rb
Fixes #3053 
Currently, Fluentd core does not handle/refer Linux capability.
This class should handle/refer Linux capability.
Note that this class implementation is only working for Linux with
libcap-ng binding (capng_c) installed platform.
In other platform, this class only returns stubbed results.
in_tail should handle Linux capabilities.
In in_tail, File.readable? does not handles Linux capabilities.
So, we should handle them by libcap-ng binding wrapped class
which is Fluent::Capability.
On in_tail, the following capabilities should be handled:
* CAP_DAC_READ_SEARCH(:dac_read_search on capng_c)
* CAP_DAC_OVERRIDE(:dac_override on capng_c)
Needed. ~~I'll write and register Linux capability …
=> Handle linux capability if available

lib/fluent/plugin/buffer.rb
With this patch, Fluentd on armv7l Linux environment can handle optimized `#hash` method in Metadata.
```
fluent@497f8dcf9876:/fluentd$ uname -a
Linux 497f8dcf9876 4.9.140-tegra #1 SMP PREEMPT Mon Dec 9 22:52:02 PST 2019 aarch64 GNU/Linux
```
<details>
From outside armhf container:
```
$ for i in {1..100}; do echo '{"status":"OK"}' | bundle exec fluent-cat test; done
```
```
fluent@497f8dcf9876:/$ echo '<source>
@type forward
port 24224
</source>
<match test.**>
@type file
path log/%Y%m%d.${tag}
append true
<buffer tag,time>
@type file
path log/
timekey 1d
</buffer>
</match>
' > /fluentd/etc/issue3088.conf
fluent@497f8dcf9876:/$ cd fluentd
fluent@497f8dcf9876:/fluentd$ fluentd -c /fluentd/etc/issue3088.conf -vvv
2020-08-04 08:32:01 …
```
=> buffer: Enable optimization for metadata comparison in all platform

lib/fluent/plugin/formatter.rb, lib/fluent/plugin/formatter_csv.rb, lib/fluent/plugin/formatter_hash.rb, lib/fluent/plugin/formatter_ltsv.rb, lib/fluent/plugin/formatter_out_file.rb, lib/fluent/plugin/formatter_single_value.rb, lib/fluent/plugin/formatter_tsv.rb
Follow up: https://github.com/fluent/fluentd/pull/3152
- Add `freeze` to string parameter
- Remove duplicated `freeze`
No need
Add this to Refactoring code
=> Make better use of freeze

bin/fluent-cap-ctl, lib/fluent/command/cap_ctl.rb, test/command/test_cap_ctl.rb
Please review #3155 first.
None. Follows up #3155
Linux capability operation should be handled in Fluentd management command.
This should be unified interface to add/drop/get/clear operations for Ruby executables which are used to execute Fluentd supervisor and worker(s).
Needed.  ~~I'll send a PR to describe this command.~~
https://github.com/fluent/fluentd-docs-gitbook/pull/249
Same as title.
=> Add fluent-cap-ctl command to handle add/drop/get/clear capability operations

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml
Fixes N/A
In the previous version, there are only two choices for
bug and feature request.
So Fluentd user tends to use "Bug Report" even though it is not a
bug report definitely.
This PR try to add third choice explicitly to guide to user forum.
Before:
* Bug Report
* Feature request
After:
* Bug Report
* Feature request
* Ask a question
Additionally, the explanation about bug report is updated to emphasize
it is a "Bug Report".
N/A
N/A
=> github: add a guide to google groups

lib/fluent/command/plugin_config_formatter.rb, lib/fluent/plugin.rb, test/command/test_plugin_config_formatter.rb
None
Non abbreviate form of `new_service_discovery` is needed for fluent-plugin-config-formatter comand.
No needed?
Same as title.
=> Handle service_discovery type on fluent-plugin-config-formatter

lib/fluent/plugin_helper/http_server/compat/server.rb
None
Otherwise, Ruby 2.7 complains with the following warnings (also Fluentd master doesn't take care of it):
```log
/usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/plugin_helper/http_server/compat/server.rb:84: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.5/lib/fluent/plugin_helper/http_server/compat/webrick_handler.rb:26: warning: The called method `build' is defined here
```
No need.
Same as title.
=> plugin_helper: server: compat: Suppress keyword arguments incompatibiity warnings

lib/fluent/plugin/in_tail.rb, lib/fluent/plugin/in_tail/position_file.rb, test/plugin/in_tail/test_position_file.rb, test/plugin/test_in_tail.rb
Revive of #1660  
From #1660:
> Add ability to track inodes inside fluentd in_tail plugin to enable combination of '*' in `path` configuration with rotation inside same directory and `read_from_head` set to true. In proposed solution we add `follow_inodes` flag (set to `false` by default to preserve current behavior). When `follow_inodes` is set to `true` and file rotation is detected - we do not reread file, instead we are checking if such inode is present inside pos file - if yes, we don't recreate TailWatcher. TailWatcher is closed after `rotate_wait` period and file marked as unwatched inside position file after `limit_recently_modified` time passed. Pos file is cleaned on startup as it was before, but also …
=> Add follow_inodes parameter on in_tail

lib/fluent/plugin/in_tail.rb, lib/fluent/plugin/in_tail/position_file.rb, test/plugin/in_tail/test_position_file.rb, test/plugin/test_in_tail.rb
Follows up #3182 
Unify path and inode arguments.
No needed.
Same as title.
=> Refactor path and inode arguments related code

lib/fluent/plugin/output.rb, lib/fluent/plugin_helper/retry_state.rb
Fixes #2123
This PR prevents `@retry.step` from being called too many times in a short time by ensuring that the current time is greater than or equal to `@retry.next_time` to call it.
As all the flush threads share `@retry`, `@retry.step` can be called almost as many times as the number of the threads in a short time, and there is a possibility that one of them reaches the retry limit before the plugin transits to the secondary output. That is the reason why all chunks are sometimes dropped without transition to the secondary.
You can confirm the behavior using the following files:
```conf
<source>
@type sample
auto_increment_key id
rate 20
tag sample
</source>
<match sample.**>
@type sleep_and_fail # the …
```
=> Prevent retry.step from being called too many times in a short time

.github/workflows/stale-actions.yml
N/A
Disable mark as "stale" when the issue is marked as "feature request".
This is change for GitHub stale Actions.
N/A
N/A
=> github workflow: ignore "feature request" from stale bot target

bin/fluent-ctl, lib/fluent/command/ctl.rb, lib/fluent/supervisor.rb, lib/fluent/winsvc.rb, test/command/test_ctl.rb, test/test_supervisor.rb
None
Since Windows doesn't have UNIX signals, features realized by them such as flushing buffers aren't implemented on Windows.
This PR adds triggers for them by using win32 events. Currently only supervisor process supports them.
In addition, this PR adds a new command `fluent-ctl`. It sends a simple command to a fluentd process.
The main purpose of this command is that providing a kill command alternative on Windows.
On UNIX, it just only send a UNIX signal to a specified process.
```
Usage: fluent-ctl COMMAND PID_OR_SIGNAME
Commands:
shutdown
restart
flush
reload
```
SIGNAME can be specified by fluentd's "-x" or "--signame" option.
Note that this command doesn't support sending events to windows service. …
=> Add win32 events alternative to unix signals

lib/fluent/plugin/in_tcp.rb
Not bound to specific issue
in_udp plugin shows log message when starting server, but this
behavior is not true for in_tcp plugin.
For consistency it is better to show startup message.
[info]: #0 listening tcp socket bind="..." port=...
This change is introduced that there is a case that inconsistency log
leads confusion when in_tcp and in_udp is used at the same time.
N/A
N/A
=> in_tcp: show listening address and port for consistency with in_udp

lib/fluent/plugin_helper/inject.rb, lib/fluent/time.rb, test/plugin_helper/test_inject.rb
This PR adds new time types "unixtime_micros" and "unixtime_nanos" to inject time for the same reason as https://github.com/fluent/fluentd/pull/3145.
If we collect docker container logs using the fluentd logging driver, we need to sort the logs by the time to merge logs from various containers. Although we can now specify unixtime_millis, logs with line feed sometimes have the same time in milliseconds. As a result, the logs are sorted in the wrong order. This PR will resolve the problem by introducing new types of unixtime with higher precision.
Needed. I'll create a pull request to change [configuration/inject-section.md#time-parameters](https://github.com/fluent/fluentd-docs-gitbook/blob/71e49c869fb4e5416a528f6d77b35f8a67b17bac/ …
=> Support unixtime_micros and unixtime_nanos to inject time

README.md
Seems not to be part of the fluentd-docs-gitbook repo anymore.
So let's use the image from the main website, like done in other parts
of the REAMDE.md.
Fixes a dead link the the README.md.
Update link location.
=> Fix fluentd architecture image location in README

test/plugin/test_parser_syslog.rb
No issue
Fix fixed-year test failure in `test_parser_syslog.rb`
No need.
Same as title.
=> test_parser_syslog: Fix 2020-year failure

lib/fluent/plugin/out_http.rb, test/plugin/test_out_http.rb
Fixes #3237
Add `headers_from_placeholders` parameter to set placeholder based header.
```
headers_from_placeholders {"x-foo-bar":"${$.foo.bar}","x-tag":"app-${tag}"}
<buffer tag,$.foo.bar>
</buffer>
```
Add `headers_from_placeholders` to `out_http` article.
Same as title
=> out_http: Add headers_from_placeholders. fix #3237

lib/fluent/command/plugin_config_formatter.rb, templates/plugin_config_formatter/param.md-table.erb, test/command/test_plugin_config_formatter.rb
You can see list of parameters at a glance with --compact option
Before:
```
* name (type) (required?) description
* Available values: ...
* Default value: ...
* Alias:
* Deprecated:
* Obsoleted:
```
After:
```
|parameter|type|description|default|
|---|---|---|---|
|...|...|...|...|
```
=> fluent-plugin-config-format: use markdown table

.github/workflows/build.yaml
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>
This config converts .travis.yml to GitHub Actions, as discussed with @edsiper some time ago.
Still in progress, I'd like to hear the project maintainer's feedback on the current file version and we'll iterate later.
=> GitHub Actions build action added

lib/fluent/command/ca_generate.rb, test/plugin_helper/test_http_server_helper.rb, test/plugin_helper/test_server.rb
none
Some TLS related tests are failed as of OpenSSL 1.1.1f due to creating
broken certification files. Although a value of `nsCertType` extension
should be `OpenSSL::ASN1::BitString` but previous code passed raw string.
OpenSSL 1.1.1e or before doesn't reject such certifications.
To create valid extensions, use `OpenSSL::X509::ExtensionFactory` instead.
none
same with the title
=> Fix creating TLS certification files which include broken extensions

lib/fluent/command/fluentd.rb, lib/fluent/supervisor.rb, lib/fluent/system_config.rb, test/command/test_fluentd.rb, test/test_supervisor.rb
none
Fluentd always creates ServerEngine::SocketManager's shared socket even if it's not required. The shared socket isn't needed if there is no plugin that uses it such as in_forward, in_http and in_syslog.
Although it can be disabled if Fluentd doesn't use multiple workers, this patch adds `disable_shared_socket` instead of checking number of workers to keep backward compatibility for third-party plugins (`PluginHelper::Server.create_server_connection` uses shared socket by default).
Opening a needless socket may cause conflict with other applications especially on Windows because `ServerEngine::SocketManager` uses TCP socket on Windows.
* Add `disable_shared_socket` to …
=> Add an option to disable shared socket forcedly

fluentd.gemspec, test/plugin/test_out_http.rb
none
CI on Ruby 3.0 & head fail because webrick isn't installed.
WEBrick isn't bundled anymore as of Ruby 3.0.
none
none
=> Add a missing dependency to webrick

.github/ISSUE_TEMPLATE/config.yml
N/A
As migration to discource instance is announced, I've updated navigation link.
Moving to discourse forums
https://groups.google.com/g/fluentd/c/z6e4ziIfzdo
README.md should be updated in another PR.
N/A
=> Update navigation link to https://discuss.fluentd.org/

test/command/test_fluentd.rb
none
RubyInstaller sets RUBYOPT=-Eutf8 by default as of 2.7, it breaks
precondition of these tests.
```
Failure: test: ruby path contains spaces(TestFluentdCommand::configured to run 2 workers):
execution timeout.
<"\r\n" +
"aho@SKYLAKE C:\\Users\\aho\\Projects\\fluentd\\test\\tmp\\command\\fluentd>C:/Ruby27-x64/bin/ruby.exe C:/Users/aho/Projects/fluentd/bin/fl
uentd -c C:/Users/aho/Projects/fluentd/test/tmp/command/fluentd/space_mixed_ruby_path_test.conf \r\n" +
"2021-02-23 10:39:35 +0900 [info]: parsing config file is succeeded path=\"C:/Users/aho/Projects/fluentd/test/tmp/command/fluentd/space_mix
ed_ruby_path_test.conf\"\r\n" +
"2021-02-23 10:39:35 +0900 [info]: gem 'fluentd' version '1.12.1'\r\n" + …
```
=> Clear RUBYOPT while running some tests for fluentd command

test/plugin/in_tail/test_position_file.rb
N/A
It is a straight forward enough approach to use File.stat for these
test cases.
In test case, setup creates a temporary file and each test case try to access 
via Fluent::Filewrapper.stat but it causes INVALID_HANDLE_VALUE.
N/A
N/A
=> test: avoid conflict access to tempfile on windows

lib/fluent/plugin/in_tail.rb
This is a minimal attempt to fix #3274. While I was here I was also trying to address #3224.
I'd appreciate quick review first, happy to add changelog/release note entry later.
=> in_tail: expect ENOENT during stat (try to fix #3274 and #3224)

lib/fluent/plugin/out_forward.rb, test/plugin/test_out_forward.rb
* Fixes #3137
* Suspend try_flush in before shutdown phase
* Confirm ack until after shutdown phase or last try_write
Signed-off-by: yugo-horie <yugo-horie@jocdn.co.jp>
Fixes #3137
Now we use fluentd for collecting the huge amount of access logs through the 200 over on-premises hosts.
And we often necessary to restart fluentd for some maintenance. So we usually test that log transmit has done well if fluentd restart  considering the maintenance during the log transmission. Although we always failed this test for log duplication.
Thus, We open the issue #3137
During the digging of the fluentd's behaviors, we found the mechanism of duplicating transmit chunks in @forward
see also: …
=> Prevent from deplicating transmit reload forward

lib/fluent/plugin/out_forward.rb, test/plugin/test_out_forward.rb
none
Some nitpicks for #3267
* Suppress a warning while testing out_forward
> warning: instance variable @delayed_commit_timeout not initialized
* Use more meaningful name for a method (`set_interval` -> `ack_select_interval`)
none
none
=> Follow up #3267

lib/fluent/time.rb, test/test_time_parser.rb
Use Case 1: Most of timestamp format is unixtime, but some entry use %iso8601
```
time_type mixed
time_format_fallbacks unixtime, %iso8601
```
Use Case 2: Most of timestamp format is %iso8601, but some entry use unixtime
```
time_type mixed
time_format_fallbacks %iso8601, unixtime
```
Fixes #3248
Even though time format is changed from time to time, there is no
need to workaround (define multiple filter for each format)
It should be documented on https://docs.fluentd.org/configuration/parse-section#time-parameters
N/A
=> Support multiple kind of timestamp format

lib/fluent/plugin/out_copy.rb, test/plugin/test_out_copy.rb
Revised #3190
In this revised version, I added a testcase fix for https://github.com/fluent/fluentd/pull/3190#discussion_r538052270.
According to #3130:
> This PR makes a change in the Copy Output plugin so you can inform the fluentd to ignore said copy if the previous output succeeded.
> This enables having multiple nested outputs as backup of each other by doing:
> ```aconf
>    <store ignore_error>
>      @type test
>      name c0
>    </store>
>    <store ignore_if_prev_success ignore_error>
>      @type test
>      name c1
>    </store>
>    <store ignore_if_prev_success>
>      @type test
>      name c2
>    </store>
> ```
> Adding the defined ignore_if_prev_successes attribute to the tag …
=> Revise feat ignore_if_prev_successes to copy plugin

lib/fluent/plugin/formatter_ltsv.rb, test/test_formatter.rb
Revise #1666
formatter_ltsv creates malformed LTSV files when values include tabs.
This PR prevent it by replacing tabs with spaces.
`replacement` should be added to https://docs.fluentd.org/parser/ltsv
=> formatter_ltsv: suppress delimiters in output

test/plugin/test_in_tail.rb
N/A
This PR aims to fix in_tail test cases on Windows.
On Windows, when the file or directory is removed and created
frequently, there is a case that creating file or directory will fail.
This situation is caused by pending file or directory deletion which
is mentioned on win32 API document.
ref. https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea#files
As a workaround, execute rename and remove method.
N/A
N/A
=> test in_tail: use safer method to cleanup

lib/fluent/config/types.rb, lib/fluent/plugin/storage_local.rb
None
DeepSource complains that fluentd uses insecure methods:
* `Kernel.open`: https://deepsource.io/gh/cosmo0920/fluentd/issue/RB-SC1004/
* `JSON.load`: https://deepsource.io/gh/cosmo0920/fluentd/issue/RB-SC1002/occurrences
No need.
Same as title.
=> Use more secure methods

lib/fluent/plugin/in_tail.rb
Related to #3292
If a file is mv-ed and a new file is created during calling `#refresh_watchers`s, and `#refresh_watchers`
won't run `#start_watchers` and `#stop_watchers` for the path because `#target_paths_hash` always contains the path.
No need.
Same as title
=> in_tail: Handle to send rotated logs when mv is used for rotating

lib/fluent/command/plugin_config_formatter.rb
Follow up for #3240.
Suppress the following message while testing FluentPluginConfigFormatter:
```
2021-03-17T05:57:52.3545997Z /home/runner/work/fluentd/fluentd/lib/fluent/command/plugin_config_formatter.rb:165: warning: instance variable @table not initialized
```
none
none
=> Fill an uninitialized instance variable of FluentPluginConfigFormatter

lib/fluent/command/plugin_generator.rb
Fixes N/A
In the previous version, <name> of prefix is not mentioned in fluent-plugin-generate -h
Before:
```
Usage: fluent-plugin-generate [options] <type> <name>
Generate a project skeleton for creating a Fluentd plugin
Arguments:
type: input,output,filter,parser,formatter
name: Your plugin name
Options:
--[no-]license=NAME          Specify license name (default: Apache-2.0)
```
After:
```
Usage: fluent-plugin-generate [options] <type> <name>
Generate a project skeleton for creating a Fluentd plugin
Arguments:
type: input,output,filter,parser,formatter
name: Your plugin name (fluent-plugin- prefix will be added to <name>)
Options:
--[no-]license=NAME          Specify license name (default: Apache-2.0)
```
**Docs …
=> fluent-plugin-generate: add note about plugin name

fluentd.gemspec, test/plugin/out_forward/test_connection_manager.rb, test/plugin/test_out_forward.rb, test/plugin/test_output.rb, test/plugin_helper/service_discovery/test_manager.rb, test/plugin_helper/test_http_server_helper.rb, test/test_output.rb
Related to #3263
Older rr did not support Ruby 3.0. We should upgrade rr to 3.0.
No needed.
Same as title.
=> Use rr 3.0 on unit tests for Ruby 3.0 kwargs changes

lib/fluent/plugin/parser_csv.rb, lib/fluent/plugin/parser_syslog.rb, test/plugin/test_parser_csv.rb, test/plugin/test_parser_syslog.rb
Fixes #3296
These plugins accept a parameter `plugin_type` but it hides the parent
class's method `Fluent::Plugin::Parser#parser_type`, it causes
unexpected behavior on a plugin which uses this method such as in_exec.
We may need to update the following pages:
* https://docs.fluentd.org/parser/csv
* https://docs.fluentd.org/parser/syslog
But I think it's not needed because this patch keeps backward compatibility, and adding a new parameter name may confuse users.
=> parser_csv, parser_syslog: Fix a naming conflict on parser_type

lib/fluent/plugin_helper/socket_option.rb, test/plugin_helper/test_server.rb
Allow incoming TLS connections to use keep-alive socket option when a listener is created, such as the`send_keepalive_packet` option in `forward` input. It's currently blocked by `socket_option_validate!`
We've been using this on several busy production servers for 2 months and haven't experienced any problem.
`send_keepalive_packet` is critical in some network setup, for instance in ours where AWS sometimes turned connections from private network into zombies - they linger and keep accumulating until fluentd is restarted, while according to clients they should have been closed normally days or weeks earlier. (I suspect there might be some bug in async socket closing but  couldn't confirm or investigate) …
=> plugin_helper: Allow TLS to use keep-alive socket option

.github/workflows/windows-test.yaml
Related #3263
There are some failed unit test with Ruby 3.0 on windows,
Instead of omitting those test cases, it may be better
to mark "experimental" to clarify the issues.
N/A
N/A
=> test: mark Ruby 3.0 as experimental on windows

.gitlab-ci.yml
None
* Update Ruby versions used on GitLab CI
* Fix build error on GitLab CI.
None
None
=> GitLab CI: Update to use latest Ruby

test/plugin/test_out_forward.rb
none
It fixes the following error:
Error: test: a node supporting responses after stop(ForwardOutputTest): Fluent::Test::Driver::TestTimedOut: Test case timed out with hard limit.
/home/runner/work/fluentd/fluentd/lib/fluent/test/driver/base.rb:201:in `rescue in run_actual'
/home/runner/work/fluentd/fluentd/lib/fluent/test/driver/base.rb:196:in `run_actual'
/home/runner/work/fluentd/fluentd/lib/fluent/test/driver/base.rb:95:in `run'
/home/runner/work/fluentd/fluentd/lib/fluent/test/driver/base_owner.rb:130:in `run'
/home/runner/work/fluentd/fluentd/test/plugin/test_out_forward.rb:651:in `block in <class:ForwardOutputTest>'
In addition, add a timeout and an assertion to help investigating on failure/error cases. …
=> Fix an unstable test for ack response of out_forward

test/plugin/test_in_tail.rb
none
This commit try to fix the following failure:
```
2021-04-02T00:47:45.1133120Z Failure: test_truncate_file(TailInputTest)
2021-04-02T00:47:45.1140150Z /Users/runner/work/fluentd/fluentd/test/plugin/test_in_tail.rb:606:in `test_truncate_file'
2021-04-02T00:47:45.1140850Z      603:     end
2021-04-02T00:47:45.1141130Z      604:
2021-04-02T00:47:45.1141450Z      605:     events = d.events
2021-04-02T00:47:45.1141920Z   => 606:     assert_equal(3, events.length)
2021-04-02T00:47:45.1142440Z      607:     assert_equal({"message" => "test3"}, events[0][2])
2021-04-02T00:47:45.1142960Z      608:     assert_equal({"message" => "test4"}, events[1][2])
2021-04-02T00:47:45.1143490Z      609:     assert_equal({"message" …
```
=> Fix an unstable test of in_tail (especially on macOS)

test/plugin/test_output_as_buffered_backup.rb
Related #3263
In busy loop with wait_flush, there may be a case that Dir.glob() lose
existing entries under target directory in some test cases.
As a result Timeout::Error: execution expired will be raised.
These failures in test/plugin/test_output_as_buffered_backup
are observed with Ruby 3.0 on Windows.
N/A
N/A
=> test: add tiny wait not to lose globbed entries

lib/fluent/plugin/file_wrapper.rb, test/plugin/test_file_wrapper.rb
none
Fluent::WindowsFile passes win32 error codes to SystemCallError so that it doesn't show
correct message for them. For example when ERROR_SHARING_VIOLATION(32)
of win32 occurs, it shows Errno::EPIPE(32).
none
same with the title
=> WindowsFile: Fix incorrect error message

lib/fluent/plugin/file_wrapper.rb, test/plugin/test_file_wrapper.rb
none
In #3325 we added Win32Error to show Windows specific errors correctly,
but it's not enough for debugging because it doesn't show which file
causes the error.
none
none, same with #3325
=> WindowsFile: Show the path when Win32Error is occured

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
Fixes #3327
#3275 fixes a crash bug of in_tail, but it introduces another crash bug which may occur on catching a very short-lived log.
none
Same as title
=> in_tail: Fix an incorrect error handling on catching a short-lived log

lib/fluent/plugin/file_wrapper.rb, test/plugin/test_file_wrapper.rb
none
Additional fix for #3325 and #3329.
Since the previous code doesn't have to_s method, it shows only` Fluent::Win32Error`, doesn't show the detail.
none
Same with #3325
=> Win32Error: Add to_s and inspect methods

lib/fluent/plugin/storage_local.rb
Potentially fixes #3332
Let's use unique names for temporary files like this:
kubernetes.json.tmp.5c04a66a9731459acb723c5ee7d8d279
instead of:
kubernetes.json.tmp
This makes LocalStorage.save() practically atomic, and hence allows
Fluentd not to corrupt data even in a race condition.
Not required.
Fix position file corruption issue on concurrent gracefulReloads.
=> storage_local: change LocalStorage.save() to be atomic

README.md
None
We already moved from Travis CI to GitHub Actions. I recommend to display GitHub Actions CI results with its status badges.
No needed.
Same as title.
=> Use GitHub Actions' status badges instead of Travis CI's

lib/fluent/plugin/output.rb, test/plugin/test_output.rb
Fixes #3338
On some setup, Fluentd warns about "chunk_id" being not found in
`@chunk_keys`.
This warning is misguided. `${chunk_id}` is a special field that
Fluentd should automatically fill it with `chunk.unique_id`. It
should never try to look up the key in `@chunk_keys`.
This patch fixes the warning by adjusting the evaluation order,
extending the preceding work f18640bf5 by Brian Atkinson.
None
Fix incorrect warnings about `${chunk_id}` with `out_s3`
=> output: Fix "placeholder chunk_id not replaced" warnings

fluentd.gemspec, lib/fluent/plugin/file_wrapper.rb
none
WindowsFile calls GetLastError via win32-api to retrieve win32 error
code but the error code may be already reset by Ruby's internal code
so that it can't retrive a correct error code. Sometimes it causes
random unrecoverable errors when in_tail plugin tries to read a
non-existent file like the following:
2021-04-14 03:15:45 +0000 [error]: #2 Fluent::Win32Error code: 158, The segment is already unlocked.: C:/path/to/log.txt
Fiddle or FFI has a method to avoid this issue:
* Fiddle.win32_last_error
https://ruby-doc.org/stdlib-3.0.0/libdoc/fiddle/rdoc/Fiddle.html#method-c-win32_last_error
* FFI::LastError.winapi_error
https://www.rubydoc.info/github/ffi/ffi/FFI/LastError#winapi_error-instance_method
We've added …
=> WindowsFile: Retrieve correct Win32 error codes

fluentd.gemspec
We recommend to use win32-service v2.2.0 or later for updating outdated
win32-serivce gem.
None
see: https://github.com/fluent-plugins-nursery/td-agent-builder/pull/288/checks?check_run_id=2387368140#step:3:62002
No needed
Same as title.
=> Permit to install with win32-service 2.2.0 on Windows

lib/fluent/plugin_helper/server.rb
Fixes #3309
When a client with invalid TLS certificates is trying to connect,
following logs will be outputted repeatedly, but it doesn't include
peer information. It's hard to investigate which client has the
problem.
```
2021-03-31 08:08:58 +0000 [warn]: #1 unexpected error before accepting TLS connection by OpenSSL error_class=OpenSSL::SSL::SSLError error="SSL_accept SYSCALL returned=5 errno=0 state=SSLv3/TLS write server done"
2021-03-31 08:08:58 +0000 [warn]: #1 unexpected error before accepting TLS connection by OpenSSL error_class=OpenSSL::SSL::SSLError error="SSL_accept returned=1 errno=0 state=error: sslv3 alert bad certificate"
2021-03-31 08:08:58 +0000 [warn]: #0 unexpected error before accepting TLS …
```
=> TLSServer: Add peer information to error log message

lib/fluent/plugin_helper/service_discovery.rb, lib/fluent/plugin_helper/service_discovery/manager.rb, test/plugin_helper/test_service_discovery.rb
The current `service_discovery` plugin helper requires users (plugin authors) to build `configurations` structure as shown in [this document](https://docs.fluentd.org/plugin-helper-overview/api-plugin-helper-service_discovery).
But in most cases, service discovery types and configurations are written in `conf` and they can be read from the plugin helper scope. So, the current API requires additional things to plugins.
This change is to:
* Configure `discovery_manager` almost automatically only by calling `#service_discovery_configure` method in `Plugin#configure`
* Support service directives without `<service_discovery>` directive (the pattern of `out_forward`)
* Follow the manner about method names with `service_discovery_` prefix
**Docs …
=> Configure Service Discovery using plugin helper with automatically loaded configurations

lib/fluent/plugin/out_forward.rb, lib/fluent/plugin_helper/service_discovery.rb, test/plugin/test_out_forward.rb
none
Apply a new helper method added at #3299 to out_forward.
This PR is revised version of #3300 which was closed unexpectedly.
Same with #3299
Same with #3299
=> Apply newer service_discovery plugin helper methods

lib/fluent/command/fluentd.rb, lib/fluent/log.rb, lib/fluent/supervisor.rb, lib/fluent/system_config.rb, test/config/test_system_config.rb, test/test_config.rb, test/test_supervisor.rb
Fixes N/A
In the previous versions, log rotation options were supported as
--log-rotate-age or --log-rotate-size via command line options.
On Windows, as fluentd is launched as a windows service, it is
required to configure again via --reg-winsvc-fluentdopt or edit
fluentdopt registry key for customization.
This approach is not convenient for Windows users, so it may be better
to support more comprehensive solution - customize via configuration
file.
This commit introduces such a configurable parameter in .conf
```
<system>
<log>
rotate_age 5
rotate_size 1048576
</log>
</system>
```
TODO: https://docs.fluentd.org/deployment/logging#by-config-file should be updated.
N/A
=> Enable system.log.rotate_... system configuration

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
Follows up #3185 
In this case, timer watcher tells file contents every 1 seconds and file
contents changes is also notified from stats watcher.
In such circumstances, if some tailing files are steadily growing,
previous implementation does not prevent log ingestion for written
contents which is notified by stat watcher.
This commit also prevents log ingestion in such cases.
No needed.
Same as title.
**Additional context**
I can implement this edge case patch, but how can we write down into test cases...?
=> Handle both of stat and timer watchers are enabled and steady growing file case

lib/fluent/plugin/in_http.rb, test/plugin/test_in_http.rb
Fixes #3372
Azure App uses GET requests to check if the HTTP server is working all right.
Since Fluentd responds with "400 Bad Requests" to HTTP GET, it does not work well.
Teach Fluentd to respond nicely with "200 OK" to HTTP GET.
Not needed
* Starting this version,  `in_http` responds with `200 OK` to GET requests (instead of `404 Bad request`)
=> in_http: Add support for HTTP GET requests

lib/fluent/command/cat.rb, test/command/test_cat.rb
Originally reported to https://github.com/fluent/fluentd-docs-gitbook/issues/306
https://docs.fluentd.org/output/secondary_file#how-to-resend-secondary-file
explains that it supports secondary file to resend,
but it get error when [Fluent::EventTime, Hash] format is given as a record.
Input must be a map (got Array)
In this commit, check record content and support [Fluent::EventTime,
Hash] format too.
N/A
N/A
=> fluent-cat: support secondary [Fluent::EventTime, {}] record too

bin/fluentd
Related to #3375 
In recent CRuby, RubyVM::InstructionSequence is always defined.
But other implementation such as truffleruby does not provide such
class.
But even if this commit, fluentd does not work correctly with truffleruby. 
Especially, Fluentd sometimes does not terminate correctly with TERM signal.
No needed.
Same as title.
**Additional Note**:
`TruffleRuby` can be installed with `rbenv install truffleruby-21.0.0`. We can use it to investigate issue which is caused by truffleruby.
=> bin: fluentd: Specify trace_instruction as false if available

lib/fluent/plugin/file_wrapper.rb, lib/fluent/plugin/in_tail.rb, test/plugin/test_file_wrapper.rb, test/plugin/test_in_tail.rb
None.
Reported at https://discuss.fluentd.org/t/windiws-server-fluentd-stops-working/61
On Windows, a win32 error ERROR_SHARING_VIOLATION is occured on
`Fluent::FileWrapper.stat(path)` when a file is temporarily used by
another process. Such files should be skipped safely until the file is
released as same as ENOENT case.
This patch rescues also other EACCES cases although they rarely occur.
None.
Same as title.
=> in_tail: Safely skip files used by another process on Windows

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
Follow up #3185
in_tail: read_bytes_limit_per_second should precede read_lines_limit
Otherwise it doesn't limit reading pace on reading many short lines.
none
Same with #3185
=> in_tail: read_bytes_limit_per_second should precede read_lines_limit

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
Fixes #3323 #3345 #3333 (maybe)
in_tail takes very long time to shutdown when it's reading huge files.
This patch ensure to shutdown ASAP just after receiving a shutdown
command.
* Constructed tail watchers should be registered ASAP to be recognized
by the shutdown process.
* Break `TailWatcher#on_notify` ASAP
Wait 5 secdonds before breaking it to ensure reading remaining lines.
It takes effect only when `skip_refresh_on_startup` is enabled, because
reading files is occurred on main thread without it. It should be
enabled by default in the future.
none
Same as title
=> in_tail: Shutdown immediately & safely even if reading huge files

.github/workflows/windows-test.yaml
Fixes #3263
On Ruby 3.0, we need to use fiddle 1.0.8 or later to retrieve correct
error code. In addition, we have to specify the path of fiddle by RUBYLIB
because RubyInstaller loads Ruby's bundled fiddle before initializing gem.
See also:
* https://github.com/ruby/fiddle/issues/72
* https://bugs.ruby-lang.org/issues/17813
* https://github.com/oneclick/rubyinstaller2/blob/8225034c22152d8195bc0aabc42a956c79d6c712/lib/ruby_installer/build/dll_directory.rb
none
none
=> CI: Use fiddle 1.0.8 for Ruby 3.0 on Windows

lib/fluent/plugin/in_tail/position_file.rb, test/plugin/in_tail/test_position_file.rb
#3365
Same change with #3391. This PR is for v1.12
(from #3365)
In the previous Fluentd v1.11.x implementation uses path based tailing keys.
We wouldn't rewrite tailing mechanism entirely.
And also we're implicitly assuming path based equality for TargetInfo in tailing logic.
We should handle TargetInfo with path based equality instead of path and
inode based equality.
none
in_tail: Fix a bug that in_tail fails to handle file rotations
=> in_tail: position_file: Define path based equalities on TargetInfo (for v1.12)

lib/fluent/config/section.rb, test/config/test_section.rb
Fixes N/A
If pp instance of Fluent::Config::Section, it raises the following
exception:
Unexpected error undefined method `pretty_print' for
<Fluent::Config::Section {}>
This commit fixes such a case to make debugging easy.
(When debugging https://github.com/fluent/fluentd/pull/3396, I've found
that this feature is missing)
N/A
N/A
=> Support pretty print Fluent::Config::Section for debugging

test/plugin/test_in_tail.rb
none
Suppress a test failure on Drone CI:
https://cloud.drone.io/fluent/fluentd/1444/1/2
none
none
=> test: Omit test_EACCES_error_after_setup_watcher if current user is root

test/command/test_cat.rb, test/plugin/test_in_forward.rb, test/plugin/test_in_http.rb, test/plugin/test_in_syslog.rb, test/plugin/test_in_tcp.rb, test/plugin/test_in_udp.rb, test/plugin/test_out_forward.rb, test/plugin/test_out_stream.rb, test/plugin_helper/test_http_server_helper.rb, test/plugin_helper/test_server.rb, test/plugin_helper/test_socket.rb
none
In the previous code an used port was stored in `PORT` on loading test classes,
but it doesn't make sure to be unused at run time of each tests. I think this is the
why sometimes tests for in_tcp, in_udp and etc... fail on CI environment like this:
https://cloud.drone.io/fluent/fluentd/1449/1/2
```
Error: test: source_address_key(TcpInputTest): Errno::EADDRINUSE: Address already in use - bind(2) for 0.0.0.0:45259
/usr/local/lib/ruby/2.6.0/socket.rb:201:in `bind'
/usr/local/lib/ruby/2.6.0/socket.rb:201:in `listen'
/drone/src/vendor/bundle/ruby/2.6.0/gems/serverengine-2.2.4/lib/serverengine/socket_manager_unix.rb:66:in `listen_tcp_new'
/drone/src/vendor/bundle/ruby/2.6.0/gems/serverengine-2.2.4/lib/serverengine/ …
```
=> test: Make sure to select unused port

test/plugin/test_out_forward.rb
none
It may be a cause of the following error:
https://github.com/fluent/fluentd/runs/2717168203
```
2021-06-01T09:28:12.9420478Z Error: test: a node supporting responses after stop(ForwardOutputTest): Fluent::Test::Driver::TestTimedOut: Test case timed out with hard limit.
2021-06-01T09:28:12.9423524Z /home/runner/work/fluentd/fluentd/lib/fluent/test/driver/base.rb:201:in `rescue in run_actual'
2021-06-01T09:28:12.9425798Z /home/runner/work/fluentd/fluentd/lib/fluent/test/driver/base.rb:196:in `run_actual'
2021-06-01T09:28:12.9427235Z /home/runner/work/fluentd/fluentd/lib/fluent/test/driver/base.rb:95:in `run'
2021-06-01T09:28:12.9428528Z /home/runner/work/fluentd/fluentd/lib/fluent/test/driver/base_owner.rb:130:i …
```
=> test_out_forward: Extend ack timeout for a test

lib/fluent/plugin/out_forward.rb
none
Follow up #3405.
There is no reason to use thread local unpacker, using method local one is more safe.
none
Same with #3405
=> out_forward: Use method local unpacker

test/plugin/test_in_tail.rb
none
Although throttling tests try many data, about half of them are
meaningless. Since these tests take 1-2 seconds per datum, they
should be removed to reduce whole test time.
none
none
=> test_in_tail: Remove meaningless test data for throttling tests

test/plugin_helper/test_child_process.rb
none
The test "can specify subprocess name" is failed on rbenv because the
ruby command is executed via rbenv-exec.
This commit replace the ruby command with sh,
because this test doesn't require ruby.
```
Failure: test: can specify subprocess name(ChildProcessTest):
assert{ proc_lines.select{|line| line =~ /^\s*#{pid}\s/ }.first.strip.split(/\s+/)[1] == "sleeeeeeeeeper" }
|          |                                      |     |     |           |   |
|          |                                      |     |     |           |   false
|          |                                      |     |     |           "bash"
|          |                                      |     |     ["557858", "bash", …
```
=> test_child_process: Fix a failed test on rbenv

.github/workflows/linux-test.yaml, .github/workflows/windows-test.yaml, .gitlab-ci.yml
none
Ruby 2.5 is already EOL:
https://www.ruby-lang.org/en/news/2021/04/05/ruby-2-5-9-released/
none
none
=> CI: Drop Ruby 2.5

lib/fluent/plugin/in_tail.rb
Fixes #3416
By #3185, log throttling per file feature was merged, but
it also introduces too much debug logging code in #handle_notify.
Before:
```ruby
def handle_notify
...
while true
...
@log.debug("reading file: ...")
...
end
...
```
N/A
N/A
=> Remove too much verbose debug logging

test/plugin/test_out_forward.rb
None. But this is one of the left task of adopting Ruby 3. 
Without this change, Fluentd testcases insists as follows:
```log
O
========================================================================================================================
Omission: Proxy of RR doesn't support kwargs of Ruby 3 yet [test: Create new connection per send_data(ForwardOutputTest)]
/media/Data2/Gitrepo/fluentd/test/plugin/test_out_forward.rb:1231:in `block in <class:ForwardOutputTest>'
========================================================================================================================
<snip>
O
================================================================= …
```
=> Run omitted testcases for Ruby3 incompatibility of RR

lib/fluent/plugin/service_discovery.rb
Fixes N/A
The license text is duplicated in service_discovery.rb
This is introduced by https://github.com/fluent/fluentd/commit/ce870c4a2f8af84d925c15a5c12b79e66e7e6546.
But I guess that it is not intended.
N/A
N/A
=> Remove duplicated license text

lib/fluent/plugin_helper/http_server/router.rb, test/plugin_helper/http_server/test_route.rb
I had a security scan flag up a potential XSS vulnerability on the fluentd Prometheus metrics port:
```
The request string used to detect this flaw was :
/cgi-bin/<script>cross_site_scripting.nasl</script>.asp
The output was :
HTTP/1.1 404 Not Found
Content-Type: text/plain
connection: close
content-length: 71
404 Not Found: /cgi-bin/<script>cross_site_scripting.nasl</script>.asp
Note that this XSS attack may only work against web browsers
that have "content sniffing" enabled.
```
This is because `<script>` tags in the URL are echoed back in plaintext.
I don't think this represents a real security vulnerability:
- you're unlikely to be interacting with fluentd in a browser
- the Content-Type is text/plain, so the browser would need to ignore it ("may only work against web browsers that …
=> Don't echo back the provided path on a 404 error

lib/fluent/command/binlog_reader.rb, lib/fluent/plugin/formatter.rb
None
I got a following error when I use to `binlog_reader`:
```
`<module:Mixin>': undefined method `windows?' for Fluent:Module (NoMethodError)
```
No needed.
Same as title.
=> formatter: Add a missing fluent/env require

lib/fluent/command/plugin_generator.rb
Fixes #3442
In the previous versions, it expected that Fluentd is installed
via bundler, thus it assumes that Gemfile.lock exists.
It is not always true because it may be installed via gem command.
In such a case, we use Gem::Specification.find_by_gem (Gem::Version)
as a fallback.
N/A
N/A
=> fluent-plugin-generate: fix crash bug without bundler

lib/fluent/config.rb, lib/fluent/config/v1_parser.rb
Fixes https://github.com/fluent/fluentd-kubernetes-daemonset/issues/583
By #3352, an early stage config parser is introduced to enable setting
log rotation by system config. While this stage, the global logger
doesn't exist yet, so that it causes crash when the config parser try to
output log. This commit avoid the crash by checking $log. Same logs will
be output at the later stage so that it's not needed in the early stage.
See also: https://github.com/fluent/fluentd-kubernetes-daemonset/issues/583
None
=> Avoid to crash on outputting log at the early stage config parser

fluentd.gemspec
Fixes #3374 #3409
http_parser.rb 0.6.0 includes a garbage Gemfile.lock and it causes false
positive detection by security scanning tools. 0.7.0 fixes this issue.
See also: #3374 #3409 #3437
none
=> Relax http_parse.rb version

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
Fixes #2478
Although log throttling feature is landed at #3185 (and #3379), it has still remaining issue mentioned at https://github.com/fluent/fluentd/issues/2478#issuecomment-512086345
When the throttling feature is enabled and rotation is occurred, remaining lines will be discarded.
(When it's not enabled, in_tail make sure to reach EOF with blocking other tasks.)
This patch ensure to reach EOF even if throttling is enabled.
none
~~Same with  #3185 (if this PR is landed on v1.13)~~
=> in_tail: Ensure to reach EOF after rotate even if throttling is enabled

lib/fluent/plugin/file_wrapper.rb
Probably fixes #3340.
This is a Fluentd port of the following fix: fluent-bit#2027
Windows has a concept of DeletePending, which means "DeleteFile()
was called on that file. NTFS will remove this file once everyone
close the handlers for it".
This patch teaches Fluentd to respect the DeletePending flag.
=> WindowsFile: Allow Fluentd to respect DeletePending

test/plugin/test_file_wrapper.rb
Ammend #3457
I think I found a way to add testing for the changeset f61c08ca.
1. Create a test file with FILE_SHARE_DELETE mode.
2. Call `DeleteFile()` on that file.
3. Call `WindowsFile.stat()` on that file.
4. Check if ENOENT is raised after step 3.
Confirmed to work fine on GitHub Action:
WindowsFile exceptions:
test: ERROR_SHARING_VIOLATION raised:        .: (0.001220)
test: Errno::ENOENT raised:                  .: (0.000633)
test: Errno::ENOENT raised on DeletePending: .: (0.000717)
test: nothing raised:                        .: (0.000835)
Not required.
Not required.
=> WindowsFile: Add testing for DeletePending

lib/fluent/plugin/in_tail/position_file.rb, test/plugin/in_tail/test_position_file.rb
None
I found these bugs while addressing #3433, but fix for #3433 isn't included in this pull request yet.
This pull request fixes following two bugs:
* When both `follow_inodes` and `pos_file_compaction_interval` are specified, file entries that didn't exist on start up will be deleted unexpectedly when compaction is triggered.
* `String#bytesize` should be used instead of `String#size` for path length.
None
TBD
=> Fix some pos_file bugs

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
Fixes #3464
As described in #3464, duplicate events are emitted when `follow_inode` is `true` and rotation is occurred.
There are 2 causes on this issue:
* Wrong inode is set to `TailWatcher` when `follow_inode` is `true`
* A key (`TargetInfo`) in `@tails` isn't updated for a same path even if new
one has different inode
none
=> in_tail: Fix log duplication when follow_inode is true

lib/fluent/plugin.rb, lib/fluent/plugin/metrics.rb, lib/fluent/plugin/metrics_local.rb, lib/fluent/plugin_helper.rb, lib/fluent/plugin_helper/metrics.rb, lib/fluent/system_config.rb, test/plugin/test_metrics.rb, test/plugin/test_metrics_local.rb, test/plugin_helper/test_metrics.rb
None.
It would nice to have configurable and flexible Fluentd's metrics.
Currently, Fluentd's metrics should be tightly coupled on its implementation.
But, in our usecase, Fluentd should load different plugin such as [fluent-plugin-metrics-cmetrics](https://github.com/calyptia/fluent-plugin-metrics-cmetrics) which handles [cmetrics](https://github.com/calyptia/cmetrics) context. 
Of course, [cmetrics Ruby bindings](https://github.com/calyptia/cmetrics-ruby) should be used in Fluentd metrics plugin.  
In the real metrics plugin usecase with metrics_local is: [cosmo0920/fluentd@implement-metrics-plugin branch](https://github.com/fluent/fluentd/compare/f73c601...cosm …
=> Implement metrics plugin mechanism

lib/fluent/plugin/in_tail/position_file.rb, test/plugin/in_tail/test_position_file.rb, test/plugin/test_in_tail.rb
Fixes #3433
As described in #3433, path entries in pos_file for delete files never removed.
This patch removes such entries at start up.
For `follow_inode true` case, it''s already implemented.
I think it's also needed for `follow_inode false` case, but I'm not sure why the current implementation is only for `follow_inode true` case.
none
=> in_tail: Remove entries for deleted paths in pos_file at start up

lib/fluent/plugin/metrics.rb, lib/fluent/plugin/metrics_local.rb, test/plugin/test_metrics.rb, test/plugin/test_metrics_local.rb
Folows up #3440 
This is because our use cases doesn't need key for distinguish plugins
and agents.
One of the use cases to specify plugin_id calling has a possibility to become the bottleneck for performance.
The reason is Kernel#instance_variable_defined? method is relatively
heavy operation.
No needed.
Same as title.
=> metrics: metrics_local: Remove key argument to optimize performance

lib/fluent/event_router.rb, lib/fluent/plugin/filter.rb, lib/fluent/plugin/in_monitor_agent.rb, test/plugin/test_in_monitor_agent.rb
None
Currently, Fluentd filter metrics do not have emit size and emitted record counts for calculating flow rate (per sec or per hour).
Fluentd filter should have emit_records and emit_size metrics.
But, currently, I disabled size metrics by default for performance concerns.
Needed.
Same as title.
=> Filter plugin records count and record size metrics

lib/fluent/plugin/in_tail.rb
None.
Follow up of #3378
When a fluentd procces doesn't have permission to read a file, it should
retries to open it with a warning message. But the current
implementation suppresses the message due to #3378.
This patch revive the warning message.
None.
=> in_tail: Revive a warning message of retrying unaccecible file

lib/fluent/plugin_helper/event_emitter.rb, lib/fluent/root_agent.rb, test/plugin_helper/test_event_emitter.rb, test/test_root_agent.rb
This patch adds a way in event_emitter_router(label_name) to get the root event router. To use an empty string "" for the default router is just a proposal, maybe `@DEFAULT` would fit better.
Why I needed it:
I did not see another way to get an event it is once assigned to a label back the default route. The concat filter can send timedout events to a special label. With the _route_ plugin the tag can be prefixed and with `@label ""` the event can be sent to the default filters and output.
Will be updated if there is any interest.
Enable to get root router by `Fluent::PluginHelper::EventEmitter::event_emitter_router("@ROOT")`
=> Add ability to get the root-router

lib/fluent/plugin/in_syslog.rb, test/plugin/test_in_syslog.rb
Fixes #3472
TCP keepalive should be supported by in_syslog to avoid dead connection, as same as in_forward
`send_keepalive_packet` should be added to https://docs.fluentd.org/input/syslog
=> in_syslog: Add send_keepalive_packet option as same as in_forward

lib/fluent/compat/output.rb, lib/fluent/plugin/bare_output.rb, lib/fluent/plugin/filter.rb, lib/fluent/plugin/in_monitor_agent.rb, lib/fluent/plugin/input.rb, lib/fluent/plugin/multi_output.rb, lib/fluent/plugin/output.rb, test/plugin/test_bare_output.rb, test/plugin/test_filter.rb, test/plugin/test_in_monitor_agent.rb, test/plugin/test_in_tail.rb, test/plugin/test_input.rb, test/plugin/test_multi_output.rb, test/plugin/test_output.rb, test/test_plugin_classes.rb
None
This is the last PR series for implementing metrics plugin mechanism.
With these changes, our cmetrics metrics plugin can work with Fluentd and Fluentd can handle native metrics to send prometheus via fluent-plugin-metrics-cmetrics which binds [cmetrics library](https://github.com/calyptia/cmetrics).
Performance degradation will be prevented with https://github.com/fluent/fluentd/commit/97486d1170f75814c2e92779cb9ca22664379c6e and https://github.com/fluent/fluentd/commit/e4995895574ca48d1f75b324b50dde8c0e1b7ede. Locking with Monitor is heavy operation when it needn't to use due to disable size metrics on each plugin base classes. 
Needed.
Same as title.
=> input: filter: output: bare_output: multi_output: Use metrics plugin mechanism on plugin base classes

lib/fluent/plugin/buffer.rb, lib/fluent/plugin_helper/metrics.rb, test/plugin/test_buffer.rb, test/plugin_helper/test_metrics.rb
None
We should add more metrics plugin supported plugin base classes.
With these changes, our cmetrics metrics plugin also can work with Fluentd and Fluentd can handle native metrics to send prometheus format encodable metrics via fluent-plugin-metrics-cmetrics which binds [cmetrics library](https://github.com/calyptia/cmetrics).
Almost metrics plugin support will be handled in `#statistics` methods. So, it won't be caused significant performance degradation.
Needed.
Same as title.
=> buffer: Use metrics plugin mechanism on a plugin base class

lib/fluent/plugin_helper/server.rb
Fixes #3475
In #3330 we added host name information to the error messages but it
doesn't care the case when it fails `getpeername(2)`.
None
=> TLSServer: Fix crash on logging errors

lib/fluent/plugin/in_http.rb, test/plugin/test_in_http.rb
Fixes #3422
To support [Beacon API](https://www.w3.org/TR/beacon/), setting [Access-Control-Allow-Credentials](https://fetch.spec.whatwg.org/#http-access-control-allow-credentials) header is required because it always set [`credentials: include`](https://fetch.spec.whatwg.org/#concept-request-credentials-mode): https://www.w3.org/TR/beacon/#sec-processing-model
Add `cors_allow_credentials` to https://docs.fluentd.org/input/http
=> in_http: Enable to add Access-Control-Allow-Credentials header

lib/fluent/plugin/in_http.rb
Follow up for #3481
There is no reason I chose the default value `nil` for `cors_allow_credentials` at #3481.
It should be `false`.
none
none
=> in_http: Fix default value of cors_allow_credentials

.github/workflows/windows-test.yaml
Fixes #
Use Ruby 3.0.2 for GitHub CI.
Ruby 3.0.2 installer still bundle fiddle 1.0.6, we explicitly use fiddle 1.0.8 for a while.
```
% 7z l rubyinstaller-3.0.2-1-x64.7z|\grep fiddle
2021-07-10 04:38:19 D....            0            0  rubyinstaller-3.0.2-1-x64/lib/ruby/3.0.0/fiddle
2021-07-10 04:38:20 D....            0            0  rubyinstaller-3.0.2-1-x64/lib/ruby/gems/3.0.0/gems/fiddle-1.0.6
```
N/A
N/A
=> github: use Ruby 3.0.2 for Windows CI

lib/fluent/plugin/in_tail.rb
Fixes #3499
Follow up for #3390
`nil` check is lacked in IOHandler#eof?
In addition, `NullIOHandler` doesn't have `eof?`.
None
=> in_tail: Add missing nil check in IOHandler#eof?

lib/fluent/plugin/out_forward.rb
None.
In monitor_agent, it assumes output plugin metrics are put in under `output` branch.
With current implementation, they will be ignored on retrieving with https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/in_monitor_agent.rb#L338
No needed.
Same as title.
=> out_forward: Include node statictics information correctly

lib/fluent/plugin/out_forward.rb
Follows up #3503
Hash#merge does not merge within nested values.
They should be handled by hands.
No needed.
Same as title.
=> out_forward: Include before merging stats information correctly

lib/fluent/plugin/in_tail.rb, test/plugin/in_tail/test_io_handler.rb, test/plugin/test_in_tail.rb
None
* opened file count
* closed file count
* rotated file count
These metrics should be collected same as fluent-bit's in_tail.
They are useful to debug how much Fluentd handles tailing files on in_tail.
No needed.
Same as title.
=> in_tail: Implement file metrics

lib/fluent/plugin/out_copy.rb
None.
I found the bug while checking #3508
out_copy outputs a following warning even if a user set `ignore_if_prev_success`:
```
2021-09-24 14:10:54 +0900 [warn]: #0 ignore_errors are specified in all <store>, but ignore_if_prev_success is not specified. Is this intended?
```
This commit fixes it.
None
=> out_copy: Suppress a wrong warning for ignore_if_prev_success

lib/fluent/plugin/out_forward.rb
None
_Healthy nodes count_ and _registered nodes count_ should be treated as gauge metrics.
This could be helpful for debugging with node information via monitor agent and we can use a pluggable metrics plugin system here with cmetrics via system conf.
No needed.
Same as title.
**Addtional context**:
We don't have any proper knowledge of how to test this mechanism by using `#statistics` method for now...
=> out_forward: Use metrics mechanism for node statistics

lib/fluent/config/parser.rb, lib/fluent/config/v1_parser.rb
None
URI.open via Kernel#open is already obsoleted on Ruby 3.0.
Otherwise, the following error is occurred when using http or https
scheme URI on `@include` directive:
```aconf
@include "https://raw.githubusercontent.com/fluent/fluentd/master/example/in_forward.conf"
```
```log
bundler: failed to load command: fluentd (~/GitHub/fluentd/vendor/bundle/ruby/3.0.0/bin/fluentd)
~/GitHub/fluentd/lib/fluent/config/v1_parser.rb:175:in `initialize': include error https://raw.githubusercontent.com/fluent/fluentd/master/example/in_forward.conf - No such file or directory @ rb_sysopen - https://raw.githubusercontent.com/fluent/fluentd/master/example/in_forward.conf …
```
=> config: Use URI.open directly

lib/fluent/plugin/output.rb
Fixes #3463
It might output unfriendly fractions due to Time class's behavior as of Ruby 2.7, and actual retry time isn't so accurate.
In addition, fix inappropriate labels:
```diff
- retry_time
+ retry_times
```
```diff
- next_retry_seconds
+ next_retry_time
```
e.g.)
```diff
- [warn]: #0 failed to flush the buffer. retry_time=9 next_retry_seconds=2021-07-19 13:00:22 24648004639507749129/34359738368000000000
+ [warn]: #0 failed to flush the buffer. retry_times=9 next_retry_time=2021-07-19 13:00:22
```
none
=> output: Don't output nanoseconds field of next retry time in warning log

lib/fluent/plugin/buf_file.rb, lib/fluent/plugin/output.rb, lib/fluent/plugin/storage_local.rb, lib/fluent/plugin_id.rb, lib/fluent/supervisor.rb
Fixes #
The default value of dir or file permission is defined in fluent/env.rb.
So it should be used everywhere.
I've found this issue when checking #3521.
N/A
N/A
=> Use defined constant for consistency

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
No new logs are read when `enable_stat_watcher true` and `enable_watch_timer false`. Stat watchers for new files are created with the wrong path, so they aren't notified of any events.
Use path from target_info when creating StatWatcher
None
Fix in_tail not reading new lines with stat watcher enabled and watch timer disabled
=> in_tail: Fix StatWatcher uses wrong path

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
Signed-off-by: majimenez-stratio <majimenez@stratio.com>
None
I noticed that read_from_head affect files read during startup and new files equally. I see a few drawbacks with the current situation if `read_from_head = false` and path includes '*', namely:
- New files detected on refresh are not read from the beggining and initial lines are lost.
- Same as above for rotated files
As a result, I think we can improve the way read_from_head is applied, so that it only affects new files detected during startup. This PR changes the behavior so that:
- During startup, files are read from the position stored in the position file, if available. If not, they are read as specified in `read_from_head`.
- After startup, if a …
=> in_tail: Always read from head for new/rotated files after startup

test/plugin/test_out_exec_filter.rb
none
Some processes executed by test_out_exec_filter are remained until finishing all tests.
I found them when I was investigating #3543
none
none
=> test_out_exec_filter: Make sure to shutdown test drivers

lib/fluent/plugin/buffer.rb, test/plugin/test_buffer.rb
Fixes #
In the previous version, if BufferChunkOverflowError occurs,
whole data is not sent because of exception.
It is not appropriate because the problem exists only a partial split
data.
In this commit, detect BufferChunkOverflowError and postpone to raise
it as an exception.
So a valid partial split is processed as intended.
N/A
N/A
=> Fix a bug that BufferChunkOverflowError cause a whole data loss

test/plugin_helper/test_child_process.rb
Fixes #
Sometimes some command execution tests failed on CI (especially on Drone CI, but occurs also on others).
It seems that it's caused by Ruby interpreter's launch cost and fewer timeout setting.
They seems suppressed by using `echo` command and extending the timeout.
None
=> Fix unstable command execution tests

lib/fluent/plugin/buffer.rb, test/plugin/test_buffer.rb
Follow up #3553
Fixes #
No functionality changes.
It is more informative and distinguishable.
=> Show chunk_limit_size respectively

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
Fixes #
There is a case that processing unexpected long line causes a
BufferChunkOverflow exception.
With #3562 (Fluentd v1.14.3), it can just ignore only problematic long
record, but it always raise an exception. Thus it has performance
regression.
In this fix, skip_long_lines option enables to just skip processing
event further more.
It should be documented in in_tail.
=> in_tail: add option to skip long lines

test/plugin/test_out_exec.rb
None
I found that a test for out_exec plugin randomly fails on CI.
It often occurrs on Dron CI but sometimes on other environments too.
e.g.) https://cloud.drone.io/fluent/fluentd/1934/1/2
```
Failure: test: flushed chunk will be committed after child process successfully exits(ExecOutputTest::when executed process dies unexpectedly)
/drone/src/test/plugin/test_out_exec.rb:279:in `block (2 levels) in <class:ExecOutputTest>'
276:       expect_data =
277:         %[2011-01-02 13:14:15\ttest\tv1\n] +
278:         %[2011-01-02 13:14:15\ttest\tv2\n]
=> 279:       assert_equal expect_data, data
280:
281:       assert{ d.instance.buffer.queue.empty? }
282:       assert{ d.instance.dequeued_chunks.empty? }
<"2011-01-02 …
```
=> test_out_exec: Try to fix a randomly failed test

test/plugin/test_bare_output.rb, test/plugin/test_filter.rb, test/plugin/test_input.rb, test/plugin/test_output_as_buffered_secondary.rb, test/plugin_helper/test_timer.rb
Fixes #3543
Several tests are stalled since Ruby 3.1, I found that it's caused by
the followig Ruby's change:
https://github.com/ruby/ruby/commit/2d98593bf54a37397c6e4886ccc7e3654c2eaf85
It seems that there are some conditions to reproduce it:
* `attr_reader` is defined in a class
* `$log` is accessed by it
* `assert` is called with a block
* `assert` refers the `$log` via the `attr_reader`
* ... (some other conditions seem needed but not clarified yet)
Here is the sample test case to reproduce it:
```ruby
require 'fluent/test'
class StallTest < Test::Unit::TestCase
class Stall
attr_reader :log
def initialize
@log = $log
end
end
setup do
Fluent::Test.setup
end
20.times do |i|
test "stall #{i}" do
assert { …
```
=> test: Fix stalled tests on Ruby 3.1

lib/fluent/plugin/buffer.rb, test/plugin/test_buffer.rb
Follow up #3553
In the previous versions, even though each record size is smaller
than chunk limit size, but whole message size exceeds
chunk limit size, BufferChunkOverflowError is raised unexpectedly.
For example, if chunk limit size is 1_280_000, process 3 event
stream (every 1_000_00 bytes), it throws an exception like this:
Fluent::Plugin::Buffer::BufferChunkOverflowError(<a 1000025 bytes
record (nth: 1) is larger than buffer chunk limit size, a 1000025
bytes record (nth: 2) is larger than buffer chunk limit size>)
Now changed not to raise exception if it's record size is smaller
enough than chunk limit size.
The idea is based on that adding byte size is smaller than chunk
limit size, chunk should be unstaged and pushed into queue,
If not, it should be skipped like #3553. …
=> Don't raise exception when each message size is smaller than chunk_limit_size

lib/fluent/env.rb, lib/fluent/plugin/out_file.rb, test/plugin/test_out_file.rb
For Ruby 2.7.x and 3.0.x, out_file append option without compression
does not work. The cause is the following Ruby language bug:
https://bugs.ruby-lang.org/issues/18388.
This commit is a workaround for this problem.
See #3569.
Fixes #3569
none
out_file: Work around for a bug of Ruby on macOS that `IO.copy_stream` doesn't work as expected with append mode
=> Make out_file append option work without compression

lib/fluent/plugin/base.rb
Signed-off-by: Maksym Lisogorskyi <m.lisogorskyi@gmail.com>
Fixes [#3595](https://github.com/fluent/fluentd/issues/3595)
Replace an invalid character before it is logged out again.
_none_
`invalid byte sequence is replaced in` log line will not log out the invalid character.
=> replace bad characters before logging them out

README.md
This adds the first at at cleaning up README.md, removing things
not being kept up-to-date (and things that are explained in other
documents better).
Signed-off-by: Fujimoto Seiji <fujimoto@ceptord.net>
=> Removing obsolete paragraphs in README.md

fluentd.gemspec
Fixes #
Async::HTTP unlocks using Async-2.x since v0.56.4.
But we aren't ready for Async-2.0 yet, one of the known issue is that
it causes the following error:
https://github.com/fluent/fluentd/pull/3585#issuecomment-1005280129:
```
2021-12-27T14:53:29.8037858Z Error: test: monunt given path(HttpHelperTest::Create a HTTP server): ArgumentError: unknown keyword: :logger
2021-12-27T14:53:29.8040011Z /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/async-2.0.0/lib/async/scheduler.rb:39:in `initialize'
2021-12-27T14:53:29.8041621Z /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/async-2.0.0/lib/async/reactor.rb:32:in `initialize'
2021-12-27T14:53:29.8043219Z …
```
=> Stay Async's version to 1.x

fluentd.gemspec
None
ServerEngine v2.2.4 or former doesn't work on RubyInstaller 3.1:
https://github.com/treasure-data/serverengine/issues/114
None
=> Bump up required ServerEngine to v2.2.5

lib/fluent/plugin_helper/socket.rb
Fixes # N/A
When out_forward plugin uses TLS transport, if the TLS handshake takes a long time or hangs,
the flusher (or event_loop for heartbeat) thread waits forever even though connect_timeout is specified.
We encountered this problem in the setup that log-forwarder fluentd sends data to another fluentd cluster under a level 4 (TCP) load balancer.
The load balancer accepts TCP connections, but the backend fluentd (which needs to handle TLS) is too busy and unstable to accept the connections. This caused the TCP connection to stay open and the forwarder to hang.
This fixes the problem by applying connect_timeout to TLS handshake.
To avoid breaking existing environments configured to use the short …
=> Apply connect_timeout also to TLS handshake

lib/fluent/config/error.rb, lib/fluent/registry.rb, test/compat/test_parser.rb, test/plugin/test_filter_parser.rb, test/plugin/test_filter_stdout.rb, test/plugin/test_out_stdout.rb, test/test_formatter.rb
None.
Not found plugin is basically config error but we need to use another error class to customize this error for config validation.
In general, cloud service does not permit to install plugins via user operations.
This patch does not affect for error message for ordinary cases.
Perhaps, it might affect error handling but this should be a corner case.
No needed.
Same as title.
=> Use more concrete error class on plugin not found

lib/fluent/plugin/output.rb, test/plugin/test_output_as_buffered_retries.rb
Fixes #3161
`retry_max_times == 0` should also work as expected.
None.
=> Don't retry when retry_max_times == 0

Rakefile
Fixes #
RubyInstaller 3.1 has switched C-Runtime to UCRT so that RUBY_PLATFORM
has been changed to `x64-mingw-ucrt`:
https://rubyinstaller.org/2021/12/31/rubyinstaller-3.1.0-1-released.html
Without it, Windows specific dependent gems aren't install on RubyInstaller 3.1:
https://github.com/fluent/fluent-plugin-windows-eventlog/pull/83#issuecomment-1026909993
None
=> Build x64-mingw-ucrt gem

lib/fluent/plugin/in_http.rb, test/plugin/test_in_http.rb
Fixes #3511
This enable in_http plugin to recognize "ndjson" format, which is
basically a list of JSON objects separated by "\n".
Here is a typical ndjson message looks like:
```json
{"foo": "bar"}
{"buz": "hoge"}
```
See http://ndjson.org/ for more details.
Required. I'm going to submit a documentation patch  soonish.
`in_http: Add support for "application/x-ndjson"`
=> in_http: Add support for Application/x-ndjson

lib/fluent/plugin/bare_output.rb
Fixes #3628 
When implementing metrics plugin mechanism, it should be
named as `emit_count` instead of `emit_records`.
See
https://github.com/fluent/fluentd/commit/4a0335a43a131f5f8a428f7deff98c3942e6cf4e
N/A
N/A
=> plugin metrics: fix a typo about emit_count

lib/fluent/event_router.rb, test/test_event_router.rb
Fixes #3465
When an error occurs in the output process in a pipeline,
the modifications made by the filter process should be applied to the records
that are passed to `@ERROR` label.
None.
I have confirmed all success of `bundle exec rake test` in my environment, Ubunty 20.04.3, Ruby 2.7.0.
I have confirmed `@Error` label outputs the records including the modifications made by `record_transformer` as follows.
**Config**
```conf
<source>
@type forward
@id forward_input
</source>
<filter debug.**>
@type record_transformer
<record>
newfield "new value"
</record>
</filter>
<match debug.**>
@type stdout
@id stdout_output
<buffer>
@type memory
total_limit_size …
```
=> Apply modifications in pipeline to the records being passed to `@ERROR` label

lib/fluent/rpc.rb, test/test_supervisor.rb
Fixes #3603
`rpc_endpoint` in `<system>` section doesn't support IPv6 address.
This patch enables to parse also IPv6 address.
None
=> Support IPv6 address for rpc_endpoint in system config

lib/fluent/plugin/in_forward.rb, lib/fluent/plugin_helper/server.rb, test/plugin/test_in_forward.rb, test/plugin_helper/test_server.rb
None.
`in_forward` plugin has `linger_timeout` config, but most plugins using the `server` helper doesn't have the config, such as `in_tcp` or `in_http`.
The helper sets `0` to this option by default.
It causes the server to send RST rather than FIN on closing.
So this value needs to be changed if needing FIN signal on closing.
Adding this option to `transport_config` enables all plugins using the helper to change this value.
This fix makes `linger_timeout` config of `in_forward` plugin deprecated, but that config value can work as before.
Need.
https://github.com/fluent/fluentd-docs-gitbook/pull/392
Need.
=> Enable server plugins to specify socket-option `SO_LINGER`

lib/fluent/plugin_helper/retry_state.rb, test/plugin_helper/test_retry_state.rb
Fixes #3609
Calculation of max retry timeout for exponential backoff is wrong, 
exponents should be started with 0, not -1.
none
=> Fix wrong calculation of max retry timeout for exponential backoff

CHANGELOG.md
Fixes N/A
Since v1.13.1, heading style was unexpectedly changed.
It should be:
level1: # v1.xx
level 2: ## Release v1.xx.y - YYYY/MM/DD
The past blog entries should be updated too.
=> Fix CHANGELOG.md heading styles

lib/fluent/plugin/parser.rb
Because it is a regexp actually. This change provides flexibility and better document to users.
The `null_value_pattern` is defined as string currently, but it's actually compiled as a Regexp. But documents are written as string and it makes users confused.
Needed here: https://docs.fluentd.org/configuration/parse-section
Probably no need to mention this. No compatibility will be broken by this change.
=> Declare null_value_pattern as regexp

.github/ISSUE_TEMPLATE/config.yml, CONTRIBUTING.md, README.md
Fixes #
Discuss.fluentd.org will not work as expected with
limitation of infrastructure itself and human resources,
it may be better transition from discuss.fluentd.org to GitHub
Discussions.
NOTE: fluent/fluentd-docs-gitbook has a link to it in issue template.
=> Switch to GitHub Discussions

lib/fluent/plugin/output.rb
Signed-off-by: JiHyunSong <jihyun.song0829@gmail.com>
Fixes #
fix duplicated output metric name
N/A
N/A
=> fix metric name typo

lib/fluent/command/fluentd.rb, lib/fluent/supervisor.rb
Signed-off-by: Sergey Yedrikov <syedriko@redhat.com>
None
I needed to control permissions on files and directories fluentd creates on disk, to make them accessible only to the user running fluentd:
```
sh-4.4# find /var/lib/fluentd -ls
100978405      0 drwxr-xr-x   5  root     root           53 Feb  4 04:52 /var/lib/fluentd
157295736      0 drwx------   2  root     root           59 Feb  4 05:01 /var/lib/fluentd/pos
157295739     12 -rw-------   1  root     root        11117 Feb  4 05:02 /var/lib/fluentd/pos/es-containers.log.pos
157295855      4 -rw-------   1  root     root          137 Feb  4 05:01 /var/lib/fluentd/pos/journal_pos.json
48242762      0 drwxr-xr-x   2  root     root          115 Feb  4 05:02 …
```
=> Added --umask command line parameter

lib/fluent/command/fluentd.rb, lib/fluent/supervisor.rb
Signed-off-by: Sergey Yedrikov <syedriko@redhat.com>
This is a correction to a previous commit that added the --umask command line parameter.
The default umask needs to be a string, otherwise the following happens:
2022-03-16 05:14:45 +0000 [error]: unexpected error error_class=ArgumentError error="wrong number of arguments (given 1, expected 0)"
2022-03-16 05:14:45 +0000 [error]: /usr/local/share/gems/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:714:in `to_i'
None
=> Make the default umask a string

lib/fluent/plugin/output.rb, lib/fluent/plugin_helper/retry_state.rb, test/plugin_helper/test_retry_state.rb
This is about #3609.
Fix timeout handling for #3649.
The current `limit?` usage is complicated, so I have tried to make it simple.
None.
None.
=> [For #3649] Fix timeout handling

lib/fluent/plugin/output.rb, lib/fluent/plugin_helper/retry_state.rb, test/plugin/test_output_as_buffered_retries.rb, test/plugin/test_output_as_buffered_secondary.rb, test/plugin_helper/test_retry_state.rb
Fixes #3609
The correct total retry time should be:
```
c + c * b^1 + (...) + c*b^(k - 1)
```
But the previous implementation was:
```
c + c * b^0 + c * b^1 + (...) + c*b^(k - 1)    
```
where:
* c: constant factor, @retry_wait
* b: base factor, @retry_exponential_backoff_base
* k: number of retry times, @max_retry_times
Although the first retry interval is already added at constructor of
ExponentialBackoffRetry, same value is added again unexpectedly on the
first calc_interval call (as `c * b^0`).
In addition, this PR also fixes wrong detection of retry limit.
https://docs.fluentd.org/configuration/buffer-section#retries-parameters is also wrong, should be fixed too.
Same with …
=> Fix wrong calcuration of retry interval and detecting retry limit

CHANGELOG.md
None
There was a wrong link in CHANGELOG.
This PR fixes it.
None.
None.
=> CHANGELOG.md: Fix one wrong link in 1.12.0

lib/fluent/plugin_helper/server.rb
None.
This fix comments about #3644.
There was a lack of consideration regarding the default behavior on Windows.
https://github.com/fluent/fluentd-docs-gitbook/pull/398
None
=> Add comments to `linger_timeout` behavior about Windows

lib/fluent/plugin_helper/service_discovery.rb
Signed-off-by: JiHyunSong <jihyun.song0829@gmail.com>
Fixes #
typo fix
X
=> just fix typo

lib/fluent/command/ctl.rb, lib/fluent/config/literal_parser.rb, lib/fluent/plugin/file_wrapper.rb, lib/fluent/plugin/parser_syslog.rb, test/command/test_ctl.rb, test/config/test_system_config.rb, test/config/test_types.rb, test/plugin/in_tail/test_io_handler.rb, test/plugin/in_tail/test_position_file.rb, test/plugin/test_in_syslog.rb, test/plugin/test_in_tail.rb, test/plugin/test_parser_syslog.rb, test/plugin_helper/test_cert_option.rb
None
Many warnings are shown on running unit tests.
It makes hard to find actual bugs.
```
/Users/aho/Projects/Fluentd/fluentd/lib/fluent/config/literal_parser.rb:194: warning: assigned but unused variable - e
/Users/aho/Projects/Fluentd/fluentd/lib/fluent/plugin/parser_syslog.rb:487: warning: assigned but unused variable - e
/Users/aho/Projects/Fluentd/fluentd/test/command/test_ctl.rb:10: warning: assigned but unused variable - event_suffix
/Users/aho/Projects/Fluentd/fluentd/lib/fluent/command/ctl.rb:149: warning: assigned but unused variable - e
/Users/aho/Projects/Fluentd/fluentd/test/config/test_types.rb:193: warning: assigned but unused variable - list …
```
=> Fix warnings on runnings tests

lib/fluent/command/fluentd.rb, lib/fluent/config.rb, lib/fluent/config/yaml_parser.rb, lib/fluent/config/yaml_parser/fluent_value.rb, lib/fluent/config/yaml_parser/loader.rb, lib/fluent/config/yaml_parser/parser.rb, lib/fluent/config/yaml_parser/section_builder.rb, lib/fluent/supervisor.rb, test/command/test_fluentd.rb, test/test_config.rb, test/test_supervisor.rb
Fixes https://github.com/fluent/fluentd/issues/554
Revised #2818
Recently, fluent-bit supports YAML configuration in https://github.com/fluent/fluent-bit/pull/4621.
Now, it is reasonable to handle YAML configuration format on Fluentd, too.
This is because YAML config format is more kubernetes friendly and machine friendly.
It's time to discuss to support YAML configuration format again.
https://github.com/fluent/fluentd-docs-gitbook/pull/402
Same as title
=> Handle YAML configuration format on configuration file

lib/fluent/command/ctl.rb, lib/fluent/supervisor.rb, lib/fluent/winsvc.rb, test/plugin/test_in_object_space.rb, test/test_supervisor.rb
Fixes #3600
Currently, [Sigdump](https://github.com/fluent/sigdump/) is available by sending the CONT signal, **without Windows**.
The main purpose of this PR is to make this function available for Windows too.
To do so, add the following features to `fluent-ctl` and rpc.
We can use the following methods to use Sigdump.
- command: `$ fluent-ctl dump {pid or svcname}`
- ~~http request to Fluentd: `/api/processes.dump`~~
**Windows**
- Fluentd outputs dump-files about the supervisor process and all worker processes to the system temp dir `C:\\Windows\\Temp`.
- We can specify `SIGDUMP_PATH` environment variable to change the path.
- Automatically add each process-id to the path to avoid a writing conflict.
Examples of …
=> Add sigdump func to fluent-ctl

lib/fluent/plugin/in_tail.rb
Fixes #3752
The tail watcher for the path might by already removed from `@tails` by refresh_watchers.
Without this fix in_tail might crash on file rotation.
None
in_tail: Fix a possible crash on file rotation when `follow_inodes true`
=> in_tail: Add a missing nil check for rotated_tw in update_watcher

lib/fluent/plugin/output.rb
Fixes #3718
Because `@output_flush_thread_current_position` isn't initialize before
starting flush threads, it might cause crash when flush threads start
to processing buffers before initializing it at main thread.
None
=> output: Fix a potential crash bug of flush thread

lib/fluent/plugin/out_forward/socket_cache.rb, test/plugin/out_forward/test_socket_cache.rb
None.
In `SocketCache`, timeout of sockets are set only on creating them and
never be updated. So that cached sockets (`@available_sockets`) are
always closed after `keepalive_timeout` is passed from its creation,
even if it was used within `keepalive_timeout` seconds.
Not needed.
=> out_forward: Fix to update timeout of cached sockets

.github/workflows/windows-test.yaml, lib/fluent/plugin/file_wrapper.rb, test/plugin/test_out_forward.rb
Fixes #3585
Currently in_tail is broken on Ruby 3.1 on Windows.
In addition, some out_forward tests are broken too.
This PR fixes these issues.
In addition, this PR add CI for Ruby 3.1 and head on Windows
None.
=> Support Ruby 3.1 on Windows

.github/workflows/linux-test.yaml, test/plugin/test_in_tail.rb
None
* 3fbcc1119a5b16dc193c5c189bdde0cb49af3c2c: The rotation tests are wrong on Windows. `sub_test_rotate_file` should pass a rotated file to the block, not a new file.
In addition, it should be opened by `Fluent::FileWrapper` to avoid locking.
* 90ad37db6e1eacefbeecdddebfdd5153500ebdfb, bcba06fe5e6a66d0eda7c14df47545229de5fe2d: Create a new empty directory with a random path on each tests to avoid locking files by Windows OS.
* a065d02de25fffa037569b748fd628f4449ee8c1: Simplify deleting temp directory. The previous hacky way is no longer needed since we always create a new directory for now.
In addition, the previous implementations has some bugs, for example `FileUtils.rm_f` doesn't have `secure` option even …
=> test_in_tail: Fix unstable tests

fluentd.gemspec, lib/fluent/plugin/file_wrapper.rb, test/plugin/test_file_wrapper.rb
Fixes #3769
We don't need to call `CreateFile()` by ourself, use standard `File.open`
and `_get_osfhandle()` instead. It will also fix a bug that `WindowsFile`
cannot open non-ascii path.
None
Fix a bug that in_tail cannot open non-ascii path on Windows
=> Simplify WindowsFile

test/plugin/test_in_tail.rb
None
test_shutdown_timeout in test_in_tail is a bit unstable on Drone.io and macOS.
Probably the cause is that recording start time is too early.
None
None
=> test_in_tail: Try to fix unstable test_shutdown_timeout

test/plugin/test_in_tail.rb
Fixes #
Follow up for #3784
Showing whole `@tails` seems too heavy on CI environment:
```
2022-06-14T07:17:55.0456030Z Error: test_unwatched_files_should_be_removed(TailInputTest::path): SystemStackError: stack level too deep
2022-06-14T07:17:55.2289960Z /Users/runner/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/2.7.0/pp.rb:179:in `bind_call'
2022-06-14T07:17:55.2290470Z /Users/runner/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/2.7.0/pp.rb:179:in `object_address_group'
2022-06-14T07:17:55.2291380Z /Users/runner/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/2.7.0/pp.rb:241:in `pp_object'
...
2022-06-14T07:17:55.5055170Z /Users/runner/work/fluentd/fluentd/test/plugin/test_in_tail.rb:1615:in `test_unwatched_files_should_be_removed' …
```
=> test_in_tail: Reduce information of test_unwatched_files_should_be_removed

lib/fluent/supervisor.rb, lib/fluent/system_config.rb, test/config/test_system_config.rb
Fixes #3749
Add new option `restart_worker_interval` to system-config.
This enables workers to restart with an interval.
Please see #3749 for why this feature is necessary.
This needs the fix of ServerEngine: https://github.com/treasure-data/serverengine/pull/120
https://github.com/fluent/fluentd-docs-gitbook/pull/407
Add `restart_worker_interval` parameter in `<system>` directive to set interval to restart workers that has stopped for some reason.
**Operation example**:
Config
```
<system>
workers 3
restart_worker_interval 1m
</system>
```
Operation
* Worker-A, B, C starts.
* Kill worker-A and worker-B at the same time (set this point as 0s-point).
* Kill worker-C at …
=> Add new system-config to set interval to restart workers

test/plugin_helper/test_child_process.rb
On CI environment, these tests sometimes observe unexepected 3rd command
invocation due to delayed shutdown:
```
2022-06-13T23:57:56.4703110Z Failure: test: can execute external command many times, with leading once executed immediately(ChildProcessTest)
2022-06-13T23:57:56.4704700Z /Users/runner/work/fluentd/fluentd/test/plugin_helper/test_child_process.rb:345:in `block (2 levels) in <class:ChildProcessTest>'
2022-06-13T23:57:56.4705540Z      342:       end
2022-06-13T23:57:56.4706110Z      343:       sleep 1.9 # 1sec(second invocation) + 0.9sec
2022-06-13T23:57:56.4706880Z      344:       @d.stop; @d.shutdown; @d.close; @d.terminate
2022-06-13T23:57:56.4707620Z   => 345:       assert_equal 2, ary.size
2022-06-13T23:57:56.4708220Z      346:       assert_equal [], @d.log.out.logs …
```
=> test_child_process: Try to fix unstable tests

lib/fluent/plugin/in_tail.rb
None
In #3614 some users reported that in_tail rarely stops tailing. It seems
it's caused when skipping update_watcher due to unexpected duplicate
pos_file entries. The root cause is unknown yet. To investigate it, show
more infomation when it happens. Ideally it should't happen so that log
level "warn" is desired for it (I can't reproduce this issue yet).
None
=> in_tail: Show more information on skipping update_watcher

fluentd.gemspec, lib/fluent/command/fluentd.rb, lib/fluent/plugin/file_wrapper.rb, lib/fluent/supervisor.rb, lib/fluent/win32api.rb, lib/fluent/winsvc.rb, test/plugin/test_file_wrapper.rb
None (Found in #3844)
Recently we fail to load win32-api on Ruby 3.2-dev:
https://github.com/fluent/fluentd/runs/7660210030?check_suite_focus=true
```
D:/rubyinstaller-head-x64/lib/ruby/gems/3.2.0+2/gems/windows-api-0.4.5/lib/windows/api.rb:335:in `initialize': uninitialized constant Win32::API (NameError)
@api = Win32::API.new(func, proto, rtype, dll)
^^^^^
from D:/rubyinstaller-head-x64/lib/ruby/gems/3.2.0+2/gems/windows-pr-1.2.6/lib/windows/msvcrt/string.rb:12:in `new'
```
but Fluentd doesn't seem depend on win32-api so much.
Using Fiddle is enough instead. It's time to drop win32-api gem.
None.
=> Drop win32-api gem

lib/fluent/plugin_helper/child_process.rb
Fixes #3627
Pipes for child processes aren't closed explicitly after exiting child processes.
It might causes leave  too many file descriptors opened on certain condition.
none
=> child_process: Plug file descriptor leak

lib/fluent/supervisor.rb, lib/fluent/system_config.rb, test/config/test_system_config.rb
N/A
This adds a new option to enable Ruby JIT in worker processes.
Here is an example configuration:
```xml
<system>
workers 3
enable_jit true
</system>
```
The exact JIT strategy (in particular, mjit or yjit) will be chosen
by Ruby as it sees fit. See the following ticket for details:
https://bugs.ruby-lang.org/issues/18349
https://github.com/fluent/fluentd-docs-gitbook/pull/422
Add a new system configuration `enable_jit`
=> Add a new system config 'enable_jit'

lib/fluent/supervisor.rb
Signed-off-by: Fujimoto Seiji <fujimoto@ceptord.net>
Fixes https://github.com/fluent/fluent-package-builder/issues/411
75ef92f introduced automatic clean up as follows:
Dir.mktmpdir("fluentd-lock-") do |lock_dir|
ENV['FLUENTD_LOCK_DIR'] = lock_dir
se.run
end
This does not work with `--daemon`, because `se.run` will not
block with that option. Fix this issue by reverting to the manual
clean up method in the initial version.
N/A
`out_file: Fix append mode with --daemon flag.`
=> Make the worker lock work in '--daemon' mode as well

lib/fluent/winsvc.rb
Follow up for #3849
In #3849, getting ruby's path was replaced with
`ServerEngine.ruby_bin_path` but `require 'serverengine'` was missing.
As a result it fails to launch fluentd service.
None
None (Same with #3849)
=> winsvc: require serverengine

lib/fluent/config/yaml_parser/loader.rb, test/test_config.rb
Fixes #3901
YAML config format was added in #3712 but it didn't support glob pattern for `!include` directive.
This commit adds it.
Although V1 config also supports  fetching remote config at the corresponding implementation but this PR doesn't add it yet.
It's intentional because I don't feel the needs with the yaml format, we might add it when user really requires it.
It's already described in the example config.
(We might need to describe more detail though.)
=> Support glob for `!include` directive in YAML config format

test/command/test_fluentd.rb
N/A
A test fails on latest Ruby-3.2dev.
The expected error massage pattern was
```
in_buggy.rb:5: syntax error, unexpected end-of-input, expecting
```
but the actual error message on Ruby 3.2 is
```
in_buggy.rb:5: syntax error, unexpected end-of-input (SyntaxError)
```
N/A
N/A
=> Fix a test failure on ruby 3.2.0dev (2022-10-20)

lib/fluent/oj_options.rb
N/A
Although some oj options become configurable by #3315, we've noticed that some of them are meaningless or unsecure.
* `FLUENT_OJ_OPTION_MODE=object`
* It's unsecure, it allows executing arbitrary Ruby code.
* `FLUENT_OJ_OPTION_MAX_NESTING`
* It doesn't take effect, `Oj.default_options` doesn't support `max_nesting`
* https://github.com/fluent/fluentd/issues/3311#issuecomment-923741031
~~Needed~~ It's not described in the document yet.
=> Remove meaningless oj options

lib/fluent/command/fluentd.rb, lib/fluent/supervisor.rb, test/test_supervisor.rb
Fixes #3921
```
Suppose we set up the log rotation on Windows as follows:
<system>
<log>
rotate_age 5
</log>
</sytem>
Currently this does not work, because the supervisor and worker will
share the same log path, and they won't coordinate with each other.
This makes it sure that each process has a log file for themselves
on Windows.
```
N/A
Fix log initializer to correctly create per-process files on Windows
=> Fix "unable to rotate log files on Windows" bug

lib/fluent/plugin/out_file.rb
Fixes #3941
The check did not work well with `<worker 0-N>` directive for
the following reasons:
* When Fluentd starts up, supervisor performs sanity check on
configuration by creating actual instances of plugins.
* This check precedes SeverModule, which prepares various assets
for workers (lockdir, RPC endpoints and shared sockets etc.)
* Fluent::Plugin::Base dynamically overrides `system_config.workers`
during start-up, and leaves the value > 1 only when `<worker 0-N>`
directive is used.
Fix this issue by avoiding faulty sanity check in `configure()`.
N/A
out_file: Fix the multi-worker check with `<worker 0-N>` directive
=> out_file: Avoid performing multi-worker check in configure()

test/plugin/test_out_forward.rb
Fixes #3885
Fluent::Test::Driver::Base#instance_shutdown causes rase on Ruby 3.2 on Windows. I'm not sure the detailed mechanism of this issue but exiting the test driver normally doesn't cause it.
```
2022-09-15T04:02:03.9921391Z #<Thread:0x000001ddefc90b20@event_loop D:/a/fluentd/fluentd/lib/fluent/plugin_helper/thread.rb:70 run> terminated with exception (report_on_exception is true):
2022-09-15T04:02:03.9948504Z D:/rubyinstaller-head-x64/lib/ruby/gems/3.2.0+2/gems/cool.io-1.7.1/lib/cool.io/io.rb:35:in `attach': expected loop to be an instance of Coolio::Loop, not nil (ArgumentError)
2022-09-15T04:02:03.9948899Z
2022-09-15T04:02:03.9949030Z       @_read_watcher.attach(loop)
2022-09-15T04:02:03.9949263Z …
```
=> test_out_forward: Fix a failed test on Ruby 3.2 on Windows

.github/workflows/linux-test.yaml, .github/workflows/macos-test.yaml, .github/workflows/windows-test.yaml
N/A
v2 actions are now deprecated because of upgrading Node version from 12 to 16 on GitHub infrastructure.
See
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
No need to change 
N/A
=> github: migrate to GitHub Actions v3

lib/fluent/log/console_adapter.rb, lib/fluent/plugin_helper/http_server/server.rb, test/log/test_console_adapter.rb, test/plugin_helper/test_http_server_helper.rb
N/A
The log mechanism of [Async](https://github.com/socketry/async) gem was changed as of [async-1.17](https://github.com/socketry/async/releases/tag/v1.17.0). Async gem is used in [http_server helper](https://docs.fluentd.org/plugin-helper-overview/api-plugin-helper-http_server) of Fluentd. From async-1.17 it uses `Console::Logger` of [Console](https://github.com/socketry/console) gem which isn't compatible with Ruby's standard Logger. So we need to adapt it to our logger mechanism to output Async's log correctly.
For example sometimes following error is occurred on CI without this patch:
https://github.com/fluent/fluentd/pull/3842#discussion_r942080998
```
2022-07-01T01:29:37.2657850Z 	from …
```
=> Adapt Console::Logger to Fluent::Log

lib/fluent/plugin/buf_file.rb, lib/fluent/plugin/buf_file_single.rb
Partial fix for #3970
When `flush_at_shutdown` is `true`, the remaining chunk files during resuming are possibly broken since there may be a power failure or similar failure.
Without this log, even if we notice that we have received corrupted data on the destination server, we can not know which chunks may have been corrupted.
Not needed.
Add warning messages for restoring buffer with `flush_at_shutdown true`.
=> buffer: warning message for restoring buffer with flush_at_shutdown

lib/fluent/plugin/buf_file.rb, lib/fluent/plugin/buf_file_single.rb
Partial fix for #3970
Add logs of possible time periods of buffer corruption during buffer resumimg.
When one of the remaining chunk files is broken at the resuming, this logs `created_at` and `modified_at` of other files undetected.
```
Since a broken chunk file was found, it is possible that other files remaining at the time of resuming were also broken. Here is the list of the files.
/path/buffer.bxxxx.log: created_at=2023-01-26 18:08:16 +0900 modified_at=2023-01-26 18:08:17 +0900
/path/buffer.qxxxx.log: created_at=2023-01-26 18:08:16 +0900 modified_at=2023-01-26 18:08:17 +0900
{...}
```
Fluentd can detect the corruption when the meta-data is broken, but can't when the chunk file is broken.
So if one corruption …
=> buffer: add log for time periods of restored chunks which may be broken

lib/fluent/supervisor.rb, test/command/test_ctl.rb, test/test_supervisor.rb
( https://github.com/fluent/fluentd/pull/4034#discussion_r1096936046 )
Simply replace `$$` with `Process.pid`.
`Process.pid` is easier to read and understand.
=> Replace $$ with Process.pid

test/test_supervisor.rb
* ( https://github.com/fluent/fluentd/pull/4034#discussion_r1096938978 )
* ( https://github.com/fluent/fluentd/pull/4034#discussion_r1096936155 )
* ( https://github.com/fluent/fluentd/pull/4034#discussion_r1096940341 )
* test: use double quotes for strings containing line breaks
* test: use `.&` for nil check
* test: remove `begin rescue end` when `Process.kill`
=> refactor: test/test_supervisor.rb

lib/fluent/supervisor.rb, test/test_supervisor.rb
Fixes #3932
Don't generate sigdump files after stopping.
https://github.com/fluent/fluentd/pull/4034#issuecomment-1415431569
=> Disable sigdump after stop

lib/fluent/plugin/out_forward.rb, lib/fluent/plugin/out_forward/ack_handler.rb, test/plugin/out_forward/test_ack_handler.rb
Fixes #3962
`out_forward` has a thread always checking the ack and closing the socket.
* https://github.com/fluent/fluentd/blob/e89092ce1132a933c12bb23fe8c9323c07ca81f5/lib/fluent/plugin/out_forward.rb#L512
When stopping Fluentd, some other threads try to do it at the same time.
* https://github.com/fluent/fluentd/blob/e89092ce1132a933c12bb23fe8c9323c07ca81f5/lib/fluent/plugin/out_forward.rb#L347
* https://github.com/fluent/fluentd/blob/e89092ce1132a933c12bb23fe8c9323c07ca81f5/lib/fluent/plugin/out_forward.rb#L376
This somtimes causes errors.
Although these errors are harmless (at least as far as I can confirm), we should fix this.
This fixes 2 points.
1. Suppress the error log.
* When another thread closes the …
=> out_forward: fix error  of ack handling confict on stopping with `require_ack_response` enabled

lib/fluent/plugin/buf_file.rb, lib/fluent/plugin/buf_file_single.rb, lib/fluent/plugin/buffer.rb, lib/fluent/plugin/buffer/file_chunk.rb, lib/fluent/plugin/output.rb, test/command/test_plugin_config_formatter.rb, test/plugin/test_buf_file.rb, test/plugin/test_buf_file_single.rb
Partial fix for #3970
Backup feature was implemented in #1952, but it didn't support handling broken file chunks found in resuming buffer.
This extends the backup feature to support it.
When a file is corrupted due to power failure or other reasons, backing up the file allows us to guess which data was corrupted.
Example of a forwarder:
```xml
<system>
root_dir /test/fluentd/forwarder
</system>
<source>
@type sample
tag test
</source>
<match test.**>
@id test_id
@type forward
<buffer tag,time,file>
@type file
path /test/fluentd/forwarder/buffer
timekey 24h
flush_mode interval
flush_interval 10s
overflow_action drop_oldest_chunk
</buffer>
<server>
host localhost
port 24224
</server>
</match>
```
We can reproduce …
=> buffer: backup broken file chunk

lib/fluent/supervisor.rb, test/test_logger_initializer.rb
When log rotation is enabled on Windows, the log path is separated for each process.
But, the new path value is not applied to the instance variable, so it breaks the following behavior, since #2663.
https://github.com/fluent/fluentd/blob/bf7498d6ff2805bfa517bbd6f7c17103c7d879d4/lib/fluent/supervisor.rb#L576-L580
https://github.com/fluent/fluentd/blob/bf7498d6ff2805bfa517bbd6f7c17103c7d879d4/lib/fluent/supervisor.rb#L601-L606
I can't assume that `File.chown` is used on Windows, but `reopen` must be fixed.
(`--user` and `--group` are not intended to be used on Windows, right? If so, I will add some comments to [the doc](https://docs.fluentd.org/deployment/command-line-option) and code.)
I found this problem during fixing:
* #4037
I thought this should be …
=> Windows: Fix a bug that the wrong log file is reopened with log ratote setting when flushing or graceful reloading

lib/fluent/test/driver/base.rb, test/command/test_fluentd.rb, test/plugin/test_in_tcp.rb, test/plugin/test_out_http.rb, test/plugin/test_output.rb, test/plugin_helper/test_server.rb
Fixes #4048
After unit testing, clean up in /tmp.
(If you cannot terminate with SIGTERM and terminate with SIGKILL, some files cannot be cleaned up. https://github.com/fluent/fluentd/pull/4050#issuecomment-1427932016 https://github.com/fluent/fluentd/pull/4050#issuecomment-1430665345)
None
None
=> Clean up after unit tests

test/command/test_fluentd.rb
None
On Windows, unnecessary timeout always occurred in `TestFluentdCommand`.
This fix reduces the test time to 210s from 520s on my environment:
* Widows 10 Home
* Ruby 3.2
* CPU: core i7
* RAM: 16GB
Not needed.
Not needed.
=> TEST: Don't use SIGTERM on Windows

lib/fluent/command/fluentd.rb, lib/fluent/supervisor.rb, test/command/test_fluentd.rb, test/plugin/test_in_monitor_agent.rb, test/test_supervisor.rb
I found this problem during fixing:
* #4037
I thought this should be fixed in a separate PR, so I made this PR first.
Options explicitly specified in command line should be preferred to options specified in system config.
* https://github.com/fluent/fluentd/pull/1398
* https://github.com/fluent/fluentd/pull/2674
However, options that have a default value, such as `suppress_repeated_stacktrace`, are preferred even when they are not specified in the command line.
Because of this, the following setting is not reflected.
```xml
<system>
suppress_repeated_stacktrace false
</system>
```
> Options explicitly specified in command line should be preferred to options specified in system config.
In order to realize this …
=> Fix problem that some system configs are not reflected

test/compat/test_parser.rb, test/test_formatter.rb
( https://github.com/fluent/fluentd/pull/4066#discussion_r1118388855 )
There is a case where `Hash` is used in the test of `configure` method.
I fixed it because `configure` method should use `Fluent::Config::Element`.
=> test: use `Fluent::Config::Element` in test

test/test_formatter.rb
None. This is the following fix to
* #4074 
* #4074
In this PR, some tests passing `Hash` directly to `Fluent::Plugin::Base::configure()` are fixed so that passing `Fluent::Config::Element`.
However, a part of those tests should use the test-driver, and then we can passing `Hash` to the driver safely.
None.
None.
=> Use driver for formatter tests

test/plugin/test_parser_regexp.rb
( https://github.com/fluent/fluentd/pull/4066#discussion_r1118388855 )
I didn't know why it was commented out, but it looked good on `Fluent::Test::Driver::Parser.new(...)`.
https://github.com/fluent/fluentd/pull/1286
None
None
=> Use driver for RegexpParser tests

lib/fluent/log.rb, lib/fluent/supervisor.rb, test/test_supervisor.rb
I found this problem during fixing:
* https://github.com/fluent/fluentd/issues/4037#issuecomment-1427366287
This fix should be done before fixing this issue.
In the supervisor process, Fluentd initializes the logger twice, at `Supervisor::configure()` and `Supervisor.load_config()`.
`Supervisor.load_config()` is called in ServerEngine's reloading function, but Fluentd doesn't use the function even when `SIGHUP` or `SIGUSR2`.
So I can't see the reason for initializing the logger in that callback.
This also fixes a problem that `ignore_same_log_interval` is not passed to the `Supervisor.load_config()` and that option is not reflected to the logger of the supervisor process.
Not needed.
**Release …
=> Refactor logger initialization

lib/fluent/plugin/output.rb
None.
Fluentd outputs the following warning message even when we use `out_secondary_file` for the secondary.
```
2023-03-09 14:50:10 +0900 [warn]: #0 Use different plugin for secondary. Check the plugin works with primary like secondary_file primary="Fluent::Plugin::FileOutput" secondary="Fluent::Plugin::SecondaryFileOutput"
```
Example config:
```xml
<source>
@type sample
tag test.hoge
sample {"message": "hoge"}
</source>
<match test.**>
@type file
path /test/fluentd/log/${tag}/fluentd.log
<format>
@type single_value
</format>
<buffer tag>
@type file
path /test/fluentd/buffer
flush_mode interval
flush_interval 10s
</buffer>
<secondary>
@type secondary_file
directory /test/fluentd/error/
</secondary>
</match>
``` …
=> Suppress warning using different secondary for out_secondary_file

lib/fluent/daemon.rb, lib/fluent/log.rb, lib/fluent/supervisor.rb, test/test_supervisor.rb
This PR is the following to
* #4065 
It does not load the config anymore since
* #2709
So it should simply return the config for `ServerEngine`.
Not needed.
Not needed. (This fixes only internal specifications)
=> Refactor Superviser.load_config()

lib/fluent/plugin/base.rb, test/plugin/test_base.rb
Fixes #4051
Override `system_config` only if `conf.target_worker_ids.size >= 1`.
* If `<worker N>` or `<worker 0-N>` is not set, `conf.target_worker_ids` is empty.
* If `<system> workers N </system>` is not set, `system_config.workers` defaults to 1.
* Fix value of `system_config.workers` at `run_configure`
* Change argument type of `Fluent::Plugin::Base::configure()` to `Fluent::Config::Element` only.
=> Fix value of `system_config.workers` at `run_configure`

lib/fluent/command/fluentd.rb, test/command/test_fluentd.rb
This fixes a bug related to #4037
Sorry, there was a bug in my following fix. 
* #4064
* 8e9f46ae84e6fd603cf46c63cdef6f3b2334cca3
This PR fixes it.
Not needed.
Not needed.
=> Fix command option `--quiet`

test/command/test_fluentd.rb
Fixes #4095
Make`TestFluentdCommand` tests stable on Windows.
(Please see #4095 for details.)
Not needed.
Not needed.
=> Make `TestFluentdCommand` tests stable on Windows

fluentd.gemspec, lib/fluent/supervisor.rb, lib/fluent/test/driver/base.rb, lib/fluent/test/startup_shutdown.rb, test/plugin/test_in_http.rb, test/plugin_helper/test_server.rb
Use ServerEngine's new feature:
https://github.com/treasure-data/serverengine/pull/143
On Windows, this prevents SocketManager from wrongly selecting an unavailable port, such as a port in excluded port range.
Fixes https://github.com/treasure-data/serverengine/issues/140
(Sorry, I made the issue in ServerEngine, and not made it here.)
On Windows, `ServerEngine::SocketManager::generate_path` sometimes generates an unavailable port.
This makes Fluentd fail to start.
To fix this, I made the fix for ServerEngine:
* https://github.com/treasure-data/serverengine/pull/143
This is a fix on Fluentd's side.
Not needed.
Fix bug that Fluentd sometimes tries to use an unavailable port and …
=> SocketManager: Use new feature to select path automatically

MAINTAINERS.md
N/A
According to our [governance policy](https://github.com/fluent/fluentd/blob/master/GOVERNANCE.md), we need to vote for changing maintainership.
As @daipom contributing to fluentd a lot, so I'll propose @daipom as a new maintainer.
Currently, there are following organizations:
* @sonots (ZOZO)
* @cosmo0920 , @edsiper (Calyptia)
* @toru-takahashi (Treasure Data)
* @ashie, @kenhys (ClearCode)
And individual developers.
* @okkez
* @repeatedly 
* @tagomoris 
* @fujimotos
(We need to also update affilicated compaty information in MAINTAINERS.md later)
Thus, the total number of organization is 8 and satisfying the majority of 2/3 must be  not less than  6.
So every organization need to show :+1: or :-1:
**Docs …
=> Proposing a new Fluentd maintainer

lib/fluent/plugin/output.rb
None.
Fix bug of 3a796cd93c21190e46cd0ac108e1265e482f07a3
* #4087
In Fluentd v1.16.0, the following setting causes NameError and Fluentd to fail to start.
```xml
<match test.**>
@type stdout
<buffer>
@type memory
</buffer>
<secondary>
@type file
path /tmp/backup/
</secondary>
</match>
```
Error
```console
$ bundle exec fluentd -c .\fluent\fluent.conf
2023-04-03 18:49:11 +0900 [info]: init supervisor logger path=nil rotate_age=nil rotate_size=nil
2023-04-03 18:49:11 +0900 [info]: parsing config file is succeeded path=".\\fluent\\fluent.conf"
2023-04-03 18:49:11 +0900 [info]: gem 'fluentd' version '1.16.0'
C:/Users/reang/Documents/work/fluentd/fluentd/lib/fluent/plugin/output.rb:429:in `configure': uninitialized …
```
=> Fix NameError of `SecondaryFileOutput` when setting secondary other than `out_secondary_file`

templates/new_gem/test/helper.rb.erb
None
This code in `test/helper.rb` is unnecessary, so we should remove it.
```rb
$LOAD_PATH.unshift(File.expand_path("../../", __FILE__))
```
`File.expand_path("../../", __FILE__)` returns the repository's top directory path.
So, this enables using relative paths from the top for `require`, such as `require test/helper`.
However, we don't use this.
We use the following and use the relative paths from `test/` or `lib/`.
https://github.com/fluent/fluentd/blob/37858d36563222d71adde291d539b3ef514aff9b/templates/new_gem/Rakefile#L6-L7
https://github.com/fluent/fluentd/blob/37858d36563222d71adde291d539b3ef514aff9b/templates/new_gem/test/plugin/test_input.rb.erb#L1-L2
So I think it's unnecessary as template content. …
=> Plugin template: Remove unnecessary code

lib/fluent/plugin_helper/server.rb, test/plugin_helper/test_server.rb
None.
This fixes the problem revealed in the following PR.
* #4117
This PR just suppresses error message of UDPServer over max_bytes on Windows.
Suppressed error message on Windows:
(Please see https://github.com/fluent/fluentd/pull/4117#issuecomment-1488716289 for details)
> unexpected error in processing UDP data error_class=Errno::EMSGSIZE error="A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself. - recvfrom(2)"
New info message on Windows:
> A received data was ignored since it was too large.
On Windows, `UDPSocket::recv` and `UDPSocket::recvfrom` can raise …
=> Server helper: Suppress error of UDPServer over max_bytes on Windows

test/plugin/test_in_udp.rb
None.
Add test of `message_length_limit` for `in_udp` because there was no test for this option.
Not needed.
Not needed.
=> in_udp: add test of message_length_limit

CONTRIBUTING.md
N/A
omnibus-td-agent is obsolete, we should use fluent-package-builder for tracking issues of td-agent instead.
N/A
N/A
=> Fix a link for the repository of td-agent

test/plugin/test_in_tcp.rb
* Partially fixes #4136
We should use `Driver::logs` so that we don't have to use `shutdown: false`.
Not needed.
Not needed (or the same as the title).
=> Test `in_tcp`: Fix undesirable way to assert logs

lib/fluent/event.rb, test/plugin/test_output_as_buffered_compress.rb
* Fixes #4146
Fix that `compress` setting causes an unexpected error when receiving already compressed MessagePack.
When setting `compress gzip` of buffer, and it tries to process `CompressedMessagePackEventStream`, the following error occurs.
[error]: xxx unexpected error on reading data
host="xxx" port=xxx error_class=ArgumentError
error="unknown keyword: :packer"
This is caused by the signature unmatching in c6c6c038c5cacab6fcb9aa89a714d9366ac4902e.
A possible use case is a two-stage transfer.
Forwarder1(out_forward) -> Forwarder2(in_forward, out_forward) -> Aggregator(in_forward)
In this case, Forwarder2 should process the data of `CompressedMessagePackEventStream` as is (i.e. without decompressing) and …
=> Buffer: Fix that `compress` setting causes unexpected error when receiving already compressed MessagePack

lib/fluent/plugin/in_tcp.rb, test/plugin/test_in_tcp.rb
None.
Add the same feature to `in_tcp` as `message_length_limit` in `in_udp`, to drop too large incoming data.
TODO
**TODO**:
=> `in_tcp`: Add `message_length_limit` to drop large incoming data

lib/fluent/msgpack_factory.rb, test/test_msgpack_factory.rb
None.
@tkoba66 reported this bug. Thanks!
When `in_forward` abnormally receives incomplete (broken) data, it can't correctly receive the next sent data.
One of the main possible cases is as follows.
* There are multiple senders (`out_forward`) to one receiver (`in_forward`).
* An anomaly such as power failure occurs in one sender, and it sends broken data to the receiver.
* It can break the next data sent from another healthy sender.
Fixes bug in c6c6c038c5cacab6fcb9aa89a714d9366ac4902e (#2559).
Received incomplete data must not affect data from other senders.
In #2559, the local unpacker started to be cached to improve the performance, but this caused the problem where corrupted data was unintentionally left in …
=> MessagePackFactory: Make sure to reset local unpacker to prevent received broken data from affecting other receiving data

lib/fluent/supervisor.rb, test/test_supervisor.rb
Fixes #4187
Fix a bug of f8b73a571954b4a7cfb137cb521edeb370f3f0b5 (#4091).
Before that fix, Fluentd can start if rotation is enabled but the log file path is not specified.
After that fix, the logger setup starts to fail on Windows.
This fix solves it.
Not needed.
=> Fix failure to launch Fluentd on Windows with log rotation but not specifying the log path in the command line

lib/fluent/plugin/in_forward.rb, lib/fluent/plugin/in_sample.rb, lib/fluent/plugin/out_exec_filter.rb, lib/fluent/plugin_helper/event_loop.rb, lib/fluent/plugin_helper/thread.rb, test/plugin/test_in_forward.rb, test/plugin/test_in_unix.rb, test/plugin/test_multi_output.rb, test/plugin/test_out_exec_filter.rb, test/plugin/test_out_file.rb, test/plugin/test_output.rb, test/plugin/test_output_as_buffered.rb, test/plugin/test_output_as_buffered_retries.rb, test/plugin/test_output_as_buffered_secondary.rb, test/plugin_helper/test_child_process.rb, test/test_log.rb
Partially resolves: https://github.com/fluent/fluentd/issues/4099
This PR combines some chained method calls into one specialized call. This improves readability and performance since unnecessary intermediate steps are removed.
None
=> Refactoring: Combine chained method calls

lib/fluent/plugin/in_tail/position_file.rb
None.
This fixes the following warning message:
```
... already exists. use latest one: deleted ...
```
Even when `follow_inodes` was enabled, this message was displayed based on the path.
This PR fixes it.
In addition, this PR slightly fixed this message when `follow_inodes` is enabled.
```
... (inode: ...) already exists. use latest one: deleted ...
```
No need because this fixes only the log message.
=> in_tail: Fix warning log about overwriting entry with follow_inodes

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
* Partially fixes #3614
If `refresh_watchers` run before `update_watcher`, the old implementation of `update_watcher` detach wrongly the new TailWatcher which is added in `refresh_watcher`. This causes the problem of stopping tailing log and handle leak.
The test case `test_updateTW_after_refreshTW` reproduces this problem.
This PR solves it.
NOTE: There is another BUG about unwatching. (I adjusted some expected values of the tests for this BUG.)
When `refresh_watcher` find the rotated old file AFTER unwatching it (`rotate_wait`), then the logs will be collected in duplicate.
If `refresh_watcher` find it BEFORE unwatching it (`rotate_wait`), this problem doesn't occur because the position entry is still alive.
We …
=> in_tail: Ensure to detach correct watcher on rotation with follow_inodes

lib/fluent/command/ctl.rb, lib/fluent/command/plugin_config_formatter.rb, lib/fluent/config/dsl.rb, lib/fluent/config/v1_parser.rb, lib/fluent/counter/server.rb, lib/fluent/counter/validator.rb, lib/fluent/engine.rb, lib/fluent/match.rb, lib/fluent/plugin/base.rb, lib/fluent/plugin/filter_record_transformer.rb, lib/fluent/plugin/in_http.rb, lib/fluent/plugin/in_tail.rb, lib/fluent/plugin/out_exec_filter.rb, lib/fluent/plugin/output.rb, lib/fluent/plugin/parser_json.rb, lib/fluent/plugin_helper/record_accessor.rb, lib/fluent/plugin_id.rb, test/plugin/test_base.rb, test/plugin_helper/test_server.rb
Partially resolves: https://github.com/fluent/fluentd/issues/4099
This PR improves string processing by using more efficient methods.
In most cases, the performance differences between the old and new methods are shown as microbenchmarks at https://github.com/fastruby/fast-ruby.
None
=> Refactoring: Improve string processing

lib/fluent/plugin/in_tail.rb
Fixes #4190 
~~Add validation to make sure detach_watcher is detaching expected watcher. This can avoid unexpectedly detach new watcher created for new log file and lead to log stuck transiently.~~
Add log to check that detaching inode is the same as the detaching TailWatcher's inode when enabling `follow_inodes`.
Note: If they do not match, canceling the detach (by adding `return`) may prevent an incorrect detach.
Since #4208 will prevent an incorrect detach, we will only add the warning log in this PR for now.
N/A
~~Fix transient log stuck in in_tail when log file rotated and follow_inodes is enabled~~
=> in_tail: Check detaching inode when follow_inodes

fluentd.gemspec
None.
In 0.2.5, the bug of wrong value of `hash pairs` and `array elements` fixed.
That version will be installed without this fix, but I think we should explicitly update the version.
(Is it correct?)
We can confirm it as follows on non-Windows. (On Windows, we can use `fluent-ctl`.)
```console
$ sudo kill -CONT {pid}
$ less /tmp/sigdump-{pid}.log
```
Before: Too small Array and Hash sizes
```
...
Array 61 elements
Hash 8 pairs
```
After: Correct size
```
...
Array 41,555 elements
Hash 15,752 pairs
```
No need.
Fix wrong Object Array and Hash sizes of SIGDUMP.
**ETC**:
Should we merge this into v1.16 too?
=> Update sigdump to 0.2.5

lib/fluent/log.rb, test/test_log.rb
* Fixes #4174
With `ignore_same_log_interval`, the cache can grow unlimitedly.
This limits the size to 1000.
Specification:
* When the size is over 1000, clear the unneeded caches.
* If the size is still over, clear all the caches.
If needed, we can make the max size configurable, but for now, I don't think we need it.
Adding an explanation to https://docs.fluentd.org/deployment/logging#ignore_same_log_interval is desirable.
=> logger: Fix cache for `ignore_same_log_interval` growing unlimitedly

lib/fluent/plugin/in_tail/position_file.rb
* Related to #4212
Add debug logs about pos file compaction like the following.
```
[debug]: ... Compacted entries: [...]
[debug]: ... Remove missing entries. existing_targets=[...] entries_after_removing=[...]
```
Example on the startup.
```
2023-07-06 22:55:49 +0900 [info]: #0 fluent/log.rb:360:info: starting fluentd worker pid=1347502 ppid=1347482 worker=0
2023-07-06 22:55:49 +0900 [debug]: #0 fluent/log.rb:339:debug: Compacted entries: [101581096, 101581105]
2023-07-06 22:55:49 +0900 [debug]: #0 fluent/log.rb:339:debug: Remove missing entries. existing_targets=[101581096, 101581105] entries_after_removing=[101581096, 101581105]
2023-07-06 22:55:49 +0900 [debug]: #0 fluent/log.rb:339:debug: tailing paths: …
```
=> in_tail: Add debug log for pos file compaction

lib/fluent/event.rb, test/plugin/test_buffer_chunk.rb
None.
The argument `unpacker` of [ChunkMessagePackEventStreamer.each](https://github.com/fluent/fluentd/blob/v1.16.1/lib/fluent/event.rb#L313) seems to have been added in order to match the feature with `EventStream` at
* #2559
However, that previous implementation at that point does not work as expected.
It has never caused any issues just because the argument was not used at all.
When `unpacker` is passed, the following will be executed.
```ruby
unpacker.each($block)
```
This just iterates the internal buffer of the unpacker without reading `io` of the chunk.
Thus it seems to me that this doesn't work as expected.
Note: It could be implemented so that this argument is used, but given that it has not been used so …
=> Fix broken argument `unpacker` of `ChunkMessagePackEventStreamer.each`

lib/fluent/plugin/in_tail.rb, lib/fluent/plugin/in_tail/position_file.rb, test/plugin/in_tail/test_position_file.rb, test/plugin/test_in_tail.rb
* Following up to #4208
* Another idea of #4221
We must not unwatch targets that still exist.
If unwatching an existing target, it causes log duplication.
This problem exists from v1.13.3 (the following fix).
* #3466
This can occur when enabling `follow_inodes`.
In the existing implementation, `update_watcher` needs to unwatch the old TailWatcher since `refresh_watcher` can't unwatch it when `update_watcher` is called first (when rotation happens).
It is because `update_watcher` discards the old TailWatcher and `refresh_watcher` can't recognize the old inode is disappeared.
https://github.com/fluent/fluentd/blob/e12069351a431b30bd84996d60ff9c4a7e78adce/lib/fluent/plugin/in_tail.rb#L504-L507
However, it can wrongly …
=> in_tail: prevent wrongly unwatching with follow_inodes

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
Not related to a particular issue, but it can have something to do with reported log duplication or resource leak phenomenon about `in_tail`.
Ensure to discard TailWatcher with missing target when follow_inodes.
For example, when a rotation process is slow, there is a small time lag between moving and adding files.
There is a possibility that StatWatcher notifies too quickly to the TailWatcher before the new file is moved to that target path. From the TailWatcher, it appears as if the file is resurrected once it disappeared.
In this case, `refresh_watcher` can't recognize it, so TailWatcher needs to discard self correctly.
In the previous implementation, it was not done.
So it caused the handle leak and log …
=> in_tail: Ensure to discard TailWatcher with missing target when follow_inodes

README.md, fluentd.gemspec
N/A
The service discovery plugin helper use Array#prepend, it means that the ruby version must be 2.5 or later precisely.
fluentd.work/lib/fluent/plugin_helper/service_discovery.rb:71:in
`service_discovery_configure': undefined method `prepend' for
[]:Array (NoMethodError) from
/work/fluent/fluentd/fluentd.work/lib/fluent/plugin/out_
https://github.com/fluent/fluentd-docs-gitbook/pull/471
N/A
=> Raise minimum required ruby version

lib/fluent/plugin/buffer/file_chunk.rb, lib/fluent/plugin/buffer/file_single_chunk.rb, lib/fluent/registry.rb, lib/fluent/unique_id.rb
Dunno. Minor perf improvements never hurt badly.
=> Minor performance improvements

lib/fluent/fluent_log_event_router.rb
Previously this code was assigning instance variable like
@log_event_router = log_event_router
later, during the refactoring of Fluent Engine it was changed to
log_event_router = log_event_router
which can be now removed. For reference please review changeset at 3a3aee0227b621b61d1d7f258147f7ff661316e0
=> remove unnecessary self-assignment

lib/fluent/system_config.rb, test/config/test_system_config.rb
Fix for rotate_age where Fluentd passes as Symbol while Ruby Logger expects String
Fixes #4227
=> Fix for rotate_age where Fluentd passes as Symbol

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
Fixes #3614
Closes #4264
Although known stall issues of in_tail on `follow_inode` case are fixed
in v1.16.2, it has still a similar problem on `!follow_inode` case.
In this case, a tail watcher is possible to mark the position entry as
`unwatched` if it's tansitioned to `rotate_wait` state by
`refresh_watcher` even if another newer tail watcher is managing it.
It's hard to occur in usual because `stat_watcher` will be called
immediately after the file is changed  while `refresh_wather` is called
every 60 seconds in default. However, there is a rare possibility that
this order might be swapped especillay if in_tail is busy on processing
large amount of logs. Because in_tail is single threadied, event queues
such as …
=> in_tail: Fix a stall bug on !follow_inode case

lib/fluent/plugin/buffer.rb
When the write function encounters a chunk that is defined as a Nil object, the call to synchronize fails. This failure causes an unexpected error that is caught and handled like a failure to connect, with a 30 second retry delay. 
In an environment with a large amount of data, and this Nil scenario occurring frequently, it introduces significant processing delays since all processing activity stops during the 30 second window. The topic being queried continues to fill but no agents parse the data, leading to an ever-increasing backlog.
=> Buffer: Fix NoMethodError with empty unstaged chunk arrays

lib/fluent/plugin/in_tail.rb
This PR just adds a warning log for the following issue's !follow_inodes case.
* #3614
I believe this problem has been resolved with the next PR.
* #4327
This PR adds a warning log just in case in order to prevent silent collection stops like that.
For `refresh_watcher`, if an exisiting TailWatcher already follows a target path with a different inode, it means that the TailWatcher following the rotated file still exists.
In this case, `refresh_watcher` can't start the new TailWatcher for the new current file.
So, we should output a warning log in order to prevent silent collection stops, such as #4327.
The warning log example:
```
Could not follow a file (inode: 101584481) because an existing watcher for that …
```
=> in_tail: add warning for silent stop on !follow_inodes case

CHANGELOG.md
None.
Applies the v1.16.3 release note to the master branch.
Not needed.
Not needed.
=> CHANGELOG: apply v1.16.3 release

lib/fluent/plugin/buffer.rb, test/plugin/test_buffer.rb
Fix #3089
It fixes following error when many `chunk bytes limit exceeds` errors are occurred:
```
2020-07-28 14:59:26 +0000 [warn]: #0 emit transaction failed: error_class=IOError error="closed stream" location="/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.1/lib/fluent/plugin/buffer/file_chunk.rb:82:in `pos'" tag="cafiscode-eks-cluster.default"
2020-07-28 14:59:26 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.1/lib/fluent/plugin/buffer/file_chunk.rb:82:in `pos'
2020-07-28 14:59:26 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.1/lib/fluent/plugin/buffer/file_chunk.rb:82:in `rollback'
2020-07-28 14:59:26 +0000 [warn]: #0 …
```
=> buffer: Avoid to process discarded chunks in `write_step_by_step`

lib/fluent/plugin/buffer.rb, test/plugin/test_buffer.rb
Fix #3089
Backport #4342 to v1.16 branch
N/A
=> buffer: Avoid to process discarded chunks in write_step_by_step (for v1.16)

lib/fluent/plugin/owned_by_mixin.rb, test/plugin/test_owned_by.rb, test/plugin/test_storage.rb
This variable is unused since b32781d0f03e7984f3b4eeec63f7310fa340b562.
=> Drop unused @_plugin_id_configured from all own-able plugins

test/plugin_helper/test_child_process.rb
N/A
open("|command") spawns command and create pipes for processing pipeline.
This feature of Kernel#open is deprecated, replace it with IO#popen.
It fixes the following warning:
warning: Calling Kernel#open with a leading '|' is deprecated and will
be removed in Ruby 4.0; use IO.popen instead
N/A
N/A
=> test: use IO#popen instead of Kernel#open

.github/workflows/linux-test.yaml, .github/workflows/macos-test.yaml, .github/workflows/windows-test.yaml, test/command/test_fluentd.rb, test/plugin/test_out_forward.rb, test/plugin_helper/test_child_process.rb
N/A
Fix failed tests on Ruby 3.3.
They seem just only test's problem except #4058, no need to fix fluentd itself.
For #4058, we have to decide whether to fix in fluentd or Ruby, so mark these tests as pending until decide it.
N/A
N/A
=> Fix or suppress failed tests on Ruby 3.3

lib/fluent/plugin/buffer.rb
N/A
This PR adapts the logging for buffers to avoid calls of `dump_unique_id_hex` if the current log level is not trace. During high-load situations with a small chunk size, this makes a noticeable difference.
=> buffer: Avoid calling dump_unique_id_hex if log level is not trace

.github/DISCUSSION_TEMPLATE/q-a-japanese.yml, .github/DISCUSSION_TEMPLATE/q-a.yml
Fixes N/A
Currently, there is no template for all of GitHub Discussion categories.
At least, form template should be applied for Q&A category to support the problem.
N/A
N/A
=> github: add missing GitHub discussions form

.github/workflows/test-ruby-head.yaml, fluentd.gemspec
N/A
CI is failed on Ruby 3.4-dev:
https://github.com/fluent/fluentd/actions/runs/7949585800
N/A
N/A
=> Fixes for Ruby 3.4-dev

lib/fluent/plugin/buffer.rb
=> Backport (v1.16): buffer: Avoid calling dump_unique_id_hex if log level is not trace

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
N/A (Follow up for https://github.com/fluent/fluentd/pull/4327#issuecomment-1774330298)
After a tail watcher transitions to `rotate_wait` state, the `rotate_wait` timer is no longer managed by in_tail, it might cause unexpected behaviour. e.g.)
* It's never unwatched when shutdown occurs before `rotate_wait` passed.
* Needless `rotate_wait` timers are executed when it detects more rotations.
This patch fixes such unexpected behaviour.
N/A
=> in_tail: Manage tail watchers that are `rorate_wait` state too

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
=> Backport (v1.16): in_tail: Manage tail watchers that are `rorate_wait` state too (#4334)

test/command/test_fluentd.rb, test/plugin/test_out_forward.rb, test/plugin_helper/test_child_process.rb
=> Backport (v1.16):  Fix or suppress failed tests on Ruby 3.3 (#4375)

test/plugin/test_out_forward.rb
None.
* Avoid calling `instance_start` in duplicate.
* Avoid not calling `instance_shutdown`.
To fix the following error, which sometimes occurs.
I'm not sure this actually fixes it, but at least we should fix the points above.
Error: test: Create new connection per send_data(ForwardOutputTest): ArgumentError: expected loop to be an instance of Coolio::Loop, not nil
C:/hostedtoolcache/windows/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/cool.io-1.8.0/lib/cool.io/io.rb:35:in `attach'
C:/hostedtoolcache/windows/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/cool.io-1.8.0/lib/cool.io/io.rb:35:in `attach'
C:/hostedtoolcache/windows/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/cool.io-1.8.0/lib/cool.io/socket.rb:39:in `attach' …
=> CI: Fix unstable tests of out_forward

test/plugin/test_out_forward.rb
* #4433
Backported from 5d18f3551387c4f12b399c7e5ed33f2ac17a27c4
=> Backport (v1.16): CI: Fix unstable tests of out_forward (#4433)

CHANGELOG.md, lib/fluent/version.rb
* Version
* CHANGELOG
When releasing v1.16.3, we forgot to apply the version to the master.
So, the version on the master is still v1.16.2.
Currently, the master is the same minor version as the LTS branch v1.16, so we should update it along with the LTS branch, until releasing v1.17 on the master.
=> Apply v1.16.4 to master

lib/fluent/plugin/buffer.rb, test/plugin/test_buffer.rb
* Fixes #4446
After 95438b2eeb4bb5586a4031c1fbc35756f3c12565 (#4342) (v1.16.4), there is a section where chunks do not have a lock in `write_step_by_step()`.
`write_step_by_step()` must ensure their locks until passing them to the block.
Otherwise, race condition can occur and it can cause emit error by IOError.
Example of warning messages of emit error:
[warn]: #0 emit transaction failed: error_class=IOError error="closed stream" location=...
[warn]: #0 send an error event stream to @ERROR: error_class=IOError error="closed stream" location=...
Not needed.
Buffer: Fix emit error of v1.16.4 sometimes failing to process large data exceeding chunk size limit
=> buffer: fix emit error of race condition

lib/fluent/plugin/buffer.rb, test/plugin/test_buffer.rb
Backported from 13a5199522ee1fc3f55c40a73d30c6036d34570f (#4447).
=> Backport (v1.16): buffer: fix emit error of race condition

.github/workflows/test-ruby-head.yml, .github/workflows/test.yml
N/A
TESTOPTS=-v shows running test and the result.
If something weird happen, it show error immediately.
As rake task executes many tests, so it may be better to delay showing test details later.
NOTE: --progress-style=fault-only helps you to focus on failure, but it is inconvenient when test case has stalled.
N/A
N/A
=> ci: do not show test detail immediately

.github/workflows/test.yml
Backported from 4f02d3f4577c8e704cc6f2956c5f1526bafffa99 (#4452).
=> Backport (v1.16): ci: do not show test detail immediately

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
This PR will fix none of the issue but this was raised in community slack channel.
This feature was requested on the community slack's #fluentd channel.
For now, we didn't support for square brackets pattern and one character matcher in #expand_paths.
This shouldn't be fit for the following case.
The logs are named as follows:
```
.
├── 01.log
├── 02.log
├── 03.log
├── 12.log
├── 13.log
├── 20.log
```
Then, a user wants to tail 02.log, 03.log, 12.log, and 13.log, and excluding to tail 01.log and 20.log with the following configuration:
```
<source>
@type tail
path "[0-1][2-3].log"
<parse>
@type none
</parse>
tag log.test
read_from_head
use_extended_glob # To use this expansion, users need to enable this feature …
```
=> in_tail: Expand glob capability for square brackets and one character matcher

fluentd.gemspec, lib/fluent/plugin/out_http.rb, test/plugin/test_out_http.rb
Fixes #4444
This PR adds a new authentication method to the HTTP output plugin for AWS sigV4. We need it so that customers can use Fluentd to send data to Amazon OpenSearch Ingestion which supports the Fluentd output plugin, but requires SigV4 authentication.
* `aws_sigv4` - When this option is specified, Fluentd will sign requests using AWS Signature Version 4.
* `aws_service` - The AWS service to authenticate against
* `aws_region` - The AWS region to use when authenticating
* `aws_role_arn` - The AWS role ARN to assume when authenticating
You can optionally specify an `aws_role_arn`. If you provide it, Fluentd will assume that AWS role and send requests signing from that role. Otherwise, …
=> Implements AWS SigV4 for the HTTP output plugin. 

lib/fluent/plugin/in_http.rb, test/plugin/test_in_http.rb
To make it easy to use fluentd for CSP reporting, let's parse retrieved data as JSON if the content type is `application/csp-report`. It is guaranteed to be a well-formatted JSON according to the specification: https://www.w3.org/TR/CSP2/#violation-reports.
=> plugin/in_http: recognize CSP reports as JSON data

test/log/test_console_adapter.rb
N/A
Follow the change of the log format as of console v1.24.
N/A
N/A
=> Fix a failed test of ConsoleAdapter

lib/fluent/plugin/filter_parser.rb, lib/fluent/plugin/in_http.rb, lib/fluent/plugin/parser_json.rb, lib/fluent/plugin/parser_msgpack.rb, test/plugin/test_parser_json.rb, test/plugin/test_parser_msgpack.rb
* Partially Fixes #4100 
* Remake #4106
* Add fixes for `parser_msgpack` and some refactoring
* Make sure `parser_json` and `parser_msgpack` return Hash.
* Make `parser_json` and `parser_msgpack` accept only `Hash` or `Array` of `Hash`
It is wrong for Parser to return a record that is not Hash.
Subsequent processing may result in errors.
`parser_json` and `parser_msgpack` could return non-Hash objects, so they have been fixed in this PR.
In addition, `in_http` was designed based on this wrong behavior, so it has been fixed as well in this PR.
**However, we have a remaining problem with `filter_parser`.**
`filter_parser` could return Array based on this wrong behavior.
This PR disables it, so it can not return …
=> Make sure parser returns hash

lib/fluent/plugin/out_http.rb, test/plugin/test_out_http.rb
N/A
The HTTP output plugin recreates a connection for every HTTP request. In combination with TLS and high network latencies, this can result in very poor performance. This PR adds an option to reuse connections. 
The implementation caches one connection per flush thread. The cache is part of the HTTP plugin instance and is implemented as an array. When a thread creates its first request, it gets assigned a slot (id) in this array and the id is stored in a thread local variable. Since this slot is exclusively used by a single thread, no synchronization is required. If the endpoint changes at runtime, the old connection will be closed and replaced by a new connection to the new endpoint. During shutdown, all open …
=> out_http: Add option to reuse connections

lib/fluent/plugin/filter_parser.rb
* Following to #4474
* Related to #4100
The following problem of `filter_parser` remains in #4474 :
> However, we have a remaining problem with filter_parser.
filter_parser could return Array based on this wrong behavior.
This PR disables it, so it can not return multiple parsed results anymore.
Even though it was wrong to begin with, it's possible that this change in specifications would be unacceptable.
We need to consider this change carefully.
I explain some examples in detail below.
At least, it would not be happy if some events were lost without any warnings or errors.
So, this PR adds an error handling for that.
TODO
=> filter_parser: add error event for multiple parsed results

lib/fluent/config/yaml_parser/parser.rb, test/test_config.rb
Closes https://github.com/fluent/fluentd/issues/4463.
This is because `@log_level` is invalid for YAML.
Instead, we should interpret $log_level as `@log_level` on YAML parser.
Needed. Will handle on it.
Same as title.
=> config: yaml_parser: Handle $log_level element for special case

lib/fluent/log/console_adapter.rb
* Fixes #4487
`Console::Terminal::Logger` class path has changed in `console` gem v1.25:
https://github.com/socketry/console/compare/v1.24.0...v1.25.0#diff-6e7355da8b6a8f794e74e462aebbe4b23f7752dab2a29967d17707eabb71ce12
This causes `LoadError` for `ConsoleAdapter`.
It means that `LoadError` occurs for `plugin_helper/http_server/server`, and Fluentd replaces the helper by `plugin_helper/http_server/compat/server`.
It also causes the CI failures.
This PR fixes these problems.
Please see #4487 for details.
Note: We can't stop considering the older versions because v1.25
requires Ruby v3.1 or older. 
Note: There is another issue about `console` gem v1.25:
* #4488
Not needed because this is a bug …
=> log/console_adapter: support 'console' gem v1.25

fluentd.gemspec
* Fixes #4477 for v1.16 branch
* Fixes #4487 for v1.16 branch
console gem v1.24 and v1.25 have some specification changes that influence Fluentd.
Since they have nothing to do with vulnerability, we should keep the version on v1.16 stable branch.
Not needed.
Not needed since there is no specification change.
=> v1.16: keep console v1.23

lib/fluent/plugin/out_file.rb, test/plugin/test_out_file.rb
* Partially fixes #4490
According to the issue https://github.com/fluent/fluentd/issues/4490 , if a `tag` or `keys` is set in the chunk key and those placeholders do not exist in the `symlink_path`, multiple chunks to compete for the same symlink and some logs can't be taken from it.
Since this is unintended behavior, I think it is necessary to inform the user that this is a bad setting by the warn message.
If a `tag` or `keys` is set in the chunk key and those placeholders do not exist in the `symlink_path`, the following warning log is displayed.
Ex:
```
<source>
@type sample
sample {"message":"hoge","key1":"A","key2":"B"}
tag test.hoge
</source>
<source>
@type sample
sample …
```
=> out_file:add warn message for symlink_path-setting

.github/DISCUSSION_TEMPLATE/q-a-japanese.yml, .github/DISCUSSION_TEMPLATE/q-a.yml
None.
Stop using rendering for freestyle text area.
Not happy about free style text area being enclosed in a code block automatically.
I think this is not intended, right?
If there is a reason, please let me know.
Q&A:
Not needed.
Not needed.
=> github: stop using rendering for freestyle text area

lib/fluent/plugin/out_file.rb, test/plugin/test_out_file.rb
Backported from 74b2e3d7f86f656d65951c4ea095d68c20b0b858. (#4502)
=> Backport(v1.16): out_file: add warn message for symlink_path setting (#4502)

fluentd.gemspec
None.
Fix the current situation where CI is failing entirely.
* Example: https://github.com/fluent/fluentd/actions/runs/9312942781
`timecop` 0.9.9 supports `Process.clock_gettime`.
This breaks specifications of `process_extenstion` of Fluentd and `Fluent::Clock`.
* https://github.com/travisjeffery/timecop/pull/419
`Fluent::Clock` uses `CLOCK_MONOTONIC_RAW` if possible and it does not be affected.
However, `CLOCK_MONOTONIC_RAW` is not available on Windows, so the impact on tests on Windows is very significant.
For now, we should avoid this effect by fixing the version.
Not needed.
Not needed.
=> test: fix timecop version to keep clock specs in tests

fluentd.gemspec
Backported from 57f821b194516fabd8b8d396842932126c6cbaf5. (#4521)
=> Backport(v1.16): test: fix timecop version to keep clock specs in tests

fluent.conf
None.
It would be not desirable to try to connect with `192.168.0.11` or `192.168.0.12` by default.
This causes the following warning log:
... detached forwarding server ...
Also, this could cause some unintended problems.
Not needed.
(I have checked https://github.com/fluent/fluentd-docs-gitbook. There are no related documents.)
=> default config: disable out_forward setting

.github/workflows/test-ruby-head.yml, .github/workflows/test.yml
Fixes N/A
run Node 20 instead of Node 16.
It fixes the following warning:
Node.js 16 actions are deprecated. Please update the following actions
to use Node.js 20: actions/checkout@v3. For more information see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
N/A
N/A
=> github: use checkout@v4 to fix a warning

test/plugin/in_tail/test_io_handler.rb, test/plugin/in_tail/test_position_file.rb
None.
`Tempfile#binmode` returns `File` object, not own `Tempfile` object.
So, GC will cause its finalizer and the file can be closed during the test.
This is the cause why these tests sometimes fail by `IOError: closed stream`.
Not needed.
Not needed.
=> test: fix IOError about Tempfile closed when GC

lib/fluent/config/yaml_parser/parser.rb, test/test_config.rb
Backported from 236d87d07fea8b3396f33985247c96ad59911f3e. (#4482)
=> Backport(v1.16): config: yaml_parser: Handle $log_level element for special case (#4482)

lib/fluent/plugin/parser_json.rb, test/plugin/test_parser_json.rb
None
If Oj is not installed, LoadError with the empty message is raised.
* https://github.com/fluent/fluentd/blob/b25e989daf1501e606a6980e64670cbd3a755209/lib/fluent/plugin/parser_json.rb#L53
So, the current condition `/\boj\z/.match?(ex.message)` does not work and the following meaningless warning is displayed.
{datetime} [warn]: #x {id} LoadError
After this fix, the log message will be:
{datetime} [info]: #x {id} Oj is not installed, and failing back to Yajl for json parser
Not needed.
=> parser_json: fix wrong LoadError warning

lib/fluent/plugin/out_http.rb, test/plugin/test_out_http.rb
Fixes #4410
Adds a `compress gzip` option to `out_http` to enable compressing the http request before sending it to save on bandwidth
=> out_http: add gzip option

fluentd.gemspec
None.
Remove the following files from the gem file:
* test files
* git files
* Gemfile
This reduces the gem file size: 867k -> 558k.
We should reflect recent gemspec moves as the current `files` and `test_files` are written more than 10 years ago:
* #116
`test_files` is not documented anymore:
* https://guides.rubygems.org/specification-reference
Looks like it is not recommended:
* https://github.com/rubygems/bundler/pull/3207
Looks like we should also remove git files and Gemfile because the template of Bundler 2.4.13 is as follows:
```rb
spec.files = Dir.chdir(__dir__) do
`git ls-files -z`.split("\x0").reject do |f|
(File.expand_path(f) == __FILE__) ||
f.start_with?(*%w[bin/ test/ spec/ features/ .git .circleci …
```
=> gemspec: Remove unnecessary files from gem file

templates/new_gem/fluent-plugin.gemspec.erb
None.
* Same as #4534 for `fluent-plugin-generate`
Not needed.
(There is no change needed for https://docs.fluentd.org/plugin-development#generating-plugin-project-skeleton)
Not needed.
=> plugin-generator: update gemspec to remove unnecessary files

lib/fluent/plugin/in_exec.rb, test/plugin/test_in_exec.rb
* Fixes #4460
Add option: `encoding` to handle non-ASCII characters.
TODO
=> in_exec: add option 'encoding' to handle non-ASCII characters

lib/fluent/plugin/in_tail.rb, test/plugin/in_tail/test_fifo.rb, test/plugin/in_tail/test_io_handler.rb, test/plugin/test_in_tail.rb
**Which issue(s) this PR fixes:**
Fixes https://github.com/fluent/fluentd/issues/4494
recoverd from #4491 
**What this PR does / why we need it:**
Before this patch, long lines could cause breakdowns in fluentd, potentially posing a vulnerability. With this patch, max_line_size will be integrated into the FIFO, enabling the system to skip lines exceeding the maximum size before executing receive_lines.
**Docs Changes:**
**Release Note:**
=> Fix line skipping issue in receive_lines method

lib/fluent/plugin/in_tail.rb, test/plugin/in_tail/test_io_handler.rb, test/plugin/test_in_tail.rb
Fixes #
https://github.com/fluent/fluent-plugin-prometheus/issues/190
It adds metrics to the throttling of logs while taling logs using in_tail plugin as asked in the above issue.
Once this PR is accepted corresponding changes in prometheus plugin will be made to expose the newly added throttling metric
Need docs change in prometheus plugin for metrics description 
NA
=> Add throttling metrics

.github/workflows/stale-actions.yml, .github/workflows/test-ruby-head.yml, .github/workflows/test.yml
Fixes N/A
It is related token permission topic
https://scorecard.dev/viewer/?uri=github.com/fluent/fluentd
By default, it is enough to give read permission.
For stale actions, it require manipulate issues,
so write permission is given explicitly.
N/A
N/A
=> github: set job permissions

.github/workflows/test-ruby-head.yml
N/A
When a test is failed, the job should be also treated as failed.
But the current setting ignore errors.
Please see https://github.com/fluent/fluent-plugin-sql/actions/workflows/linux-ruby-head.yml
(Some tests are always failed with recent Ruby Head but jobs are all green.)
N/A
N/A
=> CI: Set continue-on-error false for Ruby Head

lib/fluent/compat/call_super_mixin.rb, lib/fluent/compat/propagate_default.rb
Fixes #
UnboundMethod#bind_call method had been introduced at Ruby 2.7 that it aims to improve performance.
Ref. https://bugs.ruby-lang.org/issues/15955
- Linux
- Manjaro Linux x86_64
- Kernel: 6.9.12-1-MANJARO
- CPU: Intel i9-14900 (32) @ 5.500GHz
- Compiler: gcc 14.1.1
- Ruby: ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-linux]
```ruby
gemfile do
gem 'benchmark-ips'
end
class Foo
def foo
end
end
meth = Foo.instance_method(:foo)
obj = Foo.new
x.report("bind.call") {
meth.bind(obj).call
}
x.report("bind_call") {
meth.bind_call(obj)
}
x.compare!
end
```
```
$ ruby bind_call.rb
ruby 3.3.4 (2024-07-09 revision be1089c8ec) …
```
=> Use UnboundMethod#bind_call method instead to improve performance

fluentd.gemspec
Fixes #
logger gem was marked as bundled gem for Ruby 3.5. Therefore, it will not work on Ruby 3.5 unless it is added as a dependency.
Ref. https://github.com/ruby/ruby/commit/d7e558e3c48c213d0e8bedca4fb547db55613f7c
(Currently, this patch will suppress `warning: logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.` message.)
Similar with GH-4411
=> Add logger gem as dependency for Ruby 3.5

test/plugin/test_out_http.rb
Fixes #
This patch will suppress following warnings:
```
$ ruby -w -I"lib:test" test/plugin/test_out_http.rb
test/plugin/test_out_http.rb:445: warning: ambiguity between regexp and two divisions: wrap regexp in parentheses or add a space after `/' operator
test/plugin/test_out_http.rb:446: warning: ambiguity between regexp and two divisions: wrap regexp in parentheses or add a space after `/' operator
test/plugin/test_out_http.rb:482: warning: ambiguity between regexp and two divisions: wrap regexp in parentheses or add a space after `/' operator
test/plugin/test_out_http.rb:483: warning: ambiguity between regexp and two divisions: wrap regexp in parentheses or add a space after `/' operator
```
Seems we will see …
=> Suppress non-parenthesis warnings

.github/dependabot.yml
It was turned out by OpenSSF
https://scorecard.dev/viewer/?uri=github.com/fluent/fluentd
Check update about github-actions every weekly.
N/A
N/A
=> github: Add missing dependabot task

test/plugin/in_tail/test_io_handler.rb, test/plugin/in_tail/test_position_file.rb
Backported from 3b2798479769c1c24020c65d0caf170423b3591a. (#4515)
=> Backport(v1.16): test: fix IOError about Tempfile closed when GC (#4515)

lib/fluent/plugin/parser_json.rb, test/plugin/test_parser_json.rb
Backported from 891ce71120198fa168232a796d4267a3cdb2c91f. (#4522)
=> Backport(v1.16): parser_json: fix wrong LoadError warning (#4522)

lib/fluent/plugin_helper/http_server/server.rb, test/plugin_helper/test_http_server_helper.rb
Fixes #4597
This patch will be able to handle frozen strings as paths to mount in http server.
=> Fix FrozenError in http_server plugin helper

lib/fluent/plugin/in_sample.rb
Fixes #4575
When in_sample plugin is used with filter parser which uses remove_key_name_field, it raises the following error repeatedly.
```
#0 dump an error event: error_class=ArgumentError error="message does not exist"
```
This kind of error occurs when key_name and remove_key_name_field removes key from record with destructive change in filter parser affects generated sample data.
TODO: Add `reuse_record` parameter.
N/A
=> in_sample: duplicate record to support destructive change

CHANGELOG.md, lib/fluent/version.rb
Fixes #
Let's make a point release.
N/A
N/A
=> Add v1.17.1

.github/workflows/test.yml
Fixes #
For updating documentation or release task, running GitHub Actions is waste of resource.
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
N/A
N/A
=> github: suppress running CI only for documentation

lib/fluent/command/fluentd.rb, test/command/test_fluentd.rb
* Fixes #4269
This option is explained as "add plugin directory".
However, since v1.16.0, the behavior has changed to overwrite the default value unintentionally.
(PR: #4064, commit: 41678bf0e5f355979fd3b584cea5828690ccbac8).
We should revert it to the original behavior.
Not needed.
=> fluentd command: fix '--plugin'('-p') option not to overwrite default value

lib/fluent/command/fluentd.rb, test/command/test_fluentd.rb
Backported from fe5843f8faf1add2bce1a34008bf08d0aaf75d0b (#4605)
=> Backport(v1.16): fluentd command: fix plugin_dirs not to overwrite default value (#4605)

CHANGELOG.md
Fixes #
It helps user to notice wrong configuration, but
bug itself is not fixed yet.
So it is not notable enhancement.
Re-label Misc it.
N/A
N/A
=> Fix inappropriate labeling in CHANGELOG.md

.github/workflows/test.yml
Fixes #
For updating documentation or release task, running GitHub Actions
is waste of resource.
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-
N/A
N/A
=> Backport(v1.16): github: backport suppress running CI only for documentation

lib/fluent/event_router.rb
Fixes #
It is trivial, but apparently index is not used at all in this method.
It does not change internal logic at all.
N/A
N/A
=> Use each instead of each_with_index

lib/fluent/supervisor.rb, lib/fluent/system_config.rb, test/config/test_system_config.rb, test/test_supervisor.rb
Fixes #4418
This patch will add `path` attribute in sytem/log section due to configure log file path  by System Configuration.
=> system_config: add path attribute in system/log section

lib/fluent/config/literal_parser.rb, test/config/test_literal_parser.rb
Fixes #4385 
Support [Embedded Ruby Code](https://docs.fluentd.org/configuration/config-file#embedded-ruby-code) for Hashes and Arrays.
```
key ["foo","#{1 + 1}"] => key ["foo","2"]
key {"foo":"#{1 + 1}"} => key {"foo":"2"}
```
This is not backward compatible.
We can disable this feature by surrounding the entire value with single quotes.
```
key `["foo","#{1 + 1}"]` => key ["foo","#{1 + 1}"]
key `{"foo":"#{1 + 1}"}` => key {"foo":"#{1 + 1}"}
```
**Note: this feature is for JSON literals**
This feature is for literals that using `[]` or `{}`.
* We need to sort out the `literal` and `value` of the Fluentd Config Syntax.
* Fluentd first interprets `literal` by parsing the config file.
* `literal` is String or JSON. …
=> Config File Syntax: Extend Embedded Ruby Code support for Hashes and Arrays

test/command/test_fluentd.rb
Fixes #
Related to #4584
Ruby parser will be replaced new parser in Ruby 3.4. https://github.com/ruby/ruby/commit/ea2af5782df63266577ba08a4ef4c30b6d63e564
The new parser might not have a fully compatible of Syntax error messages.
So I modified the assert pattern to succeed in the Ruby HEAD.
```ruby
module Foo
class Bar
def say
puts "hello"
end
end
```
```
$ ruby -v test.rb
ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]
test.rb: --> test.rb
Unmatched keyword, missing `end' ?
> 1  module Foo
test.rb:6: syntax error, unexpected end-of-input, expecting `end' or dummy end (SyntaxError)
end
^
```
```ruby
ruby -v test.rb
ruby 3.4.0dev (2024-09-25T02:45:33Z master 76543a34ab) +PRISM [x86_64-linux]
test.rb: --> …
```
=> test_fluentd: fix assert pattern of syntax error for Ruby HEAD

lib/fluent/plugin/in_http.rb, test/plugin/test_in_http.rb
Fixes #4179 
Adds optional configuration option to add prefix tag to records tailed through `in_http` plugin, similar to `in_forward`.
TODO
=> in_http: add `add_tag_prefix` configuration option

fluentd.gemspec, lib/fluent/plugin_helper/http_server/server.rb, test/plugin_helper/test_http_server_helper.rb
Fixes #
http_server plugin helper doesn't work with Async 2.x gem due to using obsolete usage.
This PR updates it to follow current documented way:
https://github.com/socketry/async-http/blob/0a65acd7cf7486e1877f0da86580e1692cd8207b/readme.md#usage
It's applicable both Async 2.x & Async 1.x.
~~But this PR still stay on Async 1.x because io-event gem which is required by Async 2.x can't build on Windows.~~
- TODO
- https://github.com/socketry/io-event/issues/111
- cool.io introduces IO::Buffer which conflicts with Ruby core classes. It affects the behavior of the Async HTTP server.
- Ref. https://github.com/socketry/async-http/issues/175
=> http_server: Ready to support Async 2.0 gem

test/plugin/out_forward/test_socket_cache.rb, test/test_event_router.rb
Fixes #4063
If it use the object applied `dont_allow` in the other test through `ObjectSpace.each_object`, it will cause the error.
To relax object constraints, this patch will use `never` instead.
See sample code in https://github.com/fluent/fluentd/issues/4063#issuecomment-2416121325
=> tests: use never instead of dont_allow

test/command/test_cat.rb, test/command/test_fluentd.rb, test/helper.rb, test/plugin/test_in_forward.rb, test/plugin/test_in_http.rb, test/plugin/test_in_monitor_agent.rb, test/plugin/test_in_syslog.rb, test/plugin/test_in_tcp.rb, test/plugin/test_in_udp.rb, test/plugin/test_out_forward.rb, test/plugin/test_out_stream.rb, test/plugin_helper/test_http_server_helper.rb, test/plugin_helper/test_server.rb, test/plugin_helper/test_socket.rb
Fixes #4674
It obtains unused port number for TCP by `unused_port` method and the number has been used in UDP. 
And that number may be already used by UDP sockets. 
This patch will obtain and use unused ports appropriately for each protocol.
=> tests: fix unused_port

test/config/test_element.rb, test/plugin/test_filter_stdout.rb, test/plugin/test_formatter_hash.rb, test/plugin/test_out_stdout.rb
Fixes #
Hash#inspect style was updated at
https://github.com/ruby/ruby/commit/a8a059125314a411eaf879a9fbfdc68d6c01a667
Since its changing, fluentd's CI fails with Ruby HEAD. https://github.com/fluent/fluentd/actions/runs/11427054212
This patch will recognize that style changing due to pass the CI tests.
=> tests: fix Hash#inspect format for Ruby HEAD

.github/workflows/test.yml
Fixes #4678
The latest bundler appears to depend on the recent RubyGems version.
Make sure to install the latest rubygem to run CI successfully.
=> CI: use latest rubygems

test/plugin/test_in_udp.rb
N/A
Although it's improved in #4676, it still takes 5 seconds on windows.
It can be reduced more by sending data that doesn't exceed the limit.
```
test: message_length_limit:                           .: (1.104855)
```
N/A
N/A
=> test_in_udp: Reduce execution time of message_length_limit test

test/command/test_cat.rb
Fixes #4674
Fixes an issue where an inappropriate protocol was specified in the `unused_port` method.
See https://github.com/fluent/fluentd/issues/4674#issuecomment-2440522606
=> test_cat: use proper protocol in unused_port method

.github/workflows/test.yml
Fixes #
Often I forget to Signed-off and push new commit again. I would like the github action related to the PR to be automatically cancelled at that time. I want the test to run on the newly pushed commit immediately.
Ref. https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
=> ci: add cancel-in-progress setting

test/plugin/out_forward/test_ack_handler.rb
Fixes #4694
When using stub, sometimes it causes errors when it remove prepared methods by stub. To improve the stability of the CI, this patch will use the singleton method instead of stub.
=> test_ack_handler: use singleton method instead of stub for stability

test/plugin/test_in_tail.rb
Fixes #4707
This PR will fix unstable tests.
=> test_in_tail: fix flaky tests for file rotation

lib/fluent/command/fluentd.rb, lib/fluent/engine.rb, lib/fluent/env.rb, lib/fluent/plugin/out_buffer.rb, lib/fluent/plugin/output.rb, lib/fluent/plugin_helper/event_emitter.rb, lib/fluent/root_agent.rb, lib/fluent/source_only_buffer_agent.rb, lib/fluent/supervisor.rb, lib/fluent/system_config.rb, test/command/test_fluentd.rb, test/config/test_system_config.rb, test/plugin/test_out_buffer.rb, test/plugin_helper/test_event_emitter.rb, test/test_plugin_classes.rb, test/test_root_agent.rb, test/test_source_only_buffer_agent.rb, test/test_supervisor.rb
None.
Related to
* #4622
This feature may be useful on its own, but mainly, this feature will help #4622 feature.
Add `--with-source-only` option to `fluentd` command.
(Ref: Similar to existing [--without-source](https://docs.fluentd.org/deployment/command-line-option) option)
(We can use system-config option `with_source_only` as well)
It launches Fluentd with Input plugins only.
Here is the specification.
* Those Input plugins emits the events to SourceOnlyBufferAgent.
* The events is kept in the buf_file during the source-only-mode.
* Send SIGWINCH to the supervisor to cancels the mode.
* After canceled, the new agent starts to load the buffer.
* Not supported on Windows. (It would be possible, but I want to …
=> Add with-source-only feature

lib/fluent/system_config.rb
* Additional fix for #4661
Need this to the section handled in `SystemConfig#dup`.
This should be added to SYSTEM_CONFIG_PARAMETERS, though this is not affected to the actual behavior,
Note: I don't understand why `log` section is not added. Maybe it should be added as well.
(It should be done by another PR).
Not needed
Not needed
=> system_config: add source_only_buffer to SYSTEM_CONFIG_PARAMETERS

lib/fluent/supervisor.rb
Fixes #4354
To daemonize the process, the following code will be invoked on Windows:
https://github.com/fluent/fluentd/blob/89f0a76fb2e050659f0a503823beb2ad8cf899eb/lib/fluent/daemon.rb#L13
$log variable does not exist because it has not executed `Superviser#setup_global_logger` method until here.
It will perform a new startup process and prepare a logger in
https://github.com/fluent/fluentd/blob/89f0a76fb2e050659f0a503823beb2ad8cf899eb/lib/fluent/daemon.rb#L13
This patch will only avoid the error since a logger is not required this process.
Not needed.
=> command: fix NoMethodError of --daemon under Windows

lib/fluent/plugin/in_udp.rb, lib/fluent/plugin_helper/server.rb, test/plugin_helper/test_server.rb
Fixes #
This patch will allow to adjust receive buffer size of UDP socket like in_udp plugin.
Related to https://github.com/fluent/fluentd/pull/1789
https://github.com/fluent/fluentd-docs-gitbook/pull/518
The same as the title
=> plugin_helper/server: Add receive_buffer_size parameter in transport section

test/plugin/test_filter_parser.rb
None.
Adds and reorganizes tests of `filter_parser` for abnormal cases.
The following PR will significantly change the implementation of `filter_parser`.
* #4620
However, currently, there aren't enough tests for abnormal cases.
This condition makes it difficult to safely make such a large change.
This PR solves the problem.
Not needed.
(Or not needed because this changes only the test codes.)
=> ci: filter_parser: reorganize tests for abnormal cases

lib/fluent/plugin/filter_parser.rb, test/plugin/test_filter_parser.rb
Fixes #4100
Transition `filter_parser` from using `filter_with_time` to `filter_stream` logic
N/A
N/A
=> filter_parser: Transition from single record to stream

lib/fluent/plugin_helper/cert_option.rb
* Fixes #4462
Use SSL_VERIFY_NONE by default for [transport tls](https://docs.fluentd.org/configuration/transport-section).
(VERIFY_PEER is used by default now).
VERIFY_NONE should be used when `client_cert_auth false` (default).
Before this fix, we need to set `insecure true` for this.
However, `insecure` option should mainly be for cipher strength.
It would not be intended VERIFY_PEER without VERIFY_FAIL_IF_NO_PEER_CERT was used even if `client_cert_auth false`.
(When VERIFY_PEER without VERIFY_FAIL_IF_NO_PEER_CERT, server does certification only when clients send its certificate.
This would be why we overlooked it long time)
Before:
| insecure | client_cert_auth |               verify_mode                | …
=> transport tls: use SSL_VERIFY_NONE by default

lib/fluent/engine.rb, lib/fluent/plugin/in_syslog.rb, lib/fluent/plugin/in_tcp.rb, lib/fluent/plugin/in_udp.rb, lib/fluent/plugin/input.rb, lib/fluent/root_agent.rb, lib/fluent/supervisor.rb, test/command/test_fluentd.rb, test/test_plugin_classes.rb, test/test_root_agent.rb, test/test_supervisor.rb
* Fixes #4622
This replaces the current `SIGUSR2` (#2716) with the new feature.
(Not supported on Windows).
* Restart the new process with zero downtime
The primary motivation is to enable the update of Fluentd without data loss of plugins such as `in_udp`.
(Please See #4622).
Specification:
* 2 ways to trigger this feature (non-Windows):
* [Signal](https://docs.fluentd.org/deployment/signals): `SIGUSR2` to the supervisor.
* Sending `SIGUSR2` to the workers triggers [the traditional GracefulReload](https://github.com/fluent/fluentd/pull/2716).
* (Leave the traditional way, just in case)
* [RPC](https://docs.fluentd.org/deployment/rpc): `/api/processes.zeroDowntimeRestart`
* Leave `/api/config.gracefulReload` for …
=> SIGUSR2:  zero downtime restart

lib/fluent/plugin_helper/cert_option.rb, lib/fluent/plugin_helper/server.rb, test/plugin_helper/test_cert_option.rb
Fixes #3121
ensure_fips option checks whether FIPS mode is
enabled by OpenSSL side.
If FIPS is not enabled in OpenSSL side, it raise an error (blocking launching fluentd) when ensure_fips is true.
NOTE: If FIPS mode is enabled by default, ensure_fips does nothing.
Document ensure_fips option in transport-section.
https://docs.fluentd.org/configuration/transport-section#tls-setting
N/A
=> Ensure FIPS compliant mode by ensure_fips option

test/plugin/test_out_file.rb
Fixes #4727
Fix the file open mode so that gz files can be read properly.
=> test_out_file: fix file open mode for binary file

test/command/test_cat.rb
Fixes #4729
The binary files may not be read properly. 
This changes to read files in binary mode.
=> test_cat: specify the reading size to read in binary mode

test/plugin/out_forward/test_socket_cache.rb, test/test_event_router.rb
Backported from a2b935ae2bc4b4d43e5adddbec01092ea4228b9e (#4671).
=> Backport(v1.16): tests: use never instead of dont_allow (#4671)

.github/workflows/test.yml
Fixes #
Tweak current CI targets.
Added: Ruby 3.4
Dropped: Ruby 3.0/2.7
Ruby 2.7 EOL: 2023-03-31
Ruby 3.0 EOL: 2024-04-23
NOTE: until PR is merged [1], 3.4 points 3.4.0-rc1.
[1] https://github.com/ruby/setup-ruby/pull/677
N/A
N/A
=> ci: tweak supported/dropped version

fluentd.gemspec
Fixes #
Since logger 1.6.3 or later, there is a bug that it cause unexpected exception (no implicit conversion of Integer into String (TypeError)) on windows. So hold on 1.6.2 for a while.
See https://github.com/ruby/logger/issues/107
N/A
N/A
=> windows: add workaround for unexpected exception

.github/workflows/test.yml
Fixes #
Ruby 3.4 binary on Windows is not ready yet.
Exclude it from matrix until it is available.
N/A
N/A
=> ci: exclude test case until Ruby 3.4 is installable

.github/workflows/test.yml
Fixes #
It seems that it fixes failure with Ruby 3.1 on windows.
```
undefined method `ignored?' for #<Gem::Specification:0x000001dccaf43168
```
N/A
N/A
=> ci: use latest rubygems again for Ruby 3.1 on windows

.github/workflows/test.yml
Fixes #
[RubyInstaller 3.4.1](https://github.com/oneclick/rubyinstaller2/releases/tag/RubyInstaller-3.4.1-1) was released.
So we can use Ruby 3.4 on Windows in CI.
=> ci: include Ruby 3.4 on Windows

test/plugin/test_out_exec_filter.rb
Fixes #4754
This PR will stable the tests.
=> test_out_exec_filter: add a sleep to ensure the stream is emitted

lib/fluent/plugin/in_tail.rb
Fixes #
`String#slice` will allocate redundant heap area internally if an incorrect length is specified.
This PR might reduce the memory usage with `in_tail` plugin.
* verify code
```ruby
gemfile do
gem 'benchmark-memory'
end
str = "a" * 10_000_000
split_point = 9_999_900
Benchmark.memory do |x|
x.report("1") {
str.slice(split_point, str.length)
}
x.report("2") {
str.slice(split_point, str.length - split_point)
}
x.report("3") {
str.slice(split_point..str.length)
}
end
```
* result
```
1    10.000M memsize (    10.000M retained)
2.000  objects (     1.000  retained)
2.000  strings (     1.000  retained)
2 …
```
=> in_tail: fix slice length to reduce memory usage

lib/fluent/plugin/formatter_out_file.rb, lib/fluent/plugin/storage_local.rb
Fixes #
When I read 10 GB file using in_tail plugin, it calls Yajl methods many times when it stores to buffer file.
Recently, Ruby's JSON has huge improvement and it is much faster.
Ref. https://byroot.github.io/ruby/json/2024/12/15/optimizing-ruby-json-part-1.html
* Before
* It spent 88.533409329 sec to handle 10 GB file
* After
* It spent 72.324643557 sec to handle 10 GB file
* config
```
<source>
@type tail
path /home/watson/prj/sandbox/fluentd/log/access*.log
pos_file /home/watson/prj/sandbox/fluentd/log/access.log.pos
tag log
read_from_head true
follow_inodes true
refresh_interval 5
<parse>
@type none
</parse>
</source>
<match **>
@type file
path /home/watson/prj/sandbox/fluentd/log/log
</match>
```
**Docs …
=> Use JSON instead of Yajl to improve performance of store/load files

lib/fluent/plugin/in_tail.rb
Fixes #
When log files are rotated at high speed, the lifespan of `IOHandler` objects may become extended.
Along with this, the lifespan of `@iobuf` also increases.
Since `@iobuf` uses 8 KB of memory, if many such objects exist simultaneously, memory usage might significantly increase.
=> in_tail: reduce the lifespan of the buffer area

lib/fluent/plugin/output.rb
Fixes #
This will remove evaluating `meta_and_data[meta] ||= []` in the iterator every time to improves performance slightly.
The results of actually reading a 10 GB file are as follows.
* Before: 67.50262675 sec
* After: 63.862033033 sec
Here is micro benchmark code.
```ruby
gemfile do
gem 'benchmark-ips'
end
h1 = {}
h2 = Hash.new { |h, k| h[k] = [] }
key = :foo
x.report("1") {
h1[key] ||= []
h1[key][0] = 1
}
x.report("2") {
h2[key][0] = 1
}
x.compare!
end
```
```
ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +PRISM [x86_64-linux]
1     1.776M i/100ms
2     2.239M i/100ms
Calculating …
```
=> output: use Hash.new {|hash, key| ... } for default value

lib/fluent/plugin/buffer/chunk.rb
Fixes #
This PR will add fast path to join chunk data using `Array#join`.
`Array#join` is faster and consumes less memory.
* verify
```ruby
gemfile do
gem 'benchmark-ips'
gem 'benchmark-memory'
end
def benchmarks(x, ary)
x.report("b") {
adding = ''.b
ary.each do |a|
adding << a.b
end
}
x.report("join") {
ary.join.force_encoding(Encoding::ASCII_8BIT)
}
end
ary = ('あ'..'ん').to_a
benchmarks(x, ary)
x.compare!
end
Benchmark.memory do |x|
benchmarks(x, ary)
end
```
```
ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +PRISM [x86_64-linux]
b    15.571k i/100ms
join    94.632k i/100ms
Calculating …
```
=> chunk: add fast path to join chunk data

lib/fluent/plugin/in_tail.rb, lib/fluent/plugin/out_secondary_file.rb, lib/fluent/plugin/parser.rb
Fixes #
#match method returns MatchData, it has some cost to create the MatchData object.
If it does not use MatchData object, it is better to use #match? method instead. 
* verify
```ruby
gemfile do
gem 'benchmark-ips'
gem 'benchmark-memory'
end
pattern = /\{.*,.*\}/
path = 'path/to/file'
x.report("match") {
pattern.match(path)
}
x.report("match?") {
pattern.match?(path)
}
x.compare!
end
```
```
ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +PRISM [x86_64-linux]
match     1.082M i/100ms
match?     1.683M i/100ms
match     11.116M (± 0.8%) i/s …
```
=> Use `#match?` method instead of `#match`

.github/workflows/test.yml, README.md, fluentd.gemspec
Fixes #
Raise baseline version of Ruby to 3.2.
fluent-package v5 (LTS) adopts ruby 3.2, so it is reasonable to set minimum version to Ruby 3.2. 
NOTE: these kind of changes might be better to apply in v1.19.0
https://docs.fluentd.org/quickstart/faq
https://github.com/fluent/fluentd-docs-gitbook/pull/524
N/A
=> Bump required ruby version

fluentd.gemspec, lib/fluent/plugin_helper/http_server/server.rb
Fixes #
Async v2.0 just supports Ruby 3.1 or above.
When we had been supporting Ruby 2.7 and 3.0, we need async v1.x and v2.x both.
Related to https://github.com/fluent/fluentd/pull/4619
Next fluentd version will drop support of Ruby 3.1 or below.
So, now we can remove the codes for async v1.x
Ref. https://github.com/fluent/fluentd/pull/4745
=> server: remove codes for async v1.x

lib/fluent/plugin/out_file.rb
Fixes #
Next fluentd version will drop support of Ruby 3.1 or below.
Ref. https://github.com/fluent/fluentd/pull/4745
So, we can remove the workaround for Ruby 2.7 and 3.0 on macOS that added at https://github.com/fluent/fluentd/pull/3579
=> out_file: remove workaround for Ruby 2.7 and 3.0 on macOS

fluentd.gemspec, lib/fluent/event.rb, lib/fluent/plugin/buffer.rb, lib/fluent/plugin/buffer/chunk.rb, lib/fluent/plugin/compressable.rb, lib/fluent/plugin/in_forward.rb, lib/fluent/plugin/out_file.rb, lib/fluent/plugin/out_forward.rb, lib/fluent/plugin/output.rb, test/plugin/test_buffer.rb, test/plugin/test_buffer_chunk.rb, test/plugin/test_buffer_file_chunk.rb, test/plugin/test_buffer_file_single_chunk.rb, test/plugin/test_buffer_memory_chunk.rb, test/plugin/test_in_forward.rb, test/plugin/test_out_file.rb, test/plugin/test_out_forward.rb, test/plugin/test_output.rb
Fixes #4162 
Adds new compression method support to handle messages
TODO
N/A
=> compressable:Zstd comp support

.github/ISSUE_TEMPLATE/config.yml
Fixes #
Add contact information to collect Fluentd's use-case
It help to collect Fluentd use-case widely.
N/A
N/A
=> github: Add link to feedback use-case/testimonial

.github/ISSUE_TEMPLATE/config.yml
Follow-up #4781 
It is harmful to add extra label.
Item should be placed under contact_links.
See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
N/A
N/A
=> github: remove needless label

lib/fluent/winsvc.rb
* Fixes #3937
Add retry for stop event for Windows Service to fix #3937.
If `Event.open()` ([OpenEvent](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-openeventw)) is called before the `Event.new()` ([CreateEvent](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createeventw)), `Event.open()` raises `Errno::ENOENT`.
This causes the service to be stopped while the supervisor and worker process remains.
It causes #3937.
This PR fixes it by adding retry.
https://github.com/fluent/fluentd/blob/30c3ce00ff165b1b5d9f53fc0a027074bbcab0da/lib/fluent/winsvc.rb#L90
https://github.com/fluent/fluentd/blob/30c3ce00ff165b1b5d9f53fc0a027074bbcab0da/lib/fluent/supervisor.rb#L299 …
=> Windows: Fix an issue where stopping the service immediately after startup could leave the processes

fluentd.gemspec, lib/fluent/plugin/buffer/file_single_chunk.rb
Fixes #
Since Ruby 3.4.0, `URI::DEFAULT_PARSER` causes warning of `warning: URI::RFC3986_PARSER.unescape is obsolete. Use URI::RFC2396_PARSER.unescape explicitly.`.
Ref. https://github.com/ruby/uri/commit/9997c1aceedfc205aa4f956b17d09b88feaf2fe2
* reproduce
```
$ bundle exec ruby -v -w -I"lib" test/plugin/test_buffer_file_single_chunk.rb -v
ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +PRISM [x86_64-linux]
/home/watson/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/async-2.21.1/lib/async/task.rb:298: warning: assigned but unused variable - error
/home/watson/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/async-pool-0.10.2/lib/async/pool/controller.rb:332: warning: assigned but unused variable - error …
```
=> file_single_chunk: use URI::RFC2396_PARSER due to suppress obsoleted message

test/command/test_cat.rb, test/command/test_fluentd.rb, test/helper.rb, test/plugin/test_in_forward.rb, test/plugin/test_in_http.rb, test/plugin/test_in_monitor_agent.rb, test/plugin/test_in_syslog.rb, test/plugin/test_in_tcp.rb, test/plugin/test_in_udp.rb, test/plugin/test_out_forward.rb, test/plugin/test_out_stream.rb, test/plugin_helper/test_http_server_helper.rb, test/plugin_helper/test_server.rb, test/plugin_helper/test_socket.rb
Fixes https://github.com/fluent/fluentd/issues/4674
It obtains unused port number for TCP by unused_port method and the number has been used in UDP.
And that number may be already used by UDP sockets.
This patch will obtain and use unused ports appropriately for each protocol.
Backported from https://github.com/fluent/fluentd/pull/4675
=> Backport(v1.16) tests: fix unused_port (PR#4675)

test/plugin/test_in_udp.rb
Fixes #
On Windows, `message_length_limit` test always take 300s for execution.
```
UdpInputTest:
test:  configure w/o parse section:			.: (0.002351)
test: configure[ipv4]:				.: (0.002723)
test: configure[ipv6]:				.: (0.002602)
test: message size with format[none]:			.: (1.029781)
test: message size with format[json]:			.: (1.113799)
test: message size with format[regexp]:		.: (1.110006)
test: message_length_limit:				.: (300.538596)
```
The 300 sec comes from https://github.com/fluent/fluentd/blob/a2b935ae2bc4b4d43e5adddbec01092ea4228b9e/lib/fluent/test/driver/base.rb#L36, and it always times out in Windows.
This patch set a short timeout to reduce test execution time on Windows.
Backported from …
=> Backport(v1.16) test_in_udp: add timeout for message_length_limit test (#4676)

test/plugin/test_in_udp.rb
Backport #4682 
Although it's improved in #4676, it still takes 5 seconds on windows. It can be reduced more by sending data that doesn't exceed the limit.
```
test: message_length_limit:                           .: (1.104855)
```
=> Backport(v1.16) test_in_udp: Reduce execution time of message_length_limit test (#4682)

test/plugin/test_out_forward.rb
Backport #4685 
Seems that timeout setting is short in ack_response_timeout.
Seems that It may take some time to receive a ACK response
so the process in ack handler has expired and the node is disabled.
This PR will remove unnecessary ack_response_timeout settings for the test
=> Backport(v1.16) test_out_forward: remove unnecessary ack_response_timeout setting (#4685)

test/command/test_cat.rb
Backport #4686
Fixes an issue where an inappropriate protocol was specified in the unused_port method.
See https://github.com/fluent/fluentd/issues/4674#issuecomment-2440522606
=> test_cat: use proper protocol in unused_port method (#4686)

test/plugin/out_forward/test_ack_handler.rb
Backport #4698 
When using stub, sometimes it causes errors when it remove prepared methods by stub. To improve the stability of the CI, this patch will use the singleton method instead of stub.
=> Backport(v1.16) test_ack_handler: use singleton method instead of stub for stability

test/plugin/test_in_tail.rb
Backport #4710 
This PR will fix unstable tests.
* test_in_tail: fix flaky tests for file rotation
* test_in_tail: remove unnecessary inode assertions
=> Backport(v1.16) test_in_tail: fix flaky tests for file rotation (#4710)

lib/fluent/supervisor.rb
Backport #4716 
To daemonize the process, the following code will be invoked on Windows:
https://github.com/fluent/fluentd/blob/89f0a76fb2e050659f0a503823beb2ad8cf899eb/lib/fluent/daemon.rb#L13
$log variable does not exist because it has not executed `Superviser#setup_global_logger` method until here.
It will perform a new startup process and prepare a logger in
https://github.com/fluent/fluentd/blob/89f0a76fb2e050659f0a503823beb2ad8cf899eb/lib/fluent/daemon.rb#L13
This patch will only avoid the error since a logger is not required this process.
Not needed.
=> Backport(v1.16) command: fix NoMethodError of --daemon under Windows

README.md
Backport #4722 
Google Universal Analytics (UA) is no longer in service.
I don't know how this was used originally.
So, I remove this for now.
Not needed.
Not needed.
=> Backport(v1.16) README: remove deprecated google analytics beacon (#4722)

test/plugin/test_out_file.rb
Backport #4728 
Fix the file open mode so that gz files can be read properly.
=> Backport(v1.16) test_out_file: fix file open mode for binary file

test/command/test_cat.rb
Backport #4730 
The binary files may not be read properly.
This changes to read files in binary mode.
=> Backport(v1.16) test_cat: specify the reading size to read in binary mode (#4730)

fluentd.gemspec
Backport #4747 
Since logger 1.6.3 or later, there is a bug that it cause unexpected exception (no implicit conversion of Integer into String (TypeError)) on windows. So hold on 1.6.2 for a while.
See https://github.com/ruby/logger/issues/107
N/A
N/A
=> Backport(v1.16) windows: add workaround for unexpected exception (#4747)

test/plugin/test_out_exec_filter.rb
Backport #4755
This PR will stable the tests.
=> Backport(v1.16) test_out_exec_filter: add a sleep to ensure the stream is emitted (#4755)

lib/fluent/winsvc.rb
Backport #4782 
Add retry for stop event for Windows Service to fix #3937.
If `Event.open()`
([OpenEvent](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-openeventw)) is called before the `Event.new()`
([CreateEvent](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createeventw)), `Event.open()` raises `Errno::ENOENT`.
This causes the service to be stopped while the supervisor and worker process remains.
It causes #3937.
This PR fixes it by adding retry.
https://github.com/fluent/fluentd/blob/30c3ce00ff165b1b5d9f53fc0a027074bbcab0da/lib/fluent/winsvc.rb#L90
https://github.com/fluent/fluentd/blob/30c3ce00ff165b1b5d9f53fc0a027074bbcab0da/lib/fluent/supervisor.rb#L299 …
=> Backport(v1.16) Windows: Fix an issue where stopping the service immediately after startup could leave the processes (#4782)

.github/workflows/test.yml
Backport #4750
It seems that it fixes failure with Ruby 3.1 on windows.
```
undefined method `ignored?' for #<Gem::Specification:0x000001dccaf43168
```
NOTE: Initially introduced by #4681, then reverted in #4746. Thus, it's a side-effect of #4746.
N/A
N/A
=> Backport(v1.16) ci: use latest rubygems again for Ruby 3.1 on windows (#4750)

.github/workflows/test.yml
None.
Remove `latest` setting for `rubygems`.
We added it for Ruby 3.1 on Windows (#4750).
We have already dropped Ruby 3.1, so we don't need it anymore.
Not needed.
Not needed.
=> ci: remove latest setting for rubygems

lib/fluent/plugin/parser_json.rb, test/plugin/test_parser_json.rb
Fixes #
Recently, Ruby's json has incredible performance improvements.
It might be faster than oj gem.
So, I think json is a suitable as fallback.
This is similar with https://github.com/fluent/fluentd/pull/4759
Here is easily benchmark. (I used same log file in #4759)
* Before
* It spent 90.50963662 sec to handle 10 GB file 
* After
* It spent 74.624230077 sec to handle 10 GB file
* config
```
<source>
@type tail
path "#{File.expand_path '~/tmp/access*.log'}"
pos_file "#{File.expand_path '~/tmp/fluentd/access.log.pos'}"
tag log
read_from_head true
<parse>
@type json
</parse>
</source>
<match **>
@type file
path "#{File.expand_path '~/tmp/fluentd/log'}"
</match>
```
FYI)
* …
=> parser_json: use JSON as fallback parser instead of Yajl for performance

lib/fluent/plugin/parser_json.rb, test/log/test_console_adapter.rb, test/plugin/test_parser_json.rb
Fixes #
Ref. https://github.com/fluent/fluentd/pull/4813#discussion_r1937321034
Fix wrong usage of `JSON.load` method.
We should use `JSON.parse` instead.
JSON.load performs unnecessary deserialisation.
```
irb(main):001> JSON.load('{ "json_class": "String", "raw": [72, 101, 108, 108, 111] }')
=> "Hello"
irb(main):002> JSON.parse('{ "json_class": "String", "raw": [72, 101, 108, 108, 111] }')
=> {"json_class" => "String", "raw" => [72, 101, 108, 108, 111]}
```
=> parser_json: use JSON.parse instead of .load

test/plugin_helper/test_server.rb
None.
Fix unstable test.
```
Error: test: creates a udp server to read and write data using IPv6(ServerPluginHelperTest::#server_create_udp): Errno::EADDRINUSE: Address already in use - bind(2) for "::1" port 8859
/home/runner/work/fluentd/fluentd/test/plugin_helper/test_server.rb:697:in 'UDPSocket#bind'
/home/runner/work/fluentd/fluentd/test/plugin_helper/test_server.rb:697:in 'block (3 levels) in <class:ServerPluginHelperTest>'
<internal:numeric>:257:in 'Integer#times'
/home/runner/work/fluentd/fluentd/test/plugin_helper/test_server.rb:694:in 'block (2 levels) in <class:ServerPluginHelperTest>'
```
Not needed.
=> ci: fix unstable test

test/plugin_helper/test_server.rb
* Backport #4820
Fix unstable test.
```
Error: test: creates a udp server to read and write data using IPv6(ServerPluginHelperTest::#server_create_udp): Errno::EADDRINUSE: Address already in use - bind(2) for "::1" port 8859
/home/runner/work/fluentd/fluentd/test/plugin_helper/test_server.rb:697:in 'UDPSocket#bind'
/home/runner/work/fluentd/fluentd/test/plugin_helper/test_server.rb:697:in 'block (3 levels) in <class:ServerPluginHelperTest>'
<internal:numeric>:257:in 'Integer#times'
/home/runner/work/fluentd/fluentd/test/plugin_helper/test_server.rb:694:in 'block (2 levels) in <class:ServerPluginHelperTest>'
```
Not needed.
=> Backport(v1.16) ci: fix unstable test (#4820)

fluentd.gemspec
Fixes #4742
This reverts commit b193dc4957b4f957fc5de518f90e26183a10c440.
Because https://github.com/ruby/logger/issues/107 was fixed.
=> Revert "windows: add workaround for unexpected exception (#4747)"

lib/fluent/plugin/formatter_json.rb, test/plugin/test_out_stdout.rb
Fixes #
Recently, Ruby's json has incredible performance improvements.
It might be faster than oj gem.
So, I think json is a suitable as fallback.
This is similar with https://github.com/fluent/fluentd/pull/4813
* Before
* It spent 70.708872503 sec to handle 10 GB file 
* After
* It spent 54.428017716 sec to handle 10 GB file
* config
```
<source>
@type tail
path "#{File.expand_path('~/tmp/fluentd/access*.log')}"
pos_file "#{File.expand_path('~/tmp/fluentd/access.log.pos')}"
tag log
read_from_head true
<parse>
@type none
</parse>
</source>
<match **>
@type file
path "#{File.expand_path('~/tmp/fluentd/output/log')}"
format json
</match>
```
=> formatter_json: use JSON as fallback parser instead of Yajl for performance

test/test_supervisor.rb
* Fixes #4063
Sigdump.dump iterates ObjectSpace.
If there are DoubleDefinition objects of RR, it can set some expectations of RR unexpectedly.
It can cause test failure.
By doing GC, we can remove DoubleDefinition objects made in other tests.
See https://github.com/fluent/fluentd/issues/4063
Failure: test_cont_in_main_process_signal_handlers(SupervisorTest):
class()
Called 0 times.
Expected 1 times.
(...)/sigdump-0.2.5/lib/sigdump.rb:76:in `block in dump_object_count'
(...)/sigdump-0.2.5/lib/sigdump.rb:75:in `each_object'
(...)/sigdump-0.2.5/lib/sigdump.rb:75:in `dump_object_count'
(...)/sigdump-0.2.5/lib/sigdump.rb:18:in `block in dump'
(...)/sigdump-0.2.5/lib/sigdump.rb:138:in `open' …
=> test: fix Sigdump tests failure

test/test_supervisor.rb
* Backport #4846
Sigdump.dump iterates ObjectSpace.
If there are DoubleDefinition objects of RR, it can set some expectations of RR unexpectedly.
It can cause test failure.
By doing GC, we can remove DoubleDefinition objects made in other tests.
See https://github.com/fluent/fluentd/issues/4063
Failure: test_cont_in_main_process_signal_handlers(SupervisorTest):
class()
Called 0 times.
Expected 1 times.
(...)/sigdump-0.2.5/lib/sigdump.rb:76:in `block in dump_object_count'
(...)/sigdump-0.2.5/lib/sigdump.rb:75:in `each_object'
(...)/sigdump-0.2.5/lib/sigdump.rb:75:in `dump_object_count'
(...)/sigdump-0.2.5/lib/sigdump.rb:18:in `block in dump'
(...)/sigdump-0.2.5/lib/sigdump.rb:138:in `open' …
=> Backport(v1.16) test: fix Sigdump tests failure (#4846)

lib/fluent/config/v1_parser.rb
Fixes #
By [CodeQL documentation](https://codeql.github.com/codeql-query-help/ruby/rb-non-constant-kernel-open/), it is safer to avoid using `URI.open`.
This is similar with https://github.com/fluent/fluentd/pull/4848
=> v1_parser: use URI#open instead of URI.open

fluentd.gemspec, lib/fluent/log/console_adapter.rb
Fixes #
This patch will fix following error:
```
NoMethodError: undefined method `seek' for nil:NilClass
/home/runner/work/fluentd/fluentd/lib/fluent/log/console_adapter.rb:61:in `call'
/opt/hostedtoolcache/Ruby/3.2.7/x64/lib/ruby/gems/3.2.0/gems/console-1.30.0/lib/console/output/wrapper.rb:35:in `call'
/opt/hostedtoolcache/Ruby/3.2.7/x64/lib/ruby/gems/3.2.0/gems/console-1.30.0/lib/console/output/failure.rb:38:in `call'
/opt/hostedtoolcache/Ruby/3.2.7/x64/lib/ruby/gems/3.2.0/gems/console-1.30.0/lib/console/filter.rb:48:in `block (3 levels) in []'
/home/runner/work/fluentd/fluentd/test/log/test_console_adapter.rb:58:in `test_args'
```
Ref. https://github.com/fluent/fluentd/actions/runs/13714056838
The variable name …
=> console_adapter: support console gem v1.30

test/test_supervisor.rb
None.
Related to
* #4063
* #4846
Sigdump.dump iterates ObjectSpace.
If there are DoubleDefinition objects of RR, it can set some expectations of RR unexpectedly.
It can cause test failure.
By doing GC, we can remove DoubleDefinition objects made in other tests.
This allows us to simplify this test.
See https://github.com/fluent/fluentd/issues/4063
Not needed.
Not needed.
=> test: improve Sigdump test for Windows

lib/fluent/supervisor.rb, test/command/test_fluentd.rb
None.
Adds error handling similar to worker process.
https://github.com/fluent/fluentd/blob/8df10863769da32459aba2a1408134d0b8e7d9f4/lib/fluent/supervisor.rb#L1149-L1164
`Fluent::Engine.run_configure` calls `Fluent::Registry#search`.
It can run `Kernel.require`.
It can raise `LoadError`, `ConflictError` and others.
Without this error handling, Fluentd cannot log those errors.
This makes a situation where Fluentd fails to start, but there is no error log in the log file.
This solves that problem.
This appears to be an oversight of the following fix:
* https://github.com/fluent/fluentd/pull/2651
Not needed.
=> Add logging for errors about loading dependencies on startup

lib/fluent/plugin/buffer/memory_chunk.rb, test/plugin/test_output_as_buffered_compress.rb
Fixes #1657
Seems that a full GC have to run in order to collect the wasted String object in `@chunk`.
However, full GC is not performed frequently.
This patch purges internal memory in wasted String object immediately.
Here is memory usage retrieved by `ObjectSpace.memsize_of_all`.
> [!NOTE]
> Ruby has various optimization, such as reusing freed heap areas by pooling them.
> For this reason, it may not be reflected in the process's memory usage immediately even if it clear the object.
* Configuration
```
<source>
@type tcp
tag testing
format json
port 10130
</source>
<match **>
@type forward
require_ack_response true
<server>
host 127.0.0.1
port 10131
</server>
<buffer tag>
flush_mode interval
flush_interval 1s …
```
=> memory_chunk: clear internal memory use in buffer string

test/test_supervisor.rb
* Backport #4847
Sigdump.dump iterates ObjectSpace.
If there are DoubleDefinition objects of RR, it can set some expectations of RR unexpectedly.
It can cause test failure.
By doing GC, we can remove DoubleDefinition objects made in other tests. This allows us to simplify this test.
See https://github.com/fluent/fluentd/issues/4063
Not needed.
Not needed.
=> Backport(v1.16) test: improve Sigdump test for Windows (#4847)

fluentd.gemspec
Fixes #
Since Ruby 3.5, `fiddle` gem was marked as bundled gem.
https://github.com/ruby/ruby/commit/10ecdeb4665cbc061f80cc26c5456ff124703d89
This patch will fix following warning on Windows Ruby 3.4 and fix load error on Windows Ruby 3.5:
```
C:/hostedtoolcache/windows/Ruby/3.4.2/x64/lib/ruby/gems/3.4.0/gems/serverengine-2.4.0/lib/serverengine/winsock.rb:21: warning: fiddle/import is found in fiddle, which will no longer be part of the default gems starting from Ruby 3.5.0.
You can add fiddle to your Gemfile or gemspec to silence this warning.
```
FYI)
`fiddle` has been used in
https://github.com/fluent/fluentd/blob/f1f0bb2474ed8d4f7b6011a321a2b93e3b1dd9cb/lib/fluent/win32api.rb#L21-L22
**Release …
=> Add fiddle as dependency gem for Ruby 3.5 on Windows

lib/fluent/compat/formatter.rb, lib/fluent/plugin/formatter_csv.rb
Fixes #3627
Seems `in_exec` plugin creats Thread object each interval and  it invoke formatter_csv on the thread.
If it use a Thread object as hash key when caching with formatter_csv, that thread will be permanently referenceable and will not be collected by the GC.
Here is memory usage of Ruby's process.
See #3627
```
<system>
process_name fluentd_monitor
</system>
<source>
@type exec
tag hardware.memory
run_interval 0.1
command /home/watson/prj/sandbox/fluentd/get_memory_metrics.sh
<parse>
@type json
types mem_available:float,swap_total:float,swap_free:float
</parse>
</source>
<match **>
@type exec
command /home/watson/prj/sandbox/fluentd/psql_memory.sh
<format>
@type csv
force_quotes false
delimiter |
fields …
```
=> formatter_csv: fix memory leak

test/plugin/test_in_tail.rb
Fixes #4079
For reasons such as the load on the CI execution environment, looks like that rotation detection is delayed and the test does not execute as expected.
For this reason, this patch adds a wait to ensure to detect the rotation.
Before the patch was introduced, tests failed about once every 20 to 50 times.
After, the test was successful  500 consecutive times.
=> test_in_tail: add wait to detect rotation

test/plugin/test_output_as_buffered_retries.rb
Fixes #4873
Before invoke `@num_errors_metrics.inc`, the `does retries correctly when #try_write fails` test will be failed if thread will be switched at https://github.com/fluent/fluentd/blob/f34a2531fcfc4e8958f665301d48558de200aa3a/lib/fluent/plugin/output.rb#L1313-L1315
It is easy to reproduce by adding `sleep` just before `@num_errors_metrics.inc`, like:
```diff
diff --git a/lib/fluent/plugin/output.rb b/lib/fluent/plugin/output.rb
index a987937b..d97d8ec6 100644
--- a/lib/fluent/plugin/output.rb
+++ b/lib/fluent/plugin/output.rb
@@ -1312,6 +1312,7 @@ def check_slow_flush(start)
def update_retry_state(chunk_id, using_secondary, error = nil)
@retry_mutex.synchronize do
+          sleep 0.1 …
```
=> test_output_as_buffered_retries: fix flaky test

lib/fluent/plugin/in_tail.rb
Fixes #
Previous, I changed lifespan of `iobuf` at https://github.com/fluent/fluentd/pull/4763 to work GC collector well.
In addition, it seems that clearing `iobuf` manually when it is no longer needed, it might improve memory efficiency.
* config
```
<source>
@type tail
path "#{File.expand_path '~/tmp/access*.log'}"
pos_file "#{File.expand_path '~/tmp/fluentd/access.log.pos'}"
tag log
refresh_interval 5s
<parse>
@type none
</parse>
</source>
<match **>
@type file
path "#{File.expand_path '~/tmp/log'}"
</match>
```
* script to generate log data
```
require "json"
path = File.expand_path("~/tmp/access.log")
File.open(path, "w") do |f|
loop do
log = { time: Time.now, message: "a" * 10_000 }.to_json
f.puts log
sleep …
```
=> in_tail: reduce memory usage slightly

lib/fluent/plugin/in_http.rb, test/plugin/test_in_http.rb
Some requests, such as those made by apps, certain automated scripts, or older browsers, may not include an Origin header. Previously, such requests were blocked by the CORS check, even though they may not necessarily be cross-origin.
For CORS, the server is responsible for reporting the allowed origins. The web browser is responsible for enforcing that requests are only sent from allowed domains. So this change updates the CORS handling logic to allow requests with an empty Origin header to pass, ensuring compatibility with legitimate non-browser clients while maintaining security.
https://github.com/fluent/fluentd-docs-gitbook/pull/574
=> in_http: allow empty Origin header requests to pass CORS checks

lib/fluent/plugin/formatter_out_file.rb
Fixes #
When dealing with long logs at fast, it might improve memory efficient to clear the original strings used in string interpolation.
* config
```
<source>
@type tail
path "#{File.expand_path '~/tmp/access*.log'}"
pos_file "#{File.expand_path '~/tmp/fluentd/access.log.pos'}"
tag log
refresh_interval 5s
<parse>
@type none
</parse>
</source>
<match **>
@type file
path "#{File.expand_path '~/tmp/log'}"
</match>
```
* script to generate log data
```ruby
require "json"
path = File.expand_path("~/tmp/access.log")
File.open(path, "w") do |f|
loop do
log = { time: Time.now, message: "a" * 50 * 1024 }.to_json
f.puts log
sleep 0.0001
end
end
```
=> formatter_out_file: reduce memory usage

lib/fluent/plugin/formatter_json.rb
Fixes #
When dealing with long logs at fast, it might improve memory efficient to clear the original strings used in string interpolation.
This is similar with #4884 .
* config
```
<source>
@type sample
tag test
sample {"message": "#{'a' * 100 * 1024}"}
size 100
</source>
<match **>
@type file
path "#{File.expand_path '~/tmp/log'}"
format json
</match>
```
=> formatter_json: reduce memory usage

.github/workflows/test.yml
Fixes #
It enables manual operation.
It is useful when you want to re-run the same tests on the latest runner.
(This feature is enabled for ruby-head, so enable it too)
=> ci: allow running test manually

lib/fluent/plugin/in_monitor_agent.rb
* Partially Fixes #4648
Stop requiring WEBrick on `in_monitor_agent`. 
Even if async is not installed, http_server helper requires WEBrick on its own.
So, there is no need to require WEBrick here.
There is no impact on the specification. (This is just code refactoring.)
Not needed.
Not needed. (This is just code refactoring.)
=> in_monitor_agent: remove needless require

lib/fluent/plugin_helper/http_server/request.rb, test/plugin_helper/http_server/test_request.rb
Fixes #
I'm creating a plugin using http_server, but I need to change the processing depending on the received request header.
So, I want an accessor to read request header in `Fluent::PluginHelper::HttpServer::Request`
TODO: https://docs.fluentd.org/plugin-helper-overview/api-plugin-helper-http_server#request
* `http_server` helper: add `header` method for `Request`.
=> http_server: add an accessor to read request header

fluentd.gemspec
Fixes #
metadata field could be set by gem author.
See https://guides.rubygems.org/specification-reference/
N/A
=> gemspec: Add missing metadata

test/plugin/test_output_as_buffered_retries.rb
Backport #4877
Fixes #4873
Before invoke `@num_errors_metrics.inc`, the `does retries correctly when #try_write fails` test will be failed if thread will be switched at https://github.com/fluent/fluentd/blob/f34a2531fcfc4e8958f665301d48558de200aa3a/lib/fluent/plugin/output.rb#L1313-L1315
It is easy to reproduce by adding `sleep` just before `@num_errors_metrics.inc`, like:
```diff
diff --git a/lib/fluent/plugin/output.rb b/lib/fluent/plugin/output.rb
index a987937b..d97d8ec6 100644
--- a/lib/fluent/plugin/output.rb
+++ b/lib/fluent/plugin/output.rb
@@ -1312,6 +1312,7 @@ def check_slow_flush(start)
def update_retry_state(chunk_id, using_secondary, error = nil)
@retry_mutex.synchronize do
+          sleep 0.1 …
```
=> Backport(v1.16) test_output_as_buffered_retries: fix flaky test (#4877)

lib/fluent/compat/formatter.rb, lib/fluent/plugin/formatter_csv.rb
Backport #4864
Fixes #3627
Seems `in_exec` plugin creats Thread object each interval and  it invoke formatter_csv on the thread.
If it use a Thread object as hash key when caching with formatter_csv, that thread will be permanently referenceable and will not be collected by the GC.
Here is memory usage of Ruby's process.
See #3627
```
<system>
process_name fluentd_monitor
</system>
<source>
@type exec
tag hardware.memory
run_interval 0.1
command /home/watson/prj/sandbox/fluentd/get_memory_metrics.sh
<parse>
@type json
types mem_available:float,swap_total:float,swap_free:float
</parse>
</source>
<match **>
@type exec
command /home/watson/prj/sandbox/fluentd/psql_memory.sh
<format>
@type csv
force_quotes false …
```
=> Backport(v1.16): formatter_csv: fix memory leak (#4864)

lib/fluent/config/v1_parser.rb
Backport #4854
Fixes #
By [CodeQL documentation](https://codeql.github.com/codeql-query-help/ruby/rb-non-constant-kernel-open/), it is safer to avoid using `URI.open`.
This is similar with https://github.com/fluent/fluentd/pull/4848
=> Backport(v1.16): v1_parser: use URI#open instead of URI.open (#4854)

fluentd.gemspec
Backport #4833
Fixes #4742
This reverts commit b193dc4957b4f957fc5de518f90e26183a10c440.
Because https://github.com/ruby/logger/issues/107 was fixed.
=> Backport(v1.16): Revert "windows: add workaround for unexpected exception (#4747)" (#4833)

fluentd.gemspec
Backport #4869
Fixes #
Since Ruby 3.5, `fiddle` gem was marked as bundled gem.
https://github.com/ruby/ruby/commit/10ecdeb4665cbc061f80cc26c5456ff124703d89
This patch will fix following warning on Windows Ruby 3.4 and fix load error on Windows Ruby 3.5:
```
C:/hostedtoolcache/windows/Ruby/3.4.2/x64/lib/ruby/gems/3.4.0/gems/serverengine-2.4.0/lib/serverengine/winsock.rb:21: warning: fiddle/import is found in fiddle, which will no longer be part of the default gems starting from Ruby 3.5.0.
You can add fiddle to your Gemfile or gemspec to silence this warning.
```
FYI)
`fiddle` has been used in
https://github.com/fluent/fluentd/blob/f1f0bb2474ed8d4f7b6011a321a2b93e3b1dd9cb/lib/fluent/win32api.rb#L21-L22
**Docs …
=> Backport(v1.16): Add fiddle as dependency gem for Ruby 3.5 on Windows (#4869)

test/plugin/test_in_tail.rb
Backport #4874
Fixes #4079
For reasons such as the load on the CI execution environment, looks like that rotation detection is delayed and the test does not execute as expected.
For this reason, this patch adds a wait to ensure to detect the rotation.
Before the patch was introduced, tests failed about once every 20 to 50 times.
After, the test was successful  500 consecutive times.
=> Backport(v1.16): test_in_tail: add wait to detect rotation (#4874)

lib/fluent/config/parser.rb
Backport #4855
Fixes #
This patch will fix the problem in https://github.com/fluent/fluentd/pull/4848
`u.path` has the file path without a drive letter in Windows environment.
If Fluentd is worked on `c` drive and config file exists in `d` drive, it can't parse config file, I think.
=> Backport(v1.16): parser: fix file path into URI#open for Windows (#4855)

.github/workflows/test.yml
Backport: #4689 
Fixes #
Often I forget to Signed-off and push new commit again. I would like the github action related to the PR to be automatically cancelled at that time. I want the test to run on the newly pushed commit immediately.
Ref. https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
=> Backport(v1.16): ci: add cancel-in-progress setting (#4689)

lib/fluent/config/element.rb, test/config/test_element.rb
Fixes #
In the previous versions, it is hard to identify
the separator of elements.
Added attr: and elements: prefix for properties and mark it <...>.
Before:
```
name:ROOT, arg:, {}, [name:system, arg:,
{"config_include_dir"=>"..."}, [], name:source, arg:,
{"@type"=>"forward"}, [], name:source, arg:, {"@type"=>"tcp"}, []]
```
After:
```
<name:ROOT, arg:, attrs:{}, elements:[<name:system, arg:,
attrs:{"config_include_dir"=>"..."}, elements:[]>, <name:source,
arg:, attrs:{"@type"=>"forward"}, []>, <name:source, arg:,
atrrs:{"@type"=>"tcp"}, elements:[]>]
```
N/A
=> config: change inspect format

lib/fluent/supervisor.rb, lib/fluent/winsvc.rb, test/config/test_plugin_configuration.rb, test/plugin/test_buffer.rb, test/plugin/test_filter_grep.rb, test/plugin/test_filter_parser.rb, test/plugin/test_out_http.rb, test/plugin/test_output.rb, test/plugin/test_parser_csv.rb, test/test_tls.rb
Fixes #
It will reduce rubocop warnings with the following configuration:
```yml
Layout/TrailingWhitespace:
Enabled: true
```
This is just cosmetic change. It will not break tests.
N/A
N/A
=> rubocop: fix trailing-whitespace

lib/fluent/compat/socket_util.rb, lib/fluent/plugin/owned_by_mixin.rb, lib/fluent/plugin_id.rb, lib/fluent/system_config.rb, test/compat/test_parser.rb, test/test_log.rb
Fixes #
This is cosmetic change, it does not change behavior at all. It was detected by the following rubocop configuration:
```
Performance/StringIdentifierArgument:
Enabled: true
```
Apparently, string identifier argument should not be used.
```
get instance variable with string notation
918.201k i/100ms
get instance variable with symbol notation
2.186M i/100ms
get instance variable with string notation
10.480M (± 1.5%) i/s   (95.42 ns/i) -     53.256M in   5.082903s
get instance variable with symbol notation
27.349M (± 1.3%) i/s …
```
=> robocop: reduce string to symbol conversion for performance

lib/fluent/config/types.rb, lib/fluent/plugin.rb
Fixes #
This is cosmetic change, it does not change behavior at all. It was detected by the following rubocop configuration:
```
Performance/StringIdentifierArgument:
Enabled: true
```
Apparently, string identifier argument should not be used.
```
check method with string notation
875.323k i/100ms
check method with symbol notation
1.880M i/100ms
check method with string notation
8.828M (± 1.4%) i/s  (113.28 ns/i) -     44.641M in   5.058002s
check method with symbol notation
19.766M (± 2.2%) i/s   (50.59 ns/i) -     99.631M in …
```
=> rubocop: reduce string to symbol conversion for performance

lib/fluent/root_agent.rb, lib/fluent/static_config_analysis.rb, lib/fluent/supervisor.rb
Fixes #
This is cosmetic change, it does not change behavior at all.
The following rubocop configuration detected it:
```
Performance/CollectionLiteralInLoop:
Enabled: true
```
hash literals in loops should not be used.
NOTE: hash literals in loops exists in test/*, but it is overkill to
fix them.
```
in loops   550.000 i/100ms
out of loops     1.464k i/100ms
in loops      5.452k (± 1.5%) i/s  (183.43 μs/i) -     27.500k in   5.045506s
out of loops     14.592k (± 1.0%) i/s   (68.53 μs/i) -     73.200k in   5.016839s
Comparison:
out of …
```
=> rubocop: reduce hash literals in loops for performance

lib/fluent/test/base.rb, lib/fluent/test/formatter_test.rb, lib/fluent/test/parser_test.rb
Fixes #
This is cosmetic change, it does not change behavior at all. It was detected by the following rubocop configuration:
```
Performance/StringIdentifierArgument:
Enabled: true
```
string identifier argument should not be used.
```
define method with string notation
225.825k i/100ms
define method with symbol notation
278.180k i/100ms
define method with string notation
2.337M (± 2.0%) i/s  (427.83 ns/i) -     11.743M in   5.025989s
define method with symbol notation
2.765M (± 3.8%) i/s  (361.70 ns/i) -     13.909M in   5.038885s …
```
=> rubocop: reduce string to symbol conversion for performance (define_singleton_method)

lib/fluent/config/literal_parser.rb, lib/fluent/config/v1_parser.rb
Fixes #
This is cosmetic change, it does not change behavior at all. The following rubocop configuration detects it.
```
Performance/ConstantRegexp:
Enable: true
```
```
interpret everytime    26.127k i/100ms
interpret once     3.172M i/100ms
interpret everytime    254.171k (± 2.6%) i/s    (3.93 μs/i) -      1.280M in   5.040357s
interpret once     33.755M (± 1.7%) i/s   (29.62 ns/i) -    171.289M in   5.075867s
Comparison:
interpret once: 33755320.3 i/s
interpret everytime:   254171.5 i/s - 132.81x  slower
```
Regex should not be …
=> rubocop: reduce every regex evaluation for performance

lib/fluent/env.rb, lib/fluent/plugin/in_tail.rb
Fixes #
This is cosmetic change, it does not change behavior at all. The following rubocop configuration detects it.
```
Performance/StringInclude:
Enable: true
```
```
check method with ===
411.815k i/100ms
check method with include?
1.180M i/100ms
check method with ===
3.797M (± 5.3%) i/s  (263.38 ns/i) -     18.943M in   5.003267s
check method with include?
12.067M (± 3.5%) i/s   (82.87 ns/i) -     61.348M in   5.090688s
Comparison:
check method with include?: 12066561.6 i/s
check method with ===:  3796826.8 i/s - 3.18x  slower …
```
=> rubocop: reduce a regex match for performance

lib/fluent/plugin/in_http.rb, lib/fluent/plugin/in_tail.rb, lib/fluent/supervisor.rb, lib/fluent/winsvc.rb, test/config/test_plugin_configuration.rb, test/plugin/test_buffer.rb, test/plugin/test_filter_grep.rb, test/plugin/test_in_http.rb, test/plugin/test_output.rb, test/plugin/test_parser_csv.rb, test/test_tls.rb
Backport: #4928
Fixes #
It will reduce rubocop warnings with the following configuration:
```yml
Layout/TrailingWhitespace:
Enabled: true
```
This is just cosmetic change. It will not break tests.
NOTE: the following files are additionally detected only in v1.16 branch
* lib/fluent/plugin/in_http.rb
* lib/fluent/plugin/in_tail.rb
* test/plugin/test_in_http.rb
N/A
N/A
=> Backport(v1.16): rubocop: fix trailing-whitespace (#4928)

lib/fluent/winsvc.rb
Backport #4909
None.
Even if the supervisor process is dead due to config error or etc, the service process will continue running unexpectedly because no one monitor it. This commit fix this issue.
Not needed.
=> Backport(v1.16): winsvc: Stop the service when the supervisor is dead (#4909)

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
~~Fixes #~~
This PR provides a warning for typical configuration mistakes that prevent log transfer from starting.
When using the tail type as a source, it is common for directories with inappropriate partitions to be mistakenly included in the source path.
In my opinion, it would be preferable to issue a warning in such cases to help users avoid these mistakes.
Steps to Reproduce:
```shell
$ sudo mkdir /var/log/noaccess
$ sudo mkdir /var/log/noaccess/noaccess2
$ sudo touch /var/log/noaccess/noaccess2/fluentd.log
$ sudo chmod 0000 /var/log/noaccess
$ sed -Ei 's|^([[:space:]]*)path .*|\1path /var/log/noaccess/noaccess2/fluentd.log|' example/in_tail.conf
$ bundle exec fluentd -c example/in_tail.conf
{no warning...} …
```
=> Add warning for directory permission to in_tail.rb

.github/workflows/test.yml, lib/fluent/winsvc.rb, test/scripts/windows_service_test.ps1
This fixes a bug of #4909.
After 53bcd3c83edb2bdc0d98481c86e9955ffdc4f5ef (#4909), the service accidentally stops after starting, without stopping the supervisor and workers.
Not needed.
=> winsvc: Fix bug where service accidentally stops after starting

.github/workflows/test.yml
Backport #4581.
By default, it is enough to give read permission.
For stale actions, it require manipulate issues,
so write permission is given explicitly.
N/A
N/A
=> Backport(v1.16): github: set job permissions (#4581)

.github/workflows/test.yml, lib/fluent/winsvc.rb, test/scripts/windows_service_test.ps1
Backport #4954.
After 53bcd3c83edb2bdc0d98481c86e9955ffdc4f5ef (#4909), the service accidentally stops after starting, without stopping the supervisor and workers.
Not needed.
=> Backport(v1.16): winsvc: Fix bug where service accidentally stops after starting (#4954)

lib/fluent/test/driver/base.rb, lib/fluent/test/filter_test.rb, lib/fluent/test/input_test.rb, lib/fluent/test/output_test.rb
Fixes #
This is cosmetic change, it does not change behavior at all. The following rubocop configuration detects it.
```
Performance/RedundantBlockCall:
Exclude:
- 'test/**/*'
#- 'lib/fluent/**/*.rb'
- 'lib/fluent/plugin_helper/*.rb'
- 'lib/fluent/plugin/*.rb'
- 'lib/fluent/compat/*.rb'
- 'lib/fluent/config/*.rb'
- 'lib/fluent/*.rb'
Enabled: true
```
```
block call     1.315M i/100ms
yield with &block     1.721M i/100ms
yield without &block     1.692M i/100ms
block call     13.572M (± 0.5%) i/s   (73.68 ns/i) -     68.365M in …
```
=> rubocop: use yield without block

lib/fluent/test/helpers.rb, test/plugin/test_in_http.rb
None.
Add a test for `in_http` multipart content-type.
There is no test case for this. We need it.
Not needed.
Not needed.
=> test: add in_http multipart test case

lib/fluent/command/fluentd.rb, lib/fluent/root_agent.rb, lib/fluent/supervisor.rb, lib/fluent/system_config.rb, test/command/test_fluentd.rb, test/config/test_system_config.rb, test/test_root_agent.rb, test/test_supervisor.rb
Fixes #
I ran fluend with `--enable-input-metrics` option and read 10GB file with the `in_tail` plugin
There was no significant performance degradation.
So, I think it is safe to always enable `--enable-input-metrics`.
* ruby 3.4.3 (2025-04-14 revision d0b7e5b6a0) +PRISM [x86_64-linux]
* fluentd master branch (efbb51d7)
* `ruby bin/fluentd -c in_tail.conf`
* 65.939232375 seconds
* `ruby bin/fluentd --enable-input-metrics -c in_tail.conf`
* 67.776236261 seconds
* fluentd 1.16.9 (daccbc6f)
* `ruby bin/fluentd -c in_tail.conf`
* 106.312500419 seconds
```
<source>
@type tail
tag test
path "#{File.expand_path '~/tmp/fluentd/access-*.log'}"
read_from_head true
<parse>
@type json
</parse>
</source>
<match **>
@type file …
```
=> metrics: enable input metrics by default

lib/fluent/plugin/out_http.rb, lib/fluent/tls.rb, test/plugin/test_out_http.rb, test/test_tls.rb
Fixes #4332 
Changes the way we configure Net::HTTP client.
https://github.com/fluent/fluentd-docs-gitbook/pull/579
=> out_http: TLS1.3 support

test/test_static_config_analysis.rb
Fixes #
This is cosmetic change, it does not change behavior at all. The
following rubocop configuration detects it.
```
Performance/MapMethodChain:
Enabled: true
```
```
map method chain   139.000 i/100ms
method chain   225.000 i/100ms
map method chain      1.429k (± 1.5%) i/s  (699.83 μs/i) -      7.228k in   5.059646s
method chain      2.154k (± 3.1%) i/s  (464.15 μs/i) -     10.800k in   5.018163s
Comparison:
method chain:     2154.5 i/s
map method chain:     1428.9 i/s - 1.51x  slower
```
Appendix: benchmark script
```ruby
require …
```
=> rubocop test: reduce map method chain

test/plugin/test_buffer.rb, test/plugin/test_in_tail.rb
Fixes #
This is cosmetic change, it does not change behavior at all. The
following rubocop configuration detects it.
```
Performance/TimesMap:
Enable: true
```
```
Array.new()   983.000 i/100ms
times.map   681.000 i/100ms
Array.new()     10.268k (± 0.8%) i/s   (97.39 μs/i) -     52.099k in   5.074330s
times.map      6.855k (± 1.0%) i/s  (145.88 μs/i) -     34.731k in   5.066975s
Comparison:
Array.new():    10267.8 i/s
times.map:     6855.0 i/s - 1.50x  slower
```
Appendix: benchmark script
```ruby
gemfile do …
```
=> rubocop test: reduce times.map call

test/plugin/test_in_forward.rb, test/plugin/test_output_as_buffered_retries.rb, test/plugin_helper/test_server.rb
Fixes #
This is cosmetic change, it does not change behavior at all. The
following rubocop configuration detects it.
```
Performance/RedundantEqualityComparisonBlock
Enable: true
```
```
all? { |t| t == XXX }
1.138M i/100ms
all?(XXX)     1.330M i/100ms
all? { |t| t == XXX }
12.599M (± 1.9%) i/s   (79.37 ns/i) -     63.700M in   5.057889s
all?(XXX)     14.230M (± 2.1%) i/s   (70.27 ns/i) -     71.821M in   5.049436s
Comparison:
all?(XXX): 14230128.9 i/s
all? { |t| t == XXX }: 12598812.4 i/s - 1.13x  slower
```
Appendix: benchmark script: …
=> rubocop test: fix Performance/RedundantEqualityComparisonBlock

lib/fluent/plugin/output.rb, test/plugin/test_in_monitor_agent.rb, test/plugin/test_output.rb, test/plugin/test_output_as_buffered_overflow.rb
Fixes #
When `overflow_action drop_oldest_chunk` is configured, the oldest buffer chunk will be automatically discarded when the total buffer capacity is exhausted.
This PR introduces a new metric, `drop_oldest_chunk_count`, which counts the number of discarded chunks.
https://github.com/fluent/fluentd-docs-gitbook/pull/582
Same as the title
=> output: add metrics for dropped oldest chunk count

lib/fluent/plugin/base.rb, test/log/test_console_adapter.rb, test/plugin/test_base.rb, test/plugin/test_output_as_buffered_backup.rb
Fixes #
This PR will removes unnecessary trailing semicolons to improve code style.
Not needed.
Code refactoring
=> Remove redundant semicolon

lib/fluent/plugin/buf_file.rb, lib/fluent/plugin/buf_file_single.rb, lib/fluent/plugin/buffer.rb, lib/fluent/plugin/buffer/file_chunk.rb, test/plugin/test_buf_file.rb, test/plugin/test_buf_file_single.rb
None.
Add feature to evacuate chunk files when retry limit.
When reached the retry limit, `buf_file` and `buf_file_single` evacuates all the chunk files (and the meta files) in the queue to the following dir before purging.
* `(root_dir)/buffer/(plugin-id)/`
`root_dir` is `system_config.root_dir` if it is configured.
Otherwise, `DEFAULT_BACKUP_DIR` is applied.
(`/tmp/fluent`. We can change this by env var `FLUENT_BACKUP_DIR`)
There is no separate directory for each worker because the IDs of each chunk are entirely unique.
This makes recovery easier.
After the problem with the flush (such as a network issue) is resolved, we can put back the files and restart Fluentd to flush them again.
The `backup` feature is for …
=> buffer: add feature to evacuate chunk files when retry limit

.github/workflows/benchmark.yml, .gitignore, Gemfile, Rakefile, fluentd.gemspec, tasks/benchmark.rb, tasks/benchmark/conf/in_tail.conf, tasks/benchmark/patch_in_tail.rb
Fixes #
This PR adds benchmark that measures performance using the `in_tail` plugin.
It would be good if performance regression can be found in the future...
We can check the results on the summary page in Benchmark workflow.
https://github.com/fluent/fluentd/actions/runs/15407283089?pr=4989
Not needed.
=> CI: Add benchmark scripts

README.md
Fixes #
The current badge does not represent the CI status, so this PR will be updated.
=> README: update CI status badge

lib/fluent/config/configure_proxy.rb, lib/fluent/config/section.rb, lib/fluent/plugin/buffer.rb, lib/fluent/plugin/out_exec_filter.rb, lib/fluent/plugin/out_forward.rb, lib/fluent/plugin/output.rb, lib/fluent/plugin_helper/child_process.rb, lib/fluent/plugin_helper/http_server/request.rb, lib/fluent/plugin_helper/storage.rb, test/plugin/test_in_tail.rb, test/plugin/test_out_exec.rb
None.
The safe navigation operator was introduced at [Ruby 2.3](https://www.ruby-lang.org/en/news/2015/12/25/ruby-2-3-0-released/).
I think it makes the code cleaner.
Not needed.
Minor code refactoring
=> Use safe navigation operator to clean up the codes

lib/fluent/plugin/compressable.rb, test/plugin/test_compressable.rb
Fixes #5005
This PR will fix RuntimeError with large zstd compressed data
Not needed because this feature has not been released yet.
Should be described with #4657
=> compressable: fix RuntimeError with large zstd compressed data

lib/fluent/plugin/in_forward.rb, test/plugin/test_in_forward.rb, test/plugin/test_out_forward.rb
Fixes #
This PR will enable `skip_invalid_event` in `in_forward` by default.
If broken data is received for any reason, it may cause the following error.
```
2025-06-12 18:27:30 +0900 [error]: unexpected error on reading data host="127.0.0.1" port=55970 error_class=TypeError error="can't convert String into an exact number"
2025-06-12 18:27:30 +0900 [error]: <internal:timev>:325:in 'Time.at'
2025-06-12 18:27:30 +0900 [error]: /Users/watson/src/fluentd/lib/fluent/plugin/formatter_stdout.rb:42:in 'Fluent::Plugin::StdoutFormatter#format'
2025-06-12 18:27:30 +0900 [error]: /Users/watson/src/fluentd/lib/fluent/plugin/out_stdout.rb:67:in 'Fluent::Plugin::StdoutOutput#format'
2025-06-12 18:27:30 +0900 [error]: …
```
=> in_forward: enable skip_invalid_event by default

MAINTAINERS.md
Update maintainers file with new Eduardo and Hiroshi's email/companies. As well add a reference to Fluent Bit maintainers file
=> maintainers: update Eduardo & Hiroshi's emails

lib/fluent/log.rb, test/test_log.rb
* Fixes a bug in #5008
In #5008, we have added a new feature `force_stacktrace_level`.
However, it was not applied to `PluginLogger`.
So, depending on the settings and error locations, `force_stacktrace_level` could not work.
This PR fixes it.
Not needed because #5008 is not released yet.
Not needed because #5008 is not released yet.
**How to reproduce the bug**:
conf:
```xml
<system>
<log>
forced_stacktrace_level info
</log>
</system>
<source>
@type sample
@id test
tag test.fail
</source>
<match test.fail>
@type null
@id null
never_flush
<buffer>
flush_mode interval
flush_interval 1s
</buffer>
</match>
```
* Set `@id` to use `PluginLogger`.
* Use `buffer` to use …
=> logger: force_stacktrace_level was not applied to PluginLogger

lib/fluent/plugin/out_stdout.rb, test/plugin/test_out_stdout.rb
* Fixes #5029
Add `use_logger` option to `out_stdout` plugin.
* Type: `bool`
* Default: `true`
If you set `false` to this option, `out_stdout` outputs events to `$stdout`, instead of `$logger`.
This feature enables events to be output to STDOUT in containerized environments, such as K8s.
This does not change the default behavior.
Note: Although it's preferable for the default value of a `bool` option to be `false` (because it can be used as a flag), I couldn't think of a suitable name for it.
https://github.com/fluent/fluentd-docs-gitbook/pull/593
out_stdout: support output to STDOUT independently of Fluentd logger by setting `use_logger` to `false`.
=> out_stdout: support output to $stdout independently of logger

CHANGELOG.md
None.
Fix v1.19.0 CHANGELOG.
What is experimental is out_forward.
See https://github.com/fluent/fluentd/pull/4896.
Not needed.
Not needed.
=> CHANGELOG: fix zstd experimental

.github/workflows/test-ruby-head.yml, .github/workflows/test.yml
Fixes #
Very rarely, tests may take a long time to run, but it is difficult to determine which tests took a long time.
At [test-unit](https://github.com/test-unit/test-unit) v3.6.3, `--report-slow-tests` option was introduced to show the top 5 slow tests.
https://github.com/test-unit/test-unit/blob/d641c29d4068d407808c42b15c6dcdf9c2f2b439/doc/text/news.md?plain=1#L137-L140
I think it might be useful.
Related to https://github.com/fluent/fluentd/issues/5041
Not needed.
CI improvements.
=> ci: add "--report-slow-tests" option

test/test_plugin_helper.rb
Fixes #
`test_config.rb` and `test_plugin_helper.rb` has same class name.
https://github.com/fluent/fluentd/blob/338050012279f401af41c95049d82cb98b2a370b/test/test_config.rb#L8
https://github.com/fluent/fluentd/blob/338050012279f401af41c95049d82cb98b2a370b/test/test_plugin_helper.rb#L5
The test class name should be unique.
Not needed.
CI improvements.
=> test_plugin_helper: fix test class name

fluentd.gemspec
* Related to #5041
This reverts commit 420e166c41e824594cc14b8a6c154da0c4fc5f54.
85740ac878d6dc408c47ade4e2d389ccfe2dc88a should resolve the fundamental issue.
Not needed.
CI fixes.
=> Revert "gemspec: fix io-event and io-stream version to avoid unstable behavior on Windows (#5042)"

SECURITY.md
None.
Add notes about fluent-package and Docker image.
The appropriate reporting destination varies depending on the type, but the guidance is insufficient now.
Not needed.
Not needed.
=> security: add note for package or Docker image

CHANGELOG.md
None.
Apply v1.16.10 release to CHANGELOG in master.
* https://github.com/fluent/fluentd/pull/5093
Not needed.
Not needed.
=> CHANGELOG: apply v1.16.10 release

lib/fluent/command/cat.rb, lib/fluent/compat/exec_util.rb, lib/fluent/log.rb, lib/fluent/plugin/in_exec.rb, lib/fluent/plugin/in_object_space.rb, lib/fluent/plugin/in_syslog.rb, lib/fluent/plugin/out_exec_filter.rb, test/command/test_binlog_reader.rb, test/command/test_ca_generate.rb, test/plugin/test_formatter_out_file.rb, test/plugin/test_out_exec.rb, test/plugin/test_out_file.rb, test/plugin/test_parser_json.rb
yajl is much slower than json nowadays.
See 1d5b0dec495a57e4fd8603735d4477a9f28186af and maintainer comment in https://github.com/brianmario/yajl-ruby/pull/228.
=> Replace yajl with built-in json for simple cases
