lib/fluent/plugin/filter_record_transformer.rb, test/plugin/test_filter_record_transformer.rb
a proposed implementation for #521
=> support JSON hash/array in filter_record_transformer

lib/fluent/supervisor.rb
Fix https://github.com/fluent/fluentd/issues/540
This is the first easiest implementation to fix the issue.
=> Fix ThreadError occuring on Signal.trap SIGHUP

lib/fluent/event.rb, test/test_event.rb
Improve EventStream#to_msgpack_stream increases the throughput.
And added tests for EventStream classes.
=> Improve EventStream and add its tests

ChangeLog
=> FIX Release 0.12.5 year to ChangeLog

ChangeLog
=> minor fix.

lib/fluent/config/configure_proxy.rb, test/config/test_configurable.rb
* overwriting config_section options like required/multi/alias breaks behavior of `super`
* so subclass must not overwrite these options
* subsection definitions of subsections (Hash) is simply merged
* it is bug, because same section definition like <a> is overwritten by subclass
* under this bug, subclass MUST repeat superclass's definition, and add original definition
* but this is impossible in the real world
* subsection definitions should be merged correctly
This bug especially make effect to the situations such like `<buffer>` configuration sections.
* Once Buffer base class define `<buffer>` section as non-required and non-multi
* Next AwesomeBuffer class (subclass of base class) define `<buffer>` section as required and multi
* `super` of AwesomeBuffer must raises error always …
=> Fix bug to overwrite all subsections definition by subclass

lib/fluent/plugin/out_forward.rb
Fixes #576. I haven't had time to add tests, but here's a PR for the change itself.
=> out_forward should resend on dropped connection

example/filter_stdout.conf, lib/fluent/formatter.rb, lib/fluent/plugin/filter_stdout.rb, test/plugin/test_filter_stdout.rb
This implementation is almost same with the implementation at https://github.com/fluent/fluentd/pull/307#issuecomment-68285384, but filter plugin not output plugin.
=> add filter_stdout

lib/fluent/parser.rb, test/test_parser.rb
This patch allows to use `keep_time_key` option in `in_tail` plugin. 
Now, writing config like:
```apache
<source>
type tail
path /var/log/nginx/access.log
pos_file tmp/access.log.pos
tag accesslog
format /^(?<remote>[^ ]*) (?<host>[^ ]*) (?<remoteuser>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)" "(?<forwardedfor>[^"]*)")?$/
time_format %d/%b/%Y:%H:%M:%S %z
keep_time_key true
</source>
```
keeps the `time` field in records.
=> Added keep_time_key option to parsers

lib/fluent/plugin/filter_record_transformer.rb, test/plugin/test_filter_record_transformer.rb
Same thing with https://github.com/sonots/fluent-plugin-record-reformer/pull/21
=> filter_transformer: add renew_time_key option

lib/fluent/plugin/out_forward.rb
@sonots Please check this patch ASAP.
=> Fix UDP heartbeat regression caused by #625

lib/fluent/plugin/in_status.rb
Related to https://github.com/fluent/fluentd/issues/520
=> Warn deprecation message for in_status plugin

lib/fluent/command/fluentd.rb, lib/fluent/config/configure_proxy.rb, lib/fluent/configurable.rb, lib/fluent/supervisor.rb, test/config/test_configure_proxy.rb
=> Add show plugin config

lib/fluent/plugin/out_exec.rb
See https://github.com/treasure-data/fluent-plugin-td/pull/21
=> Tempfile should be binary mode

fluentd.gemspec
=> v0.14 suppors only ruby 2.1 or later

lib/fluent/plugin/filter_record_transformer.rb
Descriptions are inspired by http://docs.fluentd.org/articles/filter_record_transformer
=> Add descriptions to filter_record_transformer

lib/fluent/plugin/filter_stdout.rb
See http://docs.fluentd.org/articles/filter_stdout
=> Add description to filter-stdout

lib/fluent/plugin/in_exec.rb
See http://docs.fluentd.org/articles/in_exec
=> Add descriptions to in-exec

lib/fluent/plugin/in_tcp.rb
See http://docs.fluentd.org/articles/in_tcp
=> Add descriptions to in_tcp

lib/fluent/plugin/out_copy.rb
See http://docs.fluentd.org/articles/out_copy
=> Add description to out_copy plugin

lib/fluent/plugin/in_stream.rb
See http://docs.fluentd.org/articles/in_unix
=> Add descriptions to in_unix

lib/fluent/plugin/out_stdout.rb
See http://docs.fluentd.org/articles/out_stdout
=> Add descriptions to out_stdout plugin

lib/fluent/test.rb, lib/fluent/test/formatter_test.rb, test/test_formatter.rb
I've tried to write FormatterTestDriver in the same way as ParserTestDriver.
This PR makes more easily to write formatter plugin tests.
Related to #652.
=> Add FormatterTestDriver

lib/fluent/plugin/in_tail.rb
See http://docs.fluentd.org/articles/in_tail
I cannot find description for `read_lines_limit`.
=> Add descriptions to in_tail

lib/fluent/plugin/exec_util.rb, lib/fluent/plugin/in_exec.rb, test/plugin/test_in_exec.rb, test/scripts/exec_script.rb
=> Support built-in text parsers in in_exec. fix #698

lib/fluent/plugin/out_exec.rb
see: http://docs.fluentd.org/v0.12/categories/out_exec
=> Add descriptions to out_exec

lib/fluent/command/cat.rb, lib/fluent/engine.rb
=> Fix fluent-cat with --msgpack option

lib/fluent/plugin/out_forward.rb, test/plugin/test_out_forward.rb
=> Use TCP heartbeat by default. fix #450

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
I wrote patches for https://github.com/fluent/fluentd/issues/668 for the master branch.
Please check this.
Thanks.
=> Periodic flush on in_tail plugin for multiline format

test/test_parser.rb
Regexp, Proc, Symbol, and String (empty string) objects added.
thanks :)
=> Add some objects cannot be parsed

lib/fluent/plugin/in_forward.rb, test/plugin/test_in_forward.rb
=> Add skip_invalid_event parameter to in_forward. fixes #774

lib/fluent/output.rb
=> Skip broken event which is routed to error stream

lib/fluent/plugin/filter_record_transformer.rb
Fix https://github.com/treasure-data/td-agent/issues/85
=> Fix record_transformer to be thread-safe

lib/fluent/supervisor.rb
Introduced by https://github.com/fluent/fluentd/pull/794
=> Fix the regression of SystemConfig apply

lib/fluent/test/filter_test.rb
fluent/filter should require in filter test driver.
=> Add missing require

test/helper.rb
=> Fix to be able to get any number of available ports

fluent.conf
=> Add filter and label example to fluent.conf. fix #512

test/plugin/test_in_syslog.rb
=> Fix time which has wrongly parsed in timezone with daylight saving time

test/helper.rb
=> add test helper method to create Fluent::Config::Element

lib/fluent/supervisor.rb
I can't reproduce this problem on my Mac environment but
I can reproduce it on Ubuntu Box.
=> Require fcntl library for daemonize. fix #841

lib/fluent/supervisor.rb
=> --show-plugin-config should care -p option

fluentd.gemspec
For the bug about DST
https://github.com/nurse/strptime/issues/8
=> Update strptime version

test/config/test_config_parser.rb
This should be added in b885cead.
=> Add missing assertion

.gitignore, Vagrantfile
=> Add Vagrantfile to run Fluentd in Linux box very easily

lib/fluent/compat/formatter.rb, lib/fluent/compat/parser.rb, lib/fluent/plugin/formatter.rb, lib/fluent/plugin/formatter_csv.rb, lib/fluent/plugin/formatter_hash.rb, lib/fluent/plugin/formatter_json.rb, lib/fluent/plugin/formatter_ltsv.rb, lib/fluent/plugin/formatter_msgpack.rb, lib/fluent/plugin/formatter_out_file.rb, lib/fluent/plugin/formatter_single_value.rb, lib/fluent/plugin/formatter_stdout.rb, lib/fluent/plugin/parser.rb, lib/fluent/plugin/parser_apache.rb, lib/fluent/plugin/parser_apache2.rb, lib/fluent/plugin/parser_apache_error.rb, lib/fluent/plugin/parser_csv.rb, lib/fluent/plugin/parser_json.rb, lib/fluent/plugin/parser_ltsv.rb, lib/fluent/plugin/parser_multiline.rb, lib/fluent/plugin/parser_nginx.rb, lib/fluent/plugin/parser_none.rb, lib/fluent/plugin/parser_syslog.rb, lib/fluent/plugin/parser_tsv.rb
* with compatibility layer for v0.12 style reference
=> Add Fluent::Plugin::Formatter, Fluent::Plugin::Parser and formatter/parser plugin files

lib/fluent/plugin/storage_local.rb
because it is set by OwnedByMixin
=> #configure does not require argument "plugin"

lib/fluent/command/cat.rb
https://github.com/fluent/fluentd/pull/854 miss fluent-cat fix.
=> Fix fluent-cat to assign port directly

lib/fluent/plugin/string_util.rb, test/plugin/test_string_util.rb
=> Fix logger on Fluent::StringUtil to use $log.

lib/fluent/compat/output.rb, lib/fluent/plugin/buffer.rb, lib/fluent/plugin/buffer/chunk.rb, lib/fluent/plugin/buffer/file_chunk.rb, lib/fluent/plugin/buffer/memory_chunk.rb, lib/fluent/plugin/output.rb, test/plugin/test_buffer.rb, test/plugin/test_buffer_chunk.rb, test/plugin/test_output_as_buffered.rb, test/plugin/test_output_as_buffered_overflow.rb, test/plugin/test_output_as_standard.rb
This is same with #943, which was wrongly merged as squashed commit.
=> Support overflow action in v14 api redo

test/config/test_element.rb
Added these test cases:
* `#initialize`
* `#add_element`
* `#==`
* `#+`
* `#has_key?`
* `#to_s`
* `#inspect`
=> test_element: Add test cases for Config::Element

.travis.yml, fluentd.gemspec, lib/fluent/configurable.rb, lib/fluent/plugin/formatter.rb, lib/fluent/plugin/out_exec.rb, lib/fluent/plugin/out_file.rb, lib/fluent/plugin_helper/event_loop.rb, lib/fluent/plugin_helper/thread.rb, lib/fluent/test/driver/base.rb, lib/fluent/time.rb, test/plugin/test_out_buffered_null.rb, test/plugin_helper/test_timer.rb
This change is based on #983.
This pull request is the last call for changes included in v0.14.0 RC2.
=> Fix issues for v0.14.0

fluentd.gemspec
Fix https://github.com/fluent/fluentd/issues/985
See also discussion with hsbt (Japanese)
https://twitter.com/sonots/status/735097429251366917
=> Revert: Fix string-scrub dependency #937 (only gemspec)

example/out_forward_buf_file.conf, lib/fluent/plugin/in_monitor_agent.rb
=> Fix monitor agent v14

lib/fluent/test/output_test.rb, test/plugin/test_out_forward.rb
This is extracted from #942 .
This PR should be merged after #953.
=> Fix test for out forward

ChangeLog
=> Changes to release v0.14.0

lib/fluent/compat/input.rb, lib/fluent/compat/output.rb, lib/fluent/process.rb
=> Fix to require DetachProcessMixin in default for compat plugins

lib/fluent/supervisor.rb, test/test_supervisor.rb
=> Fix to create pid file when daemonized

lib/fluent/plugin/out_relabel.rb, test/plugin/test_out_relabel.rb, test/test_root_agent.rb
Also I've added test for `out_relabel`.
=> Migrate out_relabel to v0.14 API

lib/fluent/test/output_test.rb, test/plugin/test_out_file.rb
=> backport: Fix test for TimeSlicedOutput

test/test_event_time.rb
* This test code fails on Travis OSX environment
* It's a bit curious and cannot be reproduced in my laptop, but not important to spend time for it
=> Just a single value was invalid as JSON object in traditional way

lib/fluent/compat/filter.rb, lib/fluent/compat/input.rb, lib/fluent/compat/output.rb, lib/fluent/plugin/out_file.rb, lib/fluent/test/driver/base.rb, lib/fluent/test/driver/output.rb, lib/fluent/test/input_test.rb
=> Use extend instead of abnormal prepend

lib/fluent/test/driver/base.rb
expected_records ->
expect_records
=> Fix a typo

lib/fluent/test/driver/base.rb
* `#record_count`
* `#emit_count`
=> Add utility methods to test driver

test/plugin/test_output_as_buffered_retries.rb
By adding barriers to stop flushing on unexpected timing
=> Try to reduce occasional failure of tests

lib/fluent/compat/handle_tag_and_time_mixin.rb, lib/fluent/compat/output.rb, test/test_output.rb
=> fix to require compat modules missed in previous

ChangeLog, lib/fluent/config/configure_proxy.rb, lib/fluent/plugin/in_forward.rb, lib/fluent/plugin/in_tail.rb, lib/fluent/version.rb
v0.14.6 is mainly for fixing in_tail regression, so I remove parser/formatter and buffer compression changes from v0.14.6 release.
=> Release v0.14.6

test/plugin/test_out_secondary_file.rb
This should fix https://github.com/fluent/fluentd/issues/1115#issuecomment-246892549
=> test_out_secondary_file: wait for disk I/O completion in tests

lib/fluent/plugin/in_tail.rb
=> in_tail: Detach timer trigger when detach TailWatcher

lib/fluent/log.rb
https://travis-ci.org/fluent/fluent-logger-ruby/jobs/167564961
=> Avoid name conflict between Fluent::Logger

lib/fluent/plugin/out_file.rb
=> fix to create formatter without explicit configuration element

lib/fluent/plugin/filter_parser.rb, test/plugin/test_filter_parser.rb
v0.14's parser filter routes invalid record to @ERROR label.
This parameter enables same behaviour in v0.12.
Include refactoring.
=> filter_parser: Add emit_invalid_record_to_error parameter

lib/fluent/plugin/in_monitor_agent.rb
Add query parameter `with_ivars` to `in_monitor_agent`'s `/api/plugins.json`.
See #1393
=> Port #1393 to v0.12

lib/fluent/plugin/buffer.rb, test/plugin/test_buffer.rb
=> Revert "Keep Fluent::BufferQueueLimitError for exsting plugins"

lib/fluent/compat/output.rb, lib/fluent/output.rb, test/test_output.rb
#1450 again by using compat module
=> Keep Fluent::BufferQueueLimitError for exsting plugins

lib/fluent/plugin/filter_record_transformer.rb
=> Revert "Use BasicObject for cleanroom"

lib/fluent/plugin/in_forward.rb, test/plugin/test_in_forward.rb
- Fix source_hostname_key feature to get hostname, not address.
- Add source_address_key feature
=> in_forward: backport source / address key features

lib/fluent/plugin/in_http.rb, test/plugin/test_in_http.rb
This is the same as #1498 but for the 0.12 branch. Test has been adapted to the 0.12 style.
=> msgpack format chosen with content-type header

lib/fluent/plugin/in_syslog.rb, lib/fluent/plugin/in_tcp.rb, lib/fluent/plugin/in_udp.rb, lib/fluent/plugin/socket_util.rb, test/plugin/test_in_syslog.rb
=> Fix hostname lookup

lib/fluent/command/plugin_generator.rb
I fixed a explanation of Overwriting.
=> fix typo quite->quit

lib/fluent/parser.rb, test/test_parser.rb
=> Add rfc5424 regex without priority for v0.12

templates/new_gem/README.md.erb
fluent-plugin-format-config ->
fluent-plugin-config-format
=> Fix command name

lib/fluent/plugin/in_syslog.rb, test/plugin/test_in_syslog.rb
This PR is v0.14 version of #1615 patch.
=> Add resolve_hostname config param in in_syslog

lib/fluent/plugin/parser_syslog.rb, test/plugin/test_parser_syslog.rb
Port https://github.com/fluent/fluentd/pull/1609 to master
=> Add more available characters for tag part of syslog format

lib/fluent/engine.rb
Engine emits all log events before shutdown RootAgent.
I'll send a same patch to the master branch after this PR is merged.
=> Make sure all log events are emitted before shutdown

lib/fluent/agent.rb, lib/fluent/engine.rb
=> Revert "Make sure log events generated at shutdown phase of plugins (except"

lib/fluent/engine.rb
=> Revert "Make sure all log events are emitted before shutdown"

README.md
CNCF is experimenting with automated license scanning tools.
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Add FOSSA Badge

GOVERNANCE.md
The following PR adds a draft for the upcoming Governance model
=> Doc: add Governance document (draft)

lib/fluent/command/cat.rb, lib/fluent/command/debug.rb, lib/fluent/command/fluentd.rb, lib/fluent/plugin/in_unix.rb, lib/fluent/plugin/output.rb, lib/fluent/plugin_helper/record_accessor.rb
This makes easy to understand code.
=> Use singleton_class method instead of instead of legacy trick

lib/fluent/plugin_helper/server.rb
Thid doesn't resolve #1767 but this is better for avoiding non-used exception allocation.
And `exception: false` is bit faster when the number of requests is large.
=> in_forward: Use exception: false if available to improve resourse usage

lib/fluent/plugin/out_forward.rb
We need to call `rebuild_weight_array` after detecting server recovery because old weight array doesn't consider proper weight/standy setting.
=> out_forward: Rebuild weight array to apply server setting properly. fix #1772

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
=> in_tail: Properly handle moved back and truncated case for v0.12

lib/fluent/plugin/in_forward.rb
=> Do not close connection until write is complete on failed auth PONG

lib/fluent/plugin_helper/retry_state.rb, test/plugin_helper/test_retry_state.rb
With too big steps, calc_interval returns Infinity and it causes
FloatDomainError. To avoid this issue, re-compute interval when
calculated interval is infinite.
=> retry_state: Fix exponential backoff with too big steps. fix #1937

lib/fluent/command/cat.rb
=> fluent-cat: Handle retry limit

CHANGELOG.md
Suddenly, we got back to 2018? Haha. :wink:
=> Fix release year for v1.3.3

CONTRIBUTING.md
Signed-off-by: Nguyen Van Trung <trungnv@vn.fujitsu.com>
=> Change http to https for security links

CONTRIBUTING.md
Although it is spelling mistakes, it might make an affects
while reading.
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>
=> trivial fix typo

test/command/test_fluentd.rb, test/command/test_plugin_config_formatter.rb, test/config/test_configurable.rb, test/config/test_element.rb, test/plugin/test_filter.rb, test/plugin/test_filter_record_transformer.rb, test/plugin/test_out_secondary_file.rb, test/plugin/test_output.rb, test/plugin/test_parser_syslog.rb, test/plugin_helper/test_record_accessor.rb, test/plugin_helper/test_server.rb, test/test_output.rb, test/test_plugin.rb
This PR fixes many typos in test code.
=> Fix many typos in test code

.github/ISSUE_TEMPLATE.md
Insert the command to check the version of OS and kernel
in order to get more detail in ISSUE_TEMPLATE.
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>
=> Adding detail of how to check the OS/kernel version

README.md
Co-Authored-By: Dao Cong Tien tiendc@vn.fujitsu.com
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>
=> Adding link to github account of author

GithubWorkflow.md
Describe detail step-by-step of using github to contribute to
fluentd project.
Co-Authored-By: Dao Cong Tien tiendc@vn.fujitsu.com
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>
=> Adding github workflow for contributing to fluentd

README.md
=> Update README file with correct link

CHANGELOG.md
=> Fix outline in changelog

CHANGELOG.md, GithubWorkflow.md
Correct some words spelling for reading more easily.
Signed-off-by: Nguyen Quang Huy <huynq0911@gmail.com>
Co-Authored-By: Nguyen Van Trung <trungnvfet@outlook.com>
=> Fix some typos

lib/fluent/plugin_helper/server.rb
ref https://github.com/fluent/fluentd/pull/2395/#issuecomment-491134888
I moved `super` into the outside of a synchronized context.
TLSServer doesn't use the inner buffer(::IO::Buffer) of Coolio::IO.
Instead of using Coolio::IO's inner buffer, TLSServer has own buffer(@_handler_write_buffer). 
Actually, the only reason calling `super` here is to call Coolio::IO#disable_write_watcher.
If super is called in a synchronized context, it could cause a mutex recursive locking since Coolio::IO#on_write_complete
eventually calls TLSServer#close which try to get a lock.
https://github.com/tarcieri/cool.io/blob/0fd3fd1d8e8d81e24f79f809979367abc3f52b92/lib/cool.io/io.rb#L134-L149
No.
No.
=> No need to call super in a synchronized context

.gitlab-ci.yml, README.md
No Issue Open
This PR enables GitLab CI support on GitLab. By adding this file we enable GitLab CI to build fluentd. This can speed up the process of builds and also adds another service to assist in the event one service goes down. I.e. Travis CI goes down and builds stop, GitLab CI can pickup the slack.
No documents changed.
=> WIP: Add GitLab CI Support to FluentD

lib/fluent/plugin/in_monitor_agent.rb, test/plugin/test_in_monitor_agent.rb
nothing
* endpoint api/config checks if the path is valid.
* return status code 404 if needed
* match returned error message with https://github.com/fluent/fluentd/blob/0f3704f7f9e4b5334eca643568eb515ce6daaa3e/lib/fluent/plugin/in_monitor_agent.rb#L55-L59
not needed
not needed
=> Fix return value when not found path

lib/fluent/plugin/in_monitor_agent.rb, test/plugin/test_in_monitor_agent.rb
Depends on https://github.com/fluent/fluentd/pull/2424
Remove needless rescue and fix typo.
not needed
not needed
=> Fix needless rescue

Rakefile, lib/fluent/command/plugin_config_formatter.rb, lib/fluent/config/literal_parser.rb, lib/fluent/plugin/base.rb, lib/fluent/plugin/in_forward.rb, test/plugin/test_buf_file.rb, test/plugin/test_in_http.rb, test/plugin/test_in_udp.rb, test/plugin/test_out_file.rb, test/plugin/test_output_as_buffered.rb, test/plugin/test_output_as_buffered_retries.rb, test/plugin/test_output_as_buffered_secondary.rb, test/plugin_helper/test_server.rb, test/test_log.rb
None
Fix failure test on gitlab
No
No
=> Fix test for gitlab

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, CONTRIBUTING.md
no
I updated ISSUE_TEMPLATE to use the github feature. https://help.github.com/en/articles/about-issue-and-pull-request-templates
This change is aiming to reduce the questions by redirecting them to our mailing list.
no
no
=> Update issue template

lib/fluent/plugin/out_forward.rb
Follow up https://github.com/fluent/fluentd/pull/2483/
i forgot to pass `@node` to rebuild_weight_array.
no needed
no needed
cc @repeatedly
=> Pass `@nodes` to rebuild_weight_array

test/plugin/test_output_as_buffered.rb
no
To fix vulnerable tests like https://travis-ci.org/fluent/fluentd/jobs/557632942.
no needed
no needed
=> Fix vulnerable tests

lib/fluent/plugin/out_forward.rb, lib/fluent/plugin/out_forward/connection_manager.rb, test/plugin/out_forward/test_connection_manager.rb, test/plugin/out_forward/test_handshake_protocol.rb, test/plugin/test_out_forward.rb
no
This PR depends on https://github.com/fluent/fluentd/pull/2490.
Extract the part of connection handing as a class.
no needed
no needed
=> Connection handler

.drone.yml, README.md
Signed-off-by: Bin Lu <bin.lu@arm.com>
None
We want to enable arm ci for CNCF projects one by one.
README.md
None
=> ci: add drone.io for arm64 verification

lib/fluent/plugin/out_forward.rb, test/plugin/test_out_forward.rb
no
Refactor heartbeat code in out_forward.
Merged duplicated code and use more specify method name.
no needed
no needed
=> Refactor heartbeat

lib/fluent/plugin/out_forward/load_balancer.rb
no
LoadBalancer was thread-unsafe.
LoadBalancer#select_healthy_node  and LoadBalancer#rebuild_weight_array are called in other threads. If context switch happens [this line](https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/out_forward/load_balancer.rb#L36), and do [this line](https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/out_forward/load_balancer.rb#L97) in another thread.  [node]( https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/out_forward/load_balancer.rb#L36) can be `nil`.
no need
=> Make LoadBalancer thread safe

lib/fluent/plugin_helper/http_server/compat/webrick_handler.rb
None
Avoid lots of warning in tests
No need
Same as title
=> http_server helper: Avoid re-define render_json

test/plugin/test_output_as_buffered.rb
retry https://github.com/fluent/fluentd/pull/2494
=> Retry Fix vulnerable tests

test/plugin/test_out_forward.rb
no
Fixes https://travis-ci.org/fluent/fluentd/jobs/562022979 and shorten test time
no needed
no needed
=> Fix failed test at startup

lib/fluent/plugin/out_forward.rb, test/plugin/test_out_forward.rb
no
Add error message when node failed to establish a new connection.
no needed
no needed
=> Add error text

test/command/test_plugin_generator.rb
Initialized empty Git repository
no
suppress the warning https://travis-ci.org/fluent/fluentd/jobs/562908535
```
Initialized empty Git repository in /home/travis/build/fluent/fluentd/tmp/plugin_generator/fluent-plugin-fake/.git/
.
Initialized empty Git repository in /home/travis/build/fluent/fluentd/tmp/plugin_generator/fluent-plugin-fake/.git/
.Initialized empty Git repository in /home/travis/build/fluent/fluentd/tmp/plugin_generator/fluent-plugin-fake/.git/
.Initialized empty Git repository in /home/travis/build/fluent/fluentd/tmp/plugin_generator/fluent-plugin-fake/.git/
.Initialized empty Git repository in …
```
=> stub git process to suppress warning

.drone.yml, README.md
Modifications:
1, change to the correct status picture
2, change to the minimum test set
Signed-off-by: Bin Lu <bin.lu@arm.com>
None
None
README
None
=> optimize arm64 ci

lib/fluent/config/literal_parser.rb
Fixes #
make error message more understandable :)
=> literal_parser.rb: error message spell correction

lib/fluent/plugin/filter_grep.rb
Fixes #
cleanup log message by fix typos in it.
NONE
NONE
=> cleanup: filter_grep.rb logging message word fix

lib/fluent/compat/socket_util.rb
Fixes #
make message to end user more meaningfull and understandable
=> socket_util.rb: correct misspelled word

lib/fluent/plugin_helper/server.rb
Fixes #
cleanup error message, make it more accurate.
=> server.rb: fix word misspell in message

lib/fluent/plugin/out_file.rb
Fixes #
correct logging message
NONE
NONE
=> out_file.rb: correct logging message

test/plugin_helper/test_record_accessor.rb
Fixes #
correct misspelled words in message, make it user-friendly
NONE
NONE
=> fix typos in message: braket -> bracket

lib/fluent/plugin/buffer/file_single_chunk.rb
follow up https://github.com/fluent/fluentd/pull/2579
File#pos returns 0 since File#seek(0, IO::SEEK_SET) is called before
no need
Fix bug `@commit_position` is always 0
=> Use size instead of 

lib/fluent/plugin/in_tcp.rb, test/plugin/test_in_tcp.rb
No issue
Add `in_forward` like access restriction to in_tcp.
This is first step. We will add similar feature to other network plugins, e.g. `in_syslog`, `in_udp`, etc.
Add option to in_tcp article. I will send a patch later.
Same as title.
=> in_tcp: Add security/client to restrict the access

test/plugin/out_forward/test_socket_cache.rb, test/plugin/test_buffer_file_chunk.rb, test/plugin/test_output_as_buffered.rb, test/test_root_agent.rb
=> fix-up typo

lib/fluent/compat/call_super_mixin.rb, lib/fluent/plugin/buf_file.rb, lib/fluent/plugin/buf_file_single.rb, lib/fluent/plugin/in_tail.rb, lib/fluent/plugin_id.rb
Ref https://github.com/fluent/fluentd/issues/2624
All resources need to be cleaned for  #2624.
no need
no need
=> cleanup class variable resources

lib/fluent/engine.rb
Fixes #
fluentd no longer use this value since https://github.com/fluent/fluentd/commit/6b37daa07f94534d43d7d92c5498f874d8cd48f3
no need
no need
=> No longer use the value

lib/fluent/plugin/out_forward.rb, test/plugin/test_out_forward.rb
Fixes https://github.com/fluent/fluentd/issues/2659
not to copy `@id` or other necessary things to sd plugin.
no need
Fix sd plugin's bugs with `@id`
=> copy setting sd plugin needs only

lib/fluent/supervisor.rb, lib/fluent/system_config.rb, test/config/test_system_config.rb
Ref #2624 
Remove unused variable
no need
no need
=> Remove unused variable

lib/fluent/supervisor.rb
no
it's config.getDump, not config.dump
no need
no need
=> Fix debug log text

lib/fluent/command/fluentd.rb
no
it's just cosmetic change.
no need
no need
=> Remove unnecessary space

lib/fluent/plugin/out_forward.rb, test/plugin/out_forward/test_load_balancer.rb
None
Fixed typo in stats key.
None
None
=> Fix typo: healty -> healthy

MAINTAINERS.md
Signed-off-by: Eduardo Silva <edsiper@gmail.com>
=> MAINTAINERS: Add Eduardo Silva

.travis.yml
Signed-off-by: Namrata Bhave <Namrata.Bhave@ibm.com>
Fixes # Adding s390x support to the travis.yml builds
**What this PR does / why we need it**:  Travis deployment on s390x
**Docs Changes**: None
**Release Note**:  None
=> Adding support for s390x in Travis

lib/fluent/supervisor.rb, test/test_logger_initializer.rb
https://github.com/fluent/fluentd/pull/1130
https://github.com/fluent/fluentd/pull/1130 is very old and the author hasn't replied. so renew it 
none
=> LoggerInitializer updated to create directory when it doesn't exists

.travis.yml, fluentd.gemspec, lib/fluent/config/literal_parser.rb, lib/fluent/plugin/out_http.rb
none
Add ruby 2.7 ci support
none
none
=> Add ruby 2.7.0

README.md
none
Update for ruby version and branch
none
none
=> Update for ruby version and branch

lib/fluent/plugin/in_tail.rb, test/plugin/test_in_tail.rb
Fixes https://github.com/fluent/fluentd/pull/2001
Add path_delimiter to split with any char
needed?
=> Add path_delimiter to split with any char

test/plugin/test_out_copy.rb
no
Add assertions for `outputs`
no
no
=> Add assertions for `outputs` in out_copy plugin test

.gitignore
Signed-off-by: Kentaro Tokutomi <ktr.tokutomi@gmail.com>
no
This PR avoids to commit IntelliJ setting files to the repo.
no
no
=> Add .idea/ to ignore file

lib/fluent/plugin/in_tail.rb, test/plugin/in_tail/test_fifo.rb, test/plugin/in_tail/test_io_handler.rb, test/plugin/test_in_tail.rb
no
Reduce TailWatcher argument and adding Io handler
no
no
=> Reduce TailWatcher argument and adding Io handler

test/plugin/in_tail/test_io_handler.rb
fixes https://ci.appveyor.com/project/fluent/fluentd/builds/31358039/job/72o6ik1u4apf6bsu
I've noticed I had added the wrong test in windows in  https://github.com/fluent/fluentd/pull/2858
no need
no need
=> Test: Use binmode for Tempfile

test/plugin/test_in_tail.rb
Fixes https://travis-ci.org/fluent/fluentd/jobs/658509042#L1659
Fix an unstable test.
no need
no need
=> wait num_events  since expect_emits number is not 1, num_events

.github/workflows/issue-auto-closer.yml
I want to add issue auto closer to close issues that don't follow the issue template.
here is test repo https://github.com/ganmacs/github-action-test/
no need
no need
=> Add issue auto closer

test/plugin/test_output_as_buffered_secondary.rb
https://travis-ci.org/github/fluent/fluentd/jobs/666678658#L622
Follow up https://github.com/fluent/fluentd/pull/2901, https://github.com/fluent/fluentd/pull/2907
In https://github.com/fluent/fluentd/blob/c90c024576b3d35f356a55fd33d1232947114a9a/lib/fluent/plugin_helper/retry_state.rb
`@timeout_at` is 2016-04-13 18:34:31, `@next_time` must be less than 2016-04-13 18:34:30
`first_failure + 60 * 0.8 + 2 # => 2016-04-13 18:34:21`
`@next_time` is not added by 1, but by `randomize(@retry_wait) `https://github.com/fluent/fluentd/blob/c90c024576b3d35f356a55fd33d1232947114a9a/lib/fluent/plugin_helper/retry_state.rb#L196
`current_time(=Time.now)` + `randomize(@retry_wait)` < `@timeout_at`
(2016-04-13 18:34:21 + 6) + 3 < …
=> `now` is less than 2016-04-13 18:34:31

test/plugin/test_out_null.rb, test/plugin_helper/http_server/test_app.rb, test/plugin_helper/http_server/test_route.rb, test/plugin_helper/test_http_server_helper.rb
nope
fixed typo
no need
no need
=> test: fix typo

lib/fluent/plugin/in_syslog.rb, test/plugin/test_in_syslog.rb
Follow up https://github.com/fluent/fluentd/pull/2771
no need
no need
same as title.
=> Fix a bug in in_syslog octet-counting mode

lib/fluent/command/debug.rb
=> Fix fluent-debug command fail to start

lib/fluent/plugin_helper/socket_option.rb
Signed-off-by: Takuro Ashie <ashie@clear-code.com>
No issue
Fix indent
None
None
=> Fix indent

lib/fluent/plugin/in_http.rb
Fixes #3035
Add `dump_error_log` parameter for capturing error in fluentd logs.
Add parameter to in_http article.
Same as title
=> in_http: Add dump_error_log parameter. fix #3035

lib/fluent/plugin/buffer.rb
Fixes #3072 
Use proper log message for chunk_limit_records case.
No need
Same as title
=> buffer: Fix log message for chunk_limit_records case. fix #3072

.github/stale.yml
Fixes #3150
It closes inactive issues/PRs.
ref. https://probot.github.io/apps/stale/
No need to change.
No need to change.
=> workflow: add default configuration for probot/stale

lib/fluent/plugin/in_http.rb, test/plugin/test_in_http.rb
Fix #3188
Added `add_query_params` config option to in_http, when set it will add all query params to the record
I think so
=> feat: added support for query params in in_http plugin

CHANGELOG.md, README.md
Signed-off-by: Didier Durand <durand.didier@gmail.com>
Improves documentation
As per title, this is pure doc improvement
=> Updating and fixing text on README and CHANGELOG

.github/workflows/build.yaml
none
.github/workflows/build.yaml includes a typo so that CI doesn't work.
none
none
=> GitHub Actions: Fix a typo

test/plugin_helper/test_server.rb
none
Recent distributions disables TLS 1.1 by default due to its
vulnerability so that tests for it is always failed:
2021-02-18T01:09:13.2360942Z Failure: test: can specify multiple TLS versions by min_version/max_version(ServerPluginHelperTest::#server_create_tls::TLS version connection check):
2021-02-18T01:09:13.2362181Z   Exception raised:
2021-02-18T01:09:13.2363101Z   OpenSSL::SSL::SSLError(<SSL_connect returned=1 errno=0 state=error: no protocols available>)
...
2021-02-18T01:09:13.2479586Z /home/runner/work/fluentd/fluentd/test/plugin_helper/test_server.rb:1515:in `block (4 levels) in <class:ServerPluginHelperTest>'
2021-02-18T01:09:13.2480420Z      1512:           end
2021-02-18T01:09:13.2480756Z …
=> Drop testing TLS 1.1

test/test_formatter.rb
Follow up for #3288
In #3288, some tests are failed on #3288 due to mismatched line breaks.
none
none
=> Fix some failed tests of #3288 on Windows

.deepsource.toml
PR #3259 fixed some of the issues caught by DeepSource.
Know more about the features [here](https://deepsource.io/features/).
Integrating DeepSource to continuously analyze your repository:
- Install DeepSource on your repository [here](https://deepsource.io/signup)
- Merge this PR which includes the configuration file for DeepSource
- Activate analysis [here](https://deepsource.io/gh/fluent/fluentd/)
=> [FEATURE] DeepSource

lib/fluent/event.rb, test/test_event.rb
=> Fix MessagePackEventStream issue with Enumerable methods

MAINTAINERS.md
I moved to Calyptia, Inc.
None
@cosmo0920 has been moved into Calyptia, Inc.
No needed.
Same as title.
=> Move Hatake company

example/counter.conf
Typo in `example/counter.conf`
Changes were made here: https://github.com/fluent/fluentd/commit/056a344ad81eb71694e46095e15055c32b2e0301#diff-1e02ff26a69c76251ae416a1fadf73a89dac6368a7e4f941124802fb4b63e333R64
Looks like we forgot to make the corresponding change in `example/counter.conf`.
=> Change path to backup_path in counter_server

CONTRIBUTING.md, README.md
Fixes N/A
It is better to use a community forum instead of
the traditional mailing list in most of the cases.
Recommends using https://discuss.fluentd.org/.
N/A
N/A
=> Navigate to community forum instead of mailing list

CHANGELOG.md, lib/fluent/version.rb
none
Deliver #3391 to v1.12 users since it's a critical regression.
master branch is already for v1.13 so it has too much changes for v1.12.
So we decide to create a new branch for v1.12.
none
none
=> Release v1.12.4

CHANGELOG.md, lib/fluent/version.rb
Fixes N/A
This is PR for preparing v1.13.0 changelog entries.
v1.13.0 blog entry is also making progress here:
https://github.com/fluent/fluentd-website/pull/146
N/A
=> Add v1.13.0 changelog entries

lib/fluent/command/plugin_generator.rb, lib/fluent/test/driver/storage.rb, templates/new_gem/lib/fluent/plugin/storage.rb.erb, templates/new_gem/test/plugin/test_storage.rb.erb, test/command/test_plugin_generator.rb
Fixes N/A
E.g.
$ fluent-plugin-generate storage example
https://docs.fluentd.org/deployment/command-line-option#fluent-plugin-generate
should be updated.
N/A
=> Support to generate storage plugin template

example/v0_12_filter.conf
Fixes #
Clean up extra spaces, although these errors are not important, they affect the code specification.
=> Clean up extra spaces

fluentd.gemspec
none
We need https://github.com/chef/win32-service/pull/74 to support
additional commands of fluent-ctl
none
=> Bump up required win32-service

test/plugin_helper/test_retry_state.rb
This is about #3609.
Add scenario tests for #3649.
RetryStatement behavior is complicated, so scenario tests may be useful.
None.
None.
=> [For #3649] Add scenario test of RetryState

fluentd.gemspec
Signed-off-by: Takuro Ashie <ashie@clear-code.com>
Fixes #2200
Fixes #2426
* Enable to set interval of restarting workers
See #3749 and #3768
* Fix a bug that fluentd doesn't release its own log file even after
rotated by external tools
Fix #2200 and #2426
None
Fix a bug that fluentd doesn't release its own log file even after rotated by external tools
=> Bump up required serverengine to 2.3.0

.github/workflows/linux-test.yaml, .github/workflows/macos-test.yaml
=> CI: Add Ruby 3.2 for GNU/Linux and macOS

.github/workflows/windows-test.yaml
=> CI: Add Ruby 3.2 for Windows

test/test_supervisor.rb
None
Remove needless test code.
Not needed.
Not needed since this is just for test code.
=> test: remove needless code

lib/fluent/event.rb
None.
Just fixing a typo.
Not needed.
Not needed.
=> Event: Fix typo

lib/fluent/plugin/in_tail/position_file.rb
None.
Apply #4214 to v1.16.
No need.
=> v1.16: in_tail: Fix warning about overwriting entry with follow_inodes

CHANGELOG.md, lib/fluent/version.rb
None.
Apply v1.16.5 VERSION and CHANGELOG to the master.
None.
None.
=> Apply v1.16.5

SECURITY.md
N/A
Sorry, I forgot to update SECURITY.md in #4480
N/A
N/A
=> SECURITY.md: Update supported version

.github/ISSUE_TEMPLATE/bug_report.yml
None.
Update the old package description of GitHub issue template: `Bug Report`, taking into account `fluent-package`.
Not needed.
Not needed.
=> GitHub issue template: update old package description

.github/workflows/stale-actions.yml
None.
Fix a typo.
Not needed.
Not needed.
=> GitHub: fix typo of exempt-label

lib/fluent/command/cap_ctl.rb, lib/fluent/plugin/in_http.rb, lib/fluent/plugin/out_copy.rb, test/helpers/fuzzy_assert.rb, test/plugin/test_buf_file.rb, test/plugin/test_in_forward.rb, test/plugin/test_out_file.rb, test/plugin/test_output.rb, test/test_log.rb, test/test_root_agent.rb
Fixes #
This patch may slightly improve the code readability.
=> Fix indentations

.github/workflows/scorecards.yml, .github/workflows/stale-actions.yml, .github/workflows/test-ruby-head.yml, .github/workflows/test.yml
Part of  #4601 
fixed the pinned dependencies issue reported by the [scorecard](https://scorecard.dev/viewer/?uri=github.com/fluent/fluentd).
None
None
=> fix: fixed the pinned dependencies issue

SECURITY.md
Update `SECURITY.md` for v1.18.0 release.
Note: v1.16.x is the current LTS version.
=> SECURITY.md: Update for v1.18.0 release

lib/fluent/config/parser.rb
Fixes #
By [CodeQL documentation](https://codeql.github.com/codeql-query-help/ruby/rb-non-constant-kernel-open/), it is safer to avoid using `URI.open`.
=> parser: use URI#open instead of URI.open

lib/fluent/winsvc.rb
None.
Even if the supervisor process is dead due to config error or etc, the service process will continue running unexpectedly because no one monitor it. This commit fix this issue.
Not needed.
=> winsvc: Stop the service when the supervisor is dead

lib/fluent/plugin_id.rb
Fixes #
Fix misspell
Not needed.
=> plugin_id: fix typo

lib/fluent/plugin/sd_file.rb
Fixes #
Fix misspell
Not needed.
=> sd_file: fix typo

CHANGELOG.md
Fixes #
Merge v1.16 LTS changelog to master
Ref. https://github.com/fluent/fluentd/blob/v1.16/CHANGELOG.md
=> Merge v1.16 LTS changelog to master

test/plugin/test_buf_file.rb, test/plugin/test_buf_file_single.rb
* For #5012
Refactor code for #5012
Not needed.
Not needed because this is new code for v1.19.
=> test: refactor code

CHANGELOG.md
None.
Fix a wrong link in CHANGELOG.
Not needed.
Not needed.
=> CHANGELOG: fix wrong link

CHANGELOG.md
None.
Fix the wrong date of v1.19.0 release.
Not needed.
Not needed.
=> CHANGELOG: fix wrong date
