- .gitignore
- Gemfile
@repeatedly @tagomoris 
I often want to include my favorite development gems like `pry` and `pry-nav` for development of Fluentd. 
I recently heard some ruby developers are doing a good practice for this situation, supporting `Gemfile.local`. 
See https://github.com/tdiary/tdiary-core/blob/fd2b250792a54bf23216e4b75ecbef8e17fcb79f/Gemfile#L36-L40 for an example. 
The Gemfile.local file is ignored by .gitignore, and Gemfile includes Gemfile.local if it exists so that we can add favorite gems freely only on local. 
```
gem 'pry'
gem 'pry-nav'
```
> Support Gemfile.local

- lib/fluent/supervisor.rb
Reported by https://groups.google.com/forum/#!topic/fluentd/jFQTeNONmCA
Fix a bug by https://github.com/fluent/fluentd/pull/496
This patch makes system config be also reloadable (it was not before).
> fix SIGHUP does not reload config

- lib/fluent/output.rb
- test/test_output.rb
From v0.10.58 or later and v0.12, calc_retry_wait causes an exception if Integer is used for retry_wait.
retry_wait is `time` type, so it can be Integer value. `#finite?` is a method for Float class, not for Integer.
> calc_retry_wait is broken if Integer is used for retry_wait

- lib/fluent/plugin/buf_file.rb
noticed this while writing a docs.
Another option is to have
```rb
config_param :flush_at_shutdown, :bool, :default => false
```
but that can break backward compatibility (for example, `flush_at_shutdown false` returns different vals.
> remove the unused local variable

- lib/fluent/output.rb
- test/test_output.rb
Fix https://github.com/fluent/fluentd/issues/532
> Fix TimeSlicedOutput does not flush with SIGUSR1

- lib/fluent/output.rb
- test/test_output.rb
Continued from https://github.com/fluent/fluentd/pull/468
> fix to flush a buffer by USR1 signal on retrying

- lib/fluent/parser.rb
- test/test_parser.rb
Some hardwares such as LoadBalancer access to http servers without http-version in Request-Line. It's like following:
```
$ telnet localhost 80
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET /index.html
```
The access generates a log for Nginx and Apach2 servers.
```
127.0.0.1 - - [10/Jan/2015:17:52:50 +0900] "GET /index.html" 200 612 "-" "-"
127.0.0.1 - - [10/Jan/2015:19:17:08 +0900] "GET /index.html" 200 11510 "-" "-"
```
Embedded parser format for Nginx and Aapach2 cannot parse these logs. This request fixes the regexps to parse correctly.
> Fix Nginx and Apache2 format to parse access log without http-version

- lib/fluent/plugin/file_util.rb
- lib/fluent/plugin/in_debug_agent.rb
- lib/fluent/plugin/out_file.rb
- test/plugin/test_file_util.rb
- test/plugin/test_in_debug_agent.rb
- test/plugin/test_out_file.rb
`--config-test` is very useful, but it does not check file permission. This proposition is to make a rule to check file permissions in #configure method of each plugin because I thought it is impossible to check file permissions for each configuration parameter of each plugin from Fluentd side (Fluentd can not know what each plugin wants to do)
This pull request is just the first example of the proposition.
@repeatedly What do you think? Yes, each plugin author should support file permission check in #configure method of each plugin when we decide as this is an official way. 
PS. @repeatedly Could you tell me if you have a right place to put the file permission check utility function?
> add file writable check in #configure

- lib/fluent/command/bundler_injection.rb
Hello.
In environment with embedded ruby, such as td-agent, the `--gemfile` option may be unavailable.
It will be caused by `bundler_injection.rb` trying to exec system's `bundle` command.
This PR is going to make it find `bundle` from current ruby's gems.
If this looks good to merge, there are two questions.
1. I couldn't find tests about `bundle_inject.rb`. Should I add it?
2. When it cannot find `bundle` command,  Should I make it will put some error message?
Thank you.
> Fix bundler_injection for environment that has a embedded ruby

- lib/fluent/plugin/in_tail.rb
For example, XFS uses 64bit integer for inode.
in_tail should work on these environments.
See this thread: https://groups.google.com/d/topic/fluentd/YYrshTNGQ8c/discussion
> Support 64bit inode environment in in_tail

- lib/fluent/plugin/in_tail.rb
Enable multiline mode if format contains 'multiline'.
> Enable multiline mode if format contains 'multiline'

- lib/fluent/engine.rb
This is useful for identifying which input / application causes error events.
> Add tag information to emit log

- fluentd.gemspec
See v0.5.11 ChangeLog: https://github.com/msgpack/msgpack-ruby/commit/412d29dbb175903c844d4e97621886c74c893565
> Update msgpack dependency to avoid incompatible encoding problem

- lib/fluent/plugin/out_forward.rb
If the fluentd process of the destination node is not running, `ForwardOutput#send_heartbeat_tcp` throws `Errno::ECONNREFUSED`. If the exception at line 364 was not rescued, it would be excluded from `@nodes.each{}` and fall to send heartbeats to subsequent nodes. For this reason, if the fluentd process of a destination node stops, the fluentd process of the localhost detaches from subsequent nodes.
> Fixed the error handling upon exception at heartbeat with TCP

- lib/fluent/test/output_test.rb
Only MemoryBufferChunk is not good for plugin test.
> BufferedOutputTestDriver must use correct buffer chunk type

- lib/fluent/plugin/filter_record_transformer.rb
- test/plugin/test_filter_record_transformer.rb
@kiyoto @repeatedly 
This patch is to add a feature to support placeholders in record keys for filter_record_transformer, which is requested by @fujiwara cf. https://twitter.com/fujiwara/status/572990626930638848
> record_transformer: support placeholders in record keys

- lib/fluent/plugin/in_tail.rb
- test/plugin/test_in_tail.rb
> 560 - exclude files from tail

- lib/fluent/config/literal_parser.rb
- test/config/test_literal_parser.rb
Writing conf like:
```
<source>
type dummy
tag "#{ENV['HOGE']}foo#{ENV['MOGE']}"
</source>
```
results in a error:
```
/home/sonots/src/github.com/fluent/fluentd/lib/fluent/config/literal_parser.rb:157:in `instance_eval': (eval):1: syntax error, unexpected tSTRING_DEND, expecting end-of-input (SyntaxError)
ENV['HOGE']}foo#{ENV['MOGE']
^
from /home/sonots/src/github.com/fluent/fluentd/lib/fluent/config/literal_parser.rb:157:in `eval_embedded_code'
from /home/sonots/src/github.com/fluent/fluentd/lib/fluent/config/literal_parser.rb:84:in `scan_double_quoted_string'
from /home/sonots/src/github.com/fluent/fluentd/lib/fluent/config/literal_parser.rb:68:in `scan_string'
from /home/sonots/src/github.com/fluent/fluentd/lib/fluent/config/literal_parser.rb:61:in `parse_literal'
from …
```
> literal_parser.rb: fix scan_embeded_code

- lib/fluent/plugin/filter_record_transformer.rb
- test/plugin/test_filter_record_transformer.rb
and any field names in `enable_ruby false`.
fluent-plugin-record-reformer supported the same thing in v0.6.0.
cf. https://groups.google.com/forum/#!topic/fluentd/jFXBZws5mqg
> filter_record_transformer: support fields starting with @

- lib/fluent/output.rb
We were supposed to support `try_flush_interval < 1` and `queue_chunk_flush_interval < 1`, but the interval to call `try_flush` was still minimum 1 sec because `Engine.now` is `Time.now.to_i`. 
Illustration: The problem of the old logic:
```ruby
until @finish
time = Engine.now
if @next_time <= time # (4) have to wait to be 1427488240.1 <= 1427488241
@mutex.unlock
begin
@next_time = @output.try_flush # (1) 1427488240.1
ensure
@mutex.lock
end
next_wait = @next_time - Engine.now # (2) 0.1
else
next_wait = @next_time - time
end
cond_wait(next_wait) if next_wait > 0
end
```
`@next_time` can be like `1427488240.1` when `queued_chunk_flush_interval 0.1`. 
But, `time` exceeds the `@next_time` only when it became `1427488241` (1 sec passed) because `Engine.now` is integer.
> fix try_flush_interval < 1 and queued_chunk_flush_interval < 1 to work

- lib/fluent/config/configure_proxy.rb
- test/config/test_configurable.rb
#582 shows that #571 breaks compatibility of existing 3rd party plugins.
This pull-request does:
* revert #582 at first
* add tests for past behavior
* add `final` option to specify sections not to be overwritten
3rd party plugins should be able to overwrite super-class's behavior. But some should prohibit overwriting by sub classes. Ex: `<buffer>`.
Plugin authors should specify `final: true` for these sections.
> Refix subsection merging rule

- lib/fluent/parser.rb
- test/test_parser.rb
'keys ["key1", "key2"]' works. ',' separated value is also supported.
Related to https://github.com/fluent/fluentd/issues/590
> Parser's keys parameter accept json array configuration.

- lib/fluent/plugin/in_tail.rb
- test/plugin/test_in_tail.rb
Related to https://groups.google.com/forum/#!topic/fluentd/-6Q8pPMU-Kc
back-pressure can't resolve this problem so adding option is better.
This limit is rough so the number of emit records succeeds `read_lines_limit`.
For example, set 100 but the number of emit records becomes 105. It depends on line length of log.
Edit: Change parameter name to read_lines_limit
> Add read_lines_limit parameter to control chunk size in in_tail

- lib/fluent/plugin/file_util.rb
- lib/fluent/plugin/out_file.rb
- test/plugin/test_file_util.rb
- test/plugin/test_out_file.rb
Fix #594
Added FileUtil.writable_p?. Also, fixed FileUtil.writable? to be more strict.
> Fix out_file can create directory recursively

- lib/fluent/config/types.rb
- test/config/test_configurable.rb
Type `enum` is to:
* handle symbols only for values
* require `list: [symbols]` parameter, which specifies the list of valid options
* raises `Fluent::ConfigError` if specified value in configuration file
> Add config_param type `enum` and its tests, Fix #599

- lib/fluent/config/element.rb
- lib/fluent/configurable.rb
- lib/fluent/engine.rb
- test/config/test_configurable.rb
- test/helper.rb
We sometimes got this feature request.
If plugins add `:secret => true` in `config_param`, the values are masked with `xxxxxx` like below.
```
2015-05-29 19:50:10 +0900 [info]: using configuration file: <ROOT>
<source>
type http
port 8080
format csv
</source>
<match http.**>
type copy
deep_copy xxxxxx # for test. deep_copy is not secret
<store>
type stdout
output_type hash
</store>
</match>
</ROOT>
```
This changes two existing behaviours.
- in_monitor_agent returns masked configuration.
- Log order is changed during fluentd startup. Before: config dump -> register. After: register -> config dump
From my experience, these changes are no problem.
> Add secret option

- lib/fluent/command/cat.rb
Input plugins accept `format none` since #182 but fluent-cat doesn't yet. The tiny patch allows fluent-cat accept it.
```sh
echo "a plain text message" | fluent-cat --none debug
echo "another plain text message" | fluent-cat --format none --message-key message debug
```
The structured raw logs comes here again! I rarely agree for fluent-cat to accept rest of all formats as it should be kept simple and light weighted as it were. I guess, however, that the plain text format is enough convenient for plain simple usages expected for fluent-cat. 
The optional `--message-key` parameter could be removed to keep it simple.
It seems that `-f message` or `-f plain` could be more clear rather than `-f none` at this usage above, by the way. It should follow the vocabulary at `format` parameter at …
> fluent-cat --format none added

- lib/fluent/formatter.rb
when i use `out_copy` plugin to copy events to multiple outputs, I found out that even when I set the `deep_copy` to be true, original data would still  be modified.
The reason for such behavior is that when use `<<` to append new_line code to text, original record would also be modified.
So in order to keep original record unmodified, duplicate is need.
> Fix SingleValueFormatter to prevent record from modified

- lib/fluent/plugin/filter_record_transformer.rb
- test/plugin/test_filter_record_transformer.rb
fluent-plugin-record-reformer 0.7.0 has a new configuration "auto_typecast" to inherit type of record values if it is originated from the source record. The configuration should be imported from the plugin. This will fix #619. See also: https://github.com/sonots/fluent-plugin-record-reformer/pull/26
> Import "auto_typecast" to filter_record_transformer from fluent-plugin-record-reformer 0.7.0

- example/in_forward.conf
- example/out_forward.conf
- lib/fluent/load.rb
- lib/fluent/plugin/out_forward.rb
I want to support DNS round robin.
Ruby's `Socket.pack_sockaddr_in` or `Resolv.getaddress` or `IPSocket.getaddress`, and so on does not support DNS round robin. To do it, we have to `Resolv.getaddresses(hostname).shuffle!.first`. 
This code still works on non dns round robin environment, so I did not add any new options. 
EDIT: Writing tests is difficult because we need to set up a DNS round robin environment, but existing tests passed, and I verified this works manually.
> out_forward: Support dns round robin

- lib/fluent/plugin/out_stdout.rb
- test/plugin/test_out_stdout.rb
Make `output_type` option of `out_stdout` accept not only `json` or `hash` but also any other formatter plugin.
> Support formatter plugins in out_stdout

- lib/fluent/plugin/out_forward.rb
- test/plugin/test_out_forward.rb
Added an option to disable the heartbeat. 
Using another round robin system such as [DNS round robin](https://github.com/fluent/fluentd/pull/625), HAProxy, or something, we typically want to do health check with another system. 
BTW: This is a kind of porting from [fluent-plugin-keep-forward](https://github.com/sonots/fluent-plugin-keep-forward)
> out_forward: heartbeat_type none

- lib/fluent/config/element.rb
- lib/fluent/config/section.rb
- lib/fluent/configurable.rb
- test/config/test_configurable.rb
Currently, config_section's secret is ignored.
@sonots Could you test this with your large configuration file? This increases memory usage.
> Fix secret option to support config_section

- lib/fluent/config/v1_parser.rb
- lib/fluent/log.rb
Forgot to add `@` :crying_cat_face:
> Add '@' to log_level. Keep log_level for backward compatibility

- lib/fluent/config/element.rb
- lib/fluent/config/section.rb
- lib/fluent/configurable.rb
- lib/fluent/engine.rb
- lib/fluent/plugin.rb
- test/config/test_configurable.rb
@tagomoris Could you check this?
> Log unused section configuration as warn level

- lib/fluent/config/section.rb
- lib/fluent/plugin/out_forward.rb
- test/plugin/test_out_forward.rb
See https://github.com/fluent/fluentd/pull/631. I added `dns_round_robin` option to prevent using dns round robin with udp heartbeat.
> dns_round_robin option

- lib/fluent/parser.rb
- test/test_parser.rb
RegexpParser does not have `time_key` option currently, but it is useful if it has it. 
EDIT: `time_key` option is useful in two aspects:
１. We add `keep_time_key` option at https://github.com/fluent/fluentd/pull/587. However, without `time_key` option for RegexpParser, we still have to write a conf as follows when we need to change the time field name from `time` to `logtime` (or anything). 
```apache
<source>
type tail
format /^\[(?<time>[^\]]*)\]$/
tag accesslog
</source>
<filter accesslog>
type record_transformer
enable_ruby true
<record>
logtime ${time.to_i}
</record>
</filter>
<filter accesslog>
type typecast
types logtime:integer
</filter>
<match accesslog>
type stdout
#=> {"logtime":123456789}
</match>
```
By adding `time_key` option, this conf becomes as follows, which is pretty …
> Add time_key option for RegexpParser

- lib/fluent/output.rb
Current TimeSlicedOutput#emit emits records to buffer one by one.
It causes inconsistent state when queue has a problem.
For example, some records are stored into buffers and
raises BufferQueueLimitError. In this situation,
logs are duplicated if input plugin retries.
BufferedOutput and ObjectBufferedOutput uses another way.
These outputs format all records into data chunk first.
New behaviour is more safer than current TimeSlicedOutput way.
@sonots @tagomoris Could you check this patch? It increases temporary memory usage but current behaviour should be fixed.
> Modify TimeSlicedOutput#emit mechanizm to fit BufferedOutput#emit way

- fluentd.gemspec
Currently, fluentd's license is displayed N/A in rubygems.org.
ref: http://spdx.org/licenses/
> Add missing license in gemspec

- lib/fluent/output.rb
> Remove unnecessary method call

- lib/fluent/parser.rb
MultilineParser passes own Config::Element to RegexpParser.
RegexpParser should not re-wrap such configuration.
> RegexpParser#initialize should wrap only Hash conf by Config::Element. fix #646

- lib/fluent/parser.rb
- lib/fluent/plugin/filter_grep.rb
- lib/fluent/plugin/string_util.rb
- test/test_parser.rb
Hello.
Cannot express NULL in LTSV.
ltsv library for Ruby blank to NULL.
https://github.com/condor/ltsv/blob/master/lib/ltsv.rb#L97
I use LTSV with apache.
Apache log is If value not exists with hyphen('-').
I think hyphens to null, any of the following methods.
1. LabeledTSVParser add parameter with @null_value
※this PR
settings example.
```
<source>
type tail
path /var/log/httpd/access_log
format ltsv
time_key time
null_value -
time_format %d/%b/%Y:%H:%M:%S %z
tag td.apache.access
pos_file /var/log/td-agent/apache_access.pos
</source>
```
2. specifications similar to the Ruby library(blank to null)
3. Make your own filter plugin.
Which one is good?
> Add null_value_pattern and null_empty_string option for LabeledTSVParser, CSVParser, TSVParser.

- lib/fluent/rpc.rb
- lib/fluent/supervisor.rb
Related to #633.
Add `<endpoint>/api/config.dump` to RPC.
e.g)
example conf:
```conf
<source>
type http
bind 0.0.0.0
port 9880
body_size_limit 32MB
keepalive_timeout 10
add_http_headers false
format default
</source>
<match test>
type stdout
</match>
<system>
rpc_endpoint 127.0.0.1:9000
</system>
```
```bash
$ curl http://127.0.0.1:9000//api/config.dump
{"ok":true}
```
then, got:
```log
2015-08-28 15:45:28 +0900 [info]: dump in-memory config
2015-08-28 15:45:28 +0900 [info]: <ROOT>
<source>
type http
bind 0.0.0.0
port 9880
body_size_limit 32MB
keepalive_timeout 10
add_http_headers false
format default
</source>
<match test>
type stdout
</match>
<system>
rpc_endpoint 127.0.0.1:9000
</system>
</ROOT>
```
```bash
$ curl http://127.0.0.1:9000/api/config.getDump
{"conf":"<ROOT>\n  <source>\n …
```
> Implement RPC to dump in memory config

- lib/fluent/plugin/in_http.rb
- test/plugin/test_in_http.rb
This small patch solve bulk request parsing. Previously the code tried to insert a string into a list
which caused "no implicit conversion of String into Integer".
> Fix add_remote_addr and add_http_headers options not working on bulk request

- lib/fluent/config/configure_proxy.rb
- lib/fluent/configurable.rb
- lib/fluent/plugin/in_dummy.rb
- test/config/test_configure_proxy.rb
We can write long description easily.
> Improve describing plugin parameters

- lib/fluent/plugin/filter_record_transformer.rb
@sonots please check this patch.
> Don't use popular name to prevent field overwrite when enable_ruby is true

- lib/fluent/plugin/in_monitor_agent.rb
Here is test logs.
```
% RUBYLIB=~/dev/fluentd/fluentd/lib fluentd -v -c monitor_agent.conf                                                                        (git)-[master]
2015-09-04 21:27:41 +0900 [info]: fluent/supervisor.rb:403:read_config: reading config file path="monitor_agent.conf"
2015-09-04 21:27:41 +0900 [info]: fluent/supervisor.rb:279:supervise: starting fluentd-0.12.15
2015-09-04 21:27:41 +0900 [info]: fluent/engine.rb:100:block in configure: gem 'fluent-mixin-config-placeholders' version '0.3.0'
2015-09-04 21:27:41 +0900 [info]: fluent/engine.rb:100:block in configure: gem 'fluent-plugin-s3' version '0.5.10'
2015-09-04 21:27:41 +0900 [info]: fluent/engine.rb:100:block in configure: gem 'fluent-plugin-secure-forward' version '0.3.2'
2015-09-04 21:27:41 +0900 [info]: …
```
> in_monitor_agent emits plugins info to use exisiting plugins. fix #667

- lib/fluent/agent.rb
- lib/fluent/root_agent.rb
This helps what the plugin takes time during fluentd shutdown process.
Log example:
```sh
2015-10-27 18:36:52 +0900 [info]: reading config file path="test.conf"
2015-10-27 18:36:52 +0900 [info]: starting fluentd-0.12.16
2015-10-27 18:36:52 +0900 [info]: gem 'fluent-plugin-elasticsearch' version '1.1.0'
2015-10-27 18:36:52 +0900 [info]: gem 'fluentd' version '0.12.16'
2015-10-27 18:36:52 +0900 [info]: adding filter in @FOO pattern="**" type="grep"
2015-10-27 18:36:52 +0900 [info]: adding match in @FOO pattern="foo.**" type="stdout"
2015-10-27 18:36:52 +0900 [info]: adding filter pattern="**" type="record_transformer"
2015-10-27 18:36:52 +0900 [info]: adding match pattern="test.**" type="stdout"
2015-10-27 18:36:52 +0900 [info]: adding source type="forward"
2015-10-27 18:36:52 +0900 [info]: …
```
> Log shutdown plugin info to check shutdown sequence

- lib/fluent/buffer.rb
- lib/fluent/command/cat.rb
- lib/fluent/engine.rb
- lib/fluent/event.rb
- lib/fluent/plugin/buf_memory.rb
- lib/fluent/plugin/exec_util.rb
- lib/fluent/plugin/in_forward.rb
- lib/fluent/plugin/in_http.rb
- lib/fluent/plugin/in_stream.rb
- lib/fluent/plugin/out_stream.rb
- lib/fluent/process.rb
- test/plugin/test_in_forward.rb
- test/plugin/test_in_stream.rb
- test/plugin/test_out_copy.rb
In v0.14, core and plugin use `Engine#msgpack_factory` for creating MessagePack Packer / Unpacker.
For supporting v0.12 and v0.14 in plugin code, providing same API is better.
Related to https://github.com/fluent/fluentd/pull/653
> Add Engine#msgpack_factory for v0.14 compatibility

- lib/fluent/plugin/out_file.rb
I tried to add descriptions in out_file plugin.
Related to #584.
> Add descriptions to out_file plugin parameters

- lib/fluent/plugin/out_forward.rb
- test/plugin/test_out_forward.rb
When no <server> is set to out_forward plugin,
`Fluent::ForwardOutput#rebuild_weight_array` raises ZeroDivisionError
at `coe = (regular_nodes.size * 6) / weight_array.size`. This change
gives more useful error message to uses instead of unfriendly
ZeroDivisionError message.
> out_forward raises ZeroDivisionError when no <server> is available

- lib/fluent/supervisor.rb
Like https://github.com/cubicdaiya/fluent-plugin-setproctitle plugin.
Set `process_name`,
```aconf
<system>
process_name foo
</system>
```
ps result is below.
```
% ps aux | grep foo
repeatedly      45673   0.4  0.2  2523252  38620 s001  S+    7:04AM   0:00.44 worker:foo
repeatedly      45647   0.0  0.1  2481260  23700 s001  S+    7:04AM   0:00.40 supervisor:foo
```
> Add process_name parameter in system to change fluentd's process name

- lib/fluent/test.rb
- lib/fluent/test/parser_test.rb
- test/test_parser.rb
Currently, fluentd does not have `ParserTestDriver`.
This PR adds this test driver.
> Add ParserTestDriver

- lib/fluent/process.rb
In detach processes situation, `emit` may be called simultaneously, or `run` loop may write messagepack stream into pipe for child processes (`@w`).
So operations for `@buffer` should be protected by mutex.
> fix bug not to protect in-memory-buffer for multi thread emitting / run loop

- lib/fluent/log.rb
We can see this via `--show-plugin-config` after merge #706
> Add description to log level

- lib/fluent/plugin/in_forward.rb
Following document does not describe `backlog` and `blocking_timeout`.
See http://docs.fluentd.org/articles/in_forward
> Add descriptions to in_forward

- lib/fluent/plugin/socket_util.rb
See followings:
* http://docs.fluentd.org/articles/in_tcp
* http://docs.fluentd.org/articles/in_udp
I cannot find description for `blocking_timeout`
> Add descriptions to Fluent::SocketUtil::BaseInput

- lib/fluent/process.rb
- test/test_process.rb
I found https://github.com/fluent/fluentd/commit/66e618e6d93ccc2928e378b8b5eb702723797bf7 included a typo and it didn't work. Also, I added an unit test for the event lost issue.
> Fix DelayedForwarder#run and add unit test

- lib/fluent/plugin/in_http.rb
See http://docs.fluentd.org/articles/in_http
I cannot describe some options:
* backlog
* blocking_timeout
* cors_allow_origins
> Add descriptions to in_http

- lib/fluent/plugin/out_exec_filter.rb
See http://docs.fluentd.org/articles/out_rewrite_tag_filter
Above page does not describe following configurations:
* remove_prefix
* add_prefix
* tag
* time_key
* time_format
* localtime
* timezone
* suppress_error_log_interval
> Add descriptions to out_exec_filter plugin

- lib/fluent/plugin/out_forward.rb
See http://docs.fluentd.org/articles/out_forward
I don't describe deprecated configurations.
> Add descriptions to out_forward plugin

- lib/fluent/plugin/in_tail.rb
This is to avoid generating too many error messages from file's watcher
(which runs every second.) Each unreadable file will cause a warning.
If it becomes readable, it would be included in the next turn.
See also `refresh_interval` and #726.
> in_tail: expand_paths exclude unreadable files

- lib/fluent/plugin/in_exec.rb
in_exec plugin with `run_interval` option does not stop immediately when sending shutdown signal.
It waits at most `run_interval` seconds because the process is sleeping and not interrupted.
`Thread#run` interrupts sleep, so this fixes the problem.
> Stop in_exec immediately at shutdown

- lib/fluent/plugin/in_stream.rb
- lib/fluent/plugin/in_syslog.rb
- lib/fluent/plugin/in_tcp.rb
- lib/fluent/plugin/in_udp.rb
I've found the in_forward standard of logging, at startup, where it is
expecting incoming msgs to be very helpful.
> standardize logging level for source configs

- fluentd.gemspec
- lib/fluent/formatter.rb
- lib/fluent/parser.rb
- lib/fluent/test/formatter_test.rb
- lib/fluent/test/parser_test.rb
- test/plugin/test_out_stdout.rb
- test/test_formatter.rb
- test/test_parser.rb
oj is faster json library and it improves `JSONParser` performance.
I tested in_tail with following json.
```js
{"_id":"5671172e7ba230441460f011","index":0,"guid":"3d18838a-ae85-4986-83c7-e4a4acdd7f01","isActive":false,"balance":"$3,929.20","picture":"http://placehold.it/32x32","age":40,"eyeColor":"green","company":"MEDMEX","email":"hardin.sargent@medmex.org","phone":"+1 (865) 468-2885","address":"302 Buffalo Avenue, Bend, Louisiana, 635","latitude":"89.385551","longitude":"75.132185","greeting":"Hello, Hardin! You have 5 unread messages.","favoriteFruit":"banana"}
```
Result is
- Yajl
```
2015-12-16 18:23:37 +0900 [info]: following tail of /Users/repeatedly/tmp/fluentd/json.log
2015-12-16 18:23:38 +0900 [info]: plugin:out_flowcounter_simple count:2003      indicator:num   unit:second …
```
> Use 'oj' for performance improvement when oj is installed

- lib/fluent/buffer.rb
- test/test_buffer.rb
https://groups.google.com/forum/#!topic/fluentd/JWlpijPrsqI
Suggestion from Micheal on the above thread.
`block` action is sometimes dangerous because it causes log lost so default action is still `exception`.
I commented implementation note in the code.
Should we add `drop_last` action to drop events for non-important destination?
> Add 'buffer_queue_full_action'  parameter to control buffer actions

- lib/fluent/process.rb
Hi,
I wonder how to call `shutdown` method before the child process exits when I use `detach_process` because I'd like to shutdown my plugin properly.
After looking the code, I hope this hook point just before `exit!`. Then I can call any logic before exiting like below:
```
def on_exit_process(i)
shutdown
end
```
Is there any better way to do this?
Best,
> Add on_exit_process(i) hook point

- test/test_buffer.rb
Because Object#timeout has been deprecated since Ruby 2.3.0.
> Use `Timeout.timeout` instead of `Object#timeout`

- lib/fluent/output.rb
I cannot find description for `:try_flush_interval`.
See http://docs.fluentd.org/articles/output-plugin-overview
> Add descriptions to BufferedOutput

- lib/fluent/config/element.rb
Related to #629 and original reported is https://github.com/treasure-data/omnibus-td-agent/issues/61
Added following copy match to above 629 issue config.
```aconf
<match copy_test>
@type copy
<store>
@type stdout
foo bar
</store>
<test>
param v
</test>
</match>
```
Current:
```
2016-01-04 18:07:50 +0900 [warn]: section <foo> is not used in <user> of secure_forward plugin
2016-01-04 18:07:50 +0900 [warn]: section <test> is not used in <source> of secure_forward plugin
2016-01-04 18:07:50 +0900 [warn]: section <test> is not used in <match debug.**>
2016-01-04 18:07:50 +0900 [warn]: section <fil> is not used in <ROOT>
2016-01-04 18:07:50 +0900 [warn]: section <store> is not used in <match copy_test> of copy plugin
2016-01-04 18:07:50 +0900 [warn]: section <test> is not used in <match …
```
> Fix the regression of unused parameter warning inside sub section

- .travis.yml
But for now, Ruby 2.3.0 is specified in allow failure.
> Try to use Ruby 2.3.0 in Travis

- lib/fluent/test/input_test.rb
- lib/fluent/test/output_test.rb
I want to control wait period of d.run in input and output test driver. 
Please see what I am doing every time > https://github.com/sonots/fluent-plugin-grep/blob/master/test/helper.rb. I want to drop this monkey patch.
> Enable to control wait period of d.run in input and output test driver

- lib/fluent/plugin/filter_record_transformer.rb
- test/plugin/test_filter_record_transformer.rb
revised ruby placeholder expander with 3x faster implementation
see benchmark https://gist.github.com/sonots/a1948ed576019653daa5
```
```
The new ruby placeholder expander keeps backward compatibility and supports `record["key"]` placeholder newly. Also, `enable_ruby false` expander newly supports `record["key"]` placeholder.
> record_transformer: faster implementation of ruby placeholder expander

- lib/fluent/output.rb
- lib/fluent/test/base.rb
- test/test_output.rb
Currently, TimeSlicedOutput#emit raises an exeception when one event is invalid.
If one event in event stream has a problem, it should be treated as an error event instead of entire error.
Input plugins hard to handle such error because input plugins don't know how to recover invalid event.
So send it to error stream is better.
> Use error stream in TimeSlicedOutput#emit

- lib/fluent/configurable.rb
- lib/fluent/engine.rb
- lib/fluent/root_agent.rb
- lib/fluent/supervisor.rb
- lib/fluent/system_config.rb
- lib/fluent/test/base.rb
- test/config/test_system_config.rb
- test/test_root_agent.rb
to pass system configuration to plugins
* v0.14 feature: new Plugin API expects these configuration parameters to system config
* plugin storage path
* default file/directory permissions
* many others
> Separate system config object from supervisor

- lib/fluent/plugin/in_tail.rb
As discussed in https://groups.google.com/forum/#!topic/fluentd/BBRde4Lyl9E
> in_tail: avoid unnecessary open()s

- lib/fluent/plugin/in_monitor_agent.rb
Top level fields has config field so instance_variables don't need to
include config related values.
> Remove unnecessary fields from API response with debug mode. fix #793

- lib/fluent/configurable.rb
- lib/fluent/engine.rb
- lib/fluent/root_agent.rb
- lib/fluent/supervisor.rb
- lib/fluent/system_config.rb
- lib/fluent/test/base.rb
- test/config/test_system_config.rb
- test/test_root_agent.rb
Cherry-picked this merge commit:
```
Merge pull request #794 from fluent/separate-system-config
Separate system config object from supervisor
```
> Back port separate system config object from supervisor(#794)

- bin/fluent-cat
- bin/fluent-debug
- bin/fluent-gem
- bin/fluentd
- lib/fluent/command/bundler_injection.rb
- lib/fluent/engine.rb
- lib/fluent/plugin.rb
- lib/fluent/registry.rb
Recent Ruby loads rubygems automatically, since Ruby 1.9.
> Don't require rubygems

- lib/fluent/plugin/in_tail.rb
- test/plugin/test_in_tail.rb
The enable_watch_timer option was discussed in:
https://groups.google.com/forum/#!topic/fluentd/BBRde4Lyl9E
Setting this parameter to `false` will significantly reduce CPU and I/O consumption when tailing a large number of files on systems with inotify support.
Corresponding PR for documentation changes: https://github.com/fluent/fluentd-docs/pull/215
> Added enable_watch_timer option

- lib/fluent/plugin/filter_record_transformer.rb
- test/plugin/test_filter_record_transformer.rb
Same thing with https://github.com/sonots/fluent-plugin-record-reformer/pull/36
> filter_record_transformer: Relax conditions which auto_typecast is applied for enable_ruby yes

- lib/fluent/plugin/in_tail.rb
- test/plugin/test_in_tail.rb
Based on #700. Update patch and rebase to master.
> Fix in_tail input messages loss when receive_lines fail. fix #699

- lib/fluent/config/types.rb
- test/config/test_types.rb
> Enum list must be of symbols

- lib/fluent/output.rb
fluent/output uses fluent/status.
> Add missing require

- lib/fluent/plugin/in_http.rb
- test/plugin/test_in_http.rb
* In RFC 7230, content length header is described as [Content-**L**ength](http://tools.ietf.org/html/rfc7230#section-3.3.2).
* In RFC 7231, content type header is described as [Content-**T**ype](http://tools.ietf.org/html/rfc7231#section-3.1.1.5).
Note that `Content-type` is already corrected into `Content-Type` in internally by Net::HTTP: https://github.com/ruby/ruby/blob/5728783a0458357105c1943a4b0a9e04c1879a04/lib/net/http/header.rb#L171.
So, this change is only code appearance.
> In http: Use RFC suggested character cases of HTTP response header

- lib/fluent/config/section.rb
- test/config/test_configurable.rb
- test/config/test_types.rb
This problem makes bad effect especially for instantiated/configured twice or more in a process.
The most visible case is testing, but it might affect configuration reloaded with `HUP` signals.
> fix to dup default values to make it safe if plugins modify provided values

- lib/fluent/config.rb
- lib/fluent/filter.rb
- lib/fluent/input.rb
- lib/fluent/output.rb
- lib/fluent/plugin_id.rb
* simply speaking, it's wrong file to write it
* added a feature to check whether id is intentionally set by user or not
* it's important to check whether we can create many thing depends on id or not
* for example, id-based auto generated buffer path, and plugin storage on local filesystem
> separate PluginId module from config.rb

- Rakefile
In Rake 11.0.1 or later, `t.warning = true` is by default. This behavior had been introduced in https://github.com/ruby/rake/pull/97.
Should we suppress warnings from the new rake?
Or should we resolve warnings in Fluentd side?
IMO, concealing warnings is not good for Fluend. It reports potential problem which should be fixed in the future.
> Rakefile: Suppress warnings from ruby, enabled by rake 11

- lib/fluent/plugin/in_http.rb
- test/plugin/test_in_http.rb
This PR contains imported patch which are from https://github.com/fluent/fluentd/commit/4ebce91bdaa2fbc8ca61fafe38256ef731b6bcbc partially and https://github.com/fluent/fluentd/commit/67f9825853a692d99075e9e67d0a87272f4a19ed.
Note that this imported patch is rewritten to adopt without new v0.14 API and with current master.
Related to this developers TODO:
> * in_http test fix to check HTTP keepalive is enabled explicitly
https://github.com/fluent/fluentd/commit/67f9825853a692d99075e9e67d0a87272f4a19ed
ref: https://github.com/fluent/fluentd/wiki/Developer-notes-for-fixes-on-v0.14#plugin-miscellaneous
> in_http: Fix to check keepalive enabled explicitly

- lib/fluent/command/fluentd.rb
* If --reg-winsvc-auto-start is specified when installing the service (--reg-winsvc i), set the service type to AUTO_START rather than DEMAND_START, and also start the service immediately.
* When uninstalling (--reg-winsvc u), attempt to stop the service if it is running.  This is done unconditionally.
* Also allow --reg-winsvc-fluentdopt to be specified along with --reg-winsvc; previously the options would be ignored.  The flag can still be specified alone to change the options (although a service restart is necessary).
> Enhancements to Windows service install/uninstall.

- lib/fluent/plugin/socket_util.rb
Otherwise, I get `NameError: uninitialized constant Fluent::Input` error when I execute `bundle exec ruby test/plugin/test_out_forward.rb`.
> socket_util: Add missing require

- lib/fluent/event_router.rb
- lib/fluent/output.rb
* `Filter` constant is used in `event_router`.
* `Output` class should know filter registry with `require 'filter'`.
> Add missing requires

- lib/fluent/config/configure_proxy.rb
- test/config/test_configurable.rb
* overwriting config_section options like required/multi/alias breaks
behavior of `super`
* so subclass must not overwrite these options
* subsection definitions of subsections (Hash) is simply merged
* it is bug, because same section definition like <a> is overwritten by
subclass
* under this bug, subclass MUST repeat superclass's definition, and add
original definition
* but this is impossible in the real world
* subsection definitions should be merged correctly
> Fix overwrite subsection

- lib/fluent/log.rb
- lib/fluent/plugin.rb
- lib/fluent/plugin/base.rb
- lib/fluent/plugin_helper.rb
- lib/fluent/plugin_helper/child_process.rb
- lib/fluent/plugin_helper/event_emitter.rb
- lib/fluent/plugin_helper/event_loop.rb
- lib/fluent/plugin_helper/thread.rb
- lib/fluent/plugin_helper/timer.rb
- lib/fluent/test/base.rb
- test/plugin_helper/test_child_process.rb
- test/plugin_helper/test_event_emitter.rb
- test/plugin_helper/test_event_loop.rb
- test/plugin_helper/test_thread.rb
- test/plugin_helper/test_timer.rb
- test/test_input.rb
- test/test_plugin_helper.rb
PluginHelper provides utilities to write plugins:
* high level methods to hide underlying features and options (e.g., threads, cool.io, ...)
* pre-configured suite nice to use in plugin code (e.g., threads marked as abort_on_exception in default)
* well organized test driver integration (in future): test code runs after threads start to run correctly (no more sleeps in test code!)
And change Fluent::Plugin from class to module (because it can't be instantiated) and add Fluent::Plugin::Base class as a base class of all plugins, to define methods for plugin life cycles which are used from plugin helpers.
> add new Plugin::Base class and PluginHelper modules

- appveyor.yml
- test/plugin_helper/test_child_process.rb
* http://help.appveyor.com/discussions/problems/4371-builds-dont-finish-for-a-long-time-after-all-tests-finished
* http://www.appveyor.com/docs/how-to/rdp-to-build-worker
> Fix tests to exit correctly/immediately after tests finished

- lib/fluent/config/element.rb
- test/config/test_config_parser.rb
- test/config/test_configurable.rb
string as following
In previous version:
string_param1 string_value
string_param2 string
value
In this version:
string_param1 "string_value"
string_param2 "string\nvalue"
I don't change serialization format for other types.
See #522
> Change serialization syntax

- lib/fluent/env.rb
- lib/fluent/plugin/buf_file.rb
- lib/fluent/plugin/in_forward.rb
- lib/fluent/plugin/in_tail.rb
- lib/fluent/plugin/out_file.rb
- lib/fluent/plugin/out_forward.rb
- lib/fluent/plugin/out_stream.rb
- lib/fluent/system_config.rb
- test/config/test_system_config.rb
- test/plugin/test_buf_file.rb
- test/plugin/test_in_tail.rb
- test/plugin/test_out_file.rb
I've implemented to override default variables with system config mechanism.
This PR is related to this developer task: make process global constants obsoleve in fluent/env
ref: https://github.com/fluent/fluentd/wiki/Developer-notes-for-fixes-on-v0.14#plugin-miscellaneous
- ~~Where is suitable place to put into obsoleted variables? Or, leave them as-is is enough?~~ Solved.
> Override default variables with SystemConfig

- lib/fluent/engine.rb
- lib/fluent/msgpack_factory.rb
* to make it available from many classes without loading whole Engine
* Many classes/plugins requires accessibility for msgpack_factory to handle Fluent::EventTime
* but Engine is too big to load every time (especially in tests)
* This patch make it possible to use msgpack_factory from anywhere using Mixin
* and fetched msgpack_factory is the same instance for Engine after Engine.init
* to make it possible to use other ext types registered via Engine
* There're another methods to create factory instances without Engine effects
* it should be required especially for tests
> Separate msgpack_factory from Engine to a file

- lib/fluent/config/configure_proxy.rb
- lib/fluent/config/section.rb
- test/config/test_configurable.rb
- test/config/test_configure_proxy.rb
> Add `config_section` option `init` to initialize section objects

- lib/fluent/config/types.rb
- test/config/test_types.rb
* to specify values with very simple comma (and colon for key-value separator)
* to re-format values because comma-separated values doesn't have type information
It looks to satisfy various use-cases of 3rd party plugins, and this change is just additional
change to allow format which is currently denied as ConfigError.
> Add simplified syntax for hash and array

- lib/fluent/log.rb
If users use following config:
```log
<source>
type forward
@id hoge
log_level debug
</source>
<match test>
type stdout
@id test
log_level debug
</match>
```
Fluentd outputs following log which includes optional headers:
```log
2016-03-18 14:00:55 +0900 [info]: fluent/supervisor.rb:518:read_config: reading config file path="example/in_forward.conf"
2016-03-18 14:00:55 +0900 [info]: fluent/supervisor.rb:351:supervise: starting fluentd-0.14.0.pre.1
2016-03-18 14:00:55 +0900 [info]: fluent/engine.rb:117:block in configure: gem 'fluentd' version '0.14.0.pre.1'
2016-03-18 14:00:55 +0900 [info]: fluent/agent.rb:128:add_match: adding match pattern="test" type="stdout"
2016-03-18 14:00:55 +0900 [info]: fluent/root_agent.rb:147:add_source: [Fluent::StdoutOutput(test)] adding source …
```
> Append plugin name and id to log

- lib/fluent/plugin/in_http.rb
- test/plugin/test_in_http.rb
According to the document
https://en.wikipedia.org/wiki/Cross-origin_resource_sharing
The server should respond with 'Access-Control-Allow-Origin' header
in its response indicating which origin sites are allowed.
> Add 'Access-Control-Allow-Origin' to in_http plugin

- lib/fluent/command/debug.rb
`Fluent::Engine.init` should be passed `system_config` in `Fluent::SystemConfig::Mixin`.
> fluent-debug: Fix broken fluent-debug command

- lib/fluent/command/debug.rb
This PR is back porting following PR:
```
Merge pull request #891 from cosmo0920/fix-broken-fluent-debug-command
fluent-debug: Fix broken fluent-debug command
```
> backport Fix broken fluent-debug command(#891) to v0.12

- appveyor.yml
Recently, AppVeyor deployed Ruby 2.3 in worker VMs, it causes DevKit installation path change.
ref: https://github.com/appveyor/ci/issues/747#issuecomment-209222264
> appveyor: Follow Devkit installation path change

- lib/fluent/log.rb
PluginLoggerMixin did overwrite `optional_header` and `optional_attrs` of `@log`, and `@log`(PluginLogger instance) did overwrite `optional_*` of `@logger`.
But `@logger` is always equal to `$log`. So this code overwrites `optional_*` of global default logger always. It's a bug.
This patch will fix this problem by cloning Logger object always to create PluginLogger.
> fix not to overwrite optional headers/attrs of global logger

- lib/fluent/agent.rb
- lib/fluent/engine.rb
- lib/fluent/log.rb
- lib/fluent/output.rb
- lib/fluent/plugin/filter_grep.rb
- lib/fluent/plugin/filter_record_transformer.rb
- lib/fluent/plugin/in_exec.rb
- lib/fluent/plugin/in_forward.rb
- lib/fluent/plugin/in_object_space.rb
- lib/fluent/plugin/in_syslog.rb
- lib/fluent/plugin/out_exec_filter.rb
- lib/fluent/plugin/socket_util.rb
- lib/fluent/plugin/storage_local.rb
- lib/fluent/plugin_helper/child_process.rb
- lib/fluent/plugin_helper/storage.rb
- lib/fluent/plugin_helper/thread.rb
- lib/fluent/plugin_helper/timer.rb
- lib/fluent/root_agent.rb
In these days, many plugin authors (and core developers) writes logging code like below many times.
```ruby
log.error "my message", error_class: e.class, error: e.to_s, other: attributes
```
Fairly speaking, this is waste of time and key typing.
Fluentd will log errors like below with this change by just specifying `error: e`:
```ruby
log.error "my message", error: e
```
> Logger dumps error with classname

- lib/fluent/plugin/in_tail.rb
- test/plugin/test_in_tail.rb
Currently, ``in_tail`` plugin emits strings with ASCII-8BIT encoding, which is resulted from IO#readpartial. This behavior entails inconvenience when filtering records. For example:
- [What do we write regex at filter-grep in Japanease? / Fluentd Google Group](https://groups.google.com/forum/#!topic/fluentd/0AxzJu2SMS4)
This PR adds ``encoding`` parameter to in_tail plugin, leaving ASCII-8BIT as default for compatibility.
> Add "encoding" parameter to in_tail plugin

- lib/fluent/agent.rb
- lib/fluent/config/configure_proxy.rb
- lib/fluent/config/types.rb
- lib/fluent/configurable.rb
- lib/fluent/engine.rb
- lib/fluent/event.rb
- lib/fluent/filter.rb
- lib/fluent/label.rb
- lib/fluent/output.rb
- lib/fluent/root_agent.rb
- test/config/test_configure_proxy.rb
- test/test_root_agent.rb
This change suppresses following warnings(about 130 lines warnings):
lib/fluent/config/configure_proxy.rb:17: warning: loading in progress, circular require considered harmful
lib/fluent/config/types.rb:20: warning: loading in progress, circular require considered harmful
lib/fluent/event.rb:17: warning: loading in progress, circular require considered harmful
lib/fluent/filter.rb:19: warning: loading in progress, circular require considered harmful
lib/fluent/agent.rb:18: warning: loading in progress, circular require considered harmful
lib/fluent/output.rb:21: warning: loading in progress, circular require considered harmful
lib/fluent/root_agent.rb:21: warning: loading in progress, circular require considered harmful
> Remove redundant `require`

- lib/fluent/plugin/string_util.rb
- test/plugin/test_string_util.rb
Hello.
fix bug. related #657
> I found that log is not defined in Fluent::StringUtil.match_regexp. So this rescue block will raise NameError every time.
> Fix logger on Fluent::StringUtil to use $log.

- lib/fluent/event.rb
- lib/fluent/plugin/buffer.rb
- lib/fluent/plugin/buffer/chunk.rb
- lib/fluent/plugin/buffer/file_chunk.rb
- lib/fluent/plugin/buffer/memory_chunk.rb
- lib/fluent/plugin/output.rb
- test/plugin/test_buffer.rb
- test/plugin/test_buffer_file_chunk.rb
- test/plugin/test_buffer_memory_chunk.rb
- test/plugin/test_output.rb
- test/plugin/test_output_as_buffered.rb
- test/plugin/test_output_as_buffered_retries.rb
- test/plugin/test_output_as_buffered_secondary.rb
- test/plugin/test_output_as_standard.rb
- test/test_event.rb
This change is to add formatting for buffer chunks. Output without explicit `#format` definition will use this standard format to write event streams to buffer chunks, and actually, it's same with `EventStream.to_msgpack_stream`.
At the same time, this change moves a method to iterate events from chunks to `event.rb` as mixin. It's about event streams, not chunk itself.
> Add standard chunking format

- lib/fluent/test/output_test.rb
- test/plugin/test_out_file.rb
TimeSlicedOutputTestDriver is not used in tests of FileOutput plugin. It's unexpected and should not be continued from now on.
But TimeSlicedOutputTestDriver has a bug not to call `Chunk#enqueued!` and `Chunk#purge`, and it makes tests to reuse `b` buffer chunks in tests.
Both are fixed in this change.
> Fix test for TimeSlicedOutput

- lib/fluent/event.rb
- lib/fluent/plugin/buffer.rb
- lib/fluent/plugin/buffer/chunk.rb
- lib/fluent/plugin/buffer/file_chunk.rb
- lib/fluent/plugin/buffer/memory_chunk.rb
- lib/fluent/plugin/output.rb
- test/plugin/test_buf_file2.rb
- test/plugin/test_buffer.rb
- test/plugin/test_buffer_chunk.rb
- test/plugin/test_buffer_file_chunk.rb
- test/plugin/test_buffer_memory_chunk.rb
- test/plugin/test_output_as_buffered.rb
- test/plugin/test_output_as_standard.rb
in EventStream and Chunk.
But I leave a parameter name of `chunk_records_limit` because I think it's understandable for users, and `queued_records` and some other names of implementation / internal APIs.
In v0.12, `Chunk#size` means bytes of chunk content. So I'll add a mixin to extend chunks to return bytes of chunk content by `#size`, and apply it to chunks on compatibility layers.
> Rename number of events

- lib/fluent/output.rb
- lib/fluent/plugin/out_forward.rb
- lib/fluent/test/output_test.rb
- test/plugin/test_out_forward.rb
This change is to use BufferedOutputTestDriver in `test_out_forward`.
I added some fixes in this change. These are related with each other.
* ForwardOutput plugin will raise an error for missing ACK, but it's not defined in [the patch](https://github.com/fluent/fluentd/pull/580)
* It was missed because 
* ObjectBufferedOutput does NOT have `#format_stream` and doing it in `#emit` directly
* BufferedOutputTestDriver does NOT call `#emit`, and use `#format_stream` and `chunk << data` directly
* BufferedOutputTestDriver and TimeSlicedOutputTestDriver called `block.call` after chunking events
* It's simply wrong, because `d.emit` in blocks don't work with such code
* Assigning `Engine` is already outdated
> Fix missing error class and test for out_forward

- fluentd.gemspec
string-scrub 0.1.0 dropped today, and the strict
ruby version constraint stops fluent from being
installed on a modern ruby.
> Fix string-scrub dependency on ruby > 2

- lib/fluent/config/configure_proxy.rb
- lib/fluent/configurable.rb
- test/config/test_configure_proxy.rb
I've changed internal API related to `config_param` and `config_section`.
> Use keyword arguments for `config_param` and `config_section`

- fluentd.gemspec
- lib/fluent/plugin/string_util.rb
We don't need to install string-scrub gem Ruby 2.1 or later.
Because `String#scrub` has been added since Ruby 2.1.
We need explicit `require "string-scrub"` to use `String#scrub` with Ruby 2.0 and Ruby1.9.3.
> Fix string scrub dependency

- lib/fluent/config/basic_parser.rb
- lib/fluent/config/literal_parser.rb
- lib/fluent/config/v1_parser.rb
- test/config/test_config_parser.rb
- test/config/test_literal_parser.rb
Support multiline string in " quoted string
> [#772]  Support multiline string in " quoted string

- lib/fluent/buffer.rb
- test/test_buffer.rb
- Drop oldest chunk from queue without writing to output when buffer
queue is full
- Add test
> Add support for drop_oldest_chunk when buffer queue is full

- lib/fluent/configurable.rb
- lib/fluent/log.rb
- lib/fluent/plugin/buffer/file_chunk.rb
- lib/fluent/plugin/in_forward.rb
- lib/fluent/plugin/out_forward.rb
- lib/fluent/plugin/owned_by_mixin.rb
- lib/fluent/plugin/socket_util.rb
- lib/fluent/plugin_helper.rb
- lib/fluent/plugin_id.rb
- lib/fluent/process.rb
- lib/fluent/system_config.rb
- test/config/test_system_config.rb
- test/plugin/test_buf_file.rb
- test/plugin/test_buffer.rb
- test/plugin/test_buffer_file_chunk.rb
- test/plugin/test_filter.rb
- test/plugin/test_in_forward.rb
- test/plugin/test_out_forward.rb
- test/plugin/test_output.rb
- test/plugin/test_output_as_buffered.rb
- test/plugin/test_output_as_buffered_retries.rb
- test/plugin/test_output_as_buffered_secondary.rb
- test/plugin/test_output_as_standard.rb
- test/plugin_helper/test_retry_state.rb
- test/plugin_helper/test_storage.rb
- test/plugin_helper/test_thread.rb
In previous version about 2500 lines of warnings.
In this version about 1200 lines of warnings.
Remained warinigs:
* From ServerEngine about 400 lines
* See https://github.com/fluent/serverengine/pull/47
* `Encoding.default_external`, `Encoding.default_internal` about 800 lines
* Some other warnings about 50 lines
> Suppress warnings

- lib/fluent/agent.rb
- lib/fluent/config/element.rb
- lib/fluent/plugin/output.rb
- lib/fluent/plugin_helper/storage.rb
- lib/fluent/root_agent.rb
- lib/fluent/system_config.rb
- test/config/test_element.rb
There are too many `conf.elements.select{|e| e.name == ... }`.
> Add optional arguments to #elements to select specified child elements

- lib/fluent/plugin/in_tail.rb
- test/plugin/test_in_tail.rb
Fix https://github.com/fluent/fluentd/issues/945
> Add tail_path option to in_tail plugin

- test/plugin/test_filter_stdout.rb
> backport: fix assigning an object with unconsistent API

- test/test_log.rb
* `Fluent::Log`
* `Fluent::PluginLogger`
* `Fluent::PluginLoggerMixin`
See #909
> backport: Add test for log related class and module

- lib/fluent/plugin/out_forward.rb
> add error class definition which is used but not defined yet

- test/plugin/test_in_tail.rb
Fix https://github.com/fluent/fluentd/pull/951#issuecomment-219389325
> fix unstable test_in_tail

- lib/fluent/compat/output.rb
- lib/fluent/plugin/buffer.rb
- lib/fluent/plugin/buffer/chunk.rb
- lib/fluent/plugin/buffer/file_chunk.rb
- lib/fluent/plugin/buffer/memory_chunk.rb
- lib/fluent/plugin/output.rb
- test/plugin/test_buffer.rb
- test/plugin/test_buffer_chunk.rb
- test/plugin/test_output_as_buffered.rb
- test/plugin/test_output_as_buffered_overflow.rb
- test/plugin/test_output_as_standard.rb
I found that implementing `buffer_queue_full_action` in v0.14 requires change of internal API of Buffer.
This pull-request does:
* merge `Buffer#emit` and `Buffer#emit_bulk` to `Buffer#write`
* fix `Buffer#write` to get a set of metadata and its data (as a hash) to control commit/rollback as a transaction
This change is based on #912
> Support `overflow_action` in v14 api

- lib/fluent/plugin/in_monitor_agent.rb
We want to monitor the health of our output plugins. To do so, we want to compare the current buffer_queue_length with the configured buffer_queue_limit. With the current implementation, in_monitor_agent only emits the first. Adding support for the second.
I could not find any tests for this plugin.
> Add support for emit_config to in_monitor_agent

- lib/fluent/plugin/output.rb
I commented in code comment why this change is needed.
> Fix to use time.to_i for checking when chunks should be flushed

- Rakefile
- lib/fluent/engine.rb
- lib/fluent/supervisor.rb
This change suppresses warning messages about 800 lines on CI.
```
lib/fluent/engine.rb:61: warning: setting Encoding.default_internal
lib/fluent/engine.rb:62: warning: setting Encoding.default_external
(about 400 times repeat)
lib/fluent/engine.rb:61: warning: setting Encoding.default_internal
lib/fluent/engine.rb:62: warning: setting Encoding.default_external
```
> Suppress encoding related warnings

- lib/fluent/engine.rb
- lib/fluent/plugin/in_debug_agent.rb
- lib/fluent/plugin/in_dummy.rb
- lib/fluent/plugin/in_exec.rb
- lib/fluent/plugin/in_forward.rb
- lib/fluent/plugin/in_gc_stat.rb
- lib/fluent/plugin/in_http.rb
- lib/fluent/plugin/in_monitor_agent.rb
- lib/fluent/plugin/in_object_space.rb
- lib/fluent/plugin/in_stream.rb
- lib/fluent/plugin/in_syslog.rb
- lib/fluent/plugin/in_tail.rb
- lib/fluent/plugin/out_copy.rb
- lib/fluent/plugin/out_exec_filter.rb
- lib/fluent/plugin/out_forward.rb
- lib/fluent/plugin/out_null.rb
- lib/fluent/plugin/out_roundrobin.rb
- lib/fluent/plugin/output.rb
- lib/fluent/plugin/socket_util.rb
- lib/fluent/plugin_helper/thread.rb
- lib/fluent/root_agent.rb
- lib/fluent/supervisor.rb
This change includes some changes and bug fixes about lifecycle of process and plugins.
* plugins should call `super` in `start` and `shutdown`
* plugins sometimes raise non-standard errors: these should be rescued and logged
* ServerEngine sends SIGTERM to stop worker process, but it wasn't rescued
* `shutdown` was called in `ensure` clause, and it invokes shutdown sequence *unexpectedly*
This change also includes removing `default_loop` from Engine. It wasn't used in anywhere, so I simplified main loop by removing it.
> Fix lifecycle control

- lib/fluent/agent.rb
- lib/fluent/compat/output.rb
- lib/fluent/config/element.rb
- lib/fluent/config/section.rb
- lib/fluent/configurable.rb
- lib/fluent/log.rb
- lib/fluent/plugin/in_monitor_agent.rb
- lib/fluent/plugin/multi_output.rb
- lib/fluent/plugin/out_copy.rb
- lib/fluent/plugin/out_roundrobin.rb
- lib/fluent/plugin/output.rb
- lib/fluent/plugin_id.rb
- lib/fluent/root_agent.rb
- test/plugin/test_multi_output.rb
> Show deprecated warnings for reserved params

- lib/fluent/config/configure_proxy.rb
- lib/fluent/config/section.rb
- lib/fluent/configurable.rb
- test/config/test_configurable.rb
- test/config/test_configure_proxy.rb
* "name" and "param_name" is strongly connected with plugin's code (even in base classes)
so these MUST be not changed by subclasses (subclass MUST use same names)
* separate "param_name" from "name" to detect overwriting "param_name" by subclasses to raise errors
and add "variable_name" method as internal utility
* make it possible to change default values in finalized sections
because it's very popular that 3rd party plugin prefer different default value for built-in predefined parameters
* make it possible to change "init" specification of finalized sections
because newly added/changed default values might be able to init sections
> Fix overwriting config_section definitions:

- lib/fluent/compat/output.rb
- lib/fluent/plugin/output.rb
- lib/fluent/plugin_helper/compat_parameters.rb
- test/plugin_helper/test_compat_parameters.rb
This plugin helper is to load v0.12 style buffer configurations from v0.14 plugin.
It's required to port existing plugins to v0.14 APIs.
> Introduce new plugin helper: CompatParameters

- lib/fluent/compat/output.rb
- lib/fluent/plugin/buf_file.rb
- lib/fluent/plugin/buffer.rb
- lib/fluent/plugin/out_buffered_null.rb
- lib/fluent/plugin/output.rb
- lib/fluent/plugin_helper/compat_parameters.rb
- test/plugin/test_buffer.rb
- test/plugin/test_out_buffered_null.rb
- test/plugin/test_out_exec.rb
- test/plugin/test_output.rb
- test/plugin/test_output_as_buffered.rb
- test/plugin/test_output_as_buffered_overflow.rb
- test/plugin/test_output_as_buffered_retries.rb
- test/plugin/test_output_as_standard.rb
- test/plugin_helper/test_compat_parameters.rb
I got reviewed for parameters newly added or renamed, and applied changes to rename better names.
This change will be included in v0.14.0 RC2.
> Rename v14 parameters

- lib/fluent/process.rb
Setting this to a value less than the magic number of 0.2 (like 0.0) fixes the issue in #930
> Make the detach process forward interval configurable

- lib/fluent/agent.rb
- lib/fluent/compat/output.rb
These changes fixes 2 bugs of v0.14.0 RC2.
I checked correctness of these changes by 2 example configurations below:
* example/out_forward_buf_file.conf
* example/in_forward.conf
> Fix missed bugs for v0.14

- lib/fluent/compat/output.rb
3rd party BufferedOutput plugins sometimes overrides `#emit` to control chunking keys.
This change is to provide compatibility for such plugins by using metadata.variables to pass specified chunking key to `#write`.
This fix solves #990.
> Provide `chunk.key` for v0.12 plugins which specifies `key` in overriding `#emit`

- lib/fluent/compat/output.rb
- lib/fluent/compat/propagate_default.rb
- lib/fluent/configurable.rb
- test/config/test_configurable.rb
3rd party plugins with v0.12 APIs may change default values of parameters, which is controlled by compat layers. This change should be propagated to defaults of `<buffer>` section.
This change fixes #995.
> Propagate default value change from subclass of compat plugins

- lib/fluent/compat/output.rb
* because RecordFilter depends on #format_stream implemented by that mixin itself
*   it is same with the case that plugins re-implements #format_stream
> Fix to call #format_stream of plugin themselves when RecordFilter mixin included

- lib/fluent/plugin/in_dummy.rb
- lib/fluent/root_agent.rb
These changes are to wait `#force_flush` of output plugins.
`#before_shutdown` does `#force_flush` of output plugins, but it may emit events to other plugins. We should wait completion of all plugins before proceeding `#shutdown`.
This change also includes blocker callback per kinds of plugins for each shutdown sequence steps.
This feature makes it sure to call shutdown calls of input plugins before output plugins.
> Fix shutdown sequence to wait force_flush

- lib/fluent/config/configure_proxy.rb
- lib/fluent/configurable.rb
- test/config/test_configure_proxy.rb
To make debug easier.
This change fixes #1013.
> Fix to overwrite configure_proxy name only for root sections

- fluent.conf
Without `@type` developers can not getting started
as web site says.
http://docs.fluentd.org/articles/install-by-gem
> Add `@type` to secondary section

- lib/fluent/registry.rb
Before this commit `DEFAULT_PLUGIN_PATH` pointed
`lib/fluent/registry.rb/plugin`.
I feel this is not intended and change to point
`lib/fluent/plugin`.
> Fix `DEFAULT_PLUGIN_PATH`

- fluent.conf
Reverts fluent/fluentd#1031
Secondary feature requires same formatting for buffer chunks, and it means that secondary plugins should be same type with primary.
Secondary without explicit `@type` uses same type with primary implicitly, and it's right way to use secondary plugins right now, without safe chunk decoding. We should NOT show explicit `@type` specification in example.
> Revert "Add `@type` to secondary section"

- lib/fluent/plugin/output.rb
- test/plugin/test_output_as_buffered_secondary.rb
If secondary type is not specified explicitly.
It's the same behavior with v0.12.
> fix bug not to use primary plugin type in default

- example/filter_stdout.conf
- example/in_forward.conf
- example/in_http.conf
- example/in_syslog.conf
- example/in_tail.conf
- example/in_tcp.conf
- example/in_udp.conf
- example/out_copy.conf
- example/out_file.conf
- example/out_forward.conf
- example/v0_12_filter.conf
Otherwise, I've got the following warnings:
```log
2016-06-09 15:34:17 +0900 [info]: reading config file path="example/in_forward.conf"
2016-06-09 15:34:17 +0900 [info]: starting fluentd-0.14.0
2016-06-09 15:34:17 +0900 [info]: spawn command to main: /Users/hhatake/.rbenv/versions/2.3.0/bin/ruby -Eascii-8bit:ascii-8bit /Users/hhatake/Github/fluentd/vendor/bundle/ruby/2.3.0/bin/fluentd -c example/in_forward.conf --no-supervisor
2016-06-09 15:34:17 +0900 [info]: reading config file path="example/in_forward.conf"
2016-06-09 15:34:17 +0900 [info]: starting fluentd-0.14.0 without supervision
2016-06-09 15:34:17 +0900 [info]: gem 'fluentd' version '0.14.0'
2016-06-09 15:34:17 +0900 [warn]: 'type' is deprecated parameter name. use '@type' instead.
2016-06-09 15:34:17 +0900 [info]: adding match …
```
> example: Use `@type` in example confs

- lib/fluent/compat/record_filter_mixin.rb
- lib/fluent/mixin.rb
Related to https://github.com/fluent/fluentd/wiki/Changes-proposed-for-v0.14.x#misc-development-tasks.
> Extract RecordFilter Mixin into compat

- lib/fluent/test/driver/base.rb
- lib/fluent/test/driver/base_owned.rb
- lib/fluent/test/driver/formatter.rb
- lib/fluent/test/driver/owner.rb
- lib/fluent/test/driver/parser.rb
- lib/fluent/test/helpers.rb
- test/helper.rb
When we want to write tests of 3rd party plugins, we need some more code for:
* generating Fluent::EventTime easily
* generating Fluent::Config::Element easily (required for owned plugins - parser, formatter, storage, buffer and others)
* test drivers for owned plugins to support to
* instantiate plugins
* configure plugins
* set logger, plugin id and override system configs
> Test utility methods and additional test drivers

- lib/fluent/config/types.rb
- test/config/test_types.rb
> backport: Add simplified syntax for hash and array

- example/out_buffered_null.conf
- lib/fluent/plugin/in_dummy.rb
- lib/fluent/plugin/out_buffered_stdout.rb
- test/plugin/test_out_buffered_stdout.rb
Revised: #518.
And I've added tests for added buffered output plugins for testing.
> Add buffered output plugins for tests

- lib/fluent/plugin/in_http.rb
- test/plugin/test_in_http.rb
In the case of running fluentd behind HTTP proxy or load balancer,
a source address of TCP/IP packet will be replaced by load balancer.
This commit will be helpful in these case.
> add support of X-Forwarded-For header

- lib/fluent/config/dsl.rb
- lib/fluent/config/v1_parser.rb
- test/config/test_dsl.rb
This PR add include support for Ruby DSL.
And Fix bug parser include at the Windows.
Like this conditions
- First conf include absolute path
- Second(child) conf include relative path
Because `URI.parse` return `u.scheme = c`.
When Windows absolute path is `C:/projects/fluentd/test/tmp/config`.
Then used `open-uri` and basepath change `/`.
But after merge this PR.
There is a bug.
When It has some drives In the Windows.
Like a C: and D:
And upper case.
I think it is rare case.
If you need fix this bug.
Please make issue.
> [#360] Add include support for Ruby DSL

- lib/fluent/plugin/in_dummy.rb
lib/fluent/plugin/in_dummy.rb:94: warning: assigned but unused variable - e
> Suppress a warning message

- lib/fluent/command/fluentd.rb
- lib/fluent/supervisor.rb
This fixes https://github.com/fluent/fluentd/issues/1027
・We have to distinguish running only worker without supervisor from running worker under supervisor, because when using only worker, we have to create socket manager in worker.
・If we fix not to use socket manager when --no-supervisor, we have to fix plugin side, then the point to fix will increase. So I fixed supervisor side.
> Add --run-worker to distinguish it from running without supervisor

- lib/fluent/plugin/output.rb
- lib/fluent/test.rb
- lib/fluent/test/base.rb
- lib/fluent/test/log.rb
- test/plugin/test_output_as_buffered.rb
Output plugin with many chunk keys will generate too many staged chunks.
It doesn't cause crashes directly, but make performance worse and may cause any problems with file buffers.
> Warn too many staged chunks at configure

- lib/fluent/compat/handle_tag_name_mixin.rb
- lib/fluent/compat/set_tag_key_mixin.rb
- lib/fluent/compat/set_time_key_mixin.rb
- lib/fluent/compat/time_formatter.rb
- lib/fluent/compat/type_converter.rb
- lib/fluent/mixin.rb
Follows up https://github.com/fluent/fluentd/pull/1044.
I've extracted modules which are defined in `mixin.rb` into compat entirely.
> Extract more mixin module to compat

- lib/fluent/supervisor.rb
Fix https://github.com/fluent/fluentd/issues/1042
I did't use shellescape in unix for setting various values directly.
> Fix supervisor to pass RUBYOPT to worker process

- example/copy_roundrobin.conf
- lib/fluent/plugin/out_copy.rb
- lib/fluent/plugin/out_roundrobin.rb
- lib/fluent/test/driver/multi_output.rb
- test/plugin/test_out_copy.rb
- test/plugin/test_out_roundrobin.rb
- test/scripts/fluent/plugin/out_test2.rb
- test/test_output.rb
> Migrate out_copy and out_roundrobin to v0.14 API

- lib/fluent/plugin/formatter_ltsv.rb
Because `Hash#each` is simpler than `Hash#inject`,
and 20% faster.
> Use `Hash#each` instead of `Hash#inject`

- lib/fluent/supervisor.rb
Currently, if a user launches Fluentd on console with `--no-supervisor` option, that process cannot be shutdown by Ctrl-C.
This change fixes it.
> Fix to stop Fluentd worker process by Ctrl-C when --no-supervisor specified

- lib/fluent/plugin/in_syslog.rb
- test/plugin/test_in_syslog.rb
> Migrate in syslog to v0.14 API

- lib/fluent/plugin/file_wrapper.rb
On Windows, WindowsFile.new (i.e., in_tail plugin) raises an unhandled error if the path is under non-existent directory.
This has been since FileWrapper.stat() changed not to use FileWrapper.io(), which returns ENOENT unless _open_osfhandle() returns valid fd.
I'm not sure this wouldn't cause any side effect but I report it anyway :)
> handle ERROR_PATH_NOT_FOUND

- lib/fluent/plugin/buffer/chunk.rb
- lib/fluent/plugin/buffer/file_chunk.rb
- lib/fluent/plugin/buffer/memory_chunk.rb
- test/plugin/test_buffer.rb
- test/plugin/test_buffer_chunk.rb
This change is needed to minimize points to be overridden for 3rd party plugins which want to interrupt writing operations.
> Shrink buffer api

- test/plugin/test_parser_csv.rb
- test/plugin/test_parser_tsv.rb
* add missing argument `param` for test cases
* require plugin file itself explicitly
* replace variable "parser" to "d" (means test driver) because it's misleading
* remove some "time_key" for test cases without time field
> Fix tests to show what's doing explicitly

- example/in_forward.conf
- lib/fluent/supervisor.rb
* ServerEngine handles HUP as IMMEDIATE_RESTART, and it sends SIGQUIT to workers
* QUIT isn't valid signal for Fluentd worker processes
Without this change, Fluentd worker process died without shutdown sequence of plugins.
```
2016-07-08 19:09:47 +0900 [info]: Received immediate restart
2016-07-08 19:09:48 +0900 [error]: unexpected error error_class=SignalException error="SIGQUIT"
2016-07-08 19:09:48 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/engine.rb:182:in `sleep'
2016-07-08 19:09:48 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/engine.rb:182:in `run'
2016-07-08 19:09:48 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/supervisor.rb:605:in `run_engine'
2016-07-08 19:09:48 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/supervisor.rb:390:in …
```
> Fix regression about RPC /api/config.reload

- lib/fluent/compat/output.rb
- lib/fluent/event.rb
- lib/fluent/plugin/buffer.rb
- lib/fluent/plugin/buffer/chunk.rb
- lib/fluent/plugin/buffer/file_chunk.rb
- lib/fluent/plugin/buffer/memory_chunk.rb
- lib/fluent/plugin/output.rb
- lib/fluent/test/output_test.rb
- test/plugin/test_buf_file.rb
- test/plugin/test_buffer.rb
- test/plugin/test_buffer_chunk.rb
- test/plugin/test_buffer_file_chunk.rb
- test/plugin/test_output_as_standard.rb
- test/test_event.rb
This change make it possible to emit large event stream into some chunks.
It can't be done at v0.10/v0.12, but it should be done to remove warnings about chunks larger than chunk limit size.
When I was writing this change, I found some problems about locking chunks and buffer global lock.
I also improved it because the buffer with this change will operate much more chunks than ever.
> Split events emitted at once to multi chunks

- lib/fluent/event_router.rb
- test/test_event_router.rb
- test/test_plugin_classes.rb
`is_a?(Filter)` can't detect `Fluent::Plugin::Filter` and it causes non compat filter is registered as a Output plugin.
I changed test filter classes for testing this case but I'm not sure this is good or not...
> Use Fluent::Plugin::Filter instead Fluent::Filter to cover all filter classes

- test/plugin/test_in_syslog.rb
```log
% bundle exec ruby test/plugin/test_in_syslog.rb
Loaded suite test/plugin/test_in_syslog
Started
.......
Finished in 10.643330534 seconds.
--------------------------------------------------------------------------------
7 tests, 34 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
--------------------------------------------------------------------------------
0.66 tests/s, 3.19 assertions/s
% bundle exec ruby test/plugin/test_in_syslog.rb
Loaded suite test/plugin/test_in_syslog
Started
.......
Finished in 7.054952274 seconds.
--------------------------------------------------------------------------------
7 tests, 34 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed …
```
> Reduce test execution time in syslog

- test/plugin/test_in_gc_stat.rb
We should use new test driver notations in test_in_gc_stat.
> Use new test driver syntax in in_gc_stat test cases

- lib/fluent/configurable.rb
- lib/fluent/plugin_helper/formatter.rb
- lib/fluent/plugin_helper/inject.rb
- lib/fluent/plugin_helper/parser.rb
- lib/fluent/plugin_helper/storage.rb
- test/plugin_helper/test_formatter.rb
- test/plugin_helper/test_inject.rb
- test/plugin_helper/test_parser.rb
- test/plugin_helper/test_storage.rb
Originally, some plugin helpers (e.g., storage, formatter, parser, ...) defines `config_section` for sets of parameters by `included` hook. It calls `config_section` with plugin class as receivers.
But, if plugin class calls `config_section` to override default value, that **overwrites** the section definition defined by plugin helpers.
It makes many unexpected behaviors (including breaking instance variables).
This change is to prevent overwriting section definitions by plugins. By inserting a mixin module, `config_section` definition in plugin classes overrides definitions in plugin helpers, instead of overwriting it.
> Fix not to overwrite something unexpectedly

- test/plugin/test_in_exec.rb
We should use new test driver syntax and brush up more rigid test cases in test_in_exec.
> Use new test driver syntax in_exec test cases

- lib/fluent/plugin/buf_file.rb
- lib/fluent/plugin/buffer.rb
- lib/fluent/plugin/buffer/file_chunk.rb
- lib/fluent/plugin/output.rb
- test/plugin/test_buf_file.rb
- test/plugin/test_buffer_file_chunk.rb
This fixes #1098.
`buf_file` in v0.14 loads all files which matches with glob for buffer file path as queued. That behavior is to read files as much as possible when upgrading Fluentd.
But there is a bug to read files as queued, which is written by `out_file` in the same directory with buffer chunk files.
This change is to fix not to load files which doesn't have a part like `(b|q)[0-9a-f]+`, which shows that file is a buffer chunk.
#1098 is a result of combination of this bug and `append true`, which does read data from buffer chunk file (this file) and also does write these data to output file (this file) - it is infinite loop of read & write.
The minimum steps to reproduce it is:
1. execute command: `echo "foobar" > temperature.\`ruby -e 'puts Time.now.strftime("%Y%m%d")'\`.log`
2. …
> Ignore non buffer chunk files when resumed

- lib/fluent/plugin/in_syslog.rb
- test/plugin/test_in_syslog.rb
This option is useful when users transfer web access logs via syslog protocol.
Fixes #1123.
> Add option to receive longer udp syslog messages

- lib/fluent/supervisor.rb
> add a RPC call to flush buffers and stop workers

- appveyor.yml
Now, `win32-api` supports Ruby 2.3.
It's time to start to run CI Ruby 2.3 on AppVeyor!
But, this patch increases CI time on AppVeyor. (approx. 20min.)
Is this acceptable?
> appveyor: Add Ruby 2.3 matrix

- lib/fluent/plugin/in_syslog.rb
- test/plugin/test_in_dummy.rb
- test/plugin/test_in_syslog.rb
backported: #1127 
```
Merge pull request #1127 from fluent/configurable-body-size-limit-for-syslog-input
Add option to receive longer udp syslog messages
```
> backport: Add option to receive longer udp syslog messages

- lib/fluent/config/section.rb
Result is here:
```
2016-07-29 21:05:29 +0900 [info]: using configuration file: <ROOT>
<source>
@type forward
port 24271
bind 0.0.0.0
</source>
<match **>
@type secure_forward
buffer_type file
buffer_path /home/ec2-user/
buffer_chunk_limit 1048k
buffer_queue_limit 1000000
flush_interval 1s
num_threads 15
shared_key xxxxxx
secure no
self_hostname myserver.local
<server>
host localhost
port 24281
weight 100
</server>
</match>
</ROOT>
2016-07-29 21:05:29 +0900 [warn]: parameter 'weight' in <server>
host localhost
port 24281
weight 100
</server> is not used.
```
> Fix wrong message for unsupported parameter. fix #1039

- lib/fluent/plugin.rb
- lib/fluent/registry.rb
Allow to search plugin from multiple prefix directory. 
Related with issue #1131 (v0.14 doesn't load plugins from directory specified by "-p" option)
> Use separate search prefix for gems and additional plugin path

- Rakefile
- appveyor.yml
Currently we are running 6 test jobs on AppVeyer per builds (ruby [2.1, 2.2, 2.3] * [x86, x64]). But it requires 40minutes even with 2 concurrent jobs.
My idea is:
* run full tests just 4 times (2.3-x86, 2.3-x64, 2.2-x64, 2.2-x64)
* create a very short test to confirm that minimal test cases run successfully
Some gems which fluentd depends on are binary gems, which contains some versions of binary for versions of ruby, and architectures of compute (x86/x64). These combinations should be tested.
But running full tests is too much for that purpose.
So I think we can reduce total time of CI tasks by replacing full tests with very short/simple tests for some combinations of environments.
> Make CI faster for Windows environment

- lib/fluent/compat/output.rb
- lib/fluent/plugin/in_forward.rb
- lib/fluent/plugin/out_forward.rb
- test/plugin/test_in_forward.rb
- test/plugin/test_out_forward.rb
ref issue is #1135
But this patch some differences form  #1135 proposed.
Because all we want to do is to suppress calling `MessagePackEventStream#ensure_unpacked!` , this patch did not add `size` to argument of MultiEventStream#initialize
> Add size key to option in forward protocol

- lib/fluent/plugin/parser_json.rb
If we don't use strict mode strings that start with ":" are converted to symbols:
```
irb(main):002:0> Oj.load('{"log":"::1 - - [04/Aug/2016:16:15:13 +0000] \"OPTIONS * HTTP/1.0\" 200 126 \"-\" \"Apache/2.4.10 (Debian) PHP/5.6.24 (internal dummy connection)\"\n","stream":"stdout","time":"2016-08-04T16:15:13.726932176Z"}')
=> {"log"=>:":1 - - [04/Aug/2016:16:15:13 +0000] \"OPTIONS * HTTP/1.0\" 200 126 \"-\" \"Apache/2.4.10 (Debian) PHP/5.6.24 (internal dummy connection)\"\n", "stream"=>"stdout", "time"=>"2016-08-04T16:15:13.726932176Z"}
```
Using strict mode this does not happen:
```
irb(main):003:0> Oj.default_options = {bigdecimal_load: :float, :mode => :strict}
=> {:bigdecimal_load=>:float, :mode=>:strict}
irb(main):004:0> Oj.load('{"log":"::1 - - [04/Aug/2016:16:15:13 +0000] \"OPTIONS …
```
> Ensure strict mode is used for Oj parser.

- lib/fluent/supervisor.rb
Fluentd v0.12 sets `0` to umask but this code is missing in v0.14.
https://github.com/fluent/fluentd/blob/1f7cdffdb7bcae2560e536ec9cd796eff5777fc2/lib/fluent/supervisor.rb#L250
fluentd should pass chumask parameter to ServerEngine. This also fixes #1019 problem.
> Set 0 to umask for keeping v0.12 behaviour. fix #1019

- lib/fluent/plugin/filter.rb
- test/compat/test_calls_super.rb
- test/plugin/test_filter.rb
- test/test_filter.rb
This is for plugins that updates times when filtering.
ref: https://github.com/fluent/fluentd/issues/1139
> Add `filter_with_time` to `Fluent::Plugin::Filter`

- lib/fluent/supervisor.rb
- lib/fluent/winsvc.rb
When invoking fluentd as a Windows Service via winsvc.rb, winsvc.rb expects that fluetnd handle the Windows event passed by `-x` option.
But currently fluentd simply ignores it.
This patch implements to handle the event, and fixes a part of #1084.
> Handle Windows event correctly when using winsvc.rb

- lib/fluent/test/base.rb
- lib/fluent/test/driver/base.rb
- lib/fluent/test/formatter_test.rb
- lib/fluent/test/parser_test.rb
Noticed via https://github.com/fluent/fluent-plugin-s3/pull/154
v0.14 TestLogger currently outputs as:
```
2011-01-03 13:07:36 +0000 [warn]: [] out_s3: delayed events were put
```
when a TestDriver is created with a block.
v0.14 TestLogger tries to add optional_header like `[#{self.class.name}]`
```ruby
From: fluent/fluentd/lib/fluent/log.rb @ line 426 Fluent::PluginLoggerMixin#configure:
422: def configure(conf)
423:   super
428:   if level = conf['@log_level']
429:     unless @log.is_a?(PluginLogger)
430:       @log = PluginLogger.new($log.dup)
431:     end
432:     @log.level = level
433:     @log.optional_header = "[#{self.class.name}#{plugin_id_configured? ? "(" + @id + ")" : ""}] "
434:     @log.optional_attrs = {}
435:   end
436: end
```
but, TestDriver creates plugin instance with …
> Fix TestDriver to let plugin instance always to have its class name

- lib/fluent/plugin/in_tail.rb
- test/plugin/test_in_tail.rb
Encoding parameter was added in_tail on v.0.12.24 and I used it.
When I reading logs encoded in CP932+LF, fluentd output warn log like a below.
```
2016-06-01 05:14:40 +0000 [warn]: ... error="invalid byte sequence in UTF-8"
```
```
<source>
@type tail
path /path/to/log/foo.log
pos_file /path/to/log/foo.log.pos
tag foo.var
encoding utf-8
format /^ something to read $/
</source>
<match **>
@type stdout
</match>
```
> Add from_encoding parameter to in_tail plugin

- lib/fluent/supervisor.rb
Fix a problem introduced by pull request #1155 (oh, sorry...)
> `WaitForSingleObject` stops all threads

- example/multi_filters.conf
- lib/fluent/event_router.rb
- lib/fluent/plugin/filter.rb
- lib/fluent/plugin/in_dummy.rb
- test/test_event_router.rb
**Please merge this PR after #1140 is merged, Becasue this PR depends on https://github.com/fluent/fluentd/pull/1140.**
If your code can be optimized, the speed of `filter_stream` will be about 1.2 times faster.
This result is caused by avoiding to call a lot of `Fluent::MultiEventStream#add`.
the requirement of running optimization is that filter plugins that you are using don't implement `filter_stream`.
the executed command is here.
```
bundle exec fluentd -c example/multi_filters.conf
```
The measured code, as shown below. (https://github.com/fluent/fluentd/pull/1145/files#diff-c18beef6caee95367d6268a4c181f913R166)
```rb
def filter_stream(tag, es)
require 'ruby-prof'
RubyProf.start
if optimizable?
processed = optimized_filter_stream(tag, es)
else
processed = @filters.reduce(es) { …
```
> Optimize multiple filters call

- lib/fluent/plugin/output.rb
- test/plugin/test_output.rb
- test/test_output.rb
Not to warn about secondary plugin type if "standard" format is used in both of primary and secondary.
This PR closes #1150.
> Add a check that primary and secondary use `custom_format` or not

- lib/fluent/plugin/filter_record_transformer.rb
- test/plugin/test_filter_record_transformer.rb
when same keys exist in record. The bug appeared only with on `enable_ruby false`
Same thing with https://github.com/sonots/fluent-plugin-record-reformer/pull/42
> Fix to prevent overwriting reserved placeholder keys such as tag

- lib/fluent/agent.rb
- test/test_plugin_classes.rb
- test/test_root_agent.rb
MultiOutput plugins create plugin instances by themselves, but plugins' start/shutdown management are done by agents (kicked by RootAgent).
So these plugin instances must be pushed into agents.
This change fixes #1161.
> Fix to add plugin instances created by MultiOutput plugins, into agents

- lib/fluent/plugin_helper/timer.rb
- test/plugin_helper/test_timer.rb
See https://github.com/fluent/fluentd/pull/1059/files#r75269945
> Be sure to detach one-shot timer watcher

- lib/fluent/plugin/in_monitor_agent.rb
- test/plugin/test_in_monitor_agent.rb
I've migrated in_monitor_agent plugin to v0.14 API.
* support more plugin classes in in_monitor_agent (e.g. parser and storage plugins support)
> Migrate in_monitor_agent to v0.14 API

- fluentd.gemspec
- lib/fluent/supervisor.rb
This change is to tell serverengine not to restart for configuration errors.
This feature depends on ServerEngine 2.0.0 APIs and features.
Fixes #1180.
> Mark configuration errors as unrecoverable

- lib/fluent/plugin/filter_stdout.rb
See: https://github.com/fluent/fluentd/pull/1059#discussion_r76362903
> Call formatter_create in #configure instead of #start in filter_stdout

- lib/fluent/config/configure_proxy.rb
- lib/fluent/config/error.rb
- lib/fluent/config/section.rb
- lib/fluent/plugin/out_forward.rb
- test/config/test_configurable.rb
- test/config/test_types.rb
This change adds 2 options for `config_param`.
And I marked `host`, `port` of `out_forward` without `<server>` sections as obsoleted.
Unrecommended parameter, and will be removed in future.
If users specify this parameter, Fluentd warns it in logs.
Configuration parameter which is already removed.
If users specify this parameter, Fluentd stops with an error (a kind of configuration errors).
> config_param options to specify deprecated/obsoleted parameters

- lib/fluent/plugin/base.rb
- lib/fluent/plugin/output.rb
- lib/fluent/root_agent.rb
- lib/fluent/test/base.rb
- lib/fluent/test/driver/base.rb
- test/plugin/test_output.rb
- test/plugin/test_output_as_buffered.rb
- test/plugin/test_output_as_buffered_overflow.rb
- test/plugin/test_output_as_buffered_retries.rb
- test/plugin/test_output_as_buffered_secondary.rb
- test/plugin/test_output_as_standard.rb
- test/plugin_helper/test_compat_parameters.rb
- test/test_output.rb
- test/test_root_agent.rb
This method (and flag which shows this method is called properly) helps threads to start its actual process when all preparations are done.
This fixes #1187.
> Add Fluent::Plugin::Base#after_start to detect end of #start

- lib/fluent/supervisor.rb
The pipe command sender mechanism has been merged into ServerEngine (https://github.com/fluent/serverengine/pull/50).
This pull request makes fluentd to use it on Windows, to fix #1084.
> Use pipe command sender mechanism of ServerEngine on Windows

- test/test_log.rb
Related to #1115.
Using stub to freeze time is not good manner.
We should use `Timecop` to do this. :cop:
> Use timecop instead of stub in test_log

- fluentd.gemspec
- lib/fluent/event_router.rb
- lib/fluent/plugin/in_monitor_agent.rb
- test/plugin/test_filter.rb
- test/plugin/test_in_monitor_agent.rb
- test/plugin/test_in_tail.rb
- test/plugin/test_out_forward.rb
- test/test_plugin_classes.rb
This change is to reduce warnings when we run `rake test`.
Almost all warnings are about uninitialized variables, and some others are about unused variables.
I did 2 changes at the same time:
There seems no reason to specify minor version dependency for some gems. I updated these to depends on (recent) major versions. I think this operation doesn't make any problems, because all of these are development dependencies.
I also remove `json` runtime dependency, to use bundled json of Ruby runtime.
Specifying `json` version is bad practice, because it makes problem between ruby version limitations and other module's dependencies
The previous implementation depends on the behavior of `eval` for string expression, NoMethodError for nil objects and rescuing all errors (and do nothing).
It hides …
> Updates dependencies and reduce warnings

- lib/fluent/agent.rb
- lib/fluent/root_agent.rb
- test/test_root_agent.rb
Previously, it raises NeMethodError for nil.
```
2016-09-02 09:45:47 +0900 [error]: unexpected error error="undefined method `to_sym' for nil:NilClass\nDid you mean?  to_s"
2016-09-02 09:45:47 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/registry.rb:39:in `lookup'
2016-09-02 09:45:47 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/plugin.rb:146:in `new_impl'
2016-09-02 09:45:47 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/plugin.rb:104:in `new_output'
2016-09-02 09:45:47 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/agent.rb:133:in `add_match'
2016-09-02 09:45:47 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/agent.rb:69:in `block in configure'
2016-09-02 09:45:47 +0900 [error]: …
```
> fix to raise ConfigError for type missing, and its tests

- example/in_forward_client.conf
- example/in_forward_shared_key.conf
- example/in_forward_users.conf
- example/out_forward.conf
- example/out_forward_client.conf
- example/out_forward_shared_key.conf
- example/out_forward_users.conf
- lib/fluent/plugin/in_forward.rb
- lib/fluent/plugin/out_forward.rb
- lib/fluent/test/startup_shutdown.rb
- test/plugin/test_in_forward.rb
- test/plugin/test_out_forward.rb
> Add auth forward protocol

- lib/fluent/plugin/filter_parser.rb
- test/plugin/test_filter_parser.rb
v0.12 version of https://github.com/fluent/fluentd/pull/1191.
Original parser filter is for v0.12 so no need additional changes for `filter_parser.rb`.
Fix test to use `Timecop`.
> Port parser filter to v0.12

- lib/fluent/agent.rb
- lib/fluent/plugin/multi_output.rb
Basically, checking objects with its class name is wrong practice in Ruby. It's should be done with method calls.
When v0.14 MultiOutput plugins are used, Plugin.new_output requires the class at first, so Fluent::Plugin::MultiOutput reference
can succeed. When v0.12 MultiOutput plugins are used, it fails.
Refenrencing classes in core code makes circular dependencies, so we should use method calls to check objects.
This change fixes #1205.
> fix bug to depend on class name of Fluent::Plugin::MultiOutput

- example/in_dummy_with_compression.conf
- lib/fluent/event.rb
- lib/fluent/plugin/buf_file.rb
- lib/fluent/plugin/buf_memory.rb
- lib/fluent/plugin/buffer.rb
- lib/fluent/plugin/buffer/chunk.rb
- lib/fluent/plugin/buffer/file_chunk.rb
- lib/fluent/plugin/buffer/memory_chunk.rb
- lib/fluent/plugin/compressable.rb
- lib/fluent/plugin/out_forward.rb
- lib/fluent/plugin/output.rb
- test/plugin/test_buffer.rb
- test/plugin/test_buffer_chunk.rb
- test/plugin/test_buffer_file_chunk.rb
- test/plugin/test_buffer_memory_chunk.rb
- test/plugin/test_compressable.rb
- test/plugin/test_output.rb
- test/plugin/test_output_as_buffered_compress.rb
- test/test_event.rb
* Support data compression in forward protocol
Close #1169
> Support data compression in buffer plugins

- lib/fluent/plugin/in_tail.rb
Otherwise, it causes `Fluent::Plugin::MultilineParser` error as follows:
```log
% bundle exec fluentd -c example/in_tail.conf -p lib/fluent/plugin
2016-09-07 15:38:04 +0900 [info]: reading config file path="example/in_tail.conf"
2016-09-07 15:38:04 +0900 [info]: starting fluentd-0.14.5
2016-09-07 15:38:04 +0900 [info]: spawn command to main: /home/hhatake/.rbenv/versions/2.3.0/bin/ruby -Eascii-8bit:ascii-8bit  -rbundler/setup /home/hhatake/Github/fluentd/vendor/bundle/ruby/2.3.0/bin/fluentd -c example/in_tail.conf -p lib/fluent/plugin --under-supervisor
2016-09-07 15:38:05 +0900 [info]: reading config file path="example/in_tail.conf"
2016-09-07 15:38:05 +0900 [info]: starting fluentd-0.14.5 without supervision
2016-09-07 15:38:05 +0900 [info]: gem 'fluentd' version '0.14.5'
2016-09-07 …
```
> in_tail: Add a missing parser_multiline require

- test/plugin/test_in_forward.rb
This makes a test run correctly at https://travis-ci.org/fluent/fluentd/jobs/158062498#L279, https://travis-ci.org/fluent/fluentd/jobs/158062498#L299.
> Add missing arguments to test

- lib/fluent/compat/output.rb
- lib/fluent/event.rb
- lib/fluent/plugin/in_forward.rb
- lib/fluent/plugin/out_forward.rb
- lib/fluent/test/input_test.rb
- test/plugin/test_in_forward.rb
- test/plugin/test_out_forward.rb
- test/test_event.rb
Because this PR depends on #1172, please merge this after merging #1172.
This PR closes #504.
> Support compress in forward plugin

- lib/fluent/config/section.rb
- test/config/test_configurable.rb
Previously, "init: true, multi: false" sections were not instantiated (just `[]` for instance variable).
But with this behavior, we cannot use default values of these sections, except for the case to set a
blank Config::Element into `conf.elements`.
It looks abnormal, and non-useful feature for plugin authors.
So, this change will improve the situation.
Currently, there are some example without this fix:
```ruby
config_section :parse do
config_set_default :@type, "yay"
end
def configure(conf)
super
@parser = parser_create(conf: conf.elements('parse').first, default_type: "yay")
end
```
This code has default type specification twice: `config_set_default` and `default_type`.
With this change:
```ruby
config_section :parse do
config_set_default :@type, "yay"
end
def configure(conf)
super …
```
> Instantiate a section with default values even for `multi: true` sections

- lib/fluent/label.rb
- lib/fluent/root_agent.rb
- test/test_root_agent.rb
This change fixes the 2 `<label>` related bugs:
```apache
<label @test>
@type stdout
</label>
```
This is clearly wrong configuration, and warning "no patterns matched" appears always for `@test` label.
This change raises configuration error for such configuration.
```apache
<label @test>
</label>
<label @test>
</label>
```
Currently, Fluentd uses the last configuration for same labels without any errors nor warnings.
This configuration is clearly a misconfiguration. So this change is to make to report such configurations as errors.
> raise ConfigError when same label appears twice, or no match appears in label

- lib/fluent/plugin/in_monitor_agent.rb
- lib/fluent/plugin/output.rb
- test/plugin/test_in_monitor_agent.rb
> Fix monitor agent compatibility

- lib/fluent/plugin/filter_grep.rb
- lib/fluent/plugin/in_syslog.rb
- lib/fluent/plugin/out_exec.rb
- lib/fluent/plugin/parser.rb
- lib/fluent/plugin/parser_multiline.rb
One user reports following error:
```
2016-09-09 09:01:49 +0000 [error]: fluent/supervisor.rb:567:rescue in main_process: unexpected error error="uninitialized constant Fluent::Plugin::GrepFilter::ConfigError
```
> Add Fluent namespace to ConfigError in v0.14 API based plugins

- lib/fluent/command/fluentd.rb
- lib/fluent/log.rb
- lib/fluent/supervisor.rb
- test/test_log.rb
- test/test_supervisor.rb
> Enable log rotate for log

- lib/fluent/plugin/out_forward.rb
- test/plugin/test_out_forward.rb
UDP heartbeat doesn't work after https://github.com/fluent/fluentd/pull/1136
I found 'undefined variable' bugs in `Node#send_heartbeat`.
> out_forward: fix undefined variables

- test/plugin/test_in_tail.rb
This can avoid occasional stack level too deep error when CI on
AppVeyor.
https://ci.appveyor.com/project/fluent/fluentd/build/1564/job/ed9y9dky4xtcucd8
> Use timecop instead of flexmock

- lib/fluent/agent.rb
- lib/fluent/plugin/multi_output.rb
- lib/fluent/test/log.rb
- test/test_plugin_classes.rb
- test/test_root_agent.rb
This change is to fix both of #1161 and #1222.
To fix #1222, RootAgent (and Agent) should not retrieve `outputs` of output plugins dynamically in `#lifecycle`. Removing it solves the problem to call shutdown methods twice.
But this fix re-opens #1161 problem.
If all plugins are flat/static plugins or MultiOutput plugins which initialize all stores by static configuration, all plugin instances are registered in `agent.outputs`.
But once MultiOutput plugin is initialized dynamically by any plugins (e.g., fluent-plugin-forest), its sub-store/sub-plugin instances are not registered in `agent.outputs`. Lifecycle methods of these plugins are never called.
This change will add a feature to call lifecycle methods in MultiOutput. It's a kind of dirty workaround, but works well.
> Lifecycle method called correctly once

- lib/fluent/plugin/out_stdout.rb
- test/plugin/test_out_stdout.rb
Now that Fluentd supports nanosecond-resolution timestamps as of v0.14,
it follows that the stdout output plugin should print the full
timestamp.
This is a very simple patch, instead of using the default `to_s`
formatting, we call `strftime` with a custom formatting.
Right now it always prints the nanoseconds, even on second-resolution
timestamps.  This means second-resolution timestamps will display like
`2013-06-27 12:34:56.000000000 -0700`, which may be undesirable.  If so,
we can adjust the implement to print a condensed formatting for
second-resolution timestamps.
> Add nanoseconds to stdout plugin

- test/plugin/test_in_tail.rb
This can avoid occasional test failure.
This is related to https://travis-ci.org/fluent/fluentd/jobs/163340180
> Set expect_emits properly

- lib/fluent/config/v1_parser.rb
- test/config/test_config_parser.rb
v0 parser parses "k1" into `{"k1" => ""}`, but v1 parser parses into `{"k1" => nil}`.
It's bug, because empty string means true in bool type, but nil means false.
It affects tests only, because attributes are terminated with newline or end of section (`</match>`) in regular configuration files.
> key-only line (without newline) should be parsed with empty string value

- lib/fluent/plugin/in_tail.rb
This change can avoid occasional failure against `test_rotate_xxx`.
> Ignore duplicated inotify events

- lib/fluent/plugin/formatter_out_file.rb
- lib/fluent/plugin_helper/compat_parameters.rb
- lib/fluent/plugin_helper/extract.rb
- lib/fluent/plugin_helper/inject.rb
- lib/fluent/time.rb
- test/test_time_formatter.rb
- test/test_time_parser.rb
There's many use cases to parse/format times in unix time or floating point values.
It should be supported by built-in TimeParser/TimeFormatter and common configurations.
This change also implements timezone control in extracting timestamp placeholders in compat_parameters.
> Support numeric times in time parser formatter

- lib/fluent/plugin/output.rb
- test/plugin/test_output.rb
This change is mainly to make plugin authors possible to check configuration values are valid or not in the viewpoint of placeholders, like `${tag}`, `%Y-%m-%d` or `${any_key}`s.
Users can write any placeholders in their configuration parameters if plugin author provides a feature to extract it with buffer chunk keys. But buffer chunk keys and placeholders used in these values MUST be consistent. This consistency is very easy to be broken.
Newly introduced methods provides features to validate these parameters and buffering configurations. 
This change is based on #1254.
> Validators for buffering key extraction

- lib/fluent/plugin/in_tail.rb
relate to #1229
This commit runs `TailWatcher#on_notify` before attaching `stat_trigger` and `timer_trigger` and prevents `TailWatcher#on_notify` from running in two different threads(main and event loop thread) at the same time.
This change fixes the `can't modify string; temporarily locked` error.
I think fluentd v0.12 does not raise the `can't modify string; temporarily locked` error because it runs `stat_trigger` and `timer_trigger` after `TailInput#start` finishes and   thus `TailWatcher#on_notify` is not executed in two threads simultaneously.
```ruby
def start
@loop = Coolio::Loop.new
refresh_watchers
@thread = Thread.new(&method(:run))
end
def run
@loop.run
end
```
same as described in #1229
1. Create large log files by using append.rb
2. Remove a pos file (rm tmp/logs/tail.pos) …
> Run TailWatcher#on_notify before attaching triggers

- lib/fluent/plugin/base.rb
- lib/fluent/plugin/buffer.rb
- lib/fluent/plugin/output.rb
- lib/fluent/test/driver/base.rb
- lib/fluent/test/driver/output.rb
This change includes some small changes to enhance plugin development:
* Fix to raise errors (including errors from wrong scripting, e.g., NameError) instead of rescue&log it
* Add method to create a metadata for testing/validation using `extract_placeholders`, without adding metadata into `@buffer.metadata_list`
* Fix to wait actual flushing after force_flush in test drivers
This change is based on #1255.
> Plugin development enhancement

- lib/fluent/plugin/buffer/chunk.rb
- lib/fluent/plugin/output.rb
- test/plugin/test_buffer_chunk.rb
- test/plugin/test_output_as_buffered.rb
`chunk.each` (`chunk.msgpack_each`) should be available only for chunks contains msgpack binary data.
It's original design, but not implemented when v0.14 output plugins were introduced (missed to remove `include ChunkMessagePackEventStreamer` from `chunk.rb`).
Currently there are not so many output plugins using v0.14 buffered output API, so it's time to change.
`chunk.each` (`chunk.msgpack_each`) will be available only for:
* output plugins using standard format (doesn't implement #format method)
* output plugins marked to have #format method returning msgpack binary data
> Enable chunk.each only for limited plugins using msgpack

- lib/fluent/plugin/output.rb
- lib/fluent/plugin_helper/thread.rb
It's done before returning from stop/after_shutdown, but after setting flag to break while-loop.
This change suppresses log messages like 'thread doesn't exit correctly (killed or other reason)' in shutdown sequence.
> Fix to wakeup threads to quit loop in threads

- lib/fluent/command/cat.rb
Fix https://github.com/fluent/fluentd/issues/1276
> Fix fluent-cat command to send sub-second precision time

- lib/fluent/config/configure_proxy.rb
- lib/fluent/config/section.rb
- lib/fluent/plugin/filter_stdout.rb
- lib/fluent/plugin/formatter_stdout.rb
- lib/fluent/plugin/in_syslog.rb
- lib/fluent/plugin/out_stdout.rb
- lib/fluent/plugin_helper/formatter.rb
- lib/fluent/plugin_helper/parser.rb
- test/config/test_configurable.rb
- test/config/test_configure_proxy.rb
- test/plugin/test_filter_stdout.rb
- test/plugin/test_out_stdout.rb
- test/plugin_helper/test_formatter.rb
- test/plugin_helper/test_parser.rb
Adding `multi: true` for `config_section :parse` and `config_section :format` helps plugin authors not to use `conf` or `default_type` argument in `parser_create` and `formatter_create`.
With this change, plugin authors can write code to create parser(formatter) instances with default parser(formatter).
```ruby
helpers :parser
config_section :parse do
config_set_default :@type, 'myparser'
end
def configure(conf)
super
@parser = parser_create
end
```
After this change, parser(formatter) plugin helpers **always** requires default `@type` definition.
I believe that it's reasonable change for all plugins which uses parsers/formatters.
> parser/formatter plugin helper with default @type in plugin side

- lib/fluent/test/driver/base.rb
- lib/fluent/test/driver/multi_output.rb
- lib/fluent/test/driver/output.rb
- test/test_test_drivers.rb
`test_driver.run` doesn't return the value of block specified. In standard ruby way, the behavior below is expected (but not yet).
```ruby
v = d.run do
1
2
end
v == 2 # expected
```
This change fixes #1268.
> fix to return the block value as expected by many rubyists

- lib/fluent/agent.rb
- lib/fluent/plugin/base.rb
- lib/fluent/plugin/multi_output.rb
- lib/fluent/plugin/output.rb
- lib/fluent/plugin_helper/event_emitter.rb
- lib/fluent/root_agent.rb
- test/test_plugin_classes.rb
- test/test_root_agent.rb
This change introduces `context_router` for all plugin types to provide event_router to secondary output plugins.
`context_router` is the default event router for filters/outputs in `<label>` sections.
This fixes #1271.
> Event router for secondary output

- lib/fluent/command/binlog_reader.rb
- test/command/test_binlog_reader.rb
This improves test stability on Windows environment (appveyor).
> make sure to set binary mode on #open, and to wait write operation

- fluentd.gemspec
json gem 2.0.0 or later doesn't support Ruby1.9.3
> Fix json gem dependency

- lib/fluent/plugin/out_stdout.rb
- lib/fluent/plugin/output.rb
- lib/fluent/plugin_helper/thread.rb
- lib/fluent/test/driver/base_owner.rb
- lib/fluent/test/driver/output.rb
- lib/fluent/test/log.rb
- test/plugin/test_in_dummy.rb
- test/plugin/test_out_null.rb
- test/plugin/test_out_secondary_file.rb
- test/plugin/test_out_stdout.rb
This change fixes code to show error/fatal logs in testing console.
Raising errors doesn't help situation because:
* errors raised in threads will be raised in main thread by abort_on_exception=true
* main thread of test-unit will rescues and ignore errors
So we can't find any errors in unit tests without showing these on console.
I found that some `#try_write` method call `#commit_write` in it, and it misses to remove the chunk from `@dequeued_chunks`. It's a kind of bug.
Adding a chunk into `@dequeued_chunks` after calling `#try_write` has thread-unsafe bug. (because plugin may commit the chunk in another threads just after `#try_write` called, and plugin's main thread may have NOT added that chunk into `@dequeued_chunks`.)
So, I fixed it at the same time.
> Show errors on console under plugin development

- lib/fluent/plugin/output.rb
- lib/fluent/plugin_helper/thread.rb
- lib/fluent/test/driver/base.rb
- lib/fluent/test/driver/base_owner.rb
- lib/fluent/test/driver/output.rb
- lib/fluent/test/log.rb
- test/test_test_drivers.rb
This change follows #1302.
After #1302, I found that any errors in `#write` of output plugins are not raised in test case code like below:
```ruby
assert_raise AnyErrors do
d.run
d.feed(events)
end # events flushed and #write called - "AnyErrors" raised
end
```
Errors are shown on console, but we can't test it.
This change is to check all threads via thread plugin helper, and re-raise errors from these threads at the end of `#run` method. It shows all errors in all threads related with plugins explicitly as test results - so there's no need to show these errors on console.
Some changes are also included:
* add an option to retry for flush errors even in plugin development: to emulate write operations 2 or more times over failures
* use `Process.clock_gettime` instead of `Time` to work …
> Test driver fixes for error handling

- lib/fluent/compat/output.rb
- test/test_output.rb
This change fixes #1300.
Instance variables defined via `config_param` are initialized with nil (if specified so) after change #1296.
TimeSlicedOutput plugin compat layer wrongly sets instance variable before calling `super`, and the values of these instance variable are overwritten by `super`.
I fixed that problem, and wrote a test for it.
> Fix timezone for compat timesliced output plugins

- lib/fluent/plugin/in_forward.rb
- lib/fluent/plugin/out_forward.rb
- lib/fluent/test/driver/base.rb
- lib/fluent/test/driver/base_owner.rb
- lib/fluent/test/startup_shutdown.rb
- test/plugin/test_in_forward.rb
- test/plugin/test_out_forward.rb
This change is to migrate in/out_forward to v0.14 APIs, except for socket/server plugin helpers, to keep commits few and diff small.
> Migrate forward plugin to v0.14 api

- lib/fluent/plugin/filter_parser.rb
- lib/fluent/plugin_helper/compat_parameters.rb
- test/plugin/test_filter_parser.rb
Changes from original code:
- Use v0.14 namespace
- Use v0.14 API (Now working)
- Remove warnings like unused variable
> Port parser filter from fluent-plugin-parser. fix #1189

- example/out_exec_filter.conf
- lib/fluent/plugin/formatter.rb
- lib/fluent/plugin/formatter_msgpack.rb
- lib/fluent/plugin/formatter_tsv.rb
- lib/fluent/plugin/in_exec.rb
- lib/fluent/plugin/out_exec.rb
- lib/fluent/plugin/out_exec_filter.rb
- lib/fluent/plugin/output.rb
- lib/fluent/plugin/parser.rb
- lib/fluent/plugin/parser_csv.rb
- lib/fluent/plugin/parser_json.rb
- lib/fluent/plugin/parser_msgpack.rb
- lib/fluent/plugin_helper.rb
- lib/fluent/plugin_helper/child_process.rb
- lib/fluent/plugin_helper/compat_parameters.rb
- lib/fluent/plugin_helper/extract.rb
- lib/fluent/plugin_helper/inject.rb
- lib/fluent/test/driver/base.rb
- test/plugin/test_in_exec.rb
- test/plugin/test_out_exec.rb
- test/plugin/test_out_exec_filter.rb
- test/plugin_helper/test_child_process.rb
- test/plugin_helper/test_compat_parameters.rb
This change is to migrate `out_exec_filter` to v0.14 API, and make `in/out_exec` plugins free from `Fluent::ExecUtil::*` classes.
This change includes the changes to:
- make all (built-in or 3rd party) formatter/parser plugins available in exec plugins
- make inject/extract plugin helpers available in exec plugins
- add a method to return parser/formatter type for data handling (binary, text or text-per-line)
- add methods to pass io or partial data to parsers to parse binary or multiline text data in consistent way
- add options of child_process plugin helper to wait process exits and callback for exit status
This change is successor of #1048.
> Migrate exec plugins to v0.14 api

- lib/fluent/plugin/filter_record_transformer.rb
- test/plugin/test_filter_record_transformer.rb
We got many questions "Why transformed result is string?"
Time to change default behaviour before stable v0.14.
@sonots Could you check this patch?
> filter-record-transformer: remove old behaviours

- lib/fluent/plugin/in_http.rb
- lib/fluent/plugin/parser.rb
- lib/fluent/plugin_helper/compat_parameters.rb
- lib/fluent/time.rb
- test/plugin/test_in_http.rb
This change is to migrate `in_http` to v0.14 APIs, without socket/server plugin helpers (like #1306).
Currently, this change disables DetachMultiProcessMixin feature, because `event_loop` plugin helper can't work with it (error below occurs when DetachMultiProcessMixin is mixed in):
```
Assertion failed: (("libev: ev_loop recursion during release detected", loop_done != EVBREAK_RECURSE)), function ev_run, file ./../libev/ev.c, line 3437.
rake aborted!
SignalException: SIGABRT
```
> migrating in_http to v0.14 API

- lib/fluent/plugin/out_forward.rb
- test/plugin/test_out_forward.rb
> fix not to raise error when out_forward is initialized as secondary

- lib/fluent/plugin/in_monitor_agent.rb
- test/plugin/test_in_monitor_agent.rb
In our experience, almost users don't need config param because this parameter is not needed for buffer monitoring.
Removing it avoids unnecessary json processing and reduces response size.
`config` param itself is useful when user wants to check actual buffer configuration.
So add `with_config` query parameter to keep previous behaviour.
> in_monitor_agent: Add include_config parameter to remove config field from response

- lib/fluent/compat/output.rb
- test/test_output.rb
Helpers/Compat utils  can't judge user specifies both localtime/utc or converted result.
This changes conf dumpped result but it seems acceptable.
Without this change, v0.12 TimeSlicedOutput plugins with `utc` parameter don't work.
> Remove 'utc' field from TimeSlicedOutput conf to prevent ConfigError in plugin helpers

- lib/fluent/test/helpers.rb
- test/config/test_configurable.rb
- test/helper.rb
- test/test_parser.rb
From v0.14 `fluent/test/helpers`.
Reduce if conditions for v0.12 and v0.14 in tests.
> Add Fluent::Test::Helpers module for easy to write tests

- lib/fluent/plugin/in_tail.rb
> optimize to split lines

- lib/fluent/env.rb
- test/test_event_time.rb
For the behavior change of Oj 2.18.0.
CI tasks newly kicked are now failing with Oj 2.18.0. This change fixes it.
> Make sure to specify use_to_json option

- lib/fluent/plugin/in_tail.rb
File handles are not closed explicitly now, and it makes troubles on Windows (especially in tests).
After detaching watchers (and stops all threads including event loop), no threads touches to IO objects and file handlers.
File handles should be closed after that.
> Close files explicitly in in_tail

- .travis.yml
- appveyor.yml
- fluentd.gemspec
- lib/fluent/plugin/in_forward.rb
- lib/fluent/plugin/in_tcp.rb
- lib/fluent/plugin/in_udp.rb
- lib/fluent/plugin/out_forward.rb
- lib/fluent/plugin/output.rb
- lib/fluent/plugin_helper.rb
- lib/fluent/plugin_helper/event_loop.rb
- lib/fluent/plugin_helper/server.rb
- lib/fluent/plugin_helper/socket_option.rb
- lib/fluent/plugin_helper/timer.rb
- lib/fluent/test/driver/base.rb
- test/helper.rb
- test/plugin/test_in_forward.rb
- test/plugin/test_in_tcp.rb
- test/plugin/test_in_udp.rb
- test/plugin/test_out_forward.rb
- test/plugin_helper/test_server.rb
Server plugin helpers are to make plugin authors to write network servers very easily.
These make authors free from writing code to create sockets, handle event loops or threads.
The key features are:
* callback-based network daemon execution (plugin helper style)
* test driver support to wait startup/shutdown servers before actual test code running
* creating sockets via socket manager in default for coming multi-process configuration support
The full features of socket/server plugin helpers and TBDs are:
* TCP, UDP and TLS support (TLS will be implemented in future change)
* TCP/TLS keepalive (in future)
* IPv6 support
I committed all changes for this pull-request
* server plugin helper: TCP/UDP implementation complete
* tcp/udp input plugin: migrated to v0.14 APIs with server plugin …
> Introduce server plugin helpers

- lib/fluent/plugin/filter_record_transformer.rb
- test/plugin/test_filter_record_transformer.rb
- Remove `${message}` like short cut
- Use `emit_error_event` for using `@ERROR` label instead of dumping log
@sonots Could you check?
> Goodbye legacy compatibility

- lib/fluent/plugin/out_forward.rb
- test/plugin/test_out_forward.rb
> fix to convert traditional parameters

- lib/fluent/plugin/out_file.rb
- test/plugin/test_out_file.rb
out_file has been used as plugin to dump data in secondary for a long time, and
that configuration looses consistency about chunk keys (even in v0.12).
But increment placeholder of out_file can create another file name (by just numbering) for such cases.
This change makes v0.14 to work with such configuration...
This fixes #1330.
> fix not to check tag and variable placeholders when configured as secondary

- lib/fluent/plugin_helper/server.rb
Some tests show that some tests sometimes fail with Errno::ECONNRESET by unexpected disconnection from client.
https://ci.appveyor.com/project/fluent/fluentd/build/1915/job/k4jfxnjp8jxxqtch
> fix to rescue Errno::ECONNRESET to handle unexpected disconnection

- lib/fluent/config/section.rb
- test/config/test_configurable.rb
If plugin uses `config_param :name, :string, deprecated: "This is
deprecated"` then we cannot use the plugin with plugins using v0.12
compatible layer.
> Add null check for `logger`

- lib/fluent/command/cat.rb
For testing, re-install v0.12 is hard for users.
> fluent-cat: Add --time-as-integer option for v0.12 or earlier versions

- lib/fluent/plugin/in_syslog.rb
- test/plugin/test_in_syslog.rb
I want that `priority` and `facility` are in event record.
Currently, I use `fluent-plugin-record-reformer` to extract `priority` and `facility` values from tags.
However, these values have already been parsed in `in_syslog` plugin.
https://github.com/fluent/fluentd/blob/406c2a1dbfe0c2f14618b9251b67bc1e4f637813/lib/fluent/plugin/in_syslog.rb#L172-L173
I think it is useless to use another plugin for extracting `priority` and `facility`.
Then, I added `include_priority/facility` options to in_syslog.
> Add priority_key/facility_key options to in_syslog

- lib/fluent/plugin_helper/inject.rb
- test/plugin_helper/test_inject.rb
Inject plugin helper does record.dup, so that Output plugin code cannot find any
side effect of inject plugin helper. It means output cannnot do chunking with injected values.
On the other hand, there is just few good use cases about chunking with injected hostname.
* chunking hostname (just after injected) is to route events with hostname... and hostname is unique on a host
* just one good use-case, to extract hostname into ${hostname} in configured values
* but it can be done by ruby code eval
This fixes #1353.
> fix to raise error if injected hostname_key is also specified in buffer chunk key

- test/plugin_helper/test_server.rb
Windows may raise Errno::EACCESS for such case, when
bind operation fails to access port/file descriptor.
This change is to improve test stability.
> allow to raise Errno::EACCESS to bind sockets already bound

- lib/fluent/formatter.rb
- test/test_formatter.rb
Empty fields is error prone because it generates empty line.
> formatter_csv: Change fields parameter to required

- lib/fluent/output.rb
- test/test_output.rb
This is useful for debugging of buffer flush issue.
I set default value is `5.0`. This is good for local destination but `5.0` seems small for cloud based services.
Should we set large value for default setting?
This patch is for v0.12 but support this feature in v0.14 is also good.
> Add slow_flush_log_threshold parameter

- lib/fluent/engine.rb
- lib/fluent/error.rb
- lib/fluent/supervisor.rb
- test/command/test_fluentd.rb
Currently, unrecoverable errors (which serverengine doesn't try to restart workers about) are only configuration errors.
But some other situation cannot be retried. For example:
* per-worker root directory (will be introduced next) exists but it is a file
* failed to bind an address/port in server plugin helper
* failed to read a file from in_tail by permission error
* or many others
We are using ConfigError for such cases, but it's nonsense in fact.
This change also adds unrecoverable cases for scripting errors while loading plugin files.
Fluentd is now restarting for such cases, but it's just wrong behavior.
> introduce unrecoverable error type, and logs to show Fluentd process/worker started

- lib/fluent/plugin/in_exec.rb
- test/plugin/test_in_exec.rb
- test/scripts/exec_script.rb
Since 0.12.18,  `in_exec` dose not sleep `run_interval` when command or output parsing failed.
This causes the fork bomb.
This is prevended by moving `sleep @run_interval` to `ensure` clause.
(Sorry, the added test case may not be good...)
> in_exec: Ensure to sleep for prevending fork bomb

- lib/fluent/supervisor.rb
`process_name` parameter doesn't work. This code has been deleted at https://github.com/fluent/fluentd/commit/c1170cc0b83ec6c7875ee24abfe0b2dac46442f7.
before:
```
$ ps aux | grep fluentd
qwiggy    15870  1.0  0.4 251696 33664 pts/5    Sl+  02:17   0:01 ruby /home/qwiggy/work/fluentd/fluentd/vendor/bundle/ruby/2.1.0/bin/fluentd -c test.conf
qwiggy    15904  0.6  0.4 116404 33448 pts/5    Sl+  02:17   0:00 worker:fluentd1                                                            
```
after:
``` 
$ ps aux | grep fluentd
qwiggy    16248 21.3  0.4 251736 33656 pts/5    Sl+  02:20   0:01 supervisor:fluentd1                                                        
qwiggy    16282 16.0  0.4 116452 33436 pts/5    Sl+  02:20   0:00 worker:fluentd1 …
```
> fix to change process name for supervisor process

- lib/fluent/log.rb
- test/plugin/test_out_file.rb
Since ruby 2.4, `forwardable` checks the method visibility and it shows the warnings.
This patch simply removes private for targets methods.
> Fix warnings

- lib/fluent/engine.rb
- lib/fluent/log.rb
- lib/fluent/plugin/base.rb
- lib/fluent/plugin/buf_file.rb
- lib/fluent/plugin/in_tail.rb
- lib/fluent/plugin/storage_local.rb
- lib/fluent/plugin_helper/storage.rb
- lib/fluent/plugin_id.rb
- lib/fluent/supervisor.rb
- lib/fluent/system_config.rb
- test/command/test_fluentd.rb
- test/config/test_system_config.rb
- test/plugin/test_base.rb
- test/plugin/test_buf_file.rb
- test/plugin/test_in_monitor_agent.rb
- test/plugin/test_storage_local.rb
- test/plugin_helper/test_child_process.rb
- test/plugin_helper/test_storage.rb
- test/test_log.rb
- test/test_plugin_id.rb
- test/test_supervisor.rb
This change introduces system-wide "root directory" and root directory per plugins.
It's enabled when:
* `root_dir` specified in `<system>` section
* `@id` configured in each plugin configuration sections
The root directories per plugin instances must be unique in a filesystem (between many workers of fluentd). So it uses `worker_id` provided by supervisor process via environment variable.
The path of directories are: `/system-wide-root/workerN/plugin-id` (generated and provided via `Fluent::Plugin::Base#plugin_root_dir`). Plugins will creates files or directories under that.
This change also adds 2 implementations to use this new feature:
* `buf_file`: configure buffer file `path` automatically
* `storage_local`: configure storage file `path` automatically
I have an additional plan to …
> Root directory per worker process

- lib/fluent/plugin/in_monitor_agent.rb
- test/plugin/test_in_monitor_agent.rb
Related to #1379 
Will have JSON like this:
```json
{
// other monitor_agent keys
"retry": {
"start":"2016-12-23 01:36:14 +0700",
"steps":1,
"next_time":"2016-12-23 01:37:16 +0700"
}
}
```
> Ability to get real retry state of buffered output

- lib/fluent/plugin/out_forward.rb
- test/plugin/test_out_forward.rb
fixes #1388.
v0.14.11 should be released after this change is merged for quick regression fix.
The changes between v0.14.10 release and this change will be introduced at v0.14.12.
> fix bug about chunk response handling

- example/suppress_config_dump.conf
- lib/fluent/supervisor.rb
- lib/fluent/system_config.rb
- test/command/test_fluentd.rb
Currently, supervisor overwrites values from command line options by system config values (even if no parameters are configured in `<system>` sections).
This makes a bug to ignore some command line options, which can be configured via both of command line options and system config section (For example, `--suppress-config-dump`).
This change makes command line options prior than system config parameters.
It's just standard way in all daemon software.
> Fix bug to ignore some command line options

- lib/fluent/plugin/in_monitor_agent.rb
> NoMethodError when using in_monitor_agent with out_null plugin #1364
This is my fix for #1364.
----
I thought it may be better to add a `resuce e: NoMethodError` around here -> https://github.com/shuji-koike/fluentd/blob/be7ffb2/lib/fluent/plugin/in_monitor_agent.rb#L344-L346
If so, I will fix my commit :trollface:
> in_monitor_agent: get_monitor_info: fix NoMethodError

- example/in_dummy_blocks.conf
- lib/fluent/plugin/out_null.rb
- lib/fluent/plugin/output.rb
Current Fluentd master:HEAD doesn't run into infinite loop with the configuration file added by this change because thread plugin helper kills all threads (including input plugin thread emitting events).
But this change fixes the problem even with plugins creating threads by plugins themselves.
> fix to break infinite-loop when shutdown goes on

- lib/fluent/plugin/in_forward.rb
- lib/fluent/plugin_helper/server.rb
- test/plugin_helper/test_server.rb
This change is revival of #861, to close listening connections in #stop, not to accept connections to tell clients that this node denies incoming data now.
When `shared: true`, SocketManager in ServerEngine accepts connections. So plugin side cannot control it (this change doesn't affect to SM's behavior).
But it's correct, because other workers may be able to handle connections newly coming.
> close listening socket in #stop not to accept new connections anymore

- lib/fluent/plugin/out_forward.rb
- test/plugin/test_out_forward.rb
This change is revival of #735, for v0.14 `out_forward`.
This parameter is used for the case: deployment systems will create the DNS records of hosts in `<server>`.
> add ignore_network_errors_at_startup

- example/logevents.conf
- lib/fluent/agent.rb
- lib/fluent/command/fluentd.rb
- lib/fluent/engine.rb
- lib/fluent/event_router.rb
- lib/fluent/log.rb
- lib/fluent/match.rb
- lib/fluent/supervisor.rb
- lib/fluent/system_config.rb
- test/command/test_fluentd.rb
- test/config/test_system_config.rb
- test/test_log.rb
There are some issues and unexpected behavior about log events (`fluent.**` events).
This change is to fix these problems and add features.
* log events can be routed only by `<match fluent.**>` sections
* unexpectedly, `<match fluent.info>` section doesn't work #485 
* log events can be matched only by top-level match sections
* we are recommending label routing for all events #1038 
* log events sometimes occurs unexpected errors in shutting down
* log events may be routed into plugins already shutdown
Added features and changes:
* logger emits log events into `@FLUENT_LOG` labels if exists
* In that sections, mis-matched logs will be ignored without warnings (missed tags are warned at startup)
* This behavior estimates log levels of standard loggers
* Log events will NOT be emitted …
> Update log events and its handling

- lib/fluent/plugin/buffer.rb
- lib/fluent/plugin_helper/compat_parameters.rb
- test/plugin/test_buffer.rb
- test/plugin_helper/test_compat_parameters.rb
This change is to rename two buffer parameters:
* `chunk_records_limit` -> `chunk_limit_records`
* `queue_length_limit` -> `queue_limit_length`
These new names are named under the same rule with other parameters:
* `chunk_limit_size`
* `total_limit_size`
Once (in very early era in v0.14) these parameters were renamed from `chunk_size_limit` and `total_size_limit` with consultation of some English native speakers, but some others were unchanged at that time.
But I think these should be named under the same rule for consistency.
These parameters are still undocumented, so I believe we can do it now, only right now.
> Rename parameter names with the rule of other params

- lib/fluent/config/configure_proxy.rb
- lib/fluent/config/types.rb
- lib/fluent/plugin/buf_file.rb
- lib/fluent/plugin/buffer/file_chunk.rb
- test/config/test_types.rb
- test/plugin/test_buf_file.rb
The parameters defined as `config_param :name, :string` may produce ASCII-8BIT String values, but it's unexpected values for most plugin authors and users (these values will be packed into `bin` in msgpack).
This change encodes string values in utf8.
> Encode utf8 for configuration string values

- lib/fluent/plugin/out_forward.rb
- test/plugin/test_out_forward.rb
> Ensure to write str(not bin) objects, for compatibility reason

- lib/fluent/plugin/out_file.rb
- test/plugin/test_out_file.rb
> Fix a bug not to use plugin root directory for buffer path even if configured correctly

- lib/fluent/plugin/filter_record_transformer.rb
BasicObject has following methods:
>> BasicObject.instance_methods
=> [:!, :==, :!=, :__send__, :equal?, :instance_eval, :instance_exec, :__id__]
> Use BasicObject for cleanroom

- lib/fluent/registry.rb
`Registry` now loads built-in plugins first, but it should be last.
Fluentd should prefer 3rd party plugins to overwrite behaviour and keep to use same plugin, e.g. parser plugin.
> Fix plugin load order. Loading built-in plugins should be last

- lib/fluent/plugin/formatter_csv.rb
- lib/fluent/plugin/formatter_hash.rb
- lib/fluent/plugin/formatter_json.rb
- lib/fluent/plugin/formatter_ltsv.rb
- test/plugin/test_formatter_csv.rb
- test/plugin/test_formatter_hash.rb
- test/plugin/test_formatter_json.rb
- test/plugin/test_formatter_ltsv.rb
KVS or Queue like plugins don't need `\n` in the json formatted result.
This parameter controlls `\n` for such plugins.
> formatter: Add add_newline parameter to remove '\n' from the result

- lib/fluent/clock.rb
- lib/fluent/plugin/out_forward.rb
- lib/fluent/plugin/output.rb
- lib/fluent/plugin_helper/child_process.rb
- lib/fluent/plugin_helper/event_loop.rb
- lib/fluent/test/driver/base.rb
- test/test_clock.rb
Currently there are many code to use `Time.now` to control flush timing and event invoke timing.
It's basically wrong, because time may move to future or past by time adjustment, or affected by leap seconds (and Timecop).
We can use `Process.clock_gettime` to avoid this problem, but it's a bit troublesome to specify clock type available. It's too much and too raw for almost core code and plugins. Using `Process.clock_gettime` is also not controlled by test code.
So, this change will introduce a new internal API to provide clock value, which can be controlled to be frozen for tests.
> Clock api for incremental second unit counter

- lib/fluent/plugin/in_tail.rb
- test/plugin/test_in_tail.rb
* On Windows, the tail target may well be opened in "exclusive" sharing mode, where no other processes are allowed to open it.  This patch adds an option called `open_on_every_update`, which enables the plugin to tail such a target by letting the plugin open it only when it gets updated.
* In the current line splitter code, lookup for end-of-line characters is always performed byte-wise, which means it cannot deal with the file in an encoding whose minimum encoded unit consist of more than a byte (namely UTF-16(LE|BE), UCS-2(LE|BE) and UTF-32(LE|BE)).  This patch removes such a limitation.
* Access to the file by a process that tries to exclusively open it is effectively prevented by any preceding process that opens it in any mode …
> in_tail: add `open_on_every_update` setting / support for UTF-16 and UTF-32

- lib/fluent/plugin/in_tail.rb
- test/plugin/test_in_tail.rb
Essentially all unmatched lines will be placed inside the parse_fail attribute, i.e.
```
{  
"parse_fail":"unmatched line....rest of the line",
"server":"myserver",
"stack":"my-app-dev-01",
"application":"my-app",
"log_type":"apache.access",
"time":"2017-01-16T23:06:49Z"
}
```
This will enable our analytics tools to pick up any pattern matching regexp issues.
> Capture unmatched lines

- lib/fluent/plugin/filter_record_transformer.rb
- test/plugin/test_filter_record_transformer.rb
Currently, `remove_keys` doesn't work with `renew_time_key` parameter, so
user needs one more filter to remove `renew_time_key` field from the record.
```aconf
<filter pattern>
@type record_transformer
renew_time_key event_time
auto_typecast true
<record>
event_time ${Convert record["time_str"] into unixtime or float type}
</record>
</filter>
<filter pattern>
@type record_transformer
remove_keys event_time
</filter>
```
This is verbose and not good performance. `remove_keys` should remove `renew_time_key`.
```aconf
<filter pattern>
@type record_transformer
renew_time_key event_time
remove_keys event_time
auto_typecast true
<record>
event_time ${Convert record["time_str"] into unixtime or float type}
</record>
</filter>
```
> record_transformer: remove_keys processing should be last

- .travis.yml
- example/out_forward_heartbeat_none.conf
- lib/fluent/engine.rb
- lib/fluent/plugin/compressable.rb
- lib/fluent/plugin/in_forward.rb
- lib/fluent/plugin/out_forward.rb
- lib/fluent/plugin_helper/event_loop.rb
- lib/fluent/plugin_helper/thread.rb
- lib/fluent/test/driver/base.rb
- test/plugin/test_buf_file.rb
- test/plugin/test_buffer.rb
- test/plugin/test_buffer_file_chunk.rb
- test/plugin/test_compressable.rb
- test/plugin/test_in_dummy.rb
- test/plugin/test_in_monitor_agent.rb
- test/plugin/test_in_tail.rb
- test/plugin/test_out_file.rb
- test/plugin/test_out_forward.rb
- test/plugin/test_output.rb
- test/plugin/test_output_as_buffered.rb
- test/plugin/test_output_as_buffered_compress.rb
- test/plugin/test_output_as_buffered_retries.rb
- test/plugin/test_output_as_buffered_secondary.rb
- test/plugin_helper/test_child_process.rb
- test/plugin_helper/test_server.rb
- test/plugin_helper/test_timer.rb
- test/test_clock.rb
- test/test_supervisor.rb
- test/test_test_drivers.rb
To make tests stable on CI services.
Based on #1425, and fixes #1404.
> Improve test stability

- lib/fluent/config/configure_proxy.rb
- lib/fluent/system_config.rb
- test/config/test_configure_proxy.rb
Currently, plugin authors can add any keyword options on `config_param` and `config_argument`, and these are not checked.
This may occur that plugin author want to set any options, but it doesn't work well by typo or any other reasons.
So I added a validator for these options, not to be set unexpected parameter options.
> Add config param option validator

- .travis.yml
- example/in_forward_tls.conf
- example/out_forward_tls.conf
- lib/fluent/config/section.rb
- lib/fluent/configurable.rb
- lib/fluent/plugin/in_forward.rb
- lib/fluent/plugin/in_tcp.rb
- lib/fluent/plugin/out_forward.rb
- lib/fluent/plugin_helper/cert_option.rb
- lib/fluent/plugin_helper/server.rb
- lib/fluent/plugin_helper/socket.rb
- lib/fluent/plugin_helper/socket_option.rb
- test/config/test_configurable.rb
- test/plugin/test_out_forward.rb
- test/plugin_helper/test_server.rb
This change is to add a functionality to support TLS, mainly for in/out forward plugins.
The server plugin helper's TLS support is:
* plugins can use `tls_options` hash argument to specify various options about TLS options and certifications in programatic way
* plugins can load configurations about TLS via `<transport tls>` section of configuration transparently to control them by users directly (not to write any code in plugins)
This feature supports these certificate management:
* load a server certificate (signed by public/private CA)
* load a private CA certificate and private key, and generate server certificates dynamically
* generate self-signed server certificate dynamically
With this feature, v0.14 forward input/output plugins are compatible with 3rd party secure-forward plugin.
> Support TLS by socket/server plugin helper

- lib/fluent/plugin/storage_local.rb
- lib/fluent/plugin_helper/storage.rb
- test/plugin/test_storage_local.rb
- test/plugin_helper/test_storage.rb
This feature is very useful for plugins which uses 2 or more storage instances, with `root_dir` configuration.
> fix to generate storage local path using usage

- lib/fluent/plugin/buffer.rb
- test/plugin/test_buffer.rb
This is for v0.12 based plugins.
Plugin should be moved to BufferOverflowError after v0.14 migration.
But fluentd should keep API compatibility for now.
> Keep Fluent::BufferQueueLimitError for exsting plugins

- lib/fluent/plugin/parser_multiline.rb
Because parser_multiline uses Fluent::Plugin::RegexpParser it must
require parser_regexp, otherwise, you get error messages like this
when using in_tail with format multiline:
```
2017-02-09 02:02:25 +0000 [error]: #0 fluent/supervisor.rb:674:block in main_process: config error file="/etc/fluent/fluent.conf" error_class=Fluent::ConfigError error="Invalid regexp '^(?<time>\\S+\\s+\\S+\\s+\\S+)\\s+(?<host>\\S+)\\s+(?<ident>[\\w\\/\\.\\-]*)(?:\\[(?<pid>[0-9]+)\\])?[^\\:]*\\:\\s*(?<message>.*)$': uninitialized constant Fluent::Plugin::RegexpParser\nDid you mean?  RegexpError"
```
> parser_multiline.rb must require parser_regexp

- lib/fluent/plugin_helper/retry_state.rb
- test/plugin_helper/test_retry_state.rb
Current secondary transition calculation checks only `retry_timeout` parameter, but
it should consider `retry_max_times`.
> Secondary calculation should consider retry_max_times. fix #1449

- lib/fluent/plugin/output.rb
- test/plugin/test_output_as_buffered.rb
Current Output API can't skip invalid record with custom format.
Old API uses `emit` for such purpose but new API doesn't have it.
Omitting invalid record in format is good for reducing formatting cost.
> Skip record when Output#format returns nil

- lib/fluent/plugin/buffer/file_chunk.rb
This is not incomplete but keep buffer and metadata pair phase as much as possible.
Use `BufferOverflowError` in `create_new_chunk` for input plugin retry.
TODO: Writing unittest for this case is hard. It will be added to integration test.
> buf_file: handle "Too many open files" error to keep buffer and metadata pair

- lib/fluent/plugin/output.rb
- lib/fluent/plugin_helper/compat_parameters.rb
- test/plugin/test_output.rb
- test/plugin_helper/test_compat_parameters.rb
This patch improves flush_interval parameter handing.
- Set `flush_mode interval` when v0.12 configuration has `flush_interval`
This avoids a trouble for existing out_file and out_s3 configurations
- Log warning message for flush_interval without `flush_mode interval` in `<buffer>`
Currenlty, `flush_interval` is ignored silently with following configuration. It is hard to debug for users.
```
<buffer time>
timekey 3600
flush_interval 30s
</buffer>
```
> Improve flush_interval handling

- lib/fluent/plugin/in_tail.rb
- test/plugin/test_in_tail.rb
Add option `limit_recently_modified` to in_tail. 
See: https://github.com/fluent/fluentd/issues/1466
> Watch only recently modified files

- lib/fluent/log.rb
- test/test_log.rb
This is useful for AWS related plugins to set Aws::XXX::Client's logger.
AWS logger requires `#<<` method.
See https://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#initialize-instance_method
> Add `Fluent::Log#<<`

- lib/fluent/env.rb
- lib/fluent/supervisor.rb
I noticed fluentd doesn't remove SocketManager's socket file.
It remains lots of garbage files under `/tmp`.
I added `cleanup_resources` function to handle such case.
> Fix cleanup resource

- lib/fluent/plugin/parser_apache2.rb
- test/plugin/test_parser_apache2.rb
http://httpd.apache.org/docs/current/mod/mod_log_config.html#format-notes
> Allow escape sequence in Apache access log

- lib/fluent/config/types.rb
- test/config/test_types.rb
Because:
* `String#encode` will try to encode self, it will raise
`Encoding::UndefinedConversionError`.
* fluent.conf will read as ASCII-8BIT
See also https://github.com/fluent/fluent-plugin-grok-parser/issues/27
> Use `String#force_encoding` instead of `String#encode`

- lib/fluent/plugin/in_tail.rb
- test/plugin/test_in_tail.rb
Add option `skip_refresh_on_startup` to in_tail.
See: https://github.com/fluent/fluentd/issues/1465
> Skip the refresh of watching list on startup.

- lib/fluent/plugin/parser_syslog.rb
- test/plugin/test_parser_syslog.rb
This PR is related to #636 and #1488.
> Support rfc5424 syslog format

- lib/fluent/plugin/parser_syslog.rb
- test/plugin/test_parser_syslog.rb
`@message_format` is always :auto in #parse_auto.
This is pointed out in https://github.com/fluent/fluentd/pull/1495#discussion_r105095256.
> parser_syslog: Polish implementation

- lib/fluent/plugin/in_monitor_agent.rb
- test/plugin/test_in_monitor_agent.rb
MonitorAgentInput doesn't work on multi worker environment because workers
try to start servers with the same port.
> in_monitor_agent: Start one HTTP server per worker on sequential port numbers

- lib/fluent/plugin/output.rb
- test/plugin/test_output.rb
In some case, `placeholder_validate!` checks composited value.
For example, https://github.com/kaizenplatform/fluent-plugin-bigquery/pull/115.
this patch enable user to can find wrong config easily by error message even if In the case.
```
% be fluentd -c fluent.conf -v
2017-03-10 23:04:32 +0900 [info]: fluent/supervisor.rb:696:read_config: reading config file path="fluent.conf"
2017-03-10 23:04:32 +0900 [info]: fluent/supervisor.rb:537:supervise: starting fluentd-0.14.13 pid=26713
2017-03-10 23:04:32 +0900 [info]: fluent/supervisor.rb:546:supervise: spawn command to main:  cmdline=["/home/joker/.rbenv/versions/2.3.3/bin/ruby", "-Eascii-8bit:ascii-8bit", "-rbundler/setup", "/home/joker/fluentd_workspace/.bundle/ruby/2.3.0/bin/fluentd", "-c", "fluent.conf", "-v", "--under-supervisor"] …
```
> Add placeholder validation target to error message

- lib/fluent/plugin/in_http.rb
- test/plugin/test_in_http.rb
Adds support for msgpack record(s) if the content-type header is set to “application/msgpack”.
This is to support the format of messages sent by the fluentbit project’s out_http plugin.
> msgpack format chosen with content-type header

- lib/fluent/system_config.rb
- test/config/test_system_config.rb
Regression of https://github.com/fluent/fluentd/pull/1398
> Fix log_level handling in <system>. fix #1499

- lib/fluent/plugin/filter_parser.rb
- test/plugin/test_filter_parser.rb
Related to https://github.com/fluent/fluentd/issues/1480
This is acceptable for me because configuration becomes error prone without this parameter for ignoring unneeded log lines case.
```
<label @ERROR>
<match {tag1,tag2,...}>
@type null
</match>
</label>
```
`@ERROR` label is for capturing unexpected error event so blackhoke usecase is misuse.
Parameter name comes from v0.12's `filter_parser`.
> filter_parser: Add emit_invalid_record_to_error parameter

- lib/fluent/root_agent.rb
- test/test_plugin_classes.rb
- test/test_root_agent.rb
Output threads need calling `after_start` to run but
`after_start` is sometimes not called when Input#start is blocked.
This happens when in_tail with `read_from_head true` and
output with `overflow_action block`.
This fixes the problem by checking `after_start` immediately after start.
This may be related with #1485
> Fix Input and Output deadlock when buffer is full during startup

- lib/fluent/root_agent.rb
fluentd v0.12 cannot send a USR1 signal to the output instances in the label sections, so that it can not flush parts of the buffers.
This patch solves it.
before:
```
$ ./bin/fluentd -c fluent.conf
2017-03-19 16:52:08 +0900 [info]: reading config file path="fluent.conf"
2017-03-19 16:52:08 +0900 [info]: starting fluentd-0.12.33
2017-03-19 16:52:08 +0900 [info]: gem 'fluent-plugin-elasticsearch' version '1.3.0'
2017-03-19 16:52:08 +0900 [info]: gem 'fluentd' version '0.12.19'
2017-03-19 16:52:08 +0900 [info]: adding match in @fuga pattern="fuga" type="file"
2017-03-19 16:52:08 +0900 [info]: adding match pattern="hoge" type="file"
2017-03-19 16:52:08 +0900 [info]: adding match pattern="fuga" type="relabel"
2017-03-19 16:52:08 +0900 [info]: adding source type="forward"
2017-03-19 16:52:08 …
```
> root_agent flush labels

- lib/fluent/plugin/in_syslog.rb
- lib/fluent/plugin/in_udp.rb
- test/plugin/test_in_udp.rb
`in_syslog` is widely used so using `message_length_limit` is better for users.
> Unify parameter name between udp and syslog plugins

- lib/fluent/compat/detach_process_mixin.rb
- lib/fluent/compat/input.rb
- lib/fluent/compat/output.rb
Some 3rd party plugins use these methods in their code:
```ruby
class HTTPServer # w/o inheriting Fluent::Input, Fluent::Output
include DetachMultiProcess
def start
detach_multi_process do
end
end
end
```
See also:
* https://github.com/groonga/fluent-plugin-groonga/blob/530f421080cd4ad131eacc1cfd6ade474fabc19d/lib/fluent/plugin/in_groonga.rb#L144
* https://github.com/groonga/fluent-plugin-groonga/blob/530f421080cd4ad131eacc1cfd6ade474fabc19d/lib/fluent/plugin/in_groonga.rb#L83-L85
> Fix backward compatibility with Fluent::DetachProcess and Fluent::DetachMultiProcess

- lib/fluent/plugin/in_tail.rb
Currently a warning will appear for each directory in globbed results.  They will never be readable so the message appears on each refresh.
> Do not warn that directories are unreadable in the in_tail plugin.

- example/worker_section.conf
- lib/fluent/agent.rb
- lib/fluent/config/element.rb
- lib/fluent/engine.rb
- lib/fluent/plugin/base.rb
- lib/fluent/root_agent.rb
- test/command/test_fluentd.rb
- test/config/test_element.rb
- test/test_plugin_classes.rb
- test/test_root_agent.rb
Closes #1392.
This PR introduce `<worker n>` section. Configurations under this section is enabled only in specified worker and act as if they work in single worker environment. More precisely, config elements in worker section get `worker_target_id` recursively. Prior to configure phase of corresponding plugins, `system_config.workers` for the plugins is overwritten as `1` if target_worker_id equals the worker's worker_id.
It also means that plugins(including owned plugins) which doesn't support multi worker feature can run only in worker section.
A worker section can have `<label>`, `<source>`, `<filter>` and `<match>` as a child element.
Example from #1392
```
<system>
workers 8
root_dir /path/fluentd/root
</system>
<source>  # top-level sections works on all workers in parallel
@id …
```
> Add <worker n> section to set a configuration for a specific worker

- lib/fluent/plugin/filter.rb
This is a simple PR that fixes the spelling/grammar in the error message used to let users know that their plugin does not implement the correct filter methods.
> Fix spelling/grammar in an error message

- lib/fluent/command/fluentd.rb
- lib/fluent/winsvc.rb
The the file path is passed to win32-service (which calls windows functions [CreateService]( https://msdn.microsoft.com/en-us/library/windows/desktop/ms682450(v=vs.85).aspx)) and to [Process.spawn](https://ruby-doc.org/core-2.2.0/Process.html#method-c-spawn).  Both require spaces to be wrapped in quotes or windows will not properly handle them.
Without this fix fluentd will fail fail when initializing or when starting with a ruby directory that contains spaces.
> Quote the file path to the Ruby bin directory when starting fluentd as a windows service

- lib/fluent/plugin/out_file.rb
- lib/fluent/plugin_helper/compat_parameters.rb
- test/plugin/test_out_file.rb
@mururu Could you test this on your environment?
In v0.14, compat parameters handles `utc` parameter for parsers / formatters.
So if we want to use `utc` in buffer, need to specify `timekey_use_utc` in `<buffer>`.
> Fix out_file test with timezone

- lib/fluent/command/fluentd.rb
- lib/fluent/supervisor.rb
- lib/fluent/winsvc.rb
This will allow the name, display name and description fluentd is running as when it is a Windows Service to be configured.
This also removes an unneeded option 'winsvcreg'
> Allow the Windows Service name Fluentd runs as to be configurable.

- lib/fluent/config/literal_parser.rb
- test/config/test_literal_parser.rb
We can use `"\0"` in formatter delimiter, in_tcp delimiter or anywhere.
Previous behaviour is raising error so this patch should not break existing configuration.
> Allow null byte in double-quoted string. fix #1358

- lib/fluent/plugin/in_monitor_agent.rb
- test/plugin/test_in_monitor_agent.rb
in_monitor_agent plugin collects metrics by checking internal variables by `instance_exec`.  It implicitly asserts that `@buffer` is a buffer instance when get metrics of `buffer_queue_length` and `buffer_total_queued_size`. If a plugin uses the variable name for other purpose, `NoMethodError` happens.
Example configuration with fluent-plugin-concat which uses `@buffer` variable as a Hash. On this configuration, doing `curl 'http://localhost:24220/api/plugins.json'` causes
```
[error]: #0 NoMethodError in monitoring plugins key="buffer_queue_length" plugin=Fluent::Plugin::ConcatFilter error_class=NoMethodError error="undefined method `queue' for {}:Hash"
```
```
<source>
@type monitor_agent
</source>
<filter **>
@type concat
key message
multiline_start_regexp /foo.bar/
flush_interval …
```
> check variable buffer is a Buffer instance in MonitorAgentInput

- lib/fluent/log.rb
- test/test_log.rb
Fix https://github.com/fluent/fluent-plugin-s3/issues/191
> Add missing '<<' method to delegators

- lib/fluent/plugin/in_monitor_agent.rb
Configurations for plugins generated dynamically sometimes don't have @type and type. (e.g. fluent-plugin-forest)
> Enable in_monitor_agent to find plugin type from its class

- lib/fluent/time.rb
- test/test_time_parser.rb
Ruby's iso8601 parser is a restrict version and it doesn't support `20170101T120000+0900` like format.
But this parser can handle `2017-01-01T12:00:00+09:00` and `2017-01-01T12:00:00.123+09:00` cases, so supporting it makes configuration simpler for iso8601 logs.
> Support %iso8601 special case for time_format. fix #1528

- lib/fluent/command/binlog_reader.rb
```
Usage: fluent-binlog-reader cat [options] file
Options:
-p, --plugin DIR                 add library directory path
-f, --format TYPE                configure output format
-e KEY=VALUE                     configure formatter config params
-n COUNT                         Set the number of lines to display
Error: uninitialized constant Fluent::Engine
```
> Error: uninitialized constant Fluent::Engine

- lib/fluent/plugin/in_forward.rb
- lib/fluent/plugin/out_forward.rb
- test/plugin/test_out_forward.rb
This patch includes additional fixes.
- Use readpartial for SSLSocket
- Fix invalid code for event registration
> Call proper method for each connection type. fix #1554

- lib/fluent/log.rb
Like following:
```
/home/travis/build/fluent/fluentd/lib/fluent/log.rb:149:in `debug': Fluent::PluginLogger#event at /home/travis/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/forwardable.rb:156 forwarding to private method Fluent::Log#event
/home/travis/build/fluent/fluentd/lib/fluent/log.rb:150:in `debug': Fluent::PluginLogger#caller_line at /home/travis/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/forwardable.rb:156 forwarding to private method Fluent::Log#caller_line
```
> Ruby 2.4 warns to forward private methods

- lib/fluent/plugin/in_tail.rb
- test/plugin/test_in_tail.rb
This option is useful when non-readable file exist in tailing directory and hard to exclude via `exclude_path`, e.g. file is generated dynamically.
> Add ignore_repeated_permission_error

- lib/fluent/plugin_helper/cert_option.rb
- test/plugin_helper/test_server.rb
It is convenient for users to leave the way to manage private keys to them like other many middlewares.
> Accept private key for TLS server without passphrase

- lib/fluent/engine.rb
- lib/fluent/root_agent.rb
- lib/fluent/supervisor.rb
- test/command/test_fluentd.rb
Secrete parameters are masked when configuring the plugin instances, but fluentd worker processes don't create and configure the instances of plugins under worker sections for other workers. And config dump is performed on a worker process(worker0). So the secret parameters under worker section are not masked except for worker0.
This patch makes supervisor process create and configure instances of plugins for all workers before spawning worker processes and config_dump performed on supervisor process. This method is the same with dry_run.
> Mask all secret parameters in worker section, fix #1553

- lib/fluent/supervisor.rb
- test/test_supervisor.rb
Fluentd assumes configuration file encoding is UTF-8.
Fix #1590
> Set UTF-8 encoding to string from configuration file

- lib/fluent/plugin/in_tail.rb
Newly created files after creating the `excluded` list may not be excluded.
Fix the order of creating the `paths`/`excluded` list. Creating the `excluded` list should be last for certainly excluding.
> in_tail: There are cases where the excluded_path doesn't apply by timing.

- lib/fluent/plugin/in_tail.rb
Because StatWatcher and TimerWatcher should not fire
events (inotify, timer) until close their owner TailWatcher after
detect log rotation.
Fix #1383
> Detach watchers before run `update_watcher` when detect log rotation

- lib/fluent/plugin/out_forward.rb
v0.14's out_forward uses timer helper and it stops timer when error happens.
It is not good for heartbeat because heartbeat sometimes failed when network has a problem.
v0.14 should follow v0.12's way: https://github.com/fluent/fluentd/blob/bcd37cf71fd904b5d3a88eb9951c9d7b420aa154/lib/fluent/plugin/out_forward.rb#L381
fix: https://github.com/fluent/fluentd/issues/1596
> out_forward: Don't stop heartbeat when error happen

- lib/fluent/parser.rb
- test/test_parser.rb
About the TAG part of syslog format (RFC3164).
RFC3164 says "Any non-alphanumeric character will terminate the TAG field". But some syslog senders send non-alphanumeric characters as a part of TAG, so currently fluentd allowed some non-alphanumeric characters: `[a-zA-Z0-9_\/\.\-]`. In the real world, there are cases that require more characters. For example, Cisco ASA Series Syslog Messages includes `%` like `%ASA-1-101001`. It is useful if fluentd can handle such messages.
rsyslog syslog-ng and accept all characters except ` `, `:` and `[`:
https://github.com/rsyslog/rsyslog/blob/master/tools/pmrfc3164.c#L314-L347
https://github.com/balabit/syslog-ng/blob/master/modules/syslogformat/syslog-format.c#L558-L609
This PR follows them.
Once this PR is merged, I will send a PR for the master …
> Add more available characters for tag part of syslog format

- lib/fluent/plugin/in_syslog.rb
- test/plugin/test_in_syslog.rb
This PR introduces `allow_without_priority` and `default_priority` option to syslog input.
I have syslog-like message formats like Common Event Format, which don't have PRI part at the top of the message. The current syslog input requires PRI part, so we can't receive both such messages and normal syslog messages on the same port. 
They're invalid as RFC, but there are some such formats in the real world. So I think it is very useful if fluentd can handle such logs with on the same way.
Actually, major syslog servers (rsyslog/syslog-ng) accept such format:
https://github.com/rsyslog/rsyslog/blob/master/runtime/parser.c#L576-L609
https://github.com/balabit/syslog-ng/blob/master/modules/syslogformat/syslog-format.c#L43-L85
By default, `default_priority` is `13`. It also follows rsyslog and …
> Add allow_without_priority and default_priority option to syslog input

- lib/fluent/plugin/filter_grep.rb
- test/plugin/test_filter_grep.rb
Users can use both `regexpN` and `<regexp>` section.
But `regexpN` displays deprecation warnings on boot.
> Use config_section for filter_grep

- lib/fluent/plugin/output.rb
This is simple solution but performance is bit decreased.
The better solution is changing retry mechanizm, e.g. don't share state, but it makes
the code complicated. This is feature task.
This fixes https://github.com/fluent/fluentd/issues/1555
> Fix race condition of retry state in flush thread

- lib/fluent/agent.rb
- lib/fluent/engine.rb
corresponding filter and output) are emitted
Here is an example. In this case, `out-ok-1`, `in-ok`, `filter-ok` and `out-ok-2` should be captured. `filter-ng` and `out-ng` should not be captured because they match fluentd's event logs. Note that the captured logs appear twice due to stdout filter.
```
<match test>
@type null
@id out-ok-1
</match>
<source>
@type dummy
tag dummy
@id in-ok
</source>
<filter test>
@type stdout
@id filter-ok
</filter>
<label @X>
<match hoge>
@type null
@id out-ok-2
</match>
</label>
<filter fluent.**>
@type stdout
@id filter-ng
</filter>
<match fluent.**>
@type stdout
@id out-ng
</match>
```
```
2017-07-12 19:25:28 +0900 [info]: shutting down fluentd
2017-07-12 19:25:28 +0900 [info]: shutting down input type="dummy" plugin_id="in-ok"
2017-07-12 19:25:29 +0900 …
```
> Make sure log events generated at shutdown phase of plugins (except

- lib/fluent/plugin/buffer/file_chunk.rb
As shown in #1589, file buffer chunks possibly make broken/empty .meta files for its metadata.
I found that some points to be improved to prevent such cases:
* write metadata into files just after initializing buffer chunk object
* before: .meta content is written at the time of `#commit` or `enqueue!` - it's too late
* write metadata msgpack binary, then truncate .meta file into the size of metadata
* before: .meta was truncated into 0 at first, then msgpack binary was written
> Write buffer metadata into file ASAP

- lib/fluent/supervisor.rb
The supervisor only send a signal to last worker process before..
(problem: after logrotate, worker processes write the log into deleted file)
I changed the supervisor send signal to send all of worker processes.
> Send signal to all workes

- lib/fluent/log.rb
- lib/fluent/supervisor.rb
- lib/fluent/system_config.rb
- test/config/test_system_config.rb
- test/test_log.rb
- test/test_supervisor.rb
This directive controls fluentd's log behaviour
Now, support two parameters:
```
<system>
<log>
format json
time_format %F
</log>
</system>
```
- format: Change fluentd log format. text and json
text:
```
2017-07-27 07:37:02 +0900 [info]: #0 fluentd worker is now running worker=0
```
json:
```
{"time":"2017-07-27 06:44:54 +0900","level":"info","message":"fluentd worker is now running worker=0","worker_id":0}
```
- time_format: Change time format of log
`time_format %Y`
```
2017 [info]: #0 fluentd worker is now running worker=0
```
I have a plan to move some logging related parameters to under `<log>` like `log_level`.
> Add <log> directive to <system>

- fluentd.gemspec
- lib/fluent/plugin/filter_grep.rb
- lib/fluent/plugin_helper.rb
- lib/fluent/plugin_helper/record_accessor.rb
- test/plugin/test_filter_grep.rb
- test/plugin_helper/test_record_accessor.rb
Implement record_accessor helper for nested record support.
Support two jsonpath like syntaxes.
- dot notation: `$.key1.key2[0]`
- bracket notation: `$['key1'][0]['this.is.key2']`
- single key: `key`
In this patch, I also update `filter_grep` to use this helper.
NOTE: I implement Accessor with normal way. If need the performance, I will change its implementaion to eval way: https://gist.github.com/repeatedly/ab553ed260cd080bd01ec71da9427312
> Record accessor helper

- lib/fluent/plugin_helper/compat_parameters.rb
- test/plugin_helper/test_compat_parameters.rb
Add missing syslog parameters.
> compat_parameters: support all syslog parser parameters

- lib/fluent/plugin/filter_parser.rb
- test/plugin/test_filter_parser.rb
Support nested record access in `key_name`
> filter_parser: use record_accessor

- lib/fluent/plugin/output.rb
- test/plugin/test_output.rb
This patch add record_accessor's dot-notation support in chunk keys.
To support bracket-notation, we need to consider relax validation in many places.
So it is the future work.
> output: Support record_accessor in buffer's chunk keys

- lib/fluent/plugin/filter_record_transformer.rb
- test/plugin/test_filter_record_transformer.rb
- Change types of `keep_keys` and `remove_keys` string into array
- Don't create new keys if the original record doesn't have keys specified `keep_keys` option
fix #1240
> plugin: Improve flter_record_transformer

- lib/fluent/plugin.rb
Will fix #1668.
Somehow Gem::Specification#require_paths prefers extension-install dir than "lib". It breaks plugin load process when it contains native extension.
> Fix plugin load order

- lib/fluent/config/element.rb
- test/config/test_element.rb
With fluentd v0.14.20, when debugging fluentd config parser with pry, I got following output for non-empty `Fluent::Config::Element`.
I think the pretty print result (`{}`) is not so pretty and it makes it hard to debug.
I changed `Fluent::Config::Element` to pretty print the same string as `#inspect`.
> Support pretty print of Fluent::Config::Element

- lib/fluent/supervisor.rb
Without this patch, sending multiple signals, e.g. call `kill -HUP pid` twice, causes "No such process"
> supervisor: Clear previous worker pids when receives kill signals. ref #1674

- lib/fluent/plugin/parser_apache2.rb
- test/plugin/test_parser_apache2.rb
In previous version,
`Fluent::Plugin::Apache2Parser.new` creates `@time_parser`
but `Fluent::Plugin::Parser#configure` overwrites it with `time_parser_create`.
In this version, `Fluent::Plugin::Apache2Parser#configure` creates
`@time_parser` proper
sequence. `Fluent::Plugin::Apache2Parser#configure` invoked after `Fluent::Plugin::Parser#configure`.
> Delay time parser initialization

- test/plugin/test_formatter_ltsv.rb
Source code
https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/formatter_ltsv.rb#L26-L28
Document
https://docs.fluentd.org/v0.14/articles/formatter_ltsv#addnewline-boolean-optional-defaults-to-true
> Fix test_config_params of ltsv formatter

- lib/fluent/plugin/formatter_tsv.rb
- test/plugin/test_formatter_tsv.rb
I found that writing to new line is impossible with tsv formatter.
So, I add `add_newline` parameter to control writing to new line by tsv formatter.
> Add support to enable writing to new lines for tsv formatter

- README.md
http://get.treasuredata.com/Fluentd_education
is redirected to 
https://www.treasuredata.com/
So, I modified URL to link https://www.fluentd.org/newsletter_signup
> update Newsletters URL of README.md

- CONTRIBUTING.md
- ENTERPRISE_PROVIDERS.md
- README.md
- fluentd.gemspec
- lib/fluent/plugin/out_forward.rb
- lib/fluent/plugin/out_stream.rb
- lib/fluent/test/helpers.rb
- templates/new_gem/README.md.erb
I updated url of the following domain from http to https.
- www.fluentd.org
- docs.fluentd.org
- kafka.apache.org
- www.splunk.com
- cncf.io
- fluentd.org
- github.com
- groups.google.com
- slack.fluentd.org
- docs.ruby-lang.org
- test-unit.github.io
> Update url from http to https

- lib/fluent/plugin_helper/cert_option.rb
- test/plugin_helper/test_server.rb
Fixes #1711 and fluent/fluent-bit#350.
> Improve generated certificates' conformance to X.509 specification

- lib/fluent/plugin/out_file.rb
- lib/fluent/plugin/out_secondary_file.rb
- lib/fluent/plugin/output.rb
- test/plugin/test_out_file.rb
- test/plugin/test_out_secondary_file.rb
- test/plugin/test_output.rb
`${chunk_id}` placeholder is useful for out_file like plugins.
So I added `CHUNK_ID_PLACEHOLDER_PATTERN` in Output to share.
For example, out_webhdfs uses own `${chunk_id}` value but it should use this predefined constant.
> out_file/out_secondary_file: Support ${chunk_id} placeholder. fix #1705

- lib/fluent/plugin_helper/record_accessor.rb
- test/plugin_helper/test_record_accessor.rb
In previous version, following just raise error:
```
record_accessor_create(%q($["key1"]["key2"]))
```
> Support double quotes in record_accessor bracket notation

- lib/fluent/supervisor.rb
> Show running ruby version in startup log

- lib/fluent/plugin/buf_file.rb
This is useful for debugging because it makes it easier to associate chunks with their corresponding metadata in the fluentd logs.
> log when a new file chunk has been created

- lib/fluent/plugin/base.rb
- lib/fluent/plugin/buf_file.rb
- lib/fluent/plugin/in_tail.rb
pos_file duplication causes broken state.
In addition, move `buffer_path_for_test?` to Base class to share the routine.
> Check pos_file duplication between in_tail sources

- lib/fluent/plugin/buffer.rb
This PR resolves https://github.com/fluent/fluentd/issues/1549.
For example, deadlock occurs by the following steps before this commit:
1. input plugin thread receives multiple events
(`metadata_and_data.size > 1`)
2. input plugin thread processes the first `metadata_and_data` element
and aquires the lock of chunk1 (`chunk.mon_exit` in `Buffer#write`)
3. enqueue thread aquires the lock of buffer
(`synchronize` in `Buffer#enqueue_chunk`)
4. enqueue thread tries to aquire the lock of chunk1
(`chunk.synchronize` in `Buffer#enqueue_chunk`)
5. input plugin thread processes the second `metadata_and_data` element
and tries to aquire the lock of buffer (`synchronize` in `Buffer#write_once`)
cf. https://github.com/fluent/fluentd/issues/1549#issuecomment-335736547
> Always lock chunks first to avoid deadlock

- lib/fluent/plugin/buffer.rb
- test/plugin/test_buffer.rb
- test/plugin/test_metadata.rb
When 2 or more input plugin threads try to emit events into an output plugin (and its buffer plugin instance), it may occur dead-lock, because the order of chunks to be locked are random for now.
This change introduces to sort metadata before locking chunks, to lock chunks in same order in different threads.
> Lock buffers in order of metadata

- lib/fluent/plugin/in_tcp.rb
- lib/fluent/plugin_helper/server.rb
The TCP input plugin shares a single buffer across all connections.  Under load
the buffer sometimes gets truncated.  The suspicion is that concurrent
connections race to modify it.
Long message is received.
Short message is received while the long message is still being parsed.
The short message is parsed so the buffer will be truncated.
The buffer, which now contains "longmessage\nshort\n", is truncated by the
length of the short message.  It is now "longm".
Another message arrives.  Now the buffer is "longmanother\n", which does not
parse.
The whole buffer is thrown away and subsequent messages are received and
handled as usual.
Eventually the pattern repeats.
The fix is to use a per-connection buffer.
> Issue 1726: Fix for in_tcp log corruption under load.

- lib/fluent/plugin/filter_parser.rb
Escape sequence is affected when user launches fluentd without log option in the console.
> filter_parser: Fix dumpped result for avoiding escape sequence injection

- lib/fluent/plugin/out_forward.rb
In the past, fluentd supports only UDP heartbeat and it uses async check between fluentd nodes.
So if previous node takes longer time for heartbeat, it doesn't affect elapsed time.
On the other hand, recent fluentd supports TCP heartbeat and it uses sync check via tcp connection.
So if previous node takes longer time, it affects elapsed time for current node and it causes misjudgment.
To avoid the problem, elapsed time calculation should be done after heartbeat.
> Move tick check to after heartbeat for avoiding the impact of other node heartbeat. fix #1719

- lib/fluent/supervisor.rb
Old implementation includes dead process pid in `worker_pid` list even if the process is restarted.
This patch replaces dead process pid with new process pid.
> Fix worker_pid handling by replacing old pid with new one. fix #1723

- lib/fluent/plugin/in_tail.rb
This is temporal solution and to log the important information.
In addition, introduce `WatcherSetupError` to unify setup error.
If we have other setup failed cause, we should use this error instead of adhoc logging/error.
> in_tail: Skip setup failed watcher to avoid resource leak and log bloat. ref #1713

- lib/fluent/root_agent.rb
I consider dump entire stacktrace but it sometimes bloats log size.
The important point is checking which plugin causes the error, so I added only first line of stacktrace to show plugin name.
> Add error location to emit error logs. fix #1737

- lib/fluent/command/plugin_generator.rb
- templates/new_gem/lib/fluent/plugin/filter.rb.erb
- templates/new_gem/lib/fluent/plugin/input.rb.erb
- templates/new_gem/lib/fluent/plugin/output.rb.erb
- templates/new_gem/lib/fluent/plugin/parser.rb.erb
- test/command/test_plugin_generator.rb
For example:
Following commands will generate fluent-plugin-rewrite-tag-filter
and register "rewrite_tag_filter".
$ fluent-plugin-generate output rewrite_tag_filter
$ fluent-plugin-generate output rewrite-tag-filter
> Consider hyphen and underscore in fluent-plugin-generate arguments

- lib/fluent/plugin/in_syslog.rb
- lib/fluent/plugin_helper/server.rb
- Add error handling
- Reduce memory allocation
- Reuse built-in buffer
> Cleanup server helper

- bin/fluentd
Based on http://atdot.net/~ko1/activities/2017_fukuoka_rubykaigi_02.pdf
It reduces avg 0.5 mb at startup. I'm not sure performace improvement but default setting should be better.
This option also works on ruby 2.5.
> Disable tracepoint feature to omit unnecessary insts

- lib/fluent/root_agent.rb
Currently, Output's flush_at_shutdown is executed in before_shutdown but
in_tail's multiline buffered logs are flushed in shutdown.
This mismatch causes log lost at shutdown/restart.
To avoid such problem, Input#shutdown should be called before Output#before_shutdown.
If this approach doesn't resolve all cases,
calling order will be changed to v0.12 like sequence.
In addition, we will consider moving flush_at_shutdown routine to `shutdown`.
> Combine before_shutdown and shutdown call in one sequence.

- lib/fluent/plugin/out_forward.rb
- lib/fluent/plugin/output.rb
Ack failure is not buffer flush error so it should not update retry state.
It create invalid retry state and this causes busy loop.
The problematic node is disabled and its node is excluded at next flush after rollback.
So non-acked chunk should be retried next flush.
To resolve this problem, we add update_retry parameter to Output#rollback_write.
This parameter controls rollback considers retry or not.
> Don't update retry state when failed to get ack response. fix #1665

- lib/fluent/plugin/multi_output.rb
- lib/fluent/plugin/out_copy.rb
- test/plugin/test_out_copy.rb
out_copy_ex supports `ignore_error` to ignore emit errors in non-important plugin.
First, we provide this feature via 3rd party plugin because we can't judge this feature is useful or not before.
Currenlty, many users still use copy_ex on the production so merging it into core is good.
> out_copy: support ignore_error in store section

- lib/fluent/plugin/in_tail.rb
- test/plugin/test_in_tail.rb
inotify sometimes lost the events.
We want to investigate inotify in libev causes unexpected behaviour or not.
disable parameter is useful for it.
> in_tail: Add enable_stat_watcher option to disable inotify events

- lib/fluent/plugin/in_tail.rb
Current in_tail already reads the file from head when truncated,
but the position is updated to stat.size. Basically it is misleading and
may cause unexpected behaviour.
> in_tail: Explicitly update position to 0 when the file is truncated

- lib/fluent/plugin/in_udp.rb
- lib/fluent/plugin_helper/socket_option.rb
- test/plugin/test_in_udp.rb
I accidentally failed to update #1787. So I create a new one.
> Add recv_buffer parameter for in_udp

- lib/fluent/plugin/in_udp.rb
- lib/fluent/plugin/socket_util.rb
- test/plugin/test_in_udp.rb
> Add receive_buffer_size parameter for in_udp for v0.12

- lib/fluent/plugin/in_tail.rb
- test/plugin/test_in_tail.rb
When same inode file reappear and the size is smaller than before, it should be handled as truncated. It triggers reading the file from head.
>  in_tail: Properly handle moved back and truncated case

- fluentd.gemspec
- lib/fluent/plugin_helper/record_accessor.rb
Because ruby_dig 0.0.2 does not support a object that responds to dig
method properly. On the other hand, dig_rb 1.0.1 supports it properly.
> Use dig_rb instead of ruby_dig when backport_dig is not installed

- lib/fluent/plugin/parser_ltsv.rb
- test/plugin/test_parser_labeled_tsv.rb
The feature is taken from
https://github.com/fluent-plugins-nursery/fluent-plugin-kv-parser
fluent-plugin-kv-parser is very simple and similar to parser_ltsv.
So we can integrate fluent-plugin-kv-parser with parser_ltsv.
> Add parameter delimiter_pattern to parser_ltsv

- lib/fluent/plugin_helper/server.rb
https://github.com/fluent/fluentd/pull/1729 introduced @buffer to
TCPCallbackSocket. TLSCallbackSocket also has to have it to be used for
in_tcp.
> Fix tcp + tls degradation

- lib/fluent/plugin_helper/record_accessor.rb
- test/plugin_helper/test_record_accessor.rb
Currently, `record_accessor` does not expose internal @keys instance.
We want to use this variable in [fluent-plugin-anonymizer](https://github.com/y-ken/fluent-plugin-anonymizer).
> Expose record_accessor internal instance `@keys` variable. Fix #1806

- lib/fluent/time.rb
`TimeFormatter#format` and `TimeFormatter#call` should call the same method.
> Fix the method for TimeFormatter#call

- lib/fluent/log.rb
- lib/fluent/plugin/buffer.rb
- lib/fluent/plugin/output.rb
1. Improve `Log#on_xxx` API performance with `yield`.
2. Old implementation is error prune. API is `log.on_info { ... }` so error should be thrown when block is not passed.
I searched the plugin code and no `log.on_xxx` without block code so it doesn't break existing plugins.
3. Use `on_trace` API in buffer. `trace` level is rare on the production so frequent object creation for trace logging is not good.
> Improve on logging

- lib/fluent/plugin/filter_record_transformer.rb
- lib/fluent/plugin_helper/record_accessor.rb
- test/plugin/test_filter_record_transformer.rb
- test/plugin_helper/test_record_accessor.rb
Additional feature for `record_accessor`.
This is useful for several mutation plugins.
Ref #1578
> Delete nested field

- fluentd.gemspec
- lib/fluent/log.rb
- lib/fluent/plugin/formatter_stdout.rb
- lib/fluent/plugin/out_stdout.rb
- lib/fluent/time.rb
- lib/fluent/timezone.rb
Use `Strftime` instead of `Time#strftime` improves the performance of time formatting.
> Use Strftime to improve fixed timestamp performance

- bin/fluent-ca-generate
- lib/fluent/command/ca_generate.rb
- test/command/test_ca_generate.rb
I ported secure-forward's certificates generating command from fluent-plugin-secure-forward.
Fix #1795
> Port certificates generating command from secure-forward

- CHANGELOG.md
Update version numbers in CHANGELOG
`v1.1.0` does not belong under `v1.0`
> Update changelog version numbers org

- lib/fluent/plugin/in_http.rb
- test/plugin/test_in_http.rb
I noticed current in_http uses 'time' field value in batch request.
Should emit Fluent::EventTime instead of Integer or Float.
> in_http: Emit event time instead of raw time value in batch

- lib/fluent/plugin_helper/event_loop.rb
- lib/fluent/plugin_helper/timer.rb
Timer plugin helpers may be used to call delayed processing with `repeat: false` option.
But if plugin authors call this method once per minute, `@_event_loop_attached_watchers` will have 60 undeleted objects per hour: that means object leakage.
This change is to fix that problem.
> Fix a bug to leak non-repeating timer watchers

- lib/fluent/plugin/in_debug_agent.rb
- test/plugin/test_in_debug_agent.rb
in_debug_agent will listen sequential port number based on worker_id
just like in_monitor_agent. #1493
> Support multi worker environment in in_debug_agent

- lib/fluent/plugin/parser_json.rb
oj 3.x sometimes raises an EncodingError for input string and it beaks parser_json behaviour.
This patch fixes it.
Here is test code:
```
Oj.load('+ cat /etc/resolv.conf')
```
- oj 3.4.0
```
test_oj.rb:6:in `load': Empty input at line 1, column 1 [parse.c:926] in '+ cat /etc/resolv.conf (EncodingError)
```
- oj 2.18.5
```
test_oj.rb:6:in `load': unexpected character at line 1, column 3 [parse.c:671] (Oj::ParseError)
```
> parser_json: Add EncodingError to rescue list for oj 3.x. fix #1866

- lib/fluent/plugin/buf_file.rb
- lib/fluent/plugin/buffer/file_chunk.rb
- test/plugin/test_buf_file.rb
On k8s environment, we received the report "file chunks are unexpectedly broken and it causes error loop during resume."
This patch mitigates this problem by ignoring broken chunks in resume.
> buf_file: Skip and delete broken file chunks during resume. fix #1760

- lib/fluent/plugin/in_tail.rb
This patch is a fix for a multi-threading bug in Fluentd core. Apparently, this bug
has been one of major causes of the long-standing testing failures on Travis CI.
Essentially, there is a concurrency bug in the implementation of `in_tail`.
While `IOHandler` (in_tail#L673) is not designed to be thread-safe, its method
`on_notify` can be called by multiple threads concurrently.
Here is how it occurs:
1. TailInput calls `on_notify` on detach/shutdown (main thread)
2. In the same time, StatWatcher triggers `on_notify` on filesystem events
(eventloop thread)
In this situation, one thread can see the data retrieved (and being actively
processed) by another thread, which will result in duplication of data records.
This patch fixes the issue by introducing a mutex, which should prevent two …
> in_tail: Prevent IOHandler.on_notify() being called concurrently

- lib/fluent/plugin_helper/cert_option.rb
- lib/fluent/plugin_helper/server.rb
Hi,
This PR add support for Client auth (also knows as [Mutual authentication](https://en.wikipedia.org/wiki/Mutual_authentication)).
This mainly consist of two things:
- Configure SSL context to load `ca_file` from `ca_path` config. In case config is not set it will default to null, which is also acceptable.
- If `client_cert_auth` config is set to `true` then configure SSL context to verify peer certificates.
This is my first ever ruby code and I'm having trouble understanding how to write test, so I would appreciate any help with that.
> Add support for TLS Mutual authentication within forward input

- lib/fluent/plugin/in_tail.rb
This is the fix for the issue reported by the bug report #1055.
It turned out that this bug was a matter of the calling order of functions in `TailWatcher.on_rotate()`.
In particular, when TailWatcher detects a log rotation and immediately finds a new file, it performs the following steps:
1) Create a new TailWatcher for the new file.
* In this process, it reads the new file and emit its contents.
* This all happens before proceeding to (2).
2) Dispatch the `on_notify()` for the archived file.
* In this process, it reads the content of the old file and emit its contents.
So naturally, newer log records (written to the new log file) will be emitted before older records in the archived log file.
This patch fixes it by enforcing flush of older log records before performing the step (1).
> in_tail: Handle records in the correct order on file rotation

- test/plugin/test_out_forward.rb
This is a fix for the test failures occurring on Travis CI every now and then. 
For actual cases of this failure, please see [job#4143.2](https://travis-ci.org/fluent/fluentd/jobs/339180777#L655), [job#4066.5](https://travis-ci.org/fluent/fluentd/jobs/312704505#L175) and [job#4167.2](https://travis-ci.org/fluent/fluentd/jobs/349665601#L907).
The failing test cases are supposed to test the handling of "broken ack responses";
To cut it short, these test cases are designed to perform the following steps:
1. Create an `in_forward` server (which sends back a broken ack response).
2. Create an `out_forward` server.
3. Send some data and check the handling of the broken ack response.
4. Shutdown the both forwarding servers.
The problem is that there might be another flush attempt occurring …
> test: Fix random test failures in test/plugin/test_out_forward.rb

- lib/fluent/config/types.rb
- test/config/test_plugin_configuration.rb
As reported at https://github.com/tagomoris/fluent-plugin-route/issues/10, `config_param :name, :bool` returns falsely value (`nil`) when it's configured without explicit value with following comment.
```ruby
config_param :b1, :bool, default: false
config_param :b2, :bool, default: false
b1
b2 # comment here
```
This bug cannot be reproducible via test cases of v1 parser, but I succeeded to reproduce it using plugin code and test driver. This bug was reported to be reproducible on actual Fluentd processes.
> Fix boolean parameters without value with following comment

- test/plugin/test_output.rb
This patch fixes the test failures around `invoke_slow_flush_log_thread_test()` which
have been occurring at Travis CI.
For actual failing test runs, see [job#4160.1](https://travis-ci.org/fluent/fluentd/jobs/348128345#L1336), [job#4169.4](https://travis-ci.org/fluent/fluentd/jobs/350206345#L844) and [job#4154.5](https://travis-ci.org/fluent/fluentd/jobs/347253490#L888)
I can reproduce this failure reliably by inserting `sleep 3` into [test_output.rb](https://github.com/fluent/fluentd/blob/master/test/plugin/test_output.rb#L909):
```ruby
def invoke_slow_flush_log_threshold_test(i)
...
i.start
i.after_start
sleep 3
t = event_time()
i.emit_events('tag', Fluent::ArrayEventStream.new([ [t, {"key" => "value1"}],
[t, {"key" => "value2"}] ]))
i.force_flush
waiting(4) { Thread.pass until …
```
> test: Fix random test failures at test/plugin/test_output.rb#L926

- lib/fluent/plugin/filter_grep.rb
- test/plugin/test_filter_grep.rb
In prevous version, following pattern raises syntax error:
<filter>
@type grep
<regexp>
key price
pattern [1-9]\d*
</regexp>
</filter>
This example is derrived from [filter-grep](https://docs.fluentd.org/v1.0/articles/filter_grep#<regexp>-directive)
> Support pattern start with character classes

- lib/fluent/plugin/out_forward.rb
- test/plugin/test_out_forward.rb
state, shared_key_nonce and auth are per request information.
Don't share these variables because Node#send_data is executed in multi thread
when flush_thread_count is larger than 2.
> out_forward: Fix race condition with <security> on multi thread environment. fix #1878

- lib/fluent/plugin/output.rb
I believe this patch fixes the CPU spikes issue reported by #1636 and #1889
(possibly also #1665).
If one flush thread sets the retry state, this makes other threads
wait until the next retry time. This behaviour itself is fine and ok.
However, in this case the `interval` variable has a meaningless value
because `state.next_clock` is behind the system time. And since the
sleep call gets skipped in such a case:
```ruby
while @output_flush_threads_running
current_clock = Fluent::Clock.now
interval = state.next_clock - current_clock
...
sleep interval if interval > 0
end
```
it effectively make the waiting threads to consume the resource
aggressively with busy loops.
This patch makes a flush thread to wait in a sleep state until the
next retry time, insteads of busy looping
This bug seems to …
> output: Prevent flushing threads from consuming too much CPU.

- lib/fluent/plugin/output.rb
- test/plugin/test_output.rb
For example,
tag is `fluentd.test.output`
`${tag[-1]}` is extracted to `output`
`${tag[-2]}` is extracted to `test`
It is useful to extract last element of variable length tag.
> Support negative index for tag when extract placeholders

- lib/fluent/time.rb
```ruby
time = Fluent::EventTime.now
p time # => #<Fluent::EventTime:0x00005635d50ecdb8 @sec=1522311320, @nsec=861617325>
p time # => 2018-03-29 17:15:20.861617325 +0900
```
> Define Fluent::EventTime#inspect method

- lib/fluent/plugin/buffer.rb
This should fix the memory-leak bug described in #1918.
> Delete empty queued_num field after purging chunks

- lib/fluent/plugin/buffer.rb
- lib/fluent/plugin/output.rb
- test/plugin/test_output_as_buffered_retries.rb
Releated to https://github.com/fluent/fluentd/issues/1904
Current patch resolves generating lots of queued chunks with small flush_interval.
Note that v0.12's the number of queues is 1.
I will check how control this parameter with `write` families.
> buffer: Add queued_chunks_limit_size to control the number of queued chunks

- lib/fluent/plugin/out_forward.rb
With TLS socket, `readpartial` raise EOFError unlike `recv` when connection is broken.
> out_forward: The node should be disabled when TLS socket for ack returns an error. Fix #1923

- CHANGELOG.md
`<foo>` is eaten by markdown renderer.
> Fix CHANGELOG markups

- lib/fluent/plugin/filter_grep.rb
- test/plugin/test_filter_grep.rb
For example:
<filter>
@type grep
<and>
<regexp>
key level
pattern ^WARN|ERROR$
</regexp>
<regexp>
key method
pattern ^GET$
</regexp>
</and>
</filter>
For more details, see test code
See #1858
> Support and/or section

- lib/fluent/config/types.rb
- lib/fluent/configurable.rb
- lib/fluent/plugin/filter_grep.rb
- lib/fluent/plugin/parser_apache.rb
- lib/fluent/plugin/parser_apache_error.rb
- lib/fluent/plugin/parser_ltsv.rb
- lib/fluent/plugin/parser_multiline.rb
- lib/fluent/plugin/parser_nginx.rb
- lib/fluent/plugin/parser_regexp.rb
- test/config/test_config_parser.rb
- test/config/test_configure_proxy.rb
- test/config/test_types.rb
- test/plugin/test_in_exec.rb
- test/plugin/test_parser_regexp.rb
This PR supports following configuration:
```ruby
config_param :pattern, :regexp
```
See also https://github.com/fluent/fluentd/pull/1897#discussion_r178730491
> Support regexp type

- lib/fluent/plugin/parser_nginx.rb
- test/plugin/test_parser_nginx.rb
Closing #1907, an update to the docs has been proposed in fluent/fluentd-docs#471.
Signed-off-by: yaron-idan <yaronidan@gmail.com>
> added http-x-forwarded-for field to nginx parser

- lib/fluent/plugin/filter_grep.rb
- Remove catch
- Reduce method call
```
old     3.371k i/100ms
new     3.522k i/100ms
old     33.531k (± 4.1%) i/s -    168.550k in   5.035547s
new     35.888k (± 3.4%) i/s -    179.622k in   5.011044s
```
> filter_grep: Improve the performance

- MAINTAINERS.md
Update new list of Fluentd maintainers.
Signed-off-by: Eduardo Silva <edsiper@gmail.com>
> Doc: Update Fluentd Maintainers List

- lib/fluent/plugin_helper/server.rb
We can't recover SSL error so closing socket is better than process crash.
in_forward continue to accept new request.
> Close invalid socket when ssl error happens on reading. fix #1924

- lib/fluent/log.rb
- lib/fluent/supervisor.rb
This PR resolves https://github.com/fluent/fluentd/issues/1951.
```
% git rev-parse HEAD
59d96759253c3894d7a7d398f2647f218ffdae18
% bundle exec ./bin/fluentd -c ./fluent.conf --log /tmp/fluent.log --log-rotate-age 1 --log-rotate-size 1024 &
[1] 19569
% kill -USR1 19569
Unexpected error wrong number of arguments (given 2, expected 0..1)
/Users/arabiki/.anyenv/envs/rbenv/versions/2.4.2/lib/ruby/2.4.0/logger.rb:715:in `reopen'
/Users/arabiki/ghq/src/github.com/fluent/fluentd/lib/fluent/supervisor.rb:364:in `reopen!'
/Users/arabiki/ghq/src/github.com/fluent/fluentd/lib/fluent/supervisor.rb:163:in `supervisor_sigusr1_handler'
/Users/arabiki/ghq/src/github.com/fluent/fluentd/lib/fluent/supervisor.rb:137:in `block in install_supervisor_signal_handlers' …
```
> Resolve unexpected exit on SIGUSR1

- lib/fluent/env.rb
- lib/fluent/plugin/output.rb
- test/plugin/test_output_as_buffered_backup.rb
Fix https://github.com/fluent/fluentd/issues/1856
Current implementation covers most bad chunk cases. I need feedback before writing test.
-  use `root_dir` parameter for backup directory when specified, `/${root_dir}/backup/worker${worker_id}/${plugin_id}/${chunk_id}.log`.
- Call secondary directly when unrecoverable error happens
> output: Add backup feature for bad chunks

- lib/fluent/plugin/in_tcp.rb
- lib/fluent/plugin/in_udp.rb
- test/plugin/test_in_tcp.rb
- test/plugin/test_in_udp.rb
> in_udp/in_tcp: Fix source_hostname_key

- test/plugin/test_output_as_buffered_backup.rb
By thread scheduling, assertions are executed before backup files are generated.
To fix this problem, add waiting code. If the problem happens, timeout error should be raised.
> Fix unstable tests of backup feature

- lib/fluent/plugin/in_monitor_agent.rb
- test/plugin/test_in_monitor_agent.rb
Now, in_monitor_agent's buffer_total_queued_size does't count queued chunk's sizes.
So fix for counting them.
- Version: Fluent1.1.3
- Buffer Settings
```
<buffer topic,tag>
@type                       file
path                        "/var/log/td-agent/buffer/#{ENV['PROCESS_NAME']}.forward_to_kafka.*.log"
queued_chunks_limit_size    10000
chunk_limit_size            32m
total_limit_size            2400m
flush_mode                  interval
flush_interval              1.0
flush_thread_burst_interval 0.1
flush_thread_count          5
retry_forever               true
retry_max_interval          30s
overflow_action             drop_oldest_chunk
</buffer>
```
- When that buffer plugin occured `dropping oldest chunk to make space after buffer overflow`, in_monitor agent returned below results. …
> Fix in_monitor_agent's buffer_total_queued_size

- lib/fluent/plugin/out_file.rb
Direct append causes broken gzipped file when Zlib::DataError happens.
This patch uses Tempfile for gzip compression to avoid broken compression.
> out_file: Temporal fix for broken gzipped files with gzip and append. ref #1903

- lib/fluent/counter/client.rb
- lib/fluent/counter/error.rb
- test/counter/test_client.rb
Similar to "get" but raises an error when API call has a problem.
> counter: Add wait API

- lib/fluent/config/configure_proxy.rb
- test/command/test_plugin_config_formatter.rb
- test/config/test_configure_proxy.rb
In previous version, fluent-plugin-config-format command does not dump
information defined by config_argument. We cannot reconstruct a plugin
config definition from dumped config.
> Dump config_argument by dump_config_definition

- README.md
I think the link about fluentd was mistook (may be old link). 
So did small change and send a PullRequest for README.
> Fix mistook weblink in README

- lib/fluent/plugin/filter_parser.rb
- test/plugin/test_filter_parser.rb
With reserve_data, key_name field is kept by default. But sometimes
users don't need key_name field when parsing is succeeded, e.g. docker log.
So removing key_name feature is useful for simple configuration.
Currently, we need more filter is needed to remove target field.
> filter_parser: Add remove_key_name_field parameter

- lib/fluent/plugin/in_tail.rb
- test/plugin_helper/test_child_process.rb
Signed-off-by: 焦龙 <jiaolongdy@163.com>
> change read_pos and read_ino. relate #1953 #1804

- lib/fluent/plugin/buffer.rb
This PR resolves https://github.com/fluent/fluentd/issues/1999.
> Wait for all chunks being purged before deleting @queued_num items

- lib/fluent/config/configure_proxy.rb
In previous version, fluent-plugin-config-format could not dump
configuration for some plugins.
See also, https://gist.github.com/okkez/1ac4b1f322275e72982803856f4737a7
> Avoid NoMethodError while running Fluent::Config::ConfigureProxy#dump_config_definition

- lib/fluent/plugin/in_http.rb
- test/plugin/test_in_http.rb
This patch fixes the issue reported by Eugen Cristea at fluent/fluentd-docs#507.
`in_http` plugin supports "batch" mode for sending multiple events in a single HTTP request.
The problem is that in_http does not honor the `keep_time_key` option when processing
those bulk-insertion requests.
This means that "time" key in each record gets discarded unconditionally in batch mode.
For example, the following request:
$ curl -d '[{"time":1514736000,"key":"foo"}]' http://localhost/
will produces a log record:
2018-01-01 01:00:00.000000000 +0900 : {"key":"foo"}
... even if the `keep_time_key` option is enabled.
This patch fixes this issue by teaching `in_http` to honor the option value of its parser
plugin instance.
> in_http: Honor `keep_time_key` parameter in batch mode.

- templates/new_gem/lib/fluent/plugin/parser.rb.erb
In Parser plugin template for fluent-plugin-generate, parse method definition is in `Fluent::Plugin` module.
I think it should be in `Fluent::Plugin::<class_name>` class.
> Fix Parser plugin template for fluent-plugin-generate

- lib/fluent/plugin/compressable.rb
This patch expect to reduce copy string object.
benchmark with minor revisions in https://github.com/fluent/fluentd-benchmark/tree/182f773eb2e2f0ba96520d80cd2a1a8541e05875/one_forward
agent.conf
```
<source>
@type tail
path dummy.log
pos_file /var/tmp/_var_log_dummy.pos
format none
tag dummy
</source>
<match dummy>
@type copy
<store>
@type forward
flush_interval 0
try_flush_interval 1
buffer_chunk_limit 1m
buffer_queue_limit 64
num_threads 32
compress gzip
<server>
host 127.0.0.1 # FIX ME
port 24224
</server>
</store>
</match>
```
receiver.conf
```
<source>
@type forward
port 24224
</source>
<match dummy>
@type flowcounter_simple
unit minute
</match>
```
dummer.conf
```
configure 'sample' do
output "dummy.log"
message "time:2013-11-25 00:23:52 …
```
> Compressable#decompress Improve performance

- lib/fluent/config/dsl.rb
- test/config/test_dsl.rb
- test/test_configdsl.rb
> dsl: Need '@' prefix for reserved system parameters. fix #2028

- lib/fluent/plugin/in_monitor_agent.rb
This is a minor patch that adds documentation for each configurable
option of Fluent::Plugin::MonitorAgentInput, which is currently
missing from the source code.
> monitor_agent: Add missing descriptions for configurable options.

- test/counter/test_client.rb
- test/counter/test_server.rb
- test/counter/test_store.rb
This patch fixes the test cases in `test/counter/test_client.rb` which are constantly
failing on AppVeyor right now. For examples:
- https://ci.appveyor.com/project/fluent/fluentd/build/3009/job/linub6g6b83d4t3c
- https://ci.appveyor.com/project/fluent/fluentd/build/3008/job/6ng3not4p900fxrc
- https://ci.appveyor.com/project/fluent/fluentd/build/3007/job/gyxnqulia1eknc6q
Evidently, Timecop.travel induces flogting-point errors to Time.now on
Windows environment:
```ruby
>>> Time.freeze(Time.parse('2016-09-22 16:59:59 +0900'))
>>> Timecop.travel(6)
>>> printf("#{Time.now.to_i}.#{Time.now.nsec}\n")
1474531204.999999999
```
... and this seems to be the cause of these test failures.
This patch fixes the issue by introducing a helper method `travel()` that
allows to travel back/forward without …
> test/counter: Fix test failures on AppVeyor due to rounding errors.

- test/plugin/test_out_file.rb
AppVeyor CI tests are constantly failing due to Zlib-related exceptions
like below:
Error: test: append(FileOutputTest): Zlib::DataError: invalid
distance too far back
This is a very weird error, because the file seems to contain a proper
gzip-compressed data stream. In fact, by inserting the following code
before the failing line, I can confirm that the file itself is NOT
broken:
```ruby
bytes = File.open(path).read   // Read the file being tested
puts(Zlib::GzipReader.new(StringIO.new(bytes)).read)
```
The strong suspicion is that Ruby's Zlib wrapper (or its build on
AppVeyor) has a serious bug that corrupts file pointers passed to
GzipReader, thus it ends up reading garbage data.
This patch is my attempt to mitigate the issue by modifying the test
functions to pass bytes (rather than …
> test_out_file.rb: Fix test failures due to Zlib::DataError.

- fluentd.gemspec
The link in rubygems doesn't seem to work for me because `fluentd.org` isn't listening to the https port.  `fluentd.org:80` does forward on to `https://www.fluentd.org`, but that isn't what is in the gemspec file.  Could change it to use http in the gemspec file maybe but better to just https everything I think.
> ssl on fluentd.org does not appear to work

- test/plugin_helper/test_retry_state.rb
This fixes 'check inf handling' test not to fail on AppVeyor CI anymore.
Specifically, in this test script, it is assumed that `0.1 * 2 ** 10.25`
overflows the float boundary and becomes an infinite number. This is not
quite true because the result is roughly `1.79e+307` and it's actually well
below the upper boundary of double-precision floats.
Still, even though the resulting number is within the maximum limit, the
test case passes on *most* environments because an overflow *will* occur
while computing raw_interval():
```ruby
def raw_interval(num)
@constant_factor.to_f * (@backoff_base ** (num))
end
```
Note: In the line above, `@backoff_base ** num` is roughly 1.79e+308, so it will
become an infinite number *if implicit type conversion occurs while evaluation.* In
other words, this …
> test_retry_state: Fix a test failure on AppVeyor with Ruby 2.3 (x86)

- lib/fluent/supervisor.rb
When the main process ends, the supervisor outputs an info log containing its exit status.
However, It seems confusing when the exit status of the main process is not 0.
E.g. (In my environemnt)
```
2018-07-04 09:45:38 +0900 [info]: process finished code=256
2018-07-04 09:44:26 +0900 [info]: process finished code=9
```
It seems to be caused by using `$?.to_i`.
Therefore, I tried to output the exit status and signal separately by using `$?.exitstatus` and` $?.termsig`.
E.g.
```
2018-07-04 09:47:30 +0900 [info]: process finished status=1 signal=nil
2018-07-04 09:49:11 +0900 [info]: process finished status=nil signal=9
```
I hope this help. (Is this the format of the log message OK?)
> Fix log when main process is finished

- lib/fluent/plugin/parser_syslog.rb
Per RFC5424, the field for PROCID is either a NILVALUE (-) or ASCII field from 1 to 128 characters.
https://tools.ietf.org/html/rfc5424#section-6
Valid RFC5424 formatted log using alphanumeric PROCID(PID) value of '__proc1__':
<16>1 2013-02-28T12:00:00.003Z 192.168.0.1 fluentd __proc1__ ID24224 [exampleSDID@20224 iut="3" eventSource="Application" eventID="11211"] Hi, from Fluentd!
The regex in this PR commit will properly match the example above.
Replacing PR #2049
> update regex of pid field for conformance to RFC5424 spec

- lib/fluent/plugin/in_http.rb
- test/plugin/test_in_http.rb
This adds support to `in_http` for the 'Content-Encoding' header,
which allows HTTP clients to transfer payload more efficiently by
applying compression (Currently it supports `gzip` and `deflate`).
You can test it using the following command:
```bash
$ echo 'json={"foo":"bar"}' | gzip > json.gz
$ curl --data-binary @json.gz -H "Content-Encoding: gzip" \
http://localhost:9880/debug.log
````
This feature should be useful especially for users who handle large
amounts of data.
> in_http: Allow users to send payload in compressed form

- lib/fluent/plugin/in_http.rb
- test/plugin/test_in_http.rb
This patch fixes the bug reported by #2035 (and other related issues as well).
What used to happen is that options in the `<parser>` section get ignored
when we send events as a JSON array. This occurs because parser plugins
are designed to handle a single hash value and do not generallly handle
an array input well.
Until now, we have tried to solve this issue by emulating the semantics
of parser plugins in Fluent::Plugin::HttpInput (see 1afbfb1, 39f3a0d
and f560017c). However, this approach turned out to be error prone and
rather tedious.
This patch takes a different path:
- Whenever `@parser` is available, reuse `@parser.convert_values()` by
manually applying it to each record in an input array.
- Otherwise, fall back to the current logic.
The good part of this approach is that we do …
> in_http: Fix "ignored parser options" problem on bulk insertion

- lib/fluent/root_agent.rb
- test/test_root_agent.rb
When setting `--emit-error-log-interval` command line parameter, fluent instead prints the following error which masks other errors:
```
fluentd_1       | 2018-07-12 23:18:26 +0000 [error]: #0 failed to emit fluentd's log event tag="fluent.error" event={"host"=>"172.20.0.1", "port"=>42300, "error"=>"#<ArgumentError: comparison of Time with 1531437277 failed>", "message"=>"unexpected error on reading data host=\"172.20.0.1\" port=42300 error_class=ArgumentError error=\"comparison of Time with 1531437277 failed\"", "time"=>"2018-07-12T23:18:26Z"} error_class=ArgumentError error="comparison of Time with 1531437277 failed"
```
Ensure time is in epoch format before comparison
Add tests
> Fix bug in suppress_emit_error_log_interval

- lib/fluent/plugin/output.rb
- lib/fluent/timezone.rb
- test/plugin/test_out_file.rb
Because the timestamp of the midnight cannot be divisible by 86400 in
localtime (JST). The timestamp of the midnight is divisible by 86400
only in UTC. Therefore we must consider offset from UTC in localtime.
For example, at `2018-07-04 01:23:23 +0900`:
If timekey is 86400 and path template is `/log/%Y%m%d.log`.
In previous version, extract path template to `/log/20180703.log`.
In this version, extract path template to `/log/20180704.log`.
Fix #1986
> Consider timezone when calculate timekey

- lib/fluent/plugin_helper/server.rb
If clients shutdown the connection immediately, `close` callback is
sometimes called before `connect` callback. It causes connection object leak.
> server-helper: Fix connection leak by close timing issue. fix #2086

- lib/fluent/plugin/in_tail.rb
> in_tail: Fix rotation related resource leak. fix #1941

- lib/fluent/plugin/output.rb
- test/command/test_plugin_config_formatter.rb
- test/plugin/test_output_as_buffered_backup.rb
> output: Add disable_chunk_backup for ignore broken chunks. fix #2112

- lib/fluent/plugin/in_tail.rb
We're trying to migrate to Fluentd for transferring web-server logs to HDFS and I can't understand why we are the first who face this issue. 
After deploying to one server with production load (read_from_head true) we restarted td-agent and after a while we found duplicated log records in HDFS storage. A quick examination led us to a strange inconsistency in pos_file like this line:
`/data/htlogs/00000000b2ebab5f/data/htlogs/nginx/w11009.log      00000000029ba830        000000000000601a9/data00000000000332a15875.log  0000000000000000        0000000000421e96`
I added debug log and found the mixing of seek and write operations from different threads. The first thread was updating log files current position (set file.pos, write) and the second thread was adding new records to pos_file (set …
> Prevent thread switching in the interval between seek and write operations to pos_file

- lib/fluent/plugin/in_http.rb
- test/plugin/test_in_http.rb
This allows users to set up the configuration like below:
<match debug.**>
@type http
cors_allow_origins ["*"]
</match>
In this case, any origin can make a request to Fluentd; Plugin users
do not need to enumerate all the possible origins explicitly, so it
should be useful for, say, collecting data from a group of websites.
See [MCD "Access-Control-Allow-Origin" header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin)
> in_http: Allow specifying the wildcard '*' as the CORS domain 

- lib/fluent/plugin/parser_syslog.rb
- test/plugin/test_parser_syslog.rb
Fix issues reported in #2068 partialy.
1. not yet for now (I could not find the example about this)
2. fixed
3. fixed
> Improve parser_syslog regexp for RFC5424

- lib/fluent/plugin/parser_json.rb
Sometimes LoadError is raised while loading oj gem, even if oj gem is
installed. Therefore we want to see the correct message of LoadError.
For example, Alpine Linux provides the package ruby which does not
include bigdecimal and provides ruby-bigdecimal.
See #2136
Signed-off-by: Kenji Okimoto <okimoto@clear-code.com>
> Handle LoadError properly

- lib/fluent/plugin/in_http.rb
- test/plugin/test_in_http.rb
This patch should fix the issue #1701.
To receive a 'application/json' request from another origin, we need
to be able to handle CORS preflight requests. Otherwise, browsers will
refuse to interact with us.
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests
This patch adds support for the feature.
> in_http: Implement support for CORS preflight requests

- lib/fluent/config/v1_parser.rb
Related to https://github.com/treasure-data/omnibus-td-agent/issues/181
Before:
```
/Users/repeatedly/dev/fluentd/fluentd/lib/fluent/config/v1_parser.rb:160:in `read': include error aaaaaaaaaa.conf (Fluent::ConfigParseError)
```
After:
```
/Users/repeatedly/dev/fluentd/fluentd/lib/fluent/config/v1_parser.rb:160:in `read': include error aaaaaaaaaa.conf - No such file or directory @ rb_sysopen - xxx (Fluent::ConfigParseError)
```
> Show root error cause when @include raises an error

- lib/fluent/plugin/in_forward.rb
- lib/fluent/plugin/out_forward.rb
- lib/fluent/plugin_helper/server.rb
TLSServer acquires lock in `on_writable` and `on_write_complete` callback is called inside its lock via cool.io.
To avoid this problem, callback order is moved to after cool.io's `on_writable`.
This patch includes out_forward tiny change to show the destination.
> Fix deadlock between on_writable and close

- lib/fluent/plugin/in_syslog.rb
- test/plugin/test_in_syslog.rb
Add `frame_type` parameter to accept octet counting.
If set `frame_type octet_count` in the configuration, `in_syslog` can accept octet counting messag from senders.
> in_syslog: Support octet counting frame. fix #1679

- lib/fluent/plugin/output.rb
- test/plugin/test_output.rb
> Check secondary type to avoid unexpected error. fix #2167

- lib/fluent/plugin/output.rb
UNRECOVERABLE_ERRORS are thought to be rather critical, so we will
benefit from backtrace output.
Originally emitted in fluentd v1.3 or earlier, but suppressed in
https://github.com/fluent/fluentd/commit/c011256bec95eca
Signed-off-by: Eiichi Tsukata <devel@etsukata.com>
> emit backtrace on UNRECOVERABLE_ERRORS

- lib/fluent/plugin/output.rb
Thread#run causes unexpected interruption and it affects
the behaviour of some libraries, e.g. DataError in zlib.
Use condition variable instead to handle thread execution.
This change is based on jl2005's #1984 patch.
Ref https://github.com/fluent/fluentd/issues/1847 / https://github.com/fluent/fluentd/issues/1903 
> Remove `Thread#run` to avoid unexpected interruption.

- lib/fluent/plugin/buffer.rb
- lib/fluent/plugin/output.rb
- test/plugin/test_buffer.rb
- test/plugin/test_output_as_buffered.rb
- test/plugin/test_output_as_buffered_retries.rb
- test/plugin/test_output_as_buffered_secondary.rb
Unlimited queued_chunks_limit_size causes unexpected resource consumption, e.g. lots of smaller files with file buffer, when
the destination has a problem with smaller flush_interval.
The default behaviour should be safe so use flush_thread_count by default.
> Use flush_thread_count value for queued_chunks_limit_size when queued_chunks_limit_size is not specified

- lib/fluent/config/types.rb
- test/config/test_types.rb
This change can raise Fluent::ConfigError when right slash is missing.
This helps users to notice the weird behavior like #2175.
> Check right slash position

- lib/fluent/plugin/out_forward.rb
- test/plugin/test_out_forward.rb
Clarify the meaning of the parameter.
See #1879 for more details
> out_forward: Rename parameter tls_cert_path to tls_ca_cert_path

- lib/fluent/plugin/out_forward.rb
- test/plugin/test_out_forward.rb
Added an option to check the out_forward node and communication when starting fluentd.
It is a matter with the following mailing list.
https://groups.google.com/forum/#!topic/fluentd/2ITnHbveYIM
Hello
I am using fluentd v1.2.6 in TLS encryption mode when forwarding in out_forward -> in_forward.
At fluentd startup I'd like to check if the out_forward process can connection with the in_forward node before listening for the forward port.
Does anyone know a good way about this?
The use case is below.
Existing applications are built across AWS and GCP, and the analysis base is in GCP.
I use out_forward TCP encryption for AWS and GCP connections.
The out_forward on the AWS side is redundant with the Active / Standby configuration.
When fluentd is deployed Switch from Active to Standby and …
> Add connection check at startup when out_forward.

- lib/fluent/plugin/filter_record_transformer.rb
When stopping fluentd, sometime I get follwoing error message on stderr;
```
Unexpected error undefined method `class' for #<Fluent::Plugin::RecordTransformerFilter::RubyPlaceholderExpander::CleanroomExpander:0x00007f7f1aca50d0>
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/sigdump-0.2.4/lib/sigdump.rb:74:in `block in dump_object_count'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/sigdump-0.2.4/lib/sigdump.rb:73:in `each_object'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/sigdump-0.2.4/lib/sigdump.rb:73:in `dump_object_count'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/sigdump-0.2.4/lib/sigdump.rb:18:in `block in dump'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/sigdump-0.2.4/lib/sigdump.rb:136:in `open'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/sigdump-0.2.4/lib/sig …
```
> Keep 'class' method to avoid error with Sigdump.dump on server stop.

- lib/fluent/plugin/out_forward.rb
- test/plugin/test_out_forward.rb
Follow up of https://github.com/fluent/fluentd/pull/2181
I reconsider for deprecated parameter. The use-case of cert_path, non CA cert can be specified for server certificate case. See https://www.fluentd.org/blog/fluentd-v0.14.12-has-been-released
So I just removed `deprecated` but keep to provide 2 parameters for clear naming.
> out_forward: Separate parameter names for certificates

- lib/fluent/plugin_helper/record_accessor.rb
- test/plugin_helper/test_record_accessor.rb
In previous version, following configuration does not work properly:
```
<source>
@type dummy
dummy [
{"foo.bar": "test1234", "message": "Hello"}
]
tag dummy
</source>
<filter dummy>
@type record_transformer
remove_keys "$['foo.bar']"
</filter>
<match dummy>
@type stdout
</match>
```
This shows like following:
```
2018-11-27 15:19:18 +0900 [info]: #0 fluentd worker is now running worker=0
2018-11-27 15:19:19.008586045 +0900 dummy: {"foo.bar":"test1234","message":"Hello"}
2018-11-27 15:19:20.009721132 +0900 dummy: {"foo.bar":"test1234","message":"Hello"}
2018-11-27 15:19:21.010784035 +0900 dummy: {"foo.bar":"test1234","message":"Hello"}
```
In this version, it works well.
See also #2109
> Delete top level using bracket style properly

- lib/fluent/plugin/in_tail.rb
- test/plugin/test_in_tail.rb
We recently encountered an issue where the subdirectory the `pos_file` should be written to didn't exist, causing the in_tail plugin to emit an exception and crash fluentd, resulting in a crash loop. The process had permission to write to the parent directory so it could have easily created the directory and avoided an outage. This change adds a mkdir_p call to create the directory if it detects that the directory the pos_file is in doesn't exist.
/cc @repeatedly
> Create pos file directory if it doesn't exist

- lib/fluent/plugin/output.rb
In the previous version, the timestamp of next_retry_seconds is the same
as logs when retrying.
Fix #2201
> Fix logs when retrying

- lib/fluent/plugin/out_forward.rb
- lib/fluent/plugin_helper/socket.rb
> out_forward: Support mutual TLS. fix #1879

- lib/fluent/plugin/buf_file.rb
This change fixes a typo in debug message.
Signed-off-by: Hokuto Hoshi <hok.kanny@gmail.com>
> Fix a typo in buf_file.rb

- lib/fluent/plugin/parser_syslog.rb
Because String#squeeze is about 7x faster than String#gsub.
See also https://gist.github.com/okkez/6e199011505c6db7e2e1003cc94f8cbc
> Use String#squeeze instead of String#gsub

- lib/fluent/plugin/parser_syslog.rb
- test/plugin/test_parser_syslog.rb
> parser_syslog: Support RFC5424 timestamp without subseconds

- appveyor.yml
> appveyor: Remove Ruby 2.1 CI targets on appveyor. Fix #2255

- lib/fluent/plugin/in_http.rb
Log example:
```
2019-01-15 20:15:09 +0900 [debug]: #0 fluent/log.rb:302:debug: incoming event is invalid: path=/log : params={"json":"json={\"var1\":\"1001.01\",\"var2\":10222.66}","HTTP_HOST":"localhost:8080","HTTP_USER_AGENT":"curl/7.43.0","HTTP_ACCEPT":"*/*","HTTP_CONTENT_TYPE":"application/json","HTTP_CONTENT_LENGTH":"39","REMOTE_ADDR":"127.0.0.1"}
```
> in_http: Add debug log for invalid event. ref #2262

- lib/fluent/plugin/in_tcp.rb
- lib/fluent/plugin/in_udp.rb
- test/plugin/test_in_tcp.rb
- test/plugin/test_in_udp.rb
in_tcp and in_udp might raise the following error:
```log
ArgumentError: parse: init is specified, but there're parameters without default values:@type
/home/hhatake/GitHub/fluentd/lib/fluent/config/section.rb:178:in `block in generate'
/home/hhatake/GitHub/fluentd/lib/fluent/config/section.rb:169:in `each'
/home/hhatake/GitHub/fluentd/lib/fluent/config/section.rb:169:in `generate'
/home/hhatake/GitHub/fluentd/lib/fluent/configurable.rb:94:in `configure'
/home/hhatake/GitHub/fluentd/lib/fluent/plugin/base.rb:57:in `configure'
/home/hhatake/GitHub/fluentd/lib/fluent/plugin_id.rb:39:in `configure'
/home/hhatake/GitHub/fluentd/lib/fluent/log.rb:580:in `configure'
/home/hhatake/GitHub/fluentd/lib/fluent/plugin_helper/event_emitter.rb:73:in `configure' …
```
> in_tcp: in_udp: Add <parse> section checking. Fix #2266

- lib/fluent/plugin/output.rb
- lib/fluent/plugin_helper/retry_state.rb
- test/plugin/test_output_as_buffered_retries.rb
Enable retry_forever with `<secondary>`.
Only unrecoverable errors are moved to secondary output.
> output: Work retry_forever and <secondary> together. fix #2257

- lib/fluent/plugin/out_file.rb
- test/plugin/test_out_file.rb
Since v1, `path` parameter supports placeholders and it means multiple buffer files exist at the same time.
So hard to refer *latest* buffer file via `symlink_path`. To resolve this problem, support placeholders in `symlink_path`.
The drawback is lots of symlink are created when there are various tags/field.
> out_file: Support placeholders in symlink_path parameter

- lib/fluent/config/v1_parser.rb
- test/config/test_config_parser.rb
> Support embedded Ruby code in section attributes. Fix #2273

- lib/fluent/plugin/output.rb
- test/plugin/test_output_as_buffered_backup.rb
Output plugin can't recover broken msgpack so it should be unrecoverable error.
See: https://github.com/fluent/fluent-plugin-kafka/issues/243
This PR includes small enchancement for unrecoverable error test.
> output: Add MessagePack::UnpackError to unrecoverable case

- test/counter/test_store.rb
- test/plugin/test_buffer.rb
Although it is spelling mistakes, it might make an affects while reading.
Co-Authored-By: Nguyen Phuong An <AnNP@vn.fujitsu.com>
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>
> Remove the duplicated words in printing

- lib/fluent/plugin/in_tail.rb
- test/plugin/test_in_tail.rb
- Show warning message for same encoding case
- Improve the performance using `encode!`
- Replace bad character for encoding error
> in_tail encoding enhancement

- lib/fluent/plugin_helper/server.rb
UDPServer overwrites Cool.io's IO#on_readable so
it should handle unrecoverable IO error like TCPSocket.
https://github.com/tarcieri/cool.io/blob/c79b4dff788071fcc45fac838d5d76dc645b8c1d/lib/cool.io/io.rb#L128
UDP's stream model is different from TCP. Some errors, e.g. EOFError, don't happen.
Related with https://github.com/fluent/fluentd/pull/2292
> Add more errors to ignore list in UDP socket

- lib/fluent/config/element.rb
- lib/fluent/plugin/base.rb
- lib/fluent/root_agent.rb
- test/config/test_element.rb
- test/test_root_agent.rb
This PR contains a naive `<worker N-M>` syntax implementation.
> Support multi workers assign syntax on `<worker>` section. Fix #2289

- lib/fluent/command/plugin_config_formatter.rb
Currently, the URL that unders **DOCS_BASE_URL** variable has been out of date.
This commit aims to update **DOCS_BASE_URL**'s URL to the working one that
user/deverloper can access.
Co-Authored-By: Nguyen Phuong An <AnNP@vn.fujitsu.com>
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>
> Update deprecated URL in 'DOCS_BASE_URL'

- lib/fluent/counter/client.rb
- lib/fluent/plugin/compressable.rb
This PR fixes some minor typos:
"retun" => "return"
"exeucte" => "execute"
> Fix some minor typos

- .gitignore
Some temp file like .vscode should not commit to github repo
Signed-off-by: Nguyen Quang Huy <huynq0911@gmail.com>
> Add .vscode to .gitignore file

- lib/fluent/plugin/in_syslog.rb
Fixes #2298 
To correctly parge message when using in_syslog plugin
> in_syslog - Check message lenght when read from buffer

- lib/fluent/plugin/out_forward.rb
Follow up of https://github.com/fluent/fluentd/pull/2187
Make important parameter secret.
No need.
See title.
> out_forward: Add secret to tls_client_private_key_passphrase

- lib/fluent/supervisor.rb
No entry.
Currently, worker's process names are same when `workers > 1`. This patch improves such case like below:
```
% ps aux | grep fluentd
repeatedly        7923   0.0  0.1  2521484  21240 s010  S+    4:25AM   0:00.83 worker:fluentd3     
repeatedly        7922   0.0  0.1  2519436  17984 s010  S+    4:25AM   0:00.82 worker:fluentd2     
repeatedly        7921   0.0  0.1  2522520  18676 s010  S+    4:25AM   0:00.86 worker:fluentd1     
repeatedly        7920   0.0  0.1  2522520  23420 s010  S+    4:25AM   0:00.88 worker:fluentd0     
repeatedly        7892   0.0  0.1  2523544  10260 s010  S+    4:25AM   0:00.65 supervisor:fluentd 
``` …
> system: Add worker_id to process_name when workers is larger than 1

- lib/fluent/plugin/parser_regexp.rb
- test/compat/test_parser.rb
- test/plugin/test_parser_regexp.rb
Avoid unexpected behaviour like #2330
multiline parser does named capture check so regexp parser should also check.
No need
regexp parser raises configuration error when no named capture in expression.
> parser_regexp: Check named capture. ref #2330

- lib/fluent/plugin/in_http.rb
- test/plugin/test_in_http.rb
Signed-off-by: Hiroki Takayasu <hiroki.kana@gmail.com>
#2336 
Currently `cors_allow_origins` could only use `*` or exact matching.  I modified able to could use wildcard in domain setting(ex: `http://*.example.com` )
No need
See PR title
> in_http: Add support for subdomain in CORS domain

- lib/fluent/plugin/buffer.rb
- lib/fluent/plugin/in_monitor_agent.rb
- test/plugin/test_buffer.rb
- test/plugin/test_in_monitor_agent.rb
This is useful for monitoring things like:
- How old is the current oldest log message still in the buffer?
- Equivalently, what is the maximum latency of the logging system as a whole? This might be interesting to track over time.
- How new is the *newest* log message in the buffer? This might indicate a delay upstream of fluentd.
None of the existing `buffer_*` metrics appear to be documented, so there doesn't seem to be a sensible place to document this.
A new `buffer_timekeys` metric provides a list of timekeys currently in the buffer when time-based chunking is enabled.
> Expose the current list of timekeys as a buffer metric

- lib/fluent/plugin/in_tcp.rb
- lib/fluent/plugin/in_udp.rb
- test/plugin/test_in_tcp.rb
- test/plugin/test_in_udp.rb
Fixes #2340 
Add source_address_key to tcp/udp input plugins.
Need to add parameter after v1.4.2 released.
Check title.
> in_tcp/in_udp: Add source_address_key parameter

- lib/fluent/plugin/in_forward.rb
- lib/fluent/plugin_helper/socket_option.rb
- test/plugin/test_in_forward.rb
- test/plugin_helper/test_server.rb
I'd like to detect half open connections and prevent them from consuming too many file descriptors because this can lead to a `"No file descriptors available"` error.
example stacktrace
```
"Unexpected error raised. Stopping the timer. title=:child_process_execute error_class=Errno::EMFILE error=\"No file descriptors available - ruby\"",
"/usr/lib/ruby/2.4.0/open3.rb:199:in `spawn'",
"/usr/lib/ruby/2.4.0/open3.rb:199:in `popen_run'",
"/usr/lib/ruby/2.4.0/open3.rb:95:in `popen3'",
"/fluentd/etc/vendor/bundle/ruby/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin_helper/child_process.rb:265:in `child_process_execute_once'",
"/fluentd/etc/vendor/bundle/ruby/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin_helper/child_process.rb:9 …
```
> Check the remote connection is available in the in_forward plugin

- lib/fluent/plugin/out_file.rb
- test/plugin/test_out_file.rb
Fixes #2346
Create directory when parent directories don't exist.
No need.
Use title
> out_file: Create directory for symlink. fix #2346

- lib/fluent/log.rb
- test/test_log.rb
Fixes #2355 
The time format for a plugin logger was out of sync with the parent logger, and the delegation of `#time_format` and `#time_format=` made it impossible to fix the plugin logger's time format without hacks.
This problem was not noticeable if the log format was text, because time formatting was delegated via `#caller_line` to the parent logger. However, in the case of JSON output, the plugin logger's `#format_time` method was called, yielding incorrectly-formatted timestamps.
Added tests for both text and JSON, and added tests for format changes in general while I was in there.
> Fix plugin log time format if format is JSON

- lib/fluent/plugin/buf_file.rb
- lib/fluent/plugin/in_tail.rb
Related to https://github.com/fluent/fluentd/issues/2348
To investigate reading files, output debug messages when `log_level` is `debug`.
No need.
Use PR title.
In addition, this patch includes small patch for in_tail.
> Add debug log to in_tail / buf_file.

- lib/fluent/plugin/in_syslog.rb
There are softwares out there that still use NUL-terminating characters when sending events through TCP. Firewalls for example are used a lots, and it's impossible to change their behavior because they are closed source. Most Firewall implement RFC3164 or CEF protocol, so using in_syslog plugin comes very usefull than in_tcp plugin.
I'm adding delimiter we can edit the default delimiter ("\n") from configuration, similar to in_tcp plugin.
I made the change in v0.12, I can do the same for v1.x If this change is good to merge.
Something important to know is that NUL(\0) or newline(\n) characters must be used with double-quote in configuration:
```
<source>
type syslog
protocol_type tcp
delimiter "\0"
</source>
```
I will update documentation when this PR make it
> support config delimiter in syslog plugin

- lib/fluent/log.rb
L195 overwrite Fluentd::Log#time_format= which is defined by `attr_accessor`.
This has been introduced since https://github.com/fluent/fluentd/commit/80e45ea2db99b2e3624e8ea9dde6b1707162416e
nope
To fix the warning from ruby such as `warning: method redefined; discarding old time_format=`.
No need.
No need.
> Remove duplicated method

- lib/fluent/plugin/out_forward.rb
Fixes #1968 
There is an obscure bug in out_forward that prevents events from
being sent to a remote node. It occures only on Windows, and is
reproducable only when SSL/TLS is enabled.
The root cause is not fully investigated yet, but disabling
SO_LINGER is confirmed to fix the issue. So this implements it.
Not required
"out_forward: fix data loss when SSL/TLS is enabled on Windows "
> out_forward: do not use SO_LINGER on Windows

- example/in_http.conf
ref:https://docs.fluentd.org/v1.0/articles/in_http 
> Deprecated parameter. Use the <parse> directive as explained below instead.
nope
nope
nope
nope
> Update config becuase format is deprecated

- lib/fluent/plugin/out_exec_filter.rb
- lib/fluent/plugin/parser_json.rb
- test/plugin/test_out_exec_filter.rb
- test/plugin/test_parser_json.rb
Fixes #609 
Allow configuration of the size of the buffer that Yajl uses when parsing streaming input.
The advantage of this is that when using `out_exec_filter`, and parsing
as JSON, it's now possible to configure this plugin to avoid having to
wait for 8192 bytes of data to be parsed before events are emitted.
**Docs Changes**: fluent/fluentd-docs#631
Use PR title.
> parser_json: Add stream_buffer_size config param

- lib/fluent/plugin/in_forward.rb
- test/plugin/test_in_forward.rb
none
I sometimes receive this request from users for aggregator.
There are several reasons:
- Port based tag handling
```
<source>
@type forward
port 24224
add_tag_prefix cluster1
</source>
<source>
@type forward
port 24225
add_tag_prefix cluster2
</source>
```
We can simulate this by adding new field for cluster detection in forwarder side and check it in aggregator side. But it makes configuration complicated.
- Make tag handling cost lower
We can rewrite tag with `route` or similar plugins but it has performance penalty for large traffic.
The implementation is very simple and it resolves above cases. So supporting these parameters is reasonable.
**Docs …
> in_forward: Add tag and add_tag_prefix parameters

- lib/fluent/command/fluentd.rb
- lib/fluent/supervisor.rb
Fixes https://github.com/fluent/fluentd/issues/2400
I added a deprecated message to `--help` and log.
none
none
> Add deprecated message to show-plugin-config option

- lib/fluent/plugin/out_forward.rb
- test/plugin/test_out_forward.rb
Fixes https://github.com/fluent/fluentd/issues/2188
Implemented keepalive feature for out_forward plugin.
~~Needed. I'll add a detail of this feature to  https://github.com/fluent/fluentd-docs/blob/master/docs/v1.0/out_forward.txt~~
https://github.com/fluent/fluentd-docs/pull/632
No need or use PR title?
@repeatedly Will you please review?
> Keepalive for out_forward plugin

- .travis.yml
Adding power support to travis.yml for "rvm:ruby-head"
Signed-off-by : ghatwala@us.ibm.com
Fixes # Adding power support to the travis.yml builds ( rvm:ruby-head)
Travis deployments on power , similar to PR- https://github.com/fluent/fluentd/pull/2386
None
None
> Added rvm support for ppc64le builds

- lib/fluent/compat/socket_util.rb
- lib/fluent/plugin/filter_parser.rb
- lib/fluent/plugin/in_tail.rb
- lib/fluent/plugin/in_tcp.rb
- lib/fluent/plugin/in_udp.rb
- test/plugin/test_filter_parser.rb
Signed-off-by: Hearen <LHearen@gmail.com>
Fixes # just tiny typo (grammar)
**Docs Changes**: no
**Release Note**: no
> just tiny typo (grammar)

- lib/fluent/plugin/storage_local.rb
Fixes #2373 
- Ignore empty file
- Add `fsync` call in `save`
No need
storage_local: fluentd starts even if existing file is empty.
storage_local: Call `fsync` in `save` for XFS
> Improve storage local plugin

- lib/fluent/plugin/in_http.rb
~~I couldn't find any issue about HTTPS support of in_http.~~
#2124
I replaced an implementation of in_http with server helper to prepare for HTTPS support.
no
no
> Use server helper in in_http

- lib/fluent/plugin/in_tail.rb
- test/plugin/test_in_tail.rb
2048 was too small for large logs.
8192 is chosen because BUFSIZ in stdio.h is 8192
on Ubuntu and Debian.
Signed-off-by: Inada Naoki <songofacandy@gmail.com>
Fixes #2416
in_tail: increased read block size from 2048 to 8192.
> in_tail: increase read block size

- lib/fluent/command/fluentd.rb
nothing
Kernel.#Integer can raise ArgumentError https://docs.ruby-lang.org/ja/2.5.0/method/Kernel/m/Integer.html  (Sorry. but I wasn't able to find the English document...  
English document which I found(https://ruby-doc.org/core-2.5.1/Kernel.html#method-i-Integer)  doesn't refer to ArgumentError. )
And I also noticed the variable name  (`rotate_ages`) is used.
https://ruby-doc.org/core-2.5.1/Kernel.html
not needed
not needed
> Fix log rotete age error handling

- lib/fluent/plugin/in_monitor_agent.rb
I'm thinking of replacing in_monitor's Webrick base HTTP server with [async](https://github.com/socketry/async) base HTTP server. In preparation for this, I cleaned up the in_monitor. 
not needed
not needed
> Refactor in monitor

- lib/fluent/plugin/in_monitor_agent.rb
- test/plugin/test_in_monitor_agent.rb
Related https://github.com/fluent/fluentd/pull/2422.
Please merge this patch after #2422 is merged.
In the current implementation, `/api/config.json` endpoint ignores `?debug=1` parameters even though `/api/plugins.json` endpoint respects the parameter.
not needed
not needed
> Enable pretty print in config

- lib/fluent/command/plugin_config_formatter.rb
- lib/fluent/command/plugin_generator.rb
**Which issue(s) this PR fixes**: None
**What this PR does / why we need it**: I found lots of `ERB.new` warnings (https://github.com/ruby/ruby/commit/cc777d09f44) in https://travis-ci.org/fluent/fluentd/jobs/539499703 and I thought it'd be annoying.
**Docs Changes**: None
**Release Note**: Suppress deprecation warnings of ERB for Ruby 2.6+
> Get rid of ERB warning for Ruby 2.6+

- lib/fluent/plugin/out_forward.rb
> Remove unused semicolon

- lib/fluent/plugin/out_forward.rb
> Fix dec_ref bug in out_forwarder plugin

- .gitlab-ci.yml
- .gitlab/cicd-template.yaml
- README.md
Fixes # None Created
1. This PR fixes the issue with the badge for GitLab on the Readme.
2. This PR removes repeat code from the gitlab-ci file and streamlines the builds.
3. This PR adds in the multiple targets for Ruby.
No Documentation Changes.
Fixes, Revises, and Improves GitLab CI files and processes.
**Important**: 
While this PR adds all functionality to build and test FluentD as well as fixes the badge. A test failure still exists as the test suite expects a folder to be writeable in the container. Despite setting this folder to writeable; The test still fails. 
This should not fail the CI/CD Pipeline at this stage. But it will need to be address on the testing code …
> GitLab CI/CD Revised and Improved

- lib/fluent/time.rb
- test/test_time_parser.rb
Fixes a `TypeError: nil can't be coerced into Integer` when a timezone name is used in a parser configuration.
> Fix error if timezone with name is used in parser

- lib/fluent/plugin/parser_none.rb
None
I found current implementation is bit slower,
```
key = 'message'
value = 'loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong'
x.report "init" do
r = {key => value}
end
x.report "init + []=" do
r = {}
r[key] = value
end
end
```
```
init   250.160k i/100ms
init + []=   243.042k i/100ms
init      5.944M (± 1.9%) i/s -     29.769M in   5.010006s
init + []=      5.508M (± 1.2%) i/s -     27.707M in   5.031503s
```
No need.
Same title
> parser_none: Use faster record creation

- lib/fluent/command/fluentd.rb
- lib/fluent/supervisor.rb
- test/command/test_fluentd.rb
- test/test_supervisor.rb
None
Some environment doesn't use utf-8 for text file and convert encoding is not easy for non technical users. This option reduces the encoding trouble.
I will add option to command line option article.
Same as title.
> command: Add --conf-encoding option to accept non utf-8 configuration file

- lib/fluent/plugin/out_forward.rb
- test/plugin/test_out_forward.rb
Fixes https://github.com/fluent/fluentd/issues/2451
If the socket which already handshaked tries to handshake, it will be
blocked and raise IO::WaitReadable [here](https://github.com/fluent/fluentd/blob/12ffa0afe313737bf09900efce8c8656baaf77bc/lib/fluent/plugin/out_forward.rb#L787).
So, I changed the code to avoid invoking handshake twice on the same socket.
no
no
> Fix keepalive and shared key bug

- lib/fluent/plugin/output.rb
no
Increment `@rollback_count` when `@buffer.takeback_chunk(chunk.unique_id)` succeeded. 
no
no
> rollback_count should be incremented when takeback_chunk succeeded

- lib/fluent/plugin/out_forward.rb
- lib/fluent/plugin_helper/socket.rb
- test/plugin/test_out_forward.rb
out_forward also supports connect_timeout parameter
None
After release v1.6.0, need to add connect_timeout parameter to socket helper/out_forward article.
socket helper/out_forward: Support connect_timeout parameter
> socket helper: Support connect_timeout for TCP/TLS

- lib/fluent/time.rb
- test/test_event_time.rb
None
Fluent::EventTime can be converted into Time via Time.at but
this approach is slower. Output plugins sometimes require Time
for client libraries so adding faster method.
Here is benchmark code:
```
require 'fluent/time'
ot = Time.now
et = Fluent::EventTime.from_time(ot)
x.report "to_time" do
et.to_time
end
x.report "Time.at" do
Time.at(et)
end
end
```
```
to_time   171.865k i/100ms
Time.at    92.733k i/100ms
to_time      2.861M (± 5.1%) i/s -     14.265M in   5.002172s
Time.at      1.184M (± 4.1%) i/s - …
```
> time: Add EventTime#to_time for faster Time creation

- lib/fluent/plugin/buffer.rb
- lib/fluent/plugin/in_monitor_agent.rb
- lib/fluent/plugin/output.rb
- test/helper.rb
- test/helpers/fuzzy_assert.rb
- test/plugin/test_in_monitor_agent.rb
no
I added metrics which output and buffer have to the response of in_monitor_agent plugin to fetch the fluentd's inner stats.
Need to revise examples https://docs.fluentd.org/input/monitor_agent#output-example
Same as the title
> Add more metrics to in_monitor_agent

- lib/fluent/command/plugin_config_formatter.rb
- test/command/test_plugin_config_formatter.rb
Signed-off-by: Takahiro YAMASHITA <nokute78@gmail.com>
None
`fluent-plugin-config-format` outputs old style URLs. (not gitbook style)
This PR is to make `fluent-plugin-config-format` supporting gitbook style URLs.
Old output is
```
[taka@localhost fluentd]$ bundle exec bin/fluent-plugin-config-format input syslog
* [parser](https://docs.fluentd.org/v1.0/articles/api-plugin-helper-parser)
* [compat_parameters](https://docs.fluentd.org/v1.0/articles/api-plugin-helper-compat_parameters)
* [server](https://docs.fluentd.org/v1.0/articles/api-plugin-helper-server)
* See also: [Input Plugin Overview](https://docs.fluentd.org/v1.0/articles/input-plugin-overview)
```
New output is
```
[taka@localhost fluentd]$ bundle exec …
```
> plugin_config_formatter: update new doc URL

- lib/fluent/plugin/out_forward.rb
- test/plugin/test_out_forward.rb
no
I added checking of the size of `regular_nodes` to avoid to raise ZeroDivisionError when there are no available nodes.
https://github.com/fluent/fluentd/blob/2ec546695a843a5751a1456ed6cdcdf22b300b8f/lib/fluent/plugin/out_forward.rb#L439
No need
No need
> Avoid zero division error when there are no available nodes

- lib/fluent/command/ca_generate.rb
- lib/fluent/plugin_helper/cert_option.rb
- lib/fluent/plugin_helper/socket.rb
When creating a TLS socket, the helpers only attempted to parse an RSA
key with `OpenSSL::PKey::RSA.new`. By using the higher level
`OpenSSL::PKey::read`, OpenSSL will determine and parse the proper key
type, adding support for EC and DSA keys.
Signed-off-by: Matthew Mussomele <matt@nefeli.io>
Fixes #2486
This adds support for using any private keys that OpenSSL supports to the socket helper. I looked for existing tests around the TLS socket to augment, but failed to find any, but offline tested that the changes snippet properly loads other key types.
None
> socket: Support all private keys OpenSSL supports

- lib/fluent/plugin/buffer.rb
- lib/fluent/plugin/output.rb
Follow up of #2450 
- `queus_size` / `stage_size` are updated by other thread so assigning these values to local variable is better
- `buffer_` prefix keys are static so avoid dynamic allocation for these keys.
No need
Improve the resource usage of `Output/Buffer`'s statistics method
> Improve stats method

- lib/fluent/plugin/in_monitor_agent.rb
- lib/fluent/plugin_helper/http_server.rb
- test/plugin_helper/test_http_server_helper.rb
no
According to https://docs.fluentd.org/plugin-helper-overview/api-plugin-helper-thread#methods, create_thread receives `title` which must be unique as an argument and http_server_helper uses thread_helper internally.
There are no problems now since http_server is used only by in_monitor plugin.
But we need to change http_server can change their name to have a unique name.
yes. need to add the description about `title`.
no
> Add title to have unique thread name

- lib/fluent/plugin/out_forward.rb
I created a new method(`connect_keepalive`) to remove too many `if/unless @keepalive` since it's too complicated.
For the same reason as above, I changed send_data to use connect.
no needed
no needed
> Separate a connection with keepalive code from  normal connection

- lib/fluent/plugin/in_syslog.rb
- test/plugin/test_in_syslog.rb
Fixes #2497
Signed-off-by: Brian Candler <b.candler@pobox.com>
Many devices emit syslog messages which don't match expected format, and are otherwise thrown away.  Add `emit_unmatched_lines` as per the [equivalent in_tail option](https://github.com/fluent/fluentd-docs-gitbook/blob/1.0/plugins/input/tail.md#emit_unmatched_lines).
Add new parameter to https://github.com/fluent/fluentd-docs-gitbook/blob/1.0/plugins/input/syslog.md
```
* in_syslog: Add `emit_unmatched_lines` to capture lines which don't parse
```
> in_syslog: add 'emit_unmatched_lines' option

- fluentd.gemspec
- lib/fluent/time.rb
- lib/fluent/timezone.rb
- test/test_time_formatter.rb
This is for v1.7.0.
None
Update tzinfo to latest v2. The merit removes deprecated `thread_safe` gem dependency.
Here is the performance comparison.
- with v2
```
timezone fixed   147.900k i/100ms
timezone region   148.310k i/100ms
timezone fixed      2.259M (± 2.7%) i/s -     11.388M in   5.045857s
timezone region      2.312M (± 1.5%) i/s -     11.568M in   5.005012s
```
- with v1
```
timezone fixed   150.174k i/100ms
timezone region   151.443k i/100ms
timezone fixed      2.324M (± 1.2%) i/s -     11.714M in …
```
> Update tzinfo to v2

- lib/fluent/plugin/out_forward.rb
no
#resolved_host is already called in L688
https://github.com/fluent/fluentd/blob/58fd5276e6458a5de75d5beaa64a5ca574f9e09c/lib/fluent/plugin/out_forward.rb#L688
no needed
no needed
> already resolved_host in L688

- lib/fluent/error.rb
- lib/fluent/plugin/parser.rb
- test/plugin/test_parser.rb
Fixes #2464 
Add timeout parameter. Thread checks parsing time and if it excedds `timeout` value, stop parsing and return nil. This is mainly for regexp parser.
```
<parse>
@type regexp
expression /wrong for the input/
timeout 1.0
</parse>
```
Need to add timeout parameter to parser article.
Same as title.
> parser: Add timeout parameter to avoid parsing stuck. fix #2464

- lib/fluent/plugin/out_forward.rb
- lib/fluent/plugin/out_forward/connection_manager.rb
- lib/fluent/plugin/out_forward/socket_cache.rb
- test/plugin/out_forward/test_connection_manager.rb
- test/plugin/out_forward/test_socket_cache.rb
- test/plugin/test_out_forward.rb
no
Old SocketCache isn't shared between other nodes since node's `port` and `host` is fixed at start time. 
In the situation nodes' port and host change dynamically, sharing SocketCache between nodes makes more efficient. 
And recent refactoring can make SocketCache more simple.
no need
no need
> Change SocketCache to be shared between nodes

- lib/fluent/plugin/out_forward.rb
no
I change to call one rebuild_weight_array per on_heartbeat_timer.
In old implementation, if there are 10 nodes which failed to invoke #send_heartbeat or #tick, it needs to call rebuild_weight_array 10 times. 
no needs
> Stop to rebuild nodes duplicately

- lib/fluent/plugin/buf_file.rb
- test/plugin/test_buf_file.rb
Fixes #2236 
Add `path_suffix` parameter to change suffix of buffer files.
This is mainly for k8s environment
Add path_suffix parameter to buf_file article.
Same as title.
> buf_file: Add path_suffix parameter. ref #2236

- lib/fluent/plugin/in_tail.rb
no
`slice!` is very slow. so I replaced in_tail implementation with `slice` + `freeze`.
This change makes FIFO of in_tail about 100x faster in ruby 2.6's simple benchmark.
benchmark script & result: https://gist.github.com/ganmacs/3f517c79881f56547cde305ae7a86b35
no
Replace in_tail with faster implementation.
> Replace in_tail with a faster implementation.

- lib/fluent/plugin/out_http.rb
- test/plugin/test_out_http.rb
None
Add HTTP output plugin for v1.7. I got several requests from different users in kubecon. Users have the endpoint to accept logs via HTTP/HTTPs. So generic HTTP output plugin is useful for typical usecases.
Discussion point:
- Support in_http format. fluentd has forward protocol so out_http -> in_http usecase is very rare. I think no need for now
- Support `[{}, {},..., {}]` like json/msgpack. Current implementation uses ndjson. I'm not sure one large array payload is useful or not.
Need to add article to output section. I will write it after ready to merge.
Add `http` output plugin
> Add HTTP output plugin

- lib/fluent/plugin/formatter_csv.rb
- test/plugin/test_formatter_csv.rb
None
Improve the performance by avoiding creating CSV object per format call.
In ruby 2.6.3, 2x faster than before.
```
now     4.627k i/100ms
new     9.692k i/100ms
now     49.484k (± 2.1%) i/s -    249.858k in   5.051491s
new     98.117k (± 8.4%) i/s -    494.292k in   5.091679s
```
```
require 'csv'
class CF
def initialize
@fields = ["key1","key2","ke,y3","ke y4","key5","key6","key7","key8"]
@generate_opts1 = {col_sep: ',', force_quotes: true}
@generate_opts2 = {col_sep: ',', force_quotes: true, headers: @fields,
row_sep: @add_newline …
```
> formatter_csv: Improve the performance.  2x faster

- lib/fluent/plugin/out_forward.rb
- test/plugin/test_out_forward.rb
no
Removed duplicated `@available` and public method.
no
no
> Refactor available

- lib/fluent/plugin/parser_csv.rb
- test/plugin/test_parser_csv.rb
Add parser_type parameter to switch the parser.
None
Parser version try of https://github.com/fluent/fluentd/pull/2529.
I implemented original method because CSV module doesn't provide the way to parse single line without recreate CSV object.
This fast implementation supports typical patterns so it is useful. See test case for supported patterns: https://github.com/fluent/fluentd/blob/8b1cb4a6899f556ddad19aa1e8b5863825313ae9/test/plugin/test_parser_csv.rb#L107
Here is the benchmark result:
```
non quote: value1,value1,value1,value1,value1,value1,value1,value1
quoted   : "fo,o","fo,o","fo,o","fo,o","fo,o","fo,o","fo,o","fo,o"
escaped  : "aa","b""b""b","c"," …
```
> parser_csv: Improve the performance for typical cases

- lib/fluent/plugin/compressable.rb
Fixes #2546
in `string_decompress()`, `gz.read` loop break when `unused.nil?`,  
but `unused.nil?` does not show end of stream.
It cause data lost.
loop shoud be break when eof.
> fix data lost on decompression

- test/counter/test_store.rb
No issues
`Timecop.return` is never called because `CounterStoreTest#shutdown` is never called.
We shuould define `CounterStoreTest.shutdown` or `CounterStoreTest#teardown`.
cf. https://github.com/test-unit/test-unit/blob/3.2.8/lib/test/unit.rb#L462-L473
As you can see, this PR corrects the elapsed time from -90938190.322263 seconds to 0.013861 seconds.
Before
```
% bundle exec rake TEST=test/counter/test_store.rb
/Users/arabiki/.anyenv/envs/rbenv/versions/2.6.2/bin/ruby -w -I"lib:test" -Eascii-8bit:ascii-8bit -I"/Users/arabiki/.anyenv/envs/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-11.3.0/lib" "/Users/arabiki/.anyenv/envs/rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-11.3.0/lib/rake/rake_test_loader.r …
```
> Use teardown instead of shutdown in CounterStoreTest

- lib/fluent/plugin/in_syslog.rb
- test/plugin/test_in_syslog.rb
Fixes #2552 
Unmatched messages from the syslog input should contain `source_hostname_key` or
`source_address_key` if configured as this information is provided by the
underlying udp oder tcp server and is available even if the message
could not be parsed.
This PR will add support for the expected behaviour of honoring `source_address_key` and `source_hostname_key` on unmatched lines.
> add support for source_hostname_key and source_address_key on umatched syslog messages

- lib/fluent/event.rb
Fixes #
```rb
class A
def empty?
size == 0
end
end
class B < A
def size
1
end
end
class C < A
def empty?
false
end
end
b = B.new
c = C.new
x.report("b") do
b.empty?
end
x.report("c") do
c.empty?
end
end
```
```
b   437.425k i/100ms
c   454.017k i/100ms
b     16.370M (± 6.5%) i/s -     81.798M in   5.021556s
c     22.938M (± 3.4%) i/s -    114.866M in   5.013438s
```
no need
same as title
> OneEvent isn't always empty

- lib/fluent/compat/output.rb
- lib/fluent/plugin/bare_output.rb
- lib/fluent/plugin/multi_output.rb
- lib/fluent/plugin/output.rb
Fixes #
I used Mutex when no need reentrant lock since Mutex is faster than Montior.
```rb
mo = Monitor.new
mu = Mutex.new
x.report("monitor") do
mo.synchronize {}
end
x.report("mutex") do
mu.synchronize {}
end
end
```
```
monitor   224.461k i/100ms
mutex   371.210k i/100ms
monitor      3.987M (± 2.4%) i/s -     19.977M in   5.013755s
mutex     10.221M (± 2.5%) i/s -     51.227M in   5.015317s
```
no need
same as title
> Use Mutex instead of Monitor

- lib/fluent/plugin/in_tcp.rb
- test/plugin/test_in_tcp.rb
None
Use `MultiEventStream` to improve the performance for multiple events in receive data.
No need.
Same as title
> in_tcp: Improve the performance for multiple events case

- lib/fluent/clock.rb
- lib/fluent/plugin/buffer/chunk.rb
- lib/fluent/plugin/buffer/file_chunk.rb
- lib/fluent/plugin/buffer/memory_chunk.rb
- lib/fluent/plugin/output.rb
- lib/fluent/time.rb
- test/helper.rb
- test/helpers/process_extenstion.rb
no
`Process.clock_gettime` is faster than `Time.now` if getting sec and nsec.
and `Time.now` is called in `EventTime.now`.
EventTime.now is called per data in [parser_none](https://github.com/fluent/fluentd/blob/785fe3df5df76ae7110ea226c506131d8e607aa6/lib/fluent/plugin/parser_none.rb#L31) and per [chunk creation](https://github.com/fluent/fluentd/blob/785fe3df5df76ae7110ea226c506131d8e607aa6/lib/fluent/plugin/buffer/chunk.rb#L60-L61). so it's better to replace them with faster version's method.
```ruby
def now1
now = Process.clock_gettime(Process::CLOCK_REALTIME, :nanosecond)
sec = now / 1_000_000_000
nsec = now % 1_000_000_000
[sec, nsec]
end
def now2
t = Time.now
sec = t.to_i
nsec = t.nsec
[sec, nsec]
end …
```
> Use faster way to get sec and nsec

- lib/fluent/plugin/buffer/file_chunk.rb
- test/plugin/test_buf_file.rb
- test/plugin/test_buffer_file_chunk.rb
Fixes #
IO#truncate call IO#flush internally. this cause heavy IO in case file buffer of fluentd.
so I change file buffer metadata format not to call IO#truncate.
*Release Note**: 
same as title.
> Not to call IO#truncate to avoid too many IO flush

- lib/fluent/plugin/out_exec_filter.rb
Fixes #
fix encoding problem
from:
"msg\":\"\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\"
to:
"msg":"你好"
> solve issue when messages contain UTF-8 (CJK)

- lib/fluent/event.rb
- lib/fluent/event_router.rb
- lib/fluent/msgpack_factory.rb
- lib/fluent/plugin/buffer/file_chunk.rb
- lib/fluent/plugin/output.rb
cache msgpack packer/unpacker not to create unnecessary objects.
https://gist.github.com/ganmacs/a620be919851d49bff3bf2de58da2052 shows decreasing CPU time of ` Fluent::EventStream#to_msgpack_stream` and ` Fluent::MessagePackFactory::Mixin#msgpack_packer`.
no need
same as title
> Cache msgpack packer/unpacker

- lib/fluent/plugin/in_tail.rb
Fixes https://github.com/fluent/fluentd/issues/2555
First time is in parser helper
https://github.com/fluent/fluentd/blob/5a7d94941371dddcb7150a73ddbe142102a68964/lib/fluent/plugin_helper/parser.rb#L82 (and the `localtime` is set in the first time. https://github.com/fluent/fluentd/issues/2555#issuecomment-521802165)
Second time is parser_create in TailInput
https://github.com/fluent/fluentd/blob/5a7d94941371dddcb7150a73ddbe142102a68964/lib/fluent/plugin/in_tail.rb#L151
same as title
> Not to call Parser#configure is called twice

- lib/fluent/plugin/in_tail.rb
Fixes #
This patch is based on a feature request from one of our customers.
Right now, in_tail emits the following warning message when it reads
a malformed line.
2019-08-18 00:20:03 +0900 [warn]: #0 "a,b\",c" error="Illegal quoting in line 1."
However, since we use in_tail extensively (e.g. tracking lots of files
at once), it is sometimes not easy to determine WHICH file caused the
error just by seeing this message.
With this patch, in_tail shows:
2019-08-18 00:27:42 +0900 [warn]: #0 invalid line found file="test.csv"
line="a,b\",c" error="Illegal quoting in line 1."
... which should be useful for debugging.
No need to update the document.
Use the PR title.
> in_tail: Dump a file name in addition to a malformed line

- lib/fluent/config/element.rb
- lib/fluent/config/section.rb
- test/config/test_configurable.rb
Fixes #2572
This PR improves warning messages using the following configuration:
```
<match debug.**>
@type s3
s3_bucket dummy
<buffer>
unused_key 1
</buffer>
</match>
```
* Before
```
2019-08-16 23:17:26 +0900 [warn]: section <buffer> is not used in <match debug.**>
```
* After
```
2019-08-18 00:31:03 +0900 [warn]: parameter 'unused_key' in <buffer>
unused_key 1
</buffer> is not used.
```
no need
same as tile
> Improve unused parameter warning messages from sections used at least once

- lib/fluent/plugin_helper/thread.rb
This helps understand thread usage with commands like `top -H` and `ps -e -T`
Before this change the thread name shows up as `thread.rb:70`. After, it may show up as whatever title was given. The exact behavior will depend on the implementation of Ruby's `native_set_another_thread_name`.
> Set thread title

- lib/fluent/plugin/buf_file_single.rb
- lib/fluent/plugin/buffer/file_single_chunk.rb
- test/plugin/test_buf_file_single.rb
- test/plugin/test_buffer_file_single_chunk.rb
Ref https://github.com/fluent/fluentd/issues/2153
`buf_file` works fine for typical cases, e.g. `in_tail`/`in_forward`, but it is not good for lots of small emit cases. It issues lots of IO operation.
So to reduce IO tps on high traffic environment, introduce `buf_file_single`. This is similar to v0.12 buf_file and this is lightweight. 
`buf_file_single` has one limitation that supports only tag or one field chunk key, `<buffer tag>` or `<buffer key>`. This limitation will be relaxed by supporting metadata header in the file.
Add `buf_file_single` article. Will send a patch later.
Same as title
> Add buf_file_single plugin

- lib/fluent/log.rb
- lib/fluent/root_agent.rb
- test/command/test_fluentd.rb
- test/plugin/test_in_tail.rb
Fixes #
make codebase clean by fix typo
N/A
N/A
> cleanup: fix some typos in code comment

- lib/fluent/plugin/buffer.rb
no
Object#hash  is called when using an object as the hash key or reference value from a hash object with the object.
Current `Struct`'s implementation is comparing all inner variables. 
https://github.com/ruby/ruby/blob/0623e2b7cc621b1733a760b72af246b06c30cf96/struct.c#L1200-L1203
This impl is a bit redundant. Especially in fluentd, it can be overhead.
e.g. [Output#handle_stream_simple](https://github.com/fluent/fluentd/blob/785fe3df5df76ae7110ea226c506131d8e607aa6/lib/fluent/plugin/output.rb#L999) creates a hash object using an object as a key. this method is called per `emit`(one of the most called methods in fluentd). 
benchmark
```rb
A = Struct.new(:l, :c, :r)
B = Struct.new(:l, :c, …
```
> Add hash method to metadata to speed up comparing it in a hash key

- lib/fluent/plugin_helper/server.rb
Fixes #2548 #2592 
I'm not sure when `SSL_accept` raises ETIMEDOUT but thread should not be died.
fluentd can't recover timedout socket so just ignore.
No need.
Same as title.
> server helper: Ignore ETIMEDOUT error in SSL_accept. fix #2592

- lib/fluent/plugin/buf_file.rb
- lib/fluent/plugin/buf_file_single.rb
- test/plugin/test_buf_file.rb
- test/plugin/test_buf_file_single.rb
Fixes #2582 
fluentd uses `{` and `}` for placeholders and these characters are special in `Dir.glob`.
Should be escaped before call `Dir.glob`.
No need.
Same as title.
> buf_file/buf_file_single: fix to ignore placeholder based path. fix #2582

- lib/fluent/plugin/buf_file_single.rb
- test/plugin/test_buf_file_single.rb
none
if user passes `/path/to/foo.*.baz` to single file buffer plugin as `path`
directive, single file buffer convert it into `/path/to/fsb.*.buf`.
in here. 
https://github.com/fluent/fluentd/blob/c7a825c7cad52f0c2a322ae88f7011e842b3d4fb/lib/fluent/plugin/buf_file_single.rb#L115-L117
When the user uses another single file buffer whose `path` is  `/path/to/` in the above situation,  single file buffer should raise an`ConfigError`, but not in present implementation.
no need
> Raise config error when using same file path in file_signle buffer

- lib/fluent/plugin/buffer/file_chunk.rb
- test/plugin/test_buffer_file_chunk.rb
Fixes https://github.com/fluent/fluentd/issues/2593
Ensure to remove metadata if #write_metadata raise an error because of disk full
no need
> Ensure to remove metadata if #write_metadata raise an error because of disk full

- fluentd.gemspec
- lib/fluent/plugin/out_forward.rb
- lib/fluent/plugin_helper/socket.rb
- test/plugin/test_out_forward.rb
None.
Currently, Fluentd does not refer Windows Certstore as OpenSSL certificates store.
This PR makes to be able to refer it and import certificates which are stored in Windows certstore.
~~Add `Load certificates from windows certstore` article in out_forward document. I will send a patch later.~~
https://github.com/fluent/fluentd-docs-gitbook/pull/102
Same as a title.
> Load certificates from windows certstore

- test/plugin/test_buffer_file_chunk.rb
- test/plugin/test_buffer_file_single_chunk.rb
- test/plugin/test_buffer_memory_chunk.rb
none
for the env which `Encoding.default_external` returns not `ASCII-8BIT`
```rb
s = StringIO.new
p s.external_encoding # => #<Encoding:UTF-8>
s.write('text'.force_encoding(Encoding::ASCII_8BIT))
p s.string.encoding # => #<Encoding:UTF-8>
s = StringIO.new('text'.force_encoding(Encoding::ASCII_8BIT))
p s.external_encoding # => #<Encoding:ASCII-8BIT>
p s.string.encoding # => #<Encoding:ASCII-8BIT>
```
no need
no need
cc. @repeatedly
> Set encoding

- fluentd.gemspec
9aca889cd started using `MessagePack::Packer#full_pack`, which was introduced in msgpack 1.2.0.
> Increase minimum msgpack version

- lib/fluent/plugin/parser_syslog.rb
- test/plugin/test_parser_syslog.rb
Fixes #2585 
Changing regexp is difficult because it may break existing user environment, so
add non-regexp based parser to support more syslog message. 
This parser is also 2x faster.
```
require 'fluent/engine'
require_relative 'lib/fluent/plugin/parser_syslog'
parser = Fluent::Plugin::SyslogParser.new
parser.configure(Fluent::Config::Element.new('ROOT', '', {'keep_time_key' => true}, []))
log = 'Feb 28 12:00:00 192.168.0.1 fluentd[11111]: [error] Syslog test'
parser2 = Fluent::Plugin::SyslogParser.new
parser2.configure(Fluent::Config::Element.new('ROOT', '', {'with_priority' => true, 'keep_time_key' => true}, []))
log2 = '<1>Feb 28 …
```
> Implement new parser for parser_syslog

- lib/fluent/plugin/output.rb
- test/plugin/test_output.rb
Fixes https://github.com/fluent/fluentd/issues/2607
I made a change to raise an error when a user specifies `timekey`  less than equal 0.
when `timekey` is 0, fluentd will raise `ZeroDivisionError` at [here](https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/output.rb#L1379).
no need
> validate if timkey is less than equal 0

- lib/fluent/plugin/multi_output.rb
- lib/fluent/plugin_helper/formatter.rb
- lib/fluent/plugin_helper/parser.rb
- lib/fluent/plugin_helper/storage.rb
- lib/fluent/root_agent.rb
- lib/fluent/system_config.rb
Fixes https://github.com/fluent/fluentd/issues/2613
Use `Object.__send__` to avoid conflicting method name
no need
> Use Object.__send__ to avoid conflicting method name

- lib/fluent/plugin/buf_file.rb
- lib/fluent/plugin/buf_file_single.rb
Fixes #2618
Chunks buffered via buf_file where not uncompressed on restore.
> Allow uncompressing buffer files during restore

- CHANGELOG.md
Signed-off-by: yuxiaobo <yuxiaobogo@163.com>
NONE
Perfect documentation.
> Perfect documentation

- lib/fluent/plugin/out_forward/socket_cache.rb
- test/plugin/out_forward/test_socket_cache.rb
since @available_sockets is initialized with
`Hash.new { |obj, k| obj[k] = [] }` at https://github.com/fluent/fluentd/blob/v1.7.1/lib/fluent/plugin/out_forward/socket_cache.rb#L27
Fixes https://github.com/fluent/fluentd/issues/2626
to avoid  NoMethodError after calling purge_obsolete_socks 
no need
same as title
> Reuse same hash object after calling purge_obsolete_socks

- lib/fluent/plugin/in_syslog.rb
- test/plugin/test_in_syslog.rb
None
I noticed `priority_key` is misleading name because it stores severity, not priority.
So I add proper `severity_key` and keep `priority_key` for backward compatibility.
`priority_key` will be removed at fluentd v2.
Will add `severity_key` and deprecate `priority_key`
Same as title.
> in_syslog: Replace priority_key with proper severity_key

- lib/fluent/plugin/in_http.rb
- test/plugin/test_in_http.rb
**The reason about this PR**: 
I used fluentd service and figured that 200 response with empty string is a little bit not precise.
According to [rfc7231](https://tools.ietf.org/html/rfc7231#section-6.3.5), 204 is more proper status code.
> a 204 status code is commonly used with document editing interfaces corresponding to a "save" action
- For more semantic status code
- Add test for this change in test_in_http
- Fix typo in test_in_http
> Semantic Status Code - modify on_request response from 200 to 204 in plugin/in_http

- lib/fluent/plugin/formatter_csv.rb
- lib/fluent/plugin_helper/record_accessor.rb
- test/plugin/test_formatter_csv.rb
Fixes #2630 
Support nested fields via `record_accessor`.
Add note for nested fields to `fields` parameter.
same as title
> formatter_csv: support nested fields. fix #2630
